$axure.loadCurrentPage({
  "url":"质量服务明细.html",
  "generationDate":new Date(1455876388691.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a2a9cce8e04546549774ac66e2e9ddf3",
    "type":"Axure:Page",
    "name":"质量服务明细",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3fa4862b8e65494c9514b8d2ddc0d751",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75b4f0ebbb340c59e33f763a87d612e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"7874f3d94cf842e5847989276d41ecff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":111,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9acdb96d448e412297058f0e11156eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":111,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"f2ec6322a4c04f83b9b0735dfa7adbdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":222,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5006d163b1384264bc95016ae8dca4f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":222,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"422e499f9b0f49b994a332728d926e9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":332,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f21e7e1f33f450982f6c303bb721b9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":332,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"a64d186402054932bda510f156a7d1df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"974e5d063e024bd9be41946ac72da961",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"8d097c387f31442fbc4264428d937487",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":111,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62187e9693ad4b939160e7c16fbda56d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":111,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"44dd3fad66fa47bc9d0113f0f6118cf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":222,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"047751037fb54e07b3b125e3fea2979d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":222,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"181c3e7c66074ae3bb4fe53405dc77ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":332,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2bb9432cb9241fca230afed4b93be55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":332,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"1aa346017669434188a109c9bdbc4a38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":443,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a261a48706b843979f9643c376b82b42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":443,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"2396c390fd2b4542a9e845cab1b14a04",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":443,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f79fea51f49041e6886f30300ad4f226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":443,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"96e271b6d6c7445cb7cbb8d2ed78bcfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":553,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2d5eb8823d24f4c9a7bba21a7475a74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":553,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"ebf5d0e963a14aa799059923cf4f86e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":664,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95da56eb12504925a2734f0b8fcbfed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":664,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"581d0f1997e64b9694a5a2427bee3886",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":775,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e8ece336a384ef6a7392dade5a1159e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":775,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"1365543e577748c2a24c7938a9ae168f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":886,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28ce1ebb6a764a749e7f0f1f70148d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":886,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"bcfeb27804d543f389615e66a1e3deb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":553,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e1133846ed24af99b7c10fb7da7d734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":553,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"436ff33414584109adf22753ef95f5cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":664,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe54194a617945a4b574c78c24e44a6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":664,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"c199419f68824a7b898450e47d3d56db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":775,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c6caa045aa64b90ac59217c14169859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":775,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"07f481cf33ad4de6ba90bf530fc8034f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":886,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf1cb84c26f84ec9bc49b2404ba39ad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":886,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"ecff6bffb8c14ab784b31e617e72366b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":996,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4496031745b48d2bb1b59849f8e69e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":996,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"164d0194319747da9c45b557c3124686",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":996,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c440b1d3281473c827c449e1277ff66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":996,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"22cba296615f4ef1a1a6ac99368b36fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":1108,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"763eababd3c9459cba000077f3dc3e15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":1108,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"72ef50c49d254662ae164ed1724198a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":1218,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc33dddcbf2a40918a9af044f0ac38c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":1218,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"b64a7072cc58449f86b2fa6527930547",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":1328,
              "y":0},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"375ca0b67cbc4af591150457e47445b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":1328,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u0.png"}},
{
          "id":"fd0285576dfa40839eb7324ee4734417",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1108,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e13d2c87344a46f18ae33e8e25f3d51d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1108,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"a324ba490abd4d5a95239eb3803c3819",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1218,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1302c79949914d4986303af15777290a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1218,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}},
{
          "id":"4aad20b1404641fb890ef7a20c565e37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1328,
              "y":29},
            "size":{
              "width":112,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11c19c16854c4fabbada1898f4b2d761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1328,
                  "y":29},
                "size":{
                  "width":112,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/质量服务明细/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3fa4862b8e65494c9514b8d2ddc0d751":{
      "scriptId":"u0"},
    "a75b4f0ebbb340c59e33f763a87d612e":{
      "scriptId":"u1"},
    "7874f3d94cf842e5847989276d41ecff":{
      "scriptId":"u2"},
    "9acdb96d448e412297058f0e11156eb4":{
      "scriptId":"u3"},
    "f2ec6322a4c04f83b9b0735dfa7adbdb":{
      "scriptId":"u4"},
    "5006d163b1384264bc95016ae8dca4f9":{
      "scriptId":"u5"},
    "422e499f9b0f49b994a332728d926e9d":{
      "scriptId":"u6"},
    "3f21e7e1f33f450982f6c303bb721b9f":{
      "scriptId":"u7"},
    "a64d186402054932bda510f156a7d1df":{
      "scriptId":"u8"},
    "974e5d063e024bd9be41946ac72da961":{
      "scriptId":"u9"},
    "8d097c387f31442fbc4264428d937487":{
      "scriptId":"u10"},
    "62187e9693ad4b939160e7c16fbda56d":{
      "scriptId":"u11"},
    "44dd3fad66fa47bc9d0113f0f6118cf1":{
      "scriptId":"u12"},
    "047751037fb54e07b3b125e3fea2979d":{
      "scriptId":"u13"},
    "181c3e7c66074ae3bb4fe53405dc77ee":{
      "scriptId":"u14"},
    "a2bb9432cb9241fca230afed4b93be55":{
      "scriptId":"u15"},
    "1aa346017669434188a109c9bdbc4a38":{
      "scriptId":"u16"},
    "a261a48706b843979f9643c376b82b42":{
      "scriptId":"u17"},
    "2396c390fd2b4542a9e845cab1b14a04":{
      "scriptId":"u18"},
    "f79fea51f49041e6886f30300ad4f226":{
      "scriptId":"u19"},
    "96e271b6d6c7445cb7cbb8d2ed78bcfe":{
      "scriptId":"u20"},
    "e2d5eb8823d24f4c9a7bba21a7475a74":{
      "scriptId":"u21"},
    "ebf5d0e963a14aa799059923cf4f86e3":{
      "scriptId":"u22"},
    "95da56eb12504925a2734f0b8fcbfed9":{
      "scriptId":"u23"},
    "581d0f1997e64b9694a5a2427bee3886":{
      "scriptId":"u24"},
    "4e8ece336a384ef6a7392dade5a1159e":{
      "scriptId":"u25"},
    "1365543e577748c2a24c7938a9ae168f":{
      "scriptId":"u26"},
    "28ce1ebb6a764a749e7f0f1f70148d12":{
      "scriptId":"u27"},
    "bcfeb27804d543f389615e66a1e3deb0":{
      "scriptId":"u28"},
    "2e1133846ed24af99b7c10fb7da7d734":{
      "scriptId":"u29"},
    "436ff33414584109adf22753ef95f5cb":{
      "scriptId":"u30"},
    "fe54194a617945a4b574c78c24e44a6d":{
      "scriptId":"u31"},
    "c199419f68824a7b898450e47d3d56db":{
      "scriptId":"u32"},
    "7c6caa045aa64b90ac59217c14169859":{
      "scriptId":"u33"},
    "07f481cf33ad4de6ba90bf530fc8034f":{
      "scriptId":"u34"},
    "cf1cb84c26f84ec9bc49b2404ba39ad3":{
      "scriptId":"u35"},
    "ecff6bffb8c14ab784b31e617e72366b":{
      "scriptId":"u36"},
    "b4496031745b48d2bb1b59849f8e69e2":{
      "scriptId":"u37"},
    "164d0194319747da9c45b557c3124686":{
      "scriptId":"u38"},
    "4c440b1d3281473c827c449e1277ff66":{
      "scriptId":"u39"},
    "22cba296615f4ef1a1a6ac99368b36fd":{
      "scriptId":"u40"},
    "763eababd3c9459cba000077f3dc3e15":{
      "scriptId":"u41"},
    "72ef50c49d254662ae164ed1724198a0":{
      "scriptId":"u42"},
    "dc33dddcbf2a40918a9af044f0ac38c2":{
      "scriptId":"u43"},
    "b64a7072cc58449f86b2fa6527930547":{
      "scriptId":"u44"},
    "375ca0b67cbc4af591150457e47445b4":{
      "scriptId":"u45"},
    "fd0285576dfa40839eb7324ee4734417":{
      "scriptId":"u46"},
    "e13d2c87344a46f18ae33e8e25f3d51d":{
      "scriptId":"u47"},
    "a324ba490abd4d5a95239eb3803c3819":{
      "scriptId":"u48"},
    "1302c79949914d4986303af15777290a":{
      "scriptId":"u49"},
    "4aad20b1404641fb890ef7a20c565e37":{
      "scriptId":"u50"},
    "11c19c16854c4fabbada1898f4b2d761":{
      "scriptId":"u51"}}});