$axure.loadCurrentPage({
  "url":"秒杀商品详情页.html",
  "generationDate":new Date(1457072024732.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cd3bcda9516a49f59d1076893d135154",
    "type":"Axure:Page",
    "name":"秒杀商品详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a198e24849b9468a96db827aa506f3f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":653},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3819313776e14ac8afa5d556f4a9cb81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":653},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/秒杀商品详情页/u0.png"}},
{
          "id":"eeead7ebb39147448d6a115ce752ac9f",
          "label":"秒杀状态",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":516,
              "y":474},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 秒杀状态 to 下一步 wrap",
                      "panelsToStates":[{
                          "panelPath":["eeead7ebb39147448d6a115ce752ac9f"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"bcde71adf2f24e41b9c8c5a8e55cc514",
              "label":"未登录状态",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5a171a34599f4c3ea28d274ac4da0547",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":27},
                    "size":{
                      "width":200,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a5726ca8bf54dc8861ee2471d5eb075",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":0,
                          "y":27},
                        "size":{
                          "width":200,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"f004734fbf394ed5972daea9d05c1ab9",
              "label":"即将开始",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"414a001202154bd580c24a033b2bd1f6",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "size":{
                      "width":200,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d347abfac7544035b7d88b93fc8e178b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "size":{
                          "width":200,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9d5c9380ac8b48d985834a5786cef6a0",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":186,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f1a7a03952c645ce866cfd0e1cb7691e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":26},
                        "size":{
                          "width":186,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/秒杀商品详情页/u7.png"}},
{
                  "id":"b9367b3aecd743adb71782c7c85af4b9",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":0,
                      "y":81},
                    "size":{
                      "width":324,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"173baf258f384c5dbc9d840af3d11989",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":0,
                          "y":81},
                        "size":{
                          "width":324,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"f4f1a3b12067471cba30d76bd4ed005f",
              "label":"刷新抢宝",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5f04a1e14a1f4760ad7cf1c3af0c856f",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "size":{
                      "width":200,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac16a948fde64cc1a0bae8edefff4ba3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "size":{
                          "width":200,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"054e24ea3cd147458e1dd0f4000d8c6a",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":0,
                      "y":81},
                    "size":{
                      "width":324,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ec4678f78e64bda9ed93c429e248d47",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":0,
                          "y":81},
                        "size":{
                          "width":324,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8272afb4e434456fa5d7570ab60c72f8",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ee4ead28baa409bbe8ed7ba16baca0f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":14,
                          "y":30},
                        "size":{
                          "width":126,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/秒杀商品详情页/u15.png"}}]},
{
              "id":"b177b70186f64c559169c3829e2bbdd7",
              "label":"立即秒杀",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"279ea56eb19c47bdbfafcf613ea9718d",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":2},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3e5dc8ead2c540988ce5a39d2875c3df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":2},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"514aad3852b74aa1a61c1aaf7856c0e5",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9c7ae896f4234eb59626d93dec82caca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f366558b7c4148cdb8a6e11c557f5b39",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":63,
                      "y":29},
                    "size":{
                      "width":213,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"192c2c03993745d6b12d18daff80ffd7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":63,
                          "y":29},
                        "size":{
                          "width":213,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/秒杀商品详情页/u21.png"}},
{
                  "id":"decdf3891c3942dd87dad5c23362cc18",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":63,
                      "y":2},
                    "size":{
                      "width":26,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c12e287dde0346c58b7a9007eeb97313",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":63,
                          "y":2},
                        "size":{
                          "width":26,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2b1dd1a76b8643ef9319ef0a73eb70b1",
                  "label":"",
                  "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":63,
                      "y":73},
                    "size":{
                      "width":125,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"296f75b462a04e7193d454f607b15254",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"eeead7ebb39147448d6a115ce752ac9f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":63,
                          "y":73},
                        "size":{
                          "width":125,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/秒杀商品详情页/u25.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "a198e24849b9468a96db827aa506f3f2":{
      "scriptId":"u0"},
    "3819313776e14ac8afa5d556f4a9cb81":{
      "scriptId":"u1"},
    "eeead7ebb39147448d6a115ce752ac9f":{
      "scriptId":"u2"},
    "5a171a34599f4c3ea28d274ac4da0547":{
      "scriptId":"u3"},
    "7a5726ca8bf54dc8861ee2471d5eb075":{
      "scriptId":"u4"},
    "414a001202154bd580c24a033b2bd1f6":{
      "scriptId":"u5"},
    "d347abfac7544035b7d88b93fc8e178b":{
      "scriptId":"u6"},
    "9d5c9380ac8b48d985834a5786cef6a0":{
      "scriptId":"u7"},
    "f1a7a03952c645ce866cfd0e1cb7691e":{
      "scriptId":"u8"},
    "b9367b3aecd743adb71782c7c85af4b9":{
      "scriptId":"u9"},
    "173baf258f384c5dbc9d840af3d11989":{
      "scriptId":"u10"},
    "5f04a1e14a1f4760ad7cf1c3af0c856f":{
      "scriptId":"u11"},
    "ac16a948fde64cc1a0bae8edefff4ba3":{
      "scriptId":"u12"},
    "054e24ea3cd147458e1dd0f4000d8c6a":{
      "scriptId":"u13"},
    "5ec4678f78e64bda9ed93c429e248d47":{
      "scriptId":"u14"},
    "8272afb4e434456fa5d7570ab60c72f8":{
      "scriptId":"u15"},
    "1ee4ead28baa409bbe8ed7ba16baca0f":{
      "scriptId":"u16"},
    "279ea56eb19c47bdbfafcf613ea9718d":{
      "scriptId":"u17"},
    "3e5dc8ead2c540988ce5a39d2875c3df":{
      "scriptId":"u18"},
    "514aad3852b74aa1a61c1aaf7856c0e5":{
      "scriptId":"u19"},
    "9c7ae896f4234eb59626d93dec82caca":{
      "scriptId":"u20"},
    "f366558b7c4148cdb8a6e11c557f5b39":{
      "scriptId":"u21"},
    "192c2c03993745d6b12d18daff80ffd7":{
      "scriptId":"u22"},
    "decdf3891c3942dd87dad5c23362cc18":{
      "scriptId":"u23"},
    "c12e287dde0346c58b7a9007eeb97313":{
      "scriptId":"u24"},
    "2b1dd1a76b8643ef9319ef0a73eb70b1":{
      "scriptId":"u25"},
    "296f75b462a04e7193d454f607b15254":{
      "scriptId":"u26"}}});