$axure.loadCurrentPage({
  "url":"商户销服明细.html",
  "generationDate":new Date(1455876388627.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7d940c9788ec4ac3a8ea3d43958802d0",
    "type":"Axure:Page",
    "name":"商户销服明细",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7085214dd9f243598fd4c503190c0543",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":643}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10cb263da41c4aa1891f8716ed29e1b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":643}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u0.png"}},
{
          "id":"c1226c4047244a1baeea605eb0c85bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":170,
              "y":82},
            "size":{
              "width":140,
              "height":28},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7c63f1722f846189ebf24b4056b44d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":170,
                  "y":82},
                "size":{
                  "width":140,
                  "height":28},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u235.png"}},
{
          "id":"f09f2c0ca45242e08ca36d3454958cd8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":115},
            "size":{
              "width":340,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5a14c4678654d45bdc860d6793b87f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":115},
                "size":{
                  "width":340,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单统计/u4.png"}},
{
          "id":"6d1ae5dd20824262ad7f0d6c349c3426",
          "label":"销服统计",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":167},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"797b0b6c64f44b9c937da41d82e4ecbb",
              "label":"销售明细",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9cf266cc610c40d3a07ace40fe3e6472",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC},
                    "size":{
                      "width":1020,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf26382f1ddc410fbf602a870ca7c1d0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC},
                        "size":{
                          "width":1020,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/订单统计/u7.png"}},
{
                  "id":"79b09e20d7a54db0b32f0dddc01af285",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":10,
                      "y":0},
                    "size":{
                      "width":68,
                      "height":20},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"339e34caab474151aaad8c809d853433",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":10,
                          "y":0},
                        "size":{
                          "width":68,
                          "height":20},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 销服统计 to 销售明细",
                              "panelsToStates":[{
                                  "panelPath":["6d1ae5dd20824262ad7f0d6c349c3426"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/订单统计/u23.png"}},
{
                  "id":"300650981cff44b3bf9f74a9b0542829",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13383c8962334b7b8ae6fc7135d6b3fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u11.png"}},
{
                  "id":"e28eb8e1e2dc4a94a931666a2024b8b2",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":128,
                      "y":30},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72180e5c0fdf448a9cff1d4d7e704c16",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":128,
                          "y":30},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u11.png"}},
{
                  "id":"11949f0a3c564a50b75972b87460fa05",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":256,
                      "y":30},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee8638b114b24a9f85fea79eab352eec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":256,
                          "y":30},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u11.png"}},
{
                  "id":"73fc37c34f3c4c299c1cbb9534c9707b",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":383,
                      "y":30},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06061630cfa446dead67f473b195d5f9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":383,
                          "y":30},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u11.png"}},
{
                  "id":"35d52b7d02d6484a9b42c1d29b335003",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":59},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"04ff1e2d27c8427aae2756b9511aa66c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":59},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"c2331d3ebf9547c19cd27c7528beb7e5",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":128,
                      "y":59},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"480b576a31d54d4e94b1c35b5ff50e30",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":128,
                          "y":59},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"3fb7540ed43d4473b39921f87775db08",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":255,
                      "y":59},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eca72598f2c440a388d583dd9bc0b5c3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":255,
                          "y":59},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"584b2dad9ecc46e0beea7093c08f83eb",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":383,
                      "y":59},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f5e6987f087a43b8887238a3cd1b2b9e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":383,
                          "y":59},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"57638256675246e09e71cafb8247a40b",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":510,
                      "y":30},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"81976f985d824103892849e4c1fb97e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":510,
                          "y":30},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u11.png"}},
{
                  "id":"0f74657d2e454ff3842eb5ce6b99d6af",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":510,
                      "y":59},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"40acef079a8142989b91239fa5a29802",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":510,
                          "y":59},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"1c349dcc4b7a44c7901e51a3ec4c389d",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":88},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71ba00b89f3845088bd8c9c5624d923e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"ca2e02967f6f43d99550633e376cbf0c",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":128,
                      "y":88},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"96351c78c33145e2a1981ffb6b177820",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":128,
                          "y":88},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"b2d3cf139a5c4c0d954692adefa12c07",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":255,
                      "y":88},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a9d4634d31174fb3be5b7d835fcf89c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":255,
                          "y":88},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"bd735a1c4581408f800319e56d0cdf2a",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":383,
                      "y":88},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45ef5b30a9c54e49acd910d11dbb13a1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":383,
                          "y":88},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"5cbc246d3c704e239ea9aa87db378c69",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":510,
                      "y":88},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1db6ae72d1e2477e826752097d4449f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":510,
                          "y":88},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"a68cfa7d3acf42af96da68b00b9b3399",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":638,
                      "y":30},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe4bfa41994b43f88630248cd3219ae6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":638,
                          "y":30},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u11.png"}},
{
                  "id":"876fba1b08c74015bd7fcda2ea53f66d",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":765,
                      "y":30},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b7347844867f4d27b2df0e0f6fb23ccf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":765,
                          "y":30},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u11.png"}},
{
                  "id":"02f545f963294fd1896f809bd6b3e2b3",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":637,
                      "y":59},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b74dc4b723cc412583e04544a7367819",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":637,
                          "y":59},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"66e3626769ae45c28d985438df32eb72",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":765,
                      "y":59},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"203c31c766da441b83c637607a1ff7a1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":765,
                          "y":59},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"5977137e1d924015b3fd457e1b915740",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":892,
                      "y":30},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efb9252bfeb64b23968b2fd783563dcf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":892,
                          "y":30},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u11.png"}},
{
                  "id":"bf00bad8886045d583fa6aea4db14d38",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":892,
                      "y":59},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f2dd5aea43a42fea52a2bb6c83ba06f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":892,
                          "y":59},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"a78269460c414a338cde22c87ebf0cca",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":637,
                      "y":88},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd826fcb878f41e7904aa6c4f52ded36",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":637,
                          "y":88},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"e0c64c0a3f1d4a1e80b7b3c228e62541",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":765,
                      "y":88},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1e1a0d023b148bf96c6fc7d43d3ef56",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":765,
                          "y":88},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"f2ff775c0a534887a7dfe61930d82d75",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":892,
                      "y":88},
                    "size":{
                      "width":128,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b0fbd153007475f9c349e0f2525ef6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":892,
                          "y":88},
                        "size":{
                          "width":128,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户销服明细/u19.png"}},
{
                  "id":"f099295c3136432584a4f3af1dc8d410",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":80,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":20},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1950b2d985d2417eaae2b811d55cff66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":80,
                          "y":0},
                        "size":{
                          "width":90,
                          "height":20},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 销服统计 to 服务明细",
                              "panelsToStates":[{
                                  "panelPath":["6d1ae5dd20824262ad7f0d6c349c3426"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/商户销服明细/u59.png"}}]},
{
              "id":"3847c30af66c48e4991eb9206f1cf4b1",
              "label":"服务明细",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"794e5fbe96e24b478d662472d9e50358",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC},
                    "size":{
                      "width":1020,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13901c4ccc914d168765578cd524336d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC},
                        "size":{
                          "width":1020,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/订单统计/u7.png"}},
{
                  "id":"f36f333048f2486287d497ca268b72ef",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":10,
                      "y":0},
                    "size":{
                      "width":68,
                      "height":20},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e29163c7e3504ee2a950719953c147b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":10,
                          "y":0},
                        "size":{
                          "width":68,
                          "height":20},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 销服统计 to 销售明细",
                              "panelsToStates":[{
                                  "panelPath":["6d1ae5dd20824262ad7f0d6c349c3426"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/订单统计/u23.png"}},
{
                  "id":"ac9368d65a2b474bba00580a20b9f320",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":80,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":20},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7efa4c9e5a8d42c4beade34dc09191db",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":80,
                          "y":0},
                        "size":{
                          "width":90,
                          "height":20},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 销服统计 to 服务明细",
                              "panelsToStates":[{
                                  "panelPath":["6d1ae5dd20824262ad7f0d6c349c3426"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/商户销服明细/u59.png"}},
{
                  "id":"bc834b7a3fd4483eace3090f502cf17f",
                  "label":"",
                  "parentDynamicPanel":"6d1ae5dd20824262ad7f0d6c349c3426",
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":1020,
                      "height":90}},
                  "adaptiveStyles":{
}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "7085214dd9f243598fd4c503190c0543":{
      "scriptId":"u0"},
    "10cb263da41c4aa1891f8716ed29e1b7":{
      "scriptId":"u1"},
    "c1226c4047244a1baeea605eb0c85bc8":{
      "scriptId":"u2"},
    "f7c63f1722f846189ebf24b4056b44d4":{
      "scriptId":"u3"},
    "f09f2c0ca45242e08ca36d3454958cd8":{
      "scriptId":"u4"},
    "c5a14c4678654d45bdc860d6793b87f8":{
      "scriptId":"u5"},
    "6d1ae5dd20824262ad7f0d6c349c3426":{
      "scriptId":"u6"},
    "9cf266cc610c40d3a07ace40fe3e6472":{
      "scriptId":"u7"},
    "bf26382f1ddc410fbf602a870ca7c1d0":{
      "scriptId":"u8"},
    "79b09e20d7a54db0b32f0dddc01af285":{
      "scriptId":"u9"},
    "339e34caab474151aaad8c809d853433":{
      "scriptId":"u10"},
    "300650981cff44b3bf9f74a9b0542829":{
      "scriptId":"u11"},
    "13383c8962334b7b8ae6fc7135d6b3fd":{
      "scriptId":"u12"},
    "e28eb8e1e2dc4a94a931666a2024b8b2":{
      "scriptId":"u13"},
    "72180e5c0fdf448a9cff1d4d7e704c16":{
      "scriptId":"u14"},
    "11949f0a3c564a50b75972b87460fa05":{
      "scriptId":"u15"},
    "ee8638b114b24a9f85fea79eab352eec":{
      "scriptId":"u16"},
    "73fc37c34f3c4c299c1cbb9534c9707b":{
      "scriptId":"u17"},
    "06061630cfa446dead67f473b195d5f9":{
      "scriptId":"u18"},
    "35d52b7d02d6484a9b42c1d29b335003":{
      "scriptId":"u19"},
    "04ff1e2d27c8427aae2756b9511aa66c":{
      "scriptId":"u20"},
    "c2331d3ebf9547c19cd27c7528beb7e5":{
      "scriptId":"u21"},
    "480b576a31d54d4e94b1c35b5ff50e30":{
      "scriptId":"u22"},
    "3fb7540ed43d4473b39921f87775db08":{
      "scriptId":"u23"},
    "eca72598f2c440a388d583dd9bc0b5c3":{
      "scriptId":"u24"},
    "584b2dad9ecc46e0beea7093c08f83eb":{
      "scriptId":"u25"},
    "f5e6987f087a43b8887238a3cd1b2b9e":{
      "scriptId":"u26"},
    "57638256675246e09e71cafb8247a40b":{
      "scriptId":"u27"},
    "81976f985d824103892849e4c1fb97e2":{
      "scriptId":"u28"},
    "0f74657d2e454ff3842eb5ce6b99d6af":{
      "scriptId":"u29"},
    "40acef079a8142989b91239fa5a29802":{
      "scriptId":"u30"},
    "1c349dcc4b7a44c7901e51a3ec4c389d":{
      "scriptId":"u31"},
    "71ba00b89f3845088bd8c9c5624d923e":{
      "scriptId":"u32"},
    "ca2e02967f6f43d99550633e376cbf0c":{
      "scriptId":"u33"},
    "96351c78c33145e2a1981ffb6b177820":{
      "scriptId":"u34"},
    "b2d3cf139a5c4c0d954692adefa12c07":{
      "scriptId":"u35"},
    "a9d4634d31174fb3be5b7d835fcf89c1":{
      "scriptId":"u36"},
    "bd735a1c4581408f800319e56d0cdf2a":{
      "scriptId":"u37"},
    "45ef5b30a9c54e49acd910d11dbb13a1":{
      "scriptId":"u38"},
    "5cbc246d3c704e239ea9aa87db378c69":{
      "scriptId":"u39"},
    "1db6ae72d1e2477e826752097d4449f5":{
      "scriptId":"u40"},
    "a68cfa7d3acf42af96da68b00b9b3399":{
      "scriptId":"u41"},
    "fe4bfa41994b43f88630248cd3219ae6":{
      "scriptId":"u42"},
    "876fba1b08c74015bd7fcda2ea53f66d":{
      "scriptId":"u43"},
    "b7347844867f4d27b2df0e0f6fb23ccf":{
      "scriptId":"u44"},
    "02f545f963294fd1896f809bd6b3e2b3":{
      "scriptId":"u45"},
    "b74dc4b723cc412583e04544a7367819":{
      "scriptId":"u46"},
    "66e3626769ae45c28d985438df32eb72":{
      "scriptId":"u47"},
    "203c31c766da441b83c637607a1ff7a1":{
      "scriptId":"u48"},
    "5977137e1d924015b3fd457e1b915740":{
      "scriptId":"u49"},
    "efb9252bfeb64b23968b2fd783563dcf":{
      "scriptId":"u50"},
    "bf00bad8886045d583fa6aea4db14d38":{
      "scriptId":"u51"},
    "8f2dd5aea43a42fea52a2bb6c83ba06f":{
      "scriptId":"u52"},
    "a78269460c414a338cde22c87ebf0cca":{
      "scriptId":"u53"},
    "cd826fcb878f41e7904aa6c4f52ded36":{
      "scriptId":"u54"},
    "e0c64c0a3f1d4a1e80b7b3c228e62541":{
      "scriptId":"u55"},
    "b1e1a0d023b148bf96c6fc7d43d3ef56":{
      "scriptId":"u56"},
    "f2ff775c0a534887a7dfe61930d82d75":{
      "scriptId":"u57"},
    "4b0fbd153007475f9c349e0f2525ef6c":{
      "scriptId":"u58"},
    "f099295c3136432584a4f3af1dc8d410":{
      "scriptId":"u59"},
    "1950b2d985d2417eaae2b811d55cff66":{
      "scriptId":"u60"},
    "794e5fbe96e24b478d662472d9e50358":{
      "scriptId":"u61"},
    "13901c4ccc914d168765578cd524336d":{
      "scriptId":"u62"},
    "f36f333048f2486287d497ca268b72ef":{
      "scriptId":"u63"},
    "e29163c7e3504ee2a950719953c147b5":{
      "scriptId":"u64"},
    "ac9368d65a2b474bba00580a20b9f320":{
      "scriptId":"u65"},
    "7efa4c9e5a8d42c4beade34dc09191db":{
      "scriptId":"u66"},
    "bc834b7a3fd4483eace3090f502cf17f":{
      "scriptId":"u67"}}});