$axure.loadCurrentPage({
  "url":"修改记录.html",
  "generationDate":new Date(1444989698295.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"777b619eb9ed4a27a112191487ed4c79",
    "type":"Axure:Page",
    "name":"修改记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aef9b77a46aa4f31bd4f124aa99ce3d3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":30},
            "size":{
              "width":1000,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98d021b5e24f422b97ca40784f4dcfc0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":0},
                "size":{
                  "width":700,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6943dcbc6b147b7a78aaaeb8091f8ec",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":0},
                    "size":{
                      "width":700,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u3.png"}},
{
              "id":"573c337260344d579e36e90a9ecea9d5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":30},
                "size":{
                  "width":700,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd66954bb1914477b8d69daec862ebc9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":30},
                    "size":{
                      "width":700,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u3.png"}},
{
              "id":"1a23f27a5ac541e485c1f657fd04d767",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":0},
                "size":{
                  "width":139,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81a7ba92480c49fbbe8f6f44d547a6ab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":0},
                    "size":{
                      "width":139,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u5.png"}},
{
              "id":"d1f42a2dde2947ae97e009176d1afc94",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":30},
                "size":{
                  "width":139,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"958508949460444380fd3193c3f9fe3a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":30},
                    "size":{
                      "width":139,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u5.png"}},
{
              "id":"81a81e40e88348bd9535a8212f45c296",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "size":{
                  "width":161,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89b078bea93e45cbbead6c1e5eb1cea8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":161,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u1.png"}},
{
              "id":"2c06d85dd9b845498cce3238beaf7b96",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":161,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"825aaf92ad7348a5a11bb7cf5e2dcac8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":161,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u1.png"}},
{
              "id":"800324b0140843e7ba7f95019af1aed0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":161,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b3738628a234fa49346d7ab06e22b5a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":161,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u1.png"}},
{
              "id":"1ff01e0b9b1b4550ad9f88caab3fede1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":60},
                "size":{
                  "width":700,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"124c840503744b7ca54f912740db49e2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":60},
                    "size":{
                      "width":700,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u3.png"}},
{
              "id":"254fb5ad9c54457c8be50135ebcf2324",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF00,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":60},
                "size":{
                  "width":139,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"33f372635de4464b90449588f9fb4055",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":60},
                    "size":{
                      "width":139,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u5.png"}},
{
              "id":"280cee1ca6394f25a7e20b58e8c5af79",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":161,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ad96f9e59c9b43669b1ebf1857d72426",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":161,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u1.png"}},
{
              "id":"b229b405712b4ad9a010f954e3fb52af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":90},
                "size":{
                  "width":700,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b38aebd99f3241d8a7528c063f514bd4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":90},
                    "size":{
                      "width":700,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u3.png"}},
{
              "id":"8e336c24f348404f903595765f50a539",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":90},
                "size":{
                  "width":139,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dce3a0cdd5cc4458a745ecf2823702b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":90},
                    "size":{
                      "width":139,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u5.png"}},
{
              "id":"2e4b7595fcf04ef59f02097c2048001a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":161,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4cedd3bf1f854bb4a98bafcbbb6f3aab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":161,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u25.png"}},
{
              "id":"f77ecf4c7201422abcc09bd224ca9c50",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":161,
                  "y":120},
                "size":{
                  "width":700,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"22960f73fb764c149d1ae6795502e213",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":161,
                      "y":120},
                    "size":{
                      "width":700,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u27.png"}},
{
              "id":"81dc0a85e7b64544b2b0c60385d74f5d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":861,
                  "y":120},
                "size":{
                  "width":139,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b08c8ecc4c964ed8975437b934da2ae6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":861,
                      "y":120},
                    "size":{
                      "width":139,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/修改记录/u29.png"}}]},
{
          "id":"433d5ec4dc9e43f893e408c25ae882a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":1272},
            "size":{
              "width":1371,
              "height":198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4065c7d6357430f80d87e080e06be55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":1272},
                "size":{
                  "width":1371,
                  "height":198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改记录/u31.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "aef9b77a46aa4f31bd4f124aa99ce3d3":{
      "scriptId":"u0"},
    "81a81e40e88348bd9535a8212f45c296":{
      "scriptId":"u1"},
    "89b078bea93e45cbbead6c1e5eb1cea8":{
      "scriptId":"u2"},
    "98d021b5e24f422b97ca40784f4dcfc0":{
      "scriptId":"u3"},
    "b6943dcbc6b147b7a78aaaeb8091f8ec":{
      "scriptId":"u4"},
    "1a23f27a5ac541e485c1f657fd04d767":{
      "scriptId":"u5"},
    "81a7ba92480c49fbbe8f6f44d547a6ab":{
      "scriptId":"u6"},
    "2c06d85dd9b845498cce3238beaf7b96":{
      "scriptId":"u7"},
    "825aaf92ad7348a5a11bb7cf5e2dcac8":{
      "scriptId":"u8"},
    "573c337260344d579e36e90a9ecea9d5":{
      "scriptId":"u9"},
    "dd66954bb1914477b8d69daec862ebc9":{
      "scriptId":"u10"},
    "d1f42a2dde2947ae97e009176d1afc94":{
      "scriptId":"u11"},
    "958508949460444380fd3193c3f9fe3a":{
      "scriptId":"u12"},
    "800324b0140843e7ba7f95019af1aed0":{
      "scriptId":"u13"},
    "3b3738628a234fa49346d7ab06e22b5a":{
      "scriptId":"u14"},
    "1ff01e0b9b1b4550ad9f88caab3fede1":{
      "scriptId":"u15"},
    "124c840503744b7ca54f912740db49e2":{
      "scriptId":"u16"},
    "254fb5ad9c54457c8be50135ebcf2324":{
      "scriptId":"u17"},
    "33f372635de4464b90449588f9fb4055":{
      "scriptId":"u18"},
    "280cee1ca6394f25a7e20b58e8c5af79":{
      "scriptId":"u19"},
    "ad96f9e59c9b43669b1ebf1857d72426":{
      "scriptId":"u20"},
    "b229b405712b4ad9a010f954e3fb52af":{
      "scriptId":"u21"},
    "b38aebd99f3241d8a7528c063f514bd4":{
      "scriptId":"u22"},
    "8e336c24f348404f903595765f50a539":{
      "scriptId":"u23"},
    "dce3a0cdd5cc4458a745ecf2823702b1":{
      "scriptId":"u24"},
    "2e4b7595fcf04ef59f02097c2048001a":{
      "scriptId":"u25"},
    "4cedd3bf1f854bb4a98bafcbbb6f3aab":{
      "scriptId":"u26"},
    "f77ecf4c7201422abcc09bd224ca9c50":{
      "scriptId":"u27"},
    "22960f73fb764c149d1ae6795502e213":{
      "scriptId":"u28"},
    "81dc0a85e7b64544b2b0c60385d74f5d":{
      "scriptId":"u29"},
    "b08c8ecc4c964ed8975437b934da2ae6":{
      "scriptId":"u30"},
    "433d5ec4dc9e43f893e408c25ae882a5":{
      "scriptId":"u31"},
    "c4065c7d6357430f80d87e080e06be55":{
      "scriptId":"u32"}}});