$axure.loadCurrentPage({
  "url":"演示.html",
  "generationDate":new Date(1444989698768.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"15df4b3e81bc402ab932013e401faeaa",
    "type":"Axure:Page",
    "name":"演示",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"91a83de5e8c24a908e4d9ca19febe960",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":48},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"747203ee997742589fbe13f2a9d03cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":48},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/演示/u0.png"}},
{
          "id":"fcdfa981d7e146a89ad0167b333b2019",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":231,
              "y":180},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "91a83de5e8c24a908e4d9ca19febe960":{
      "scriptId":"u0"},
    "747203ee997742589fbe13f2a9d03cf2":{
      "scriptId":"u1"},
    "fcdfa981d7e146a89ad0167b333b2019":{
      "scriptId":"u2"}}});