$axure.loadCurrentPage({
  "url":"业务模式.html",
  "generationDate":new Date(1474884129376.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5a0cdb0f05cf49b1affee077247b65ac",
    "type":"Axure:Page",
    "name":"业务模式",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"34335d6d1ba74e8e8b6a7496f25812ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df82a3d0c8144a20b1b6a4779fbea6cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"69d40c0b7f7c4bdba4bd00b203f4c2ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19af496d6e214453980a0aa0cef7e79f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"f0a58ea26c9443f9bc62f10a3fee5cbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":51},
            "size":{
              "width":129,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582f8a195af9416b92724b3331160b0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":123,
                  "y":51},
                "size":{
                  "width":129,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b1f7d904f2a428a9ace2f8956c56f3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":89},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44eb6bfa7c994fab81d4e76536b5f359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":89},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f01a6dbcf304afaa385d123cafd2271",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":126,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84fcfed980c0436ba933b0db574d87ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":126,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u26.png"}},
{
          "id":"20a74253527045ada23d610cea8ce643",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":130},
            "size":{
              "width":126,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b336a4daf8f4310be0d622af3dc676d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":130},
                "size":{
                  "width":126,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u26.png"}},
{
          "id":"bc432a2659fc4c84a79a9f68bc04ef5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":130},
            "size":{
              "width":126,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"560afbd698ed43a3bb8f065a58d69197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":130},
                "size":{
                  "width":126,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u26.png"}},
{
          "id":"2582f4291da344f0a723b5939c0c28e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":157.5,
              "y":180},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45e507a80ed247f883541f5229c6a02c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":157.5,
                  "y":180},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"32db24996c094e07b56f5cc9206456ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":214},
            "size":{
              "width":346,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ede05d5e59274955b00a5adfe0cf1112",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":214},
                "size":{
                  "width":346,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f90ce19a763d451daf04e3203cdaed72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":24,
              "y":300},
            "size":{
              "width":326,
              "height":205}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b279c4f068c47f4b4ea16229de70093",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":24,
                  "y":300},
                "size":{
                  "width":326,
                  "height":205}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务模式/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "34335d6d1ba74e8e8b6a7496f25812ae":{
      "scriptId":"u0"},
    "df82a3d0c8144a20b1b6a4779fbea6cb":{
      "scriptId":"u1"},
    "69d40c0b7f7c4bdba4bd00b203f4c2ef":{
      "scriptId":"u2"},
    "19af496d6e214453980a0aa0cef7e79f":{
      "scriptId":"u3"},
    "f0a58ea26c9443f9bc62f10a3fee5cbb":{
      "scriptId":"u4"},
    "582f8a195af9416b92724b3331160b0e":{
      "scriptId":"u5"},
    "8b1f7d904f2a428a9ace2f8956c56f3a":{
      "scriptId":"u6"},
    "44eb6bfa7c994fab81d4e76536b5f359":{
      "scriptId":"u7"},
    "5f01a6dbcf304afaa385d123cafd2271":{
      "scriptId":"u8"},
    "84fcfed980c0436ba933b0db574d87ca":{
      "scriptId":"u9"},
    "20a74253527045ada23d610cea8ce643":{
      "scriptId":"u10"},
    "9b336a4daf8f4310be0d622af3dc676d":{
      "scriptId":"u11"},
    "bc432a2659fc4c84a79a9f68bc04ef5b":{
      "scriptId":"u12"},
    "560afbd698ed43a3bb8f065a58d69197":{
      "scriptId":"u13"},
    "2582f4291da344f0a723b5939c0c28e2":{
      "scriptId":"u14"},
    "45e507a80ed247f883541f5229c6a02c":{
      "scriptId":"u15"},
    "32db24996c094e07b56f5cc9206456ab":{
      "scriptId":"u16"},
    "ede05d5e59274955b00a5adfe0cf1112":{
      "scriptId":"u17"},
    "f90ce19a763d451daf04e3203cdaed72":{
      "scriptId":"u18"},
    "4b279c4f068c47f4b4ea16229de70093":{
      "scriptId":"u19"}}});