$axure.loadCurrentPage({
  "url":"我的排号.html",
  "generationDate":new Date(1473824949270.82),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b6916fdc7a5445b09c86d0e5be6de926",
    "type":"Axure:Page",
    "name":"我的排号",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8d17236b596b405e852854b977129dc0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":173}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"005a037c1c5d4463adff7f4cde2be05b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":173}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特供商城/u0.png"}},
{
          "id":"f6c0c0b83e9d4f2190c5b9477b577c46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":211},
            "size":{
              "width":90,
              "height":544}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"284131692da448fb867b78546ad293f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":211},
                "size":{
                  "width":90,
                  "height":544}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的排号/u2.png"}},
{
          "id":"5e979aab9d7843ccbc6170dc41b59936",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":220,
              "y":200},
            "size":{
              "width":880,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6a646b5643d4cb0ae789fdfd8c727ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":220,
                  "y":200},
                "size":{
                  "width":880,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的排号/u4.png"}},
{
          "id":"8723d9c805b14d09b00790bf661315a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":211},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef249658df114a2285ca2c020bd8da88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":211},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d9433ca033f40648970bbc9da02571d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":220,
              "y":258},
            "size":{
              "width":880,
              "height":42},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0caab280d6f043bda9603ad39282430d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":220,
                  "y":258},
                "size":{
                  "width":880,
                  "height":42},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的排号/u8.png"}},
{
          "id":"bdd4d06c31f8400991aba4f43c53974d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":270},
            "size":{
              "width":787,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8af3ca96b3fe4a6da5cb017fc9aebbdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":270},
                "size":{
                  "width":787,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3653c5fdb28e4e1b99e5d309c32ed99f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":229,
              "y":340},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de14bf8a55ae487a8b704fe97e7b6e19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":229,
                  "y":340},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9dedf19541284ef9951ae4c83148c703",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":340},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d205c7a058d41ce9eafb0335ede9489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":340},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d77b7bb9ef6042a5b44b04e6c56dfb66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":553,
              "y":340},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f2026a188845a99d4bfbdd0bb5cee7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":553,
                  "y":340},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba89dffe14844f0484e3a45e463dab78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":340},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b6d947c9b3c4a8ebca0ab13400a3867",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":340},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e717a8b3748e4a3387d474ad523f67ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":340},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4019d033a2424d3aa5724bf81f29e033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":340},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35c48df15b2344568636d324de287c33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":340},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0922e8ee08e34ca49c4874877e8e3060",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":871,
                  "y":340},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb3f67f28e9c4fbda2eda0c0b28cc827",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":335},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e2060c280eb247ecbba2ce6b5d20ecc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":229,
              "y":375},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c58e74e9f5a249b8b7c3ae372c028f0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":229,
                  "y":375},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06e1cdad4fed4bb08ac2cf502fd494cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":375},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58e35234791a404ab24d026c13ebedd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":375},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4aa0b3432604985995b308fffe2f856",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":553,
              "y":375},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94b099bef33e4274b8289a37d249e400",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":553,
                  "y":375},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a50690bcbcd24ba883d0d438f82c200b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":375},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cae86a15cb334ccb925604f056487e4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":375},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a70aa2b3dca40f8abefcc0df3f1d3d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":375},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e67f8d119094456fa86ec433d3a991b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":375},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc5e0ccf616c4b4eb17500090270ec71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":375},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6548d35f01b34ece8b711aaf09736dbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":871,
                  "y":375},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"970cf4881b8942e4aafcc2f57d1b676b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":370},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选房",
                      "target":{
                        "targetType":"page",
                        "url":"选房.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b3f4efd0d9854ab88fcd57d6646a6699",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":229,
              "y":410},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bb8e347fd1a46149bb48668b9e324ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":229,
                  "y":410},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04e074bb16ca4045b209b878e15c140e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":410},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0aef58772f14a9296079761c045a3b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":410},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d74b082123d4e5e875c3d3acaf4ca99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":553,
              "y":410},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1df2cde4f0f64401af0e4b8e3e9b605f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":553,
                  "y":410},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"559157a9a4f5419c849ad5da6b0be49d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":410},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ff5307571c4b60b79e0cebeef402b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":410},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a986bca0caa045aaa2e789e283d2e88e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":410},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"155aa7be57dd4a71875fa24519d78377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":410},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05b4fd5d3c014e99834f7f7e493d6704",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":410},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cbbc2cdaf464b399997a3e03e6373f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":871,
                  "y":410},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e45da693e8aa42188c56f3de499af793",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":405},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e6f3612519ae4520b716d8540037d033",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":229,
              "y":445},
            "size":{
              "width":162,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37bb6ff4214a448997e2f0d8bc56d9e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":229,
                  "y":445},
                "size":{
                  "width":162,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"412b8217b6224092b93ee3c3eea51ac0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":406,
              "y":445},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfae6190aa364827a24f824cf507a5e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":406,
                  "y":445},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11dfb6d460d541e88e49da01839c873f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":553,
              "y":445},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"919b2ec20dc64b35876ca88e6ddcc65c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":553,
                  "y":445},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d90e109bb3d410686156ce3a61027b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":647,
              "y":445},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07db7dfdb7da4bb08bf82c4b60345d54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":647,
                  "y":445},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40801629067b47ae88bc1e0ca1020da1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":445},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caf42a9576fa4849a2386daf4d5c671b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":770,
                  "y":445},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"547a4dd0e36d44aa872e3c2348c5f084",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":445},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25f92476d5434fc9bd96eca2225c01cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":871,
                  "y":445},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a77b66b34f9e4fc8bba4546456577a21",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":440},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "8d17236b596b405e852854b977129dc0":{
      "scriptId":"u0"},
    "005a037c1c5d4463adff7f4cde2be05b":{
      "scriptId":"u1"},
    "f6c0c0b83e9d4f2190c5b9477b577c46":{
      "scriptId":"u2"},
    "284131692da448fb867b78546ad293f0":{
      "scriptId":"u3"},
    "5e979aab9d7843ccbc6170dc41b59936":{
      "scriptId":"u4"},
    "b6a646b5643d4cb0ae789fdfd8c727ae":{
      "scriptId":"u5"},
    "8723d9c805b14d09b00790bf661315a0":{
      "scriptId":"u6"},
    "ef249658df114a2285ca2c020bd8da88":{
      "scriptId":"u7"},
    "7d9433ca033f40648970bbc9da02571d":{
      "scriptId":"u8"},
    "0caab280d6f043bda9603ad39282430d":{
      "scriptId":"u9"},
    "bdd4d06c31f8400991aba4f43c53974d":{
      "scriptId":"u10"},
    "8af3ca96b3fe4a6da5cb017fc9aebbdd":{
      "scriptId":"u11"},
    "3653c5fdb28e4e1b99e5d309c32ed99f":{
      "scriptId":"u12"},
    "de14bf8a55ae487a8b704fe97e7b6e19":{
      "scriptId":"u13"},
    "9dedf19541284ef9951ae4c83148c703":{
      "scriptId":"u14"},
    "7d205c7a058d41ce9eafb0335ede9489":{
      "scriptId":"u15"},
    "d77b7bb9ef6042a5b44b04e6c56dfb66":{
      "scriptId":"u16"},
    "07f2026a188845a99d4bfbdd0bb5cee7":{
      "scriptId":"u17"},
    "ba89dffe14844f0484e3a45e463dab78":{
      "scriptId":"u18"},
    "8b6d947c9b3c4a8ebca0ab13400a3867":{
      "scriptId":"u19"},
    "e717a8b3748e4a3387d474ad523f67ff":{
      "scriptId":"u20"},
    "4019d033a2424d3aa5724bf81f29e033":{
      "scriptId":"u21"},
    "35c48df15b2344568636d324de287c33":{
      "scriptId":"u22"},
    "0922e8ee08e34ca49c4874877e8e3060":{
      "scriptId":"u23"},
    "cb3f67f28e9c4fbda2eda0c0b28cc827":{
      "scriptId":"u24"},
    "e2060c280eb247ecbba2ce6b5d20ecc3":{
      "scriptId":"u25"},
    "c58e74e9f5a249b8b7c3ae372c028f0e":{
      "scriptId":"u26"},
    "06e1cdad4fed4bb08ac2cf502fd494cf":{
      "scriptId":"u27"},
    "58e35234791a404ab24d026c13ebedd6":{
      "scriptId":"u28"},
    "f4aa0b3432604985995b308fffe2f856":{
      "scriptId":"u29"},
    "94b099bef33e4274b8289a37d249e400":{
      "scriptId":"u30"},
    "a50690bcbcd24ba883d0d438f82c200b":{
      "scriptId":"u31"},
    "cae86a15cb334ccb925604f056487e4f":{
      "scriptId":"u32"},
    "7a70aa2b3dca40f8abefcc0df3f1d3d0":{
      "scriptId":"u33"},
    "e67f8d119094456fa86ec433d3a991b5":{
      "scriptId":"u34"},
    "bc5e0ccf616c4b4eb17500090270ec71":{
      "scriptId":"u35"},
    "6548d35f01b34ece8b711aaf09736dbf":{
      "scriptId":"u36"},
    "970cf4881b8942e4aafcc2f57d1b676b":{
      "scriptId":"u37"},
    "b3f4efd0d9854ab88fcd57d6646a6699":{
      "scriptId":"u38"},
    "6bb8e347fd1a46149bb48668b9e324ad":{
      "scriptId":"u39"},
    "04e074bb16ca4045b209b878e15c140e":{
      "scriptId":"u40"},
    "a0aef58772f14a9296079761c045a3b5":{
      "scriptId":"u41"},
    "7d74b082123d4e5e875c3d3acaf4ca99":{
      "scriptId":"u42"},
    "1df2cde4f0f64401af0e4b8e3e9b605f":{
      "scriptId":"u43"},
    "559157a9a4f5419c849ad5da6b0be49d":{
      "scriptId":"u44"},
    "20ff5307571c4b60b79e0cebeef402b7":{
      "scriptId":"u45"},
    "a986bca0caa045aaa2e789e283d2e88e":{
      "scriptId":"u46"},
    "155aa7be57dd4a71875fa24519d78377":{
      "scriptId":"u47"},
    "05b4fd5d3c014e99834f7f7e493d6704":{
      "scriptId":"u48"},
    "1cbbc2cdaf464b399997a3e03e6373f1":{
      "scriptId":"u49"},
    "e45da693e8aa42188c56f3de499af793":{
      "scriptId":"u50"},
    "e6f3612519ae4520b716d8540037d033":{
      "scriptId":"u51"},
    "37bb6ff4214a448997e2f0d8bc56d9e3":{
      "scriptId":"u52"},
    "412b8217b6224092b93ee3c3eea51ac0":{
      "scriptId":"u53"},
    "cfae6190aa364827a24f824cf507a5e8":{
      "scriptId":"u54"},
    "11dfb6d460d541e88e49da01839c873f":{
      "scriptId":"u55"},
    "919b2ec20dc64b35876ca88e6ddcc65c":{
      "scriptId":"u56"},
    "7d90e109bb3d410686156ce3a61027b5":{
      "scriptId":"u57"},
    "07db7dfdb7da4bb08bf82c4b60345d54":{
      "scriptId":"u58"},
    "40801629067b47ae88bc1e0ca1020da1":{
      "scriptId":"u59"},
    "caf42a9576fa4849a2386daf4d5c671b":{
      "scriptId":"u60"},
    "547a4dd0e36d44aa872e3c2348c5f084":{
      "scriptId":"u61"},
    "25f92476d5434fc9bd96eca2225c01cd":{
      "scriptId":"u62"},
    "a77b66b34f9e4fc8bba4546456577a21":{
      "scriptId":"u63"}}});