$axure.loadCurrentPage({
  "url":"商品信息统计.html",
  "generationDate":new Date(1455876388271.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"41564935e2c24d7b8f037dd52733071b",
    "type":"Axure:Page",
    "name":"商品信息统计",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b5edb832da32481ca330e14b83eb395e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":643}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"742fbb2b3561489daff8e63699066b20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":643}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u0.png"}},
{
          "id":"add54c5659cf411ab5eb03cae17cbb40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":170,
              "y":82},
            "size":{
              "width":140,
              "height":28},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fa3a6af9522447ca7a7a6b41474619d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":170,
                  "y":82},
                "size":{
                  "width":140,
                  "height":28},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u235.png"}},
{
          "id":"8eef412dfa2d43c49cd7262bef7bdb8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":1028,
              "y":82},
            "size":{
              "width":120,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12064ab6da4042a6b341be905934db03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":1028,
                  "y":82},
                "size":{
                  "width":120,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u237.png"}},
{
          "id":"9ad0a8e8b06e465d9e8660682bbd3055",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCE0EC},
            "location":{
              "x":170,
              "y":120},
            "size":{
              "width":1020,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d37a9122d8c44f4a9a59a0d3aa45de3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCE0EC},
                "location":{
                  "x":170,
                  "y":120},
                "size":{
                  "width":1020,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员购买统计/u2.png"}},
{
          "id":"c7e8db3be853455b85f2e635b398b9c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF438EB9},
            "location":{
              "x":170,
              "y":157},
            "size":{
              "width":1030,
              "height":33},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33c61c127ff146a0b7ad2b2df7352c37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF438EB9},
                "location":{
                  "x":170,
                  "y":157},
                "size":{
                  "width":1030,
                  "height":33},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费明细/u6.png"}},
{
          "id":"861a5991b3254617b731e104aa9d12be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":170,
              "y":190},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f91ea57a7d4486e9f954575624606dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":170,
                  "y":190},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u10.png"}},
{
          "id":"ea68833505ad46d28a3c70efae71bb6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":429,
              "y":190},
            "size":{
              "width":257,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c309086e0254dc8b333fd72ba0c91b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":429,
                  "y":190},
                "size":{
                  "width":257,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u12.png"}},
{
          "id":"724ba259b801449990d6cbb263e210ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":686,
              "y":190},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"347a1c75cb35449c8be06672da7fce60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":686,
                  "y":190},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u10.png"}},
{
          "id":"ac90d80664e348faa72575d0094089e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":942,
              "y":190},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07b30074ce394f21bc47cd651b43df80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":942,
                  "y":190},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u10.png"}},
{
          "id":"fd22e8d6d4244de8a07895d7220bcc38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":170,
              "y":219},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e57d22461e34cc691144a391d89d055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":170,
                  "y":219},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"b48baeb34a914a7c8affee6ca9a7f97a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":428,
              "y":219},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d769b95fccc4a058d3ff35ee3cb272c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":428,
                  "y":219},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"91a7fb7860a745c8952c3f63b4c1bdb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":685,
              "y":219},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"904c0ad3ca484f6fbdbf6d81c59de393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":685,
                  "y":219},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"cbce8d9d226843149d47250d313be179",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":942,
              "y":219},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f0699e0dbb243809634ddddc800e607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":942,
                  "y":219},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"22c9f3523d134b87b3541a9935013158",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":170,
              "y":248},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03e8f5343b6846a2a4f349516369b079",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":170,
                  "y":248},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"847b24835b9446a8b3f23e16c88fa900",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":428,
              "y":248},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6590e21379d546e29ed051268d7dc60f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":428,
                  "y":248},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"0592db1609514d548a1fedafab671e8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":685,
              "y":248},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfdbcd594dcf4c87ad3306e78ad6d777",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":685,
                  "y":248},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"efddfc4f407f4c86b5f8b61bcbb13eb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":942,
              "y":248},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc36ae58414464683b59543b34884f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":942,
                  "y":248},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"c3754bb1399147ad9a0fc482912625a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":170,
              "y":277},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44d9df088d1c4812b960cd27bb441829",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":170,
                  "y":277},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"ee6796fc6e364cd084314db55afd415c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":428,
              "y":277},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efef0a784c644ddd9065f86b60c5d53a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":428,
                  "y":277},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"acf98942aaf842138a2fb900930a9346",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":685,
              "y":277},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9679542388ae4979a72f6cf5e7da5597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":685,
                  "y":277},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"ba0fb43cddaa495fb112cac136bbfd6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":942,
              "y":277},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09a3d654ea3e49acaacb62f46785dbb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":942,
                  "y":277},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"08df4b6b0e2d42a1acd2db85a1eb2569",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":170,
              "y":305},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09ff4030e5c44a599d523558a733f396",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":170,
                  "y":305},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"6a105451c035452c8a1d07dc464cd9b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":428,
              "y":305},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73a726fcacfc46a8aaa900b47c8dfbc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":428,
                  "y":305},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"b357a336804e412d863cdee35ad3b67c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":685,
              "y":305},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d76f4b50ec94e1eb43ed2d2ffd37906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":685,
                  "y":305},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"ebc087e0ecf0481091d7164d1d42e400",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":942,
              "y":305},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa8c185ed35e4312a3027719689de857",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":942,
                  "y":305},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"1479300e375b44bbad74d683f1ef56e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":170,
              "y":334},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6638a81bae3a408c88c242821bf4f5bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":170,
                  "y":334},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"a1a36e991e3248848bb4e9b2ea731f92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":428,
              "y":334},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d29b7a8fa4aa45ebacc256d19d55f41b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":428,
                  "y":334},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"76d09a97495c47d6896fec9457a28aee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":685,
              "y":334},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc7728f214444f7f8873eff20643d520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":685,
                  "y":334},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"21544525643a45a2bf43be2f9152fe71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":942,
              "y":334},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce2f2dc43cd14bfbab4159dc88ec1358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":942,
                  "y":334},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"46ffb9d8a82b42a7b3eb0dc007815eea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":170,
              "y":363},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4080945fbbd749b7a751b032cd60fea3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":170,
                  "y":363},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"96223c1e716c49f290b02a637d4dc08d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":428,
              "y":363},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"899602b2775841e183a5bc80162222a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":428,
                  "y":363},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"49fcf0b8c75949ba9db4f5b65261f317",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":685,
              "y":363},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"770dcd62bcb84641910272132db418fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":685,
                  "y":363},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"58e2b15b493449b9b7cd05b4b6f543f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":942,
              "y":363},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d616c11629545169c705911323e6647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":942,
                  "y":363},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"83daa0030c2243b8bc0ea09c7bb33878",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":170,
              "y":392},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5376ee3d3394e14bce8e03b2add4bb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":170,
                  "y":392},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"4d48bfb1b47b48de83d277d4bb08ca19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":428,
              "y":392},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17333f0376374b448c4b150935c5a046",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":428,
                  "y":392},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"5cc00440aea3488c9835bd822e43d5a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":685,
              "y":392},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"898159a7d79a47da9010049f44a2f120",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":685,
                  "y":392},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"37ad63d0eb85406ba58361aec61a4fb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":942,
              "y":392},
            "size":{
              "width":258,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bbdc4e065c04dfe91cf9306786d8022",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":942,
                  "y":392},
                "size":{
                  "width":258,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品信息统计/u18.png"}},
{
          "id":"67059630f0d344939c04d4513d4de032",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":157,
              "y":456},
            "size":{
              "width":1043,
              "height":331},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0eccf2ecce5f41b482b56b1e828abb38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":157,
                  "y":456},
                "size":{
                  "width":1043,
                  "height":331},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u2.png"}},
{
          "id":"0134ac583bea4fc5a6cc5228252dc0b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "location":{
              "x":176,
              "y":460},
            "size":{
              "width":103,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ad244a0faaf4c02b912665bfa41fc87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "location":{
                  "x":176,
                  "y":460},
                "size":{
                  "width":103,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd1a6430ebee497fa092220389d7f51e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":176,
              "y":516},
            "size":{
              "width":30,
              "height":17},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e70f63628444cb7a9a2692b78f94a36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":176,
                  "y":516},
                "size":{
                  "width":30,
                  "height":17},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u6.png"}},
{
          "id":"7de1a5dba6be48a68d014f074edb6260",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":205,
              "y":516},
            "size":{
              "width":30,
              "height":17},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5650f345302a4648871a6a4ba9a781aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":205,
                  "y":516},
                "size":{
                  "width":30,
                  "height":17},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u8.png"}},
{
          "id":"b42fcf9837514842b892306e7b262d38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":234,
              "y":516},
            "size":{
              "width":30,
              "height":17},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1df67523559413eb8a7cb33a5b1798c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":234,
                  "y":516},
                "size":{
                  "width":30,
                  "height":17},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u8.png"}},
{
          "id":"c61e64c8b56f499ea2dd31aebd7308b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":263,
              "y":516},
            "size":{
              "width":30,
              "height":17},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e31cd5f9b7c849308642b2b032a1a8e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":263,
                  "y":516},
                "size":{
                  "width":30,
                  "height":17},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u8.png"}},
{
          "id":"201b762c102b477880b8f1ca331b0b1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":292,
              "y":516},
            "size":{
              "width":30,
              "height":17},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"701e3f5b350e483b9c8e0a4d8f0c3836",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":292,
                  "y":516},
                "size":{
                  "width":30,
                  "height":17},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u8.png"}},
{
          "id":"44b71a4adb2d4809970d55b2fcbd6da7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "location":{
              "x":340,
              "y":516},
            "size":{
              "width":140,
              "height":17},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de6dbf85de2e4ebe907cb66f860248c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "location":{
                  "x":340,
                  "y":516},
                "size":{
                  "width":140,
                  "height":17},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u16.png"}},
{
          "id":"c983220cae024a988e54fc61ff5b3c95",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":630,
              "y":488},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"541ed8b2a8d94e6eb46780f793ffd6b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":630,
                  "y":488},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"488b73ba807d45db94c9e8264ed430e9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":677},
            "size":{
              "width":160,
              "height":10},
            "rotation":"322"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员统计/u20_line.png"}},
{
          "id":"28cc9713c0454a089d6762c7b40b0ee0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":355,
              "y":657},
            "size":{
              "width":123,
              "height":10},
            "rotation":"30"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员统计/u21_line.png"}},
{
          "id":"1d07e139529e40d4b7cc0e5d6c51e6a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":689},
            "size":{
              "width":140,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员统计/u22_line.png"}},
{
          "id":"60d1d1a9d29d4bca9a06dddd9ba32ee7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":594,
              "y":646},
            "size":{
              "width":140,
              "height":10},
            "rotation":"321"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员统计/u22_line.png"}},
{
          "id":"9fef3de8b5134057a5b6dab7a110d6d2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":637},
            "size":{
              "width":140,
              "height":10},
            "rotation":"30"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员统计/u22_line.png"}},
{
          "id":"ba4bc3e12f5d476787bd2416d6e84acd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":639},
            "size":{
              "width":140,
              "height":10},
            "rotation":"330"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员统计/u22_line.png"}},
{
          "id":"3e097d7fc7a74711a52c153291a0b6c1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":958,
              "y":621},
            "size":{
              "width":140,
              "height":10},
            "rotation":"15"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员统计/u22_line.png"}},
{
          "id":"551fd4ca1e414d27ab9839bacbbf45ac",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":562},
            "size":{
              "width":10,
              "height":200}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员统计/u27_line.png"}},
{
          "id":"311144d4ad444a82a19cf038e252b217",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":191,
              "y":758},
            "size":{
              "width":938,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员统计/u28_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b5edb832da32481ca330e14b83eb395e":{
      "scriptId":"u0"},
    "742fbb2b3561489daff8e63699066b20":{
      "scriptId":"u1"},
    "add54c5659cf411ab5eb03cae17cbb40":{
      "scriptId":"u2"},
    "2fa3a6af9522447ca7a7a6b41474619d":{
      "scriptId":"u3"},
    "8eef412dfa2d43c49cd7262bef7bdb8a":{
      "scriptId":"u4"},
    "12064ab6da4042a6b341be905934db03":{
      "scriptId":"u5"},
    "9ad0a8e8b06e465d9e8660682bbd3055":{
      "scriptId":"u6"},
    "0d37a9122d8c44f4a9a59a0d3aa45de3":{
      "scriptId":"u7"},
    "c7e8db3be853455b85f2e635b398b9c7":{
      "scriptId":"u8"},
    "33c61c127ff146a0b7ad2b2df7352c37":{
      "scriptId":"u9"},
    "861a5991b3254617b731e104aa9d12be":{
      "scriptId":"u10"},
    "9f91ea57a7d4486e9f954575624606dc":{
      "scriptId":"u11"},
    "ea68833505ad46d28a3c70efae71bb6c":{
      "scriptId":"u12"},
    "2c309086e0254dc8b333fd72ba0c91b8":{
      "scriptId":"u13"},
    "724ba259b801449990d6cbb263e210ea":{
      "scriptId":"u14"},
    "347a1c75cb35449c8be06672da7fce60":{
      "scriptId":"u15"},
    "ac90d80664e348faa72575d0094089e8":{
      "scriptId":"u16"},
    "07b30074ce394f21bc47cd651b43df80":{
      "scriptId":"u17"},
    "fd22e8d6d4244de8a07895d7220bcc38":{
      "scriptId":"u18"},
    "5e57d22461e34cc691144a391d89d055":{
      "scriptId":"u19"},
    "b48baeb34a914a7c8affee6ca9a7f97a":{
      "scriptId":"u20"},
    "3d769b95fccc4a058d3ff35ee3cb272c":{
      "scriptId":"u21"},
    "91a7fb7860a745c8952c3f63b4c1bdb7":{
      "scriptId":"u22"},
    "904c0ad3ca484f6fbdbf6d81c59de393":{
      "scriptId":"u23"},
    "cbce8d9d226843149d47250d313be179":{
      "scriptId":"u24"},
    "0f0699e0dbb243809634ddddc800e607":{
      "scriptId":"u25"},
    "22c9f3523d134b87b3541a9935013158":{
      "scriptId":"u26"},
    "03e8f5343b6846a2a4f349516369b079":{
      "scriptId":"u27"},
    "847b24835b9446a8b3f23e16c88fa900":{
      "scriptId":"u28"},
    "6590e21379d546e29ed051268d7dc60f":{
      "scriptId":"u29"},
    "0592db1609514d548a1fedafab671e8c":{
      "scriptId":"u30"},
    "bfdbcd594dcf4c87ad3306e78ad6d777":{
      "scriptId":"u31"},
    "efddfc4f407f4c86b5f8b61bcbb13eb8":{
      "scriptId":"u32"},
    "adc36ae58414464683b59543b34884f5":{
      "scriptId":"u33"},
    "c3754bb1399147ad9a0fc482912625a8":{
      "scriptId":"u34"},
    "44d9df088d1c4812b960cd27bb441829":{
      "scriptId":"u35"},
    "ee6796fc6e364cd084314db55afd415c":{
      "scriptId":"u36"},
    "efef0a784c644ddd9065f86b60c5d53a":{
      "scriptId":"u37"},
    "acf98942aaf842138a2fb900930a9346":{
      "scriptId":"u38"},
    "9679542388ae4979a72f6cf5e7da5597":{
      "scriptId":"u39"},
    "ba0fb43cddaa495fb112cac136bbfd6d":{
      "scriptId":"u40"},
    "09a3d654ea3e49acaacb62f46785dbb4":{
      "scriptId":"u41"},
    "08df4b6b0e2d42a1acd2db85a1eb2569":{
      "scriptId":"u42"},
    "09ff4030e5c44a599d523558a733f396":{
      "scriptId":"u43"},
    "6a105451c035452c8a1d07dc464cd9b8":{
      "scriptId":"u44"},
    "73a726fcacfc46a8aaa900b47c8dfbc3":{
      "scriptId":"u45"},
    "b357a336804e412d863cdee35ad3b67c":{
      "scriptId":"u46"},
    "2d76f4b50ec94e1eb43ed2d2ffd37906":{
      "scriptId":"u47"},
    "ebc087e0ecf0481091d7164d1d42e400":{
      "scriptId":"u48"},
    "aa8c185ed35e4312a3027719689de857":{
      "scriptId":"u49"},
    "1479300e375b44bbad74d683f1ef56e7":{
      "scriptId":"u50"},
    "6638a81bae3a408c88c242821bf4f5bb":{
      "scriptId":"u51"},
    "a1a36e991e3248848bb4e9b2ea731f92":{
      "scriptId":"u52"},
    "d29b7a8fa4aa45ebacc256d19d55f41b":{
      "scriptId":"u53"},
    "76d09a97495c47d6896fec9457a28aee":{
      "scriptId":"u54"},
    "bc7728f214444f7f8873eff20643d520":{
      "scriptId":"u55"},
    "21544525643a45a2bf43be2f9152fe71":{
      "scriptId":"u56"},
    "ce2f2dc43cd14bfbab4159dc88ec1358":{
      "scriptId":"u57"},
    "46ffb9d8a82b42a7b3eb0dc007815eea":{
      "scriptId":"u58"},
    "4080945fbbd749b7a751b032cd60fea3":{
      "scriptId":"u59"},
    "96223c1e716c49f290b02a637d4dc08d":{
      "scriptId":"u60"},
    "899602b2775841e183a5bc80162222a1":{
      "scriptId":"u61"},
    "49fcf0b8c75949ba9db4f5b65261f317":{
      "scriptId":"u62"},
    "770dcd62bcb84641910272132db418fb":{
      "scriptId":"u63"},
    "58e2b15b493449b9b7cd05b4b6f543f8":{
      "scriptId":"u64"},
    "1d616c11629545169c705911323e6647":{
      "scriptId":"u65"},
    "83daa0030c2243b8bc0ea09c7bb33878":{
      "scriptId":"u66"},
    "b5376ee3d3394e14bce8e03b2add4bb9":{
      "scriptId":"u67"},
    "4d48bfb1b47b48de83d277d4bb08ca19":{
      "scriptId":"u68"},
    "17333f0376374b448c4b150935c5a046":{
      "scriptId":"u69"},
    "5cc00440aea3488c9835bd822e43d5a3":{
      "scriptId":"u70"},
    "898159a7d79a47da9010049f44a2f120":{
      "scriptId":"u71"},
    "37ad63d0eb85406ba58361aec61a4fb8":{
      "scriptId":"u72"},
    "1bbdc4e065c04dfe91cf9306786d8022":{
      "scriptId":"u73"},
    "67059630f0d344939c04d4513d4de032":{
      "scriptId":"u74"},
    "0eccf2ecce5f41b482b56b1e828abb38":{
      "scriptId":"u75"},
    "0134ac583bea4fc5a6cc5228252dc0b4":{
      "scriptId":"u76"},
    "8ad244a0faaf4c02b912665bfa41fc87":{
      "scriptId":"u77"},
    "bd1a6430ebee497fa092220389d7f51e":{
      "scriptId":"u78"},
    "2e70f63628444cb7a9a2692b78f94a36":{
      "scriptId":"u79"},
    "7de1a5dba6be48a68d014f074edb6260":{
      "scriptId":"u80"},
    "5650f345302a4648871a6a4ba9a781aa":{
      "scriptId":"u81"},
    "b42fcf9837514842b892306e7b262d38":{
      "scriptId":"u82"},
    "e1df67523559413eb8a7cb33a5b1798c":{
      "scriptId":"u83"},
    "c61e64c8b56f499ea2dd31aebd7308b6":{
      "scriptId":"u84"},
    "e31cd5f9b7c849308642b2b032a1a8e6":{
      "scriptId":"u85"},
    "201b762c102b477880b8f1ca331b0b1d":{
      "scriptId":"u86"},
    "701e3f5b350e483b9c8e0a4d8f0c3836":{
      "scriptId":"u87"},
    "44b71a4adb2d4809970d55b2fcbd6da7":{
      "scriptId":"u88"},
    "de6dbf85de2e4ebe907cb66f860248c8":{
      "scriptId":"u89"},
    "c983220cae024a988e54fc61ff5b3c95":{
      "scriptId":"u90"},
    "541ed8b2a8d94e6eb46780f793ffd6b1":{
      "scriptId":"u91"},
    "488b73ba807d45db94c9e8264ed430e9":{
      "scriptId":"u92"},
    "28cc9713c0454a089d6762c7b40b0ee0":{
      "scriptId":"u93"},
    "1d07e139529e40d4b7cc0e5d6c51e6a8":{
      "scriptId":"u94"},
    "60d1d1a9d29d4bca9a06dddd9ba32ee7":{
      "scriptId":"u95"},
    "9fef3de8b5134057a5b6dab7a110d6d2":{
      "scriptId":"u96"},
    "ba4bc3e12f5d476787bd2416d6e84acd":{
      "scriptId":"u97"},
    "3e097d7fc7a74711a52c153291a0b6c1":{
      "scriptId":"u98"},
    "551fd4ca1e414d27ab9839bacbbf45ac":{
      "scriptId":"u99"},
    "311144d4ad444a82a19cf038e252b217":{
      "scriptId":"u100"}}});