$axure.loadCurrentPage({
  "url":"我是债权人.html",
  "generationDate":new Date(1474884129219.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"df6571431fd744de9f12140df9ad3ae5",
    "type":"Axure:Page",
    "name":"我是债权人",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3a551553ace74a5fad968debf04e93a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f03fa41dea9d43c0a5bde6546f755422",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"dd1a4b39c223408098c8611f57f2d63d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "size":{
              "width":375,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6943437ce5d340608c620d8c4d84b9d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "size":{
                  "width":375,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u2.png"}},
{
          "id":"4c3560a573c64c1d939109e7b2bd0955",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e00cd1aae15499c975b8e20e20c1f93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea44bf11de174b6aa2d68c2b1f5fcfdb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":41},
            "size":{
              "width":375,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a3dae4c92704d2186fa6e8b91450892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":41},
                "size":{
                  "width":375,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u6.png"}},
{
          "id":"017fad2ce95b4f4588728a6bd4ce4713",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":11,
              "y":112},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c1e9fb9627242db9f1329d6df5a96f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":112},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u8.png"}},
{
          "id":"b5199569164344f48fdd6c6e7557e52e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12.5,
              "y":162},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a5537a3d3da459f92badfa3dad738b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12.5,
                  "y":162},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u8.png"}},
{
          "id":"c623a103b2f040718929b9d5ea108804",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":212},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4f52b28517f464b9cafd74deb133047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":212},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u8.png"}},
{
          "id":"2fb90aa5e1e34e85b1bcde15d9301bc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":262},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53b73fbafe694e349a08cfa0b843dba0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":262},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u8.png"}},
{
          "id":"32647a5330824107bb5cff6bf5413240",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":312},
            "size":{
              "width":258,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98f9b08511a64fb29cf35323cf79dd94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":312},
                "size":{
                  "width":258,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u16.png"}},
{
          "id":"d139f3f3244e45d28f3037c20d24e78e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":312},
            "size":{
              "width":81,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b6eb3d6786543d08850a7172309c591",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":312},
                "size":{
                  "width":81,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u18.png"}},
{
          "id":"ebce5914ad1e45bc8b9585a7d0b74ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":362},
            "size":{
              "width":218,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f07d0f073e8143db8ea1dad382040926",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":362},
                "size":{
                  "width":218,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u20.png"}},
{
          "id":"02d0b66cc49e435fbf5991b2980df624",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":240,
              "y":362},
            "size":{
              "width":121,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c36fc1dcdd543e99dfa33acb4c617c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":362},
                "size":{
                  "width":121,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u22.png"}},
{
          "id":"172e93bb2da04b6eb5a19d5970e6da0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":412},
            "size":{
              "width":349,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"427ffaba34e443ca9f72e72afe78026b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":412},
                "size":{
                  "width":349,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u24.png"}},
{
          "id":"75830056c24c44fe9e0066c96434dd7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":12,
              "y":488},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5044e0dff00e480bb792d290c942b7d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":12,
                  "y":488},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u26.png"}},
{
          "id":"1286f9608f8f4775b14c5840f43eca01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":464},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ef50d643464b04a9ecd912683aff1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":464},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aef862851f643ef8894983b1dc2d0dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":610},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eda10b7d701f43eb8e2e92c731d05ea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":610},
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u30.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3a551553ace74a5fad968debf04e93a5":{
      "scriptId":"u0"},
    "f03fa41dea9d43c0a5bde6546f755422":{
      "scriptId":"u1"},
    "dd1a4b39c223408098c8611f57f2d63d":{
      "scriptId":"u2"},
    "6943437ce5d340608c620d8c4d84b9d1":{
      "scriptId":"u3"},
    "4c3560a573c64c1d939109e7b2bd0955":{
      "scriptId":"u4"},
    "6e00cd1aae15499c975b8e20e20c1f93":{
      "scriptId":"u5"},
    "ea44bf11de174b6aa2d68c2b1f5fcfdb":{
      "scriptId":"u6"},
    "0a3dae4c92704d2186fa6e8b91450892":{
      "scriptId":"u7"},
    "017fad2ce95b4f4588728a6bd4ce4713":{
      "scriptId":"u8"},
    "7c1e9fb9627242db9f1329d6df5a96f6":{
      "scriptId":"u9"},
    "b5199569164344f48fdd6c6e7557e52e":{
      "scriptId":"u10"},
    "1a5537a3d3da459f92badfa3dad738b6":{
      "scriptId":"u11"},
    "c623a103b2f040718929b9d5ea108804":{
      "scriptId":"u12"},
    "f4f52b28517f464b9cafd74deb133047":{
      "scriptId":"u13"},
    "2fb90aa5e1e34e85b1bcde15d9301bc6":{
      "scriptId":"u14"},
    "53b73fbafe694e349a08cfa0b843dba0":{
      "scriptId":"u15"},
    "32647a5330824107bb5cff6bf5413240":{
      "scriptId":"u16"},
    "98f9b08511a64fb29cf35323cf79dd94":{
      "scriptId":"u17"},
    "d139f3f3244e45d28f3037c20d24e78e":{
      "scriptId":"u18"},
    "2b6eb3d6786543d08850a7172309c591":{
      "scriptId":"u19"},
    "ebce5914ad1e45bc8b9585a7d0b74ff7":{
      "scriptId":"u20"},
    "f07d0f073e8143db8ea1dad382040926":{
      "scriptId":"u21"},
    "02d0b66cc49e435fbf5991b2980df624":{
      "scriptId":"u22"},
    "4c36fc1dcdd543e99dfa33acb4c617c7":{
      "scriptId":"u23"},
    "172e93bb2da04b6eb5a19d5970e6da0a":{
      "scriptId":"u24"},
    "427ffaba34e443ca9f72e72afe78026b":{
      "scriptId":"u25"},
    "75830056c24c44fe9e0066c96434dd7c":{
      "scriptId":"u26"},
    "5044e0dff00e480bb792d290c942b7d7":{
      "scriptId":"u27"},
    "1286f9608f8f4775b14c5840f43eca01":{
      "scriptId":"u28"},
    "d1ef50d643464b04a9ecd912683aff1c":{
      "scriptId":"u29"},
    "3aef862851f643ef8894983b1dc2d0dd":{
      "scriptId":"u30"},
    "eda10b7d701f43eb8e2e92c731d05ea4":{
      "scriptId":"u31"}}});