$axure.loadCurrentPage({
  "url":"对账数据.html",
  "generationDate":new Date(1466647807374.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"55906fe0e33646018b48f2b7a249a5b5",
    "type":"Axure:Page",
    "name":"对账数据",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ad84b2002654b1fb78af8d3adc7a611",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "size":{
              "width":1200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5521040eecbf46a48ebd22f0fb9f91df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "size":{
                  "width":1200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户提现审批/u0.png"}},
{
          "id":"fbc7a637d97447f5b875c4ccdb5bff7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":160,
              "height":560}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c8cd2471234ad1bb8d3bd422bd9385",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":160,
                  "height":560}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户提现审批/u2.png"}},
{
          "id":"04cdd02734e14bb7b754af77160aef27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":50},
            "size":{
              "width":238,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"270d6428c95a48c4a578cb5f6be424e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172,
                  "y":50},
                "size":{
                  "width":238,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"749aa59af0eb460da8060baba3eea2d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":172,
              "y":76},
            "size":{
              "width":458,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37e8801d88d944a9b2cee350815ff647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":172,
                  "y":76},
                "size":{
                  "width":458,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a09299e32b6f4ce69877efaf3129425e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":108},
            "size":{
              "width":508,
              "height":342}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35e5beb397644c7994e90e604bf7f14e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172,
                  "y":108},
                "size":{
                  "width":508,
                  "height":342}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对账数据/u8.png"}},
{
          "id":"4d467e62461a49aba8e9b7ba8d31ff87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":692,
              "y":108},
            "size":{
              "width":508,
              "height":342}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8af125bf11f54a9b8b0bfc9e50bec4c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":692,
                  "y":108},
                "size":{
                  "width":508,
                  "height":342}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/对账数据/u8.png"}},
{
          "id":"70b0aaa019f04c3ebf662c39e6acc62a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":460},
            "size":{
              "width":508,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1287fa5894644a5badbdb6522c7f0485",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172,
                  "y":460},
                "size":{
                  "width":508,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b47ec6167bf4ec58b3835ebb29a763b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":692,
              "y":460},
            "size":{
              "width":508,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b531526a0f1140749d0a42187af4ba49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":692,
                  "y":460},
                "size":{
                  "width":508,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64a358cfec4e47e3b755c9bf95da4a3d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":76},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7ec44ea1910041f19800fca00d08019e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":554},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1e70b897df76476da77a478449c87e94",
          "label":"提醒",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":445,
              "y":190},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"48bd93fb7de645ad94bd18603839f508",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"dfe0e00366874a12b711a9fdb5152750",
                  "label":"",
                  "parentDynamicPanel":"1e70b897df76476da77a478449c87e94",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":170,
                      "height":120}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48feb7fe905144bebf052da48b215a2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e70b897df76476da77a478449c87e94",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":170,
                          "height":120}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/对账数据/u19.png"}},
{
                  "id":"d5e7fac4a33c4bd097b711c094c07326",
                  "label":"",
                  "parentDynamicPanel":"1e70b897df76476da77a478449c87e94",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":52,
                      "y":30},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b6cc00b68c84884b930ee862c131d33",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e70b897df76476da77a478449c87e94",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":52,
                          "y":30},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"97e2223cff2345bca73cde36a585df88",
                  "label":"",
                  "parentDynamicPanel":"1e70b897df76476da77a478449c87e94",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":52,
                      "y":65},
                    "size":{
                      "width":65,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 提醒",
                              "objectsToFades":[{
                                  "objectPath":["1e70b897df76476da77a478449c87e94"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "5ad84b2002654b1fb78af8d3adc7a611":{
      "scriptId":"u0"},
    "5521040eecbf46a48ebd22f0fb9f91df":{
      "scriptId":"u1"},
    "fbc7a637d97447f5b875c4ccdb5bff7d":{
      "scriptId":"u2"},
    "94c8cd2471234ad1bb8d3bd422bd9385":{
      "scriptId":"u3"},
    "04cdd02734e14bb7b754af77160aef27":{
      "scriptId":"u4"},
    "270d6428c95a48c4a578cb5f6be424e1":{
      "scriptId":"u5"},
    "749aa59af0eb460da8060baba3eea2d6":{
      "scriptId":"u6"},
    "37e8801d88d944a9b2cee350815ff647":{
      "scriptId":"u7"},
    "a09299e32b6f4ce69877efaf3129425e":{
      "scriptId":"u8"},
    "35e5beb397644c7994e90e604bf7f14e":{
      "scriptId":"u9"},
    "4d467e62461a49aba8e9b7ba8d31ff87":{
      "scriptId":"u10"},
    "8af125bf11f54a9b8b0bfc9e50bec4c6":{
      "scriptId":"u11"},
    "70b0aaa019f04c3ebf662c39e6acc62a":{
      "scriptId":"u12"},
    "1287fa5894644a5badbdb6522c7f0485":{
      "scriptId":"u13"},
    "2b47ec6167bf4ec58b3835ebb29a763b":{
      "scriptId":"u14"},
    "b531526a0f1140749d0a42187af4ba49":{
      "scriptId":"u15"},
    "64a358cfec4e47e3b755c9bf95da4a3d":{
      "scriptId":"u16"},
    "7ec44ea1910041f19800fca00d08019e":{
      "scriptId":"u17"},
    "1e70b897df76476da77a478449c87e94":{
      "scriptId":"u18"},
    "dfe0e00366874a12b711a9fdb5152750":{
      "scriptId":"u19"},
    "48feb7fe905144bebf052da48b215a2a":{
      "scriptId":"u20"},
    "d5e7fac4a33c4bd097b711c094c07326":{
      "scriptId":"u21"},
    "8b6cc00b68c84884b930ee862c131d33":{
      "scriptId":"u22"},
    "97e2223cff2345bca73cde36a585df88":{
      "scriptId":"u23"}}});