$axure.loadCurrentPage({
  "url":"排号费页面.html",
  "generationDate":new Date(1473824948928.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c32ac11588b14c4dad4119abf7041844",
    "type":"Axure:Page",
    "name":"排号费页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"16e6a74ccc6f4d93aee50fa3918b64b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":173}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4931f5d18f1e44f6a09a76f508254cbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":173}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特供商城/u0.png"}},
{
          "id":"358d9e9322344465b93dbeda7690a6a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":186},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbce1de0a5e2439aa8afbb582eadfff9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":186},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a0dab9280a74da49275e44f00031dd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":186},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"611895f926ca43ed9539d82d3b48f70a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":186},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3041c1157424527b7a73f87233c144b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":439.5,
              "y":233},
            "size":{
              "width":321,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e090c513b1c743cba06792cf74dd528e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":439.5,
                  "y":233},
                "size":{
                  "width":321,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e6dfb8abc2b42999a37cf1c5c183a70",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":280},
            "size":{
              "width":1000,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/特供商城/u58_line.png"}},
{
          "id":"8752baa047ed45989a584b8fa5e4e7a5",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":300},
            "size":{
              "width":1000,
              "height":450}},
          "adaptiveStyles":{
}},
{
          "id":"b6b34adb0ab042229dd553f55437cc0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":100,
              "y":760},
            "size":{
              "width":1000,
              "height":34},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6646a705ca624c5daffa1daba9c1773f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":100,
                  "y":760},
                "size":{
                  "width":1000,
                  "height":34},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/排号费页面/u10.png"}},
{
          "id":"b8758c7277744af1b90e8e80bc0ff91f",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":769},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77f3fb4cf50c4793a35ba1d93d3c71d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":769},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"4fc4100df7d14298a1578421b340cbd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":535.5,
              "y":813},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14618f67cceb4fe1ad1e4db355a299d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":535.5,
                  "y":813},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad5fb633be4b422fa154acc5b6685a3d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":860},
            "size":{
              "width":1000,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/特供商城/u58_line.png"}},
{
          "id":"1ebfd023b47c4792b17425beeaef01bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":890},
            "size":{
              "width":470,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8260344422434ea598ce7cf8b1b4e7eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":890},
                "size":{
                  "width":470,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8566c0d450c4297863ec681e1c4b8e6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":921},
            "size":{
              "width":940,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/排号费页面/u19_line.png"}},
{
          "id":"50c5d70ad4924d5faf07a67365ec8f05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":954},
            "size":{
              "width":470,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"478c555c63e742c691b8726d5c95bc69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":954},
                "size":{
                  "width":470,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaea6fdefd4947e9a06d8be6d73c5061",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":990},
            "size":{
              "width":940,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/排号费页面/u19_line.png"}},
{
          "id":"b808448ba8b94dda80ba28909af12c10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":161,
              "y":1020},
            "size":{
              "width":470,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"413af10c46114153a4177380ba2ed410",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":161,
                  "y":1020},
                "size":{
                  "width":470,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"951b942523eb4e6ebefc616df3d3fa53",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":1050},
            "size":{
              "width":940,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/排号费页面/u19_line.png"}},
{
          "id":"fa94a602f83d44bbb4eba27578db51bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":500,
              "y":1105},
            "size":{
              "width":200,
              "height":50},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF434343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a2cb33f9b294470abd15fe5b9aa569c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":500,
                  "y":1105},
                "size":{
                  "width":200,
                  "height":50},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF434343}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的排号",
                      "target":{
                        "targetType":"page",
                        "url":"我的排号.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/排号费页面/u26.png"}},
{
          "id":"71190a358e434bac9b051c7550c276f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1240},
            "size":{
              "width":1200,
              "height":284}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccf015d6594442b0bd474eb752f60f4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1240},
                "size":{
                  "width":1200,
                  "height":284}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特供商城/u239.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "16e6a74ccc6f4d93aee50fa3918b64b2":{
      "scriptId":"u0"},
    "4931f5d18f1e44f6a09a76f508254cbb":{
      "scriptId":"u1"},
    "358d9e9322344465b93dbeda7690a6a4":{
      "scriptId":"u2"},
    "bbce1de0a5e2439aa8afbb582eadfff9":{
      "scriptId":"u3"},
    "3a0dab9280a74da49275e44f00031dd7":{
      "scriptId":"u4"},
    "611895f926ca43ed9539d82d3b48f70a":{
      "scriptId":"u5"},
    "b3041c1157424527b7a73f87233c144b":{
      "scriptId":"u6"},
    "e090c513b1c743cba06792cf74dd528e":{
      "scriptId":"u7"},
    "5e6dfb8abc2b42999a37cf1c5c183a70":{
      "scriptId":"u8"},
    "8752baa047ed45989a584b8fa5e4e7a5":{
      "scriptId":"u9"},
    "b6b34adb0ab042229dd553f55437cc0e":{
      "scriptId":"u10"},
    "6646a705ca624c5daffa1daba9c1773f":{
      "scriptId":"u11"},
    "b8758c7277744af1b90e8e80bc0ff91f":{
      "scriptId":"u12"},
    "77f3fb4cf50c4793a35ba1d93d3c71d5":{
      "scriptId":"u13"},
    "4fc4100df7d14298a1578421b340cbd9":{
      "scriptId":"u14"},
    "14618f67cceb4fe1ad1e4db355a299d1":{
      "scriptId":"u15"},
    "ad5fb633be4b422fa154acc5b6685a3d":{
      "scriptId":"u16"},
    "1ebfd023b47c4792b17425beeaef01bb":{
      "scriptId":"u17"},
    "8260344422434ea598ce7cf8b1b4e7eb":{
      "scriptId":"u18"},
    "d8566c0d450c4297863ec681e1c4b8e6":{
      "scriptId":"u19"},
    "50c5d70ad4924d5faf07a67365ec8f05":{
      "scriptId":"u20"},
    "478c555c63e742c691b8726d5c95bc69":{
      "scriptId":"u21"},
    "aaea6fdefd4947e9a06d8be6d73c5061":{
      "scriptId":"u22"},
    "b808448ba8b94dda80ba28909af12c10":{
      "scriptId":"u23"},
    "413af10c46114153a4177380ba2ed410":{
      "scriptId":"u24"},
    "951b942523eb4e6ebefc616df3d3fa53":{
      "scriptId":"u25"},
    "fa94a602f83d44bbb4eba27578db51bf":{
      "scriptId":"u26"},
    "6a2cb33f9b294470abd15fe5b9aa569c":{
      "scriptId":"u27"},
    "71190a358e434bac9b051c7550c276f5":{
      "scriptId":"u28"},
    "ccf015d6594442b0bd474eb752f60f4e":{
      "scriptId":"u29"}}});