$axure.loadCurrentPage({
  "url":"用户信息.html",
  "generationDate":new Date(1449815486543.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"708005147bee41259d4b0f2e304e0721",
    "type":"Axure:Page",
    "name":"用户信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"55052c686ec344cbb1ea17164ab04ec7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e6c2a16efe643408524769892007d5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u0.png"}},
{
          "id":"795a60294da447d899af172f323d4812",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":37},
            "size":{
              "width":235,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f965395f07574d929f52cd3dcd18a2b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":37},
                "size":{
                  "width":235,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 押宝首页",
                      "target":{
                        "targetType":"page",
                        "url":"押宝首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u2.png"}},
{
          "id":"9586244abb394c7c82a6deeb22f170d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":380,
              "y":49.5},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dca1c48281f946269e0f418c79707cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":380,
                  "y":49.5},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"685b50a6d20949f792f47cbd49262ad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":477,
              "y":50},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d952475a86b44a0dbc57257b6f9bc24f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":477,
                  "y":50},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bca4ce7706e44808868133f9dcb15902",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":599,
              "y":50},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4cddc6e8c8b4643badcaed7d5f9e0a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":599,
                  "y":50},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c4ce2bdf50b4866aa326eb1aa14c9dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":42.5},
            "size":{
              "width":127,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bf2a13721364fabb0072cf557259906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":42.5},
                "size":{
                  "width":127,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户信息",
                      "target":{
                        "targetType":"page",
                        "url":"用户信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u10.png"}},
{
          "id":"3c3f55d42fa743f9a955a881dd0e5b71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":84},
            "size":{
              "width":1200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/押宝列表页/u12_line.png"}},
{
          "id":"265f535285544a9fbcf29ca65a17bcb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1370},
            "size":{
              "width":1200,
              "height":405}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7f0b750425449e094adaec2c1e242d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1370},
                "size":{
                  "width":1200,
                  "height":405}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u82.png"}},
{
          "id":"665cec92bcb94144b51fd3f264ba0095",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":1002,
              "height":137},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e01ef54e1d774a8f80afe10c9592ee5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":1002,
                  "height":137},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息/u15.png"}},
{
          "id":"31fd2e803f3b4650a7bfbde5f3c57005",
          "label":"个人信息",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":247},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"59d6b08495d74a0280ef4a1533f9b3fd",
              "label":"押宝记录",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bd8f0acec76845c7af640f49dea3e206",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1002,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"55cedd217a314ed194fe75638f8047aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1002,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u18.png"}},
{
                  "id":"68d36bcb1cf04fa3ae08fc52ce7875e7",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":38},
                    "size":{
                      "width":1002,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"881a06d5af6a48ccabdfb96bc324dc51",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":38},
                        "size":{
                          "width":1002,
                          "height":55}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u20.png"}},
{
                  "id":"9b0bda83fca7467e8a97568add0a55eb",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":95},
                    "size":{
                      "width":1002,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad6b33fda33c4262a3215a344741001d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":95},
                        "size":{
                          "width":1002,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u22.png"}},
{
                  "id":"220ff1a5cd8742918904d62b64fa233b",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":184},
                    "size":{
                      "width":1002,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"38a7c0e1dc154a679f6c394534d0dfb4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":184},
                        "size":{
                          "width":1002,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u22.png"}},
{
                  "id":"9166930c639e410897aa45dbce6ff798",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":273},
                    "size":{
                      "width":1002,
                      "height":89}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e401002953848629f2ab7ee66cb297f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":273},
                        "size":{
                          "width":1002,
                          "height":89}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u22.png"}},
{
                  "id":"fb3169abd2e140f2a9cbc401c34de29e",
                  "label":"所有",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":675,
                      "y":159},
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"d7f088f39afd42f5b579de424ae7385a",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"fb72dcf301b445e9be41568e5abfd745",
                          "label":"",
                          "parentDynamicPanel":"fb3169abd2e140f2a9cbc401c34de29e",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":255,
                              "height":140}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"8d70962aaea64d1c9acc9f3fcf9707e2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"fb3169abd2e140f2a9cbc401c34de29e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":255,
                                  "height":140}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/往期押宝详情/u60.png"}},
{
                          "id":"e40a85c270ab4955b8144c8d7e799190",
                          "label":"",
                          "parentDynamicPanel":"fb3169abd2e140f2a9cbc401c34de29e",
                          "type":"imageMapRegion",
                          "styleType":"imageMapRegion",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":240,
                              "y":0},
                            "size":{
                              "width":15,
                              "height":20}},
                          "adaptiveStyles":{
},
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 所有",
                                      "objectsToFades":[{
                                          "objectPath":["fb3169abd2e140f2a9cbc401c34de29e"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true}]}]},
{
                  "id":"5dccb46131094b2b8fa85f3c9b83f2fa",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":675,
                      "y":140},
                    "size":{
                      "width":55,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 所有 to 状态1 show if hidden",
                              "panelsToStates":[{
                                  "panelPath":["fb3169abd2e140f2a9cbc401c34de29e"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"712319ddf9e74019ae7ddd478f955aaf",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 个人信息 to 中奖记录",
                              "panelsToStates":[{
                                  "panelPath":["31fd2e803f3b4650a7bfbde5f3c57005"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"6107ed4693ad441b92378d9b0a93c316",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":206,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 个人信息 to 晒单",
                              "panelsToStates":[{
                                  "panelPath":["31fd2e803f3b4650a7bfbde5f3c57005"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"4ba249d295b54540853fe38d1ecbc998",
              "label":"中奖记录",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2c41310f3c764e569a889479836a72a2",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1002,
                      "height":33}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52c76bb56a07495f9b6a342b79ca4d6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1002,
                          "height":33}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u35.png"}},
{
                  "id":"b169fb72eb994a2e8955068208f5ac77",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":43},
                    "size":{
                      "width":200,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"255961a38c57406b8aca1ee9337545cf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":43},
                        "size":{
                          "width":200,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d4e97480bc434d8abf1edd5ad48486ce",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":69},
                    "size":{
                      "width":230,
                      "height":343}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd9b0a966f9f4445937adc3dce0af186",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":69},
                        "size":{
                          "width":230,
                          "height":343}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u39.png"}},
{
                  "id":"003fb2ed9e3445b5bb7b7b2686fb61a1",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":206,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 个人信息 to 晒单",
                              "panelsToStates":[{
                                  "panelPath":["31fd2e803f3b4650a7bfbde5f3c57005"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"96a07bc231614526bffc29d3e1897af3",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":-1},
                    "size":{
                      "width":100,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 个人信息 to 押宝记录",
                              "panelsToStates":[{
                                  "panelPath":["31fd2e803f3b4650a7bfbde5f3c57005"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"f88e8dd0bc5846c4987387144d0fc8e7",
              "label":"晒单",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3fe6aed2033743c395a70d7d83c1c008",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1000,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbf649bac9e8494ea48915d0156d48f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1000,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u43.png"}},
{
                  "id":"43a3d0fce15d485aa56a9687b6369d66",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":47},
                    "size":{
                      "width":230,
                      "height":343}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1bb30ec9e6ad49ad98b868f194863bd4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":47},
                        "size":{
                          "width":230,
                          "height":343}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u39.png"}},
{
                  "id":"34a9ff5e232e4d77861de13b743940ca",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":260,
                      "y":47},
                    "size":{
                      "width":320,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"793db160c8a84379b1f52092294fa076",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":260,
                          "y":47},
                        "size":{
                          "width":320,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u47.png"}},
{
                  "id":"9927cb6236994abe89b21a6093f18924",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":390},
                    "size":{
                      "width":230,
                      "height":343}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c82e073402844f184f3b4aece35ab94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":390},
                        "size":{
                          "width":230,
                          "height":343}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u39.png"}},
{
                  "id":"842e59d78a1549399cf36e2aacc806e1",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":260,
                      "y":390},
                    "size":{
                      "width":320,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"61b808a7e446461697dc1a41ff27cb5f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":260,
                          "y":390},
                        "size":{
                          "width":320,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/用户信息/u47.png"}},
{
                  "id":"ab684499e3384e7b98db07130e0ae253",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":-1},
                    "size":{
                      "width":100,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 个人信息 to 押宝记录",
                              "panelsToStates":[{
                                  "panelPath":["31fd2e803f3b4650a7bfbde5f3c57005"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"a0246213990343d98ee259312ae16a5b",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 个人信息 to 中奖记录",
                              "panelsToStates":[{
                                  "panelPath":["31fd2e803f3b4650a7bfbde5f3c57005"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"4486887af80d46db8ab42b16d413c90b",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":40,
                      "y":50},
                    "size":{
                      "width":200,
                      "height":270}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 往期押宝详情",
                              "target":{
                                "targetType":"page",
                                "url":"往期押宝详情.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"30ca86497eda48fb8f2013352858fa84",
                  "label":"",
                  "parentDynamicPanel":"31fd2e803f3b4650a7bfbde5f3c57005",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":40,
                      "y":400},
                    "size":{
                      "width":200,
                      "height":270}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 往期押宝详情",
                              "target":{
                                "targetType":"page",
                                "url":"往期押宝详情.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}]},
{
          "id":"64a41eb336c84b92b710fab71f0af669",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":641,
              "y":129},
            "size":{
              "width":133,
              "height":74},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08b80648b7e748a48b2f62f1ac5dedab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":641,
                  "y":129},
                "size":{
                  "width":133,
                  "height":74},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息/u57.png"}},
{
          "id":"dab1f11ac73348889e2bf51af8d82e3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":899,
              "y":129},
            "size":{
              "width":161,
              "height":74},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"291dc93391b341548ad289bf872e4fad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":899,
                  "y":129},
                "size":{
                  "width":161,
                  "height":74},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息/u59.png"}},
{
          "id":"90dd0018b461426f9ef5ba88d82a08aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":214,
              "y":156},
            "size":{
              "width":63,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab6af9446c0647b795a1a0074fd12899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":214,
                  "y":156},
                "size":{
                  "width":63,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97a4e5793ad54d6d8c90c013d6170727",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"700",
            "location":{
              "x":214,
              "y":175},
            "size":{
              "width":69,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5754b0cd6044133b49979df8ee43326",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"700",
                "location":{
                  "x":214,
                  "y":175},
                "size":{
                  "width":69,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65665127ce4341bebbf8810cd371d908",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"10px",
            "fontWeight":"700",
            "location":{
              "x":214,
              "y":192},
            "size":{
              "width":47,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c741b4ff0a44e6be6a791a5f4c3f7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"10px",
                "fontWeight":"700",
                "location":{
                  "x":214,
                  "y":192},
                "size":{
                  "width":47,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3154dcdc00da4855a244cb699ddda542",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":665},
            "size":{
              "width":1200,
              "height":405}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5ab527a106641dfa943d9fc97bac2d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":665},
                "size":{
                  "width":1200,
                  "height":405}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u82.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "55052c686ec344cbb1ea17164ab04ec7":{
      "scriptId":"u0"},
    "9e6c2a16efe643408524769892007d5e":{
      "scriptId":"u1"},
    "795a60294da447d899af172f323d4812":{
      "scriptId":"u2"},
    "f965395f07574d929f52cd3dcd18a2b6":{
      "scriptId":"u3"},
    "9586244abb394c7c82a6deeb22f170d6":{
      "scriptId":"u4"},
    "dca1c48281f946269e0f418c79707cf8":{
      "scriptId":"u5"},
    "685b50a6d20949f792f47cbd49262ad1":{
      "scriptId":"u6"},
    "d952475a86b44a0dbc57257b6f9bc24f":{
      "scriptId":"u7"},
    "bca4ce7706e44808868133f9dcb15902":{
      "scriptId":"u8"},
    "a4cddc6e8c8b4643badcaed7d5f9e0a5":{
      "scriptId":"u9"},
    "3c4ce2bdf50b4866aa326eb1aa14c9dd":{
      "scriptId":"u10"},
    "1bf2a13721364fabb0072cf557259906":{
      "scriptId":"u11"},
    "3c3f55d42fa743f9a955a881dd0e5b71":{
      "scriptId":"u12"},
    "265f535285544a9fbcf29ca65a17bcb4":{
      "scriptId":"u13"},
    "a7f0b750425449e094adaec2c1e242d9":{
      "scriptId":"u14"},
    "665cec92bcb94144b51fd3f264ba0095":{
      "scriptId":"u15"},
    "e01ef54e1d774a8f80afe10c9592ee5a":{
      "scriptId":"u16"},
    "31fd2e803f3b4650a7bfbde5f3c57005":{
      "scriptId":"u17"},
    "bd8f0acec76845c7af640f49dea3e206":{
      "scriptId":"u18"},
    "55cedd217a314ed194fe75638f8047aa":{
      "scriptId":"u19"},
    "68d36bcb1cf04fa3ae08fc52ce7875e7":{
      "scriptId":"u20"},
    "881a06d5af6a48ccabdfb96bc324dc51":{
      "scriptId":"u21"},
    "9b0bda83fca7467e8a97568add0a55eb":{
      "scriptId":"u22"},
    "ad6b33fda33c4262a3215a344741001d":{
      "scriptId":"u23"},
    "220ff1a5cd8742918904d62b64fa233b":{
      "scriptId":"u24"},
    "38a7c0e1dc154a679f6c394534d0dfb4":{
      "scriptId":"u25"},
    "9166930c639e410897aa45dbce6ff798":{
      "scriptId":"u26"},
    "0e401002953848629f2ab7ee66cb297f":{
      "scriptId":"u27"},
    "fb3169abd2e140f2a9cbc401c34de29e":{
      "scriptId":"u28"},
    "fb72dcf301b445e9be41568e5abfd745":{
      "scriptId":"u29"},
    "8d70962aaea64d1c9acc9f3fcf9707e2":{
      "scriptId":"u30"},
    "e40a85c270ab4955b8144c8d7e799190":{
      "scriptId":"u31"},
    "5dccb46131094b2b8fa85f3c9b83f2fa":{
      "scriptId":"u32"},
    "712319ddf9e74019ae7ddd478f955aaf":{
      "scriptId":"u33"},
    "6107ed4693ad441b92378d9b0a93c316":{
      "scriptId":"u34"},
    "2c41310f3c764e569a889479836a72a2":{
      "scriptId":"u35"},
    "52c76bb56a07495f9b6a342b79ca4d6c":{
      "scriptId":"u36"},
    "b169fb72eb994a2e8955068208f5ac77":{
      "scriptId":"u37"},
    "255961a38c57406b8aca1ee9337545cf":{
      "scriptId":"u38"},
    "d4e97480bc434d8abf1edd5ad48486ce":{
      "scriptId":"u39"},
    "fd9b0a966f9f4445937adc3dce0af186":{
      "scriptId":"u40"},
    "003fb2ed9e3445b5bb7b7b2686fb61a1":{
      "scriptId":"u41"},
    "96a07bc231614526bffc29d3e1897af3":{
      "scriptId":"u42"},
    "3fe6aed2033743c395a70d7d83c1c008":{
      "scriptId":"u43"},
    "fbf649bac9e8494ea48915d0156d48f6":{
      "scriptId":"u44"},
    "43a3d0fce15d485aa56a9687b6369d66":{
      "scriptId":"u45"},
    "1bb30ec9e6ad49ad98b868f194863bd4":{
      "scriptId":"u46"},
    "34a9ff5e232e4d77861de13b743940ca":{
      "scriptId":"u47"},
    "793db160c8a84379b1f52092294fa076":{
      "scriptId":"u48"},
    "9927cb6236994abe89b21a6093f18924":{
      "scriptId":"u49"},
    "1c82e073402844f184f3b4aece35ab94":{
      "scriptId":"u50"},
    "842e59d78a1549399cf36e2aacc806e1":{
      "scriptId":"u51"},
    "61b808a7e446461697dc1a41ff27cb5f":{
      "scriptId":"u52"},
    "ab684499e3384e7b98db07130e0ae253":{
      "scriptId":"u53"},
    "a0246213990343d98ee259312ae16a5b":{
      "scriptId":"u54"},
    "4486887af80d46db8ab42b16d413c90b":{
      "scriptId":"u55"},
    "30ca86497eda48fb8f2013352858fa84":{
      "scriptId":"u56"},
    "64a41eb336c84b92b710fab71f0af669":{
      "scriptId":"u57"},
    "08b80648b7e748a48b2f62f1ac5dedab":{
      "scriptId":"u58"},
    "dab1f11ac73348889e2bf51af8d82e3c":{
      "scriptId":"u59"},
    "291dc93391b341548ad289bf872e4fad":{
      "scriptId":"u60"},
    "90dd0018b461426f9ef5ba88d82a08aa":{
      "scriptId":"u61"},
    "ab6af9446c0647b795a1a0074fd12899":{
      "scriptId":"u62"},
    "97a4e5793ad54d6d8c90c013d6170727":{
      "scriptId":"u63"},
    "c5754b0cd6044133b49979df8ee43326":{
      "scriptId":"u64"},
    "65665127ce4341bebbf8810cd371d908":{
      "scriptId":"u65"},
    "76c741b4ff0a44e6be6a791a5f4c3f7e":{
      "scriptId":"u66"},
    "3154dcdc00da4855a244cb699ddda542":{
      "scriptId":"u67"},
    "f5ab527a106641dfa943d9fc97bac2d1":{
      "scriptId":"u68"}}});