$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1474884129104.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f0baac4cb8b9442990396496c70b9c61",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"48715a9bdf5a44b0b898c2b27c49da0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dde84d3812704b3ab71a5ef085e74ec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"3b4df02dc67f4c118c1fad343001124c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8172bb10c1745c7b247a13b6e75fc58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"9d56f541fe4646a4b18edd7c7e7a1231",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":51},
            "size":{
              "width":129,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25c233df07104abc8227a74687898a4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":123,
                  "y":51},
                "size":{
                  "width":129,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae8ff93df8d84fcd80dd8fd62d10d9ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":308},
            "size":{
              "width":238,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e87a2026d014d419e6b949179becfbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":308},
                "size":{
                  "width":238,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"14bd6b4c893e46a99aa3b34b7f5e1fb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":305},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db35878a9d8d4ae081d046070c91495c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":305},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"954f3a70d3534dbe881eee170ccc73b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":352},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67fe8d1783b34e5caea06addca1cd6a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":352},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2834bb8a29b9461ba947da3a76601157",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":409},
            "size":{
              "width":238,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26d431c97b3a472c8491b585c1d67fef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":409},
                "size":{
                  "width":238,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"b525ae8e9b1d4485a6f0ab0e8ef55900",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":406},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf5feee2524d4cb2b104aa1df6f313d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":406},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"b1f3f66d443144ebb799e4b21265700c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":453},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67c6207e6abf48fa88ae8ab0a9f15ba7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":453},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4ac5ae1e4674966b6499788067e5453",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":507},
            "size":{
              "width":238,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f524282d8de44004839d84f0a128f80f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":507},
                "size":{
                  "width":238,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.png"}},
{
          "id":"c2b03e018d5b43508b61fc637555c1af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":504},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20985d93cae74a5dbd1712c52ad51fd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":504},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"44ca74d224564f97b164512dac4602bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":551},
            "size":{
              "width":200,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d26b6b49cef42faacd996d47aa581e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":551},
                "size":{
                  "width":200,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7ac57af3ce1432ab20b9c3f76b9901a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":89},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21755331f089403886dd7cb0f6d41038",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":89},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"865acf0de6254bd29bd3476090a22800",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":126,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72877ad98d1147f2b0691d9c7efffa61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":126,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u26.png"}},
{
          "id":"e7f502e0e5ad4e49b9c7b32d8fb65fc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":130},
            "size":{
              "width":126,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b24b1b743e584f57b1402d48ad31ea6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":130},
                "size":{
                  "width":126,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u26.png"}},
{
          "id":"5541985aef724ef39d7353cc424080a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":130},
            "size":{
              "width":126,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a35bb5633884b579970f81547bcd7a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":249,
                  "y":130},
                "size":{
                  "width":126,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u26.png"}},
{
          "id":"c852e654cfe84498896ef415c60ffc95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":190},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c8dec8976984c3ebbae2f7e0d8f4fda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":190},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u32.png"}},
{
          "id":"1c306b84d12e41ae83ddf6b61307d231",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":190},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"031f8fa01c8f47e78972ad549538120b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":190},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u32.png"}},
{
          "id":"ec4a602580744fdcb2a506efb1301930",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":190},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19e7131b5fc7425cbeb9766a4d36298f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":190},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u32.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "48715a9bdf5a44b0b898c2b27c49da0b":{
      "scriptId":"u0"},
    "dde84d3812704b3ab71a5ef085e74ec3":{
      "scriptId":"u1"},
    "3b4df02dc67f4c118c1fad343001124c":{
      "scriptId":"u2"},
    "d8172bb10c1745c7b247a13b6e75fc58":{
      "scriptId":"u3"},
    "9d56f541fe4646a4b18edd7c7e7a1231":{
      "scriptId":"u4"},
    "25c233df07104abc8227a74687898a4f":{
      "scriptId":"u5"},
    "ae8ff93df8d84fcd80dd8fd62d10d9ea":{
      "scriptId":"u6"},
    "9e87a2026d014d419e6b949179becfbb":{
      "scriptId":"u7"},
    "14bd6b4c893e46a99aa3b34b7f5e1fb7":{
      "scriptId":"u8"},
    "db35878a9d8d4ae081d046070c91495c":{
      "scriptId":"u9"},
    "954f3a70d3534dbe881eee170ccc73b0":{
      "scriptId":"u10"},
    "67fe8d1783b34e5caea06addca1cd6a2":{
      "scriptId":"u11"},
    "2834bb8a29b9461ba947da3a76601157":{
      "scriptId":"u12"},
    "26d431c97b3a472c8491b585c1d67fef":{
      "scriptId":"u13"},
    "b525ae8e9b1d4485a6f0ab0e8ef55900":{
      "scriptId":"u14"},
    "cf5feee2524d4cb2b104aa1df6f313d7":{
      "scriptId":"u15"},
    "b1f3f66d443144ebb799e4b21265700c":{
      "scriptId":"u16"},
    "67c6207e6abf48fa88ae8ab0a9f15ba7":{
      "scriptId":"u17"},
    "d4ac5ae1e4674966b6499788067e5453":{
      "scriptId":"u18"},
    "f524282d8de44004839d84f0a128f80f":{
      "scriptId":"u19"},
    "c2b03e018d5b43508b61fc637555c1af":{
      "scriptId":"u20"},
    "20985d93cae74a5dbd1712c52ad51fd3":{
      "scriptId":"u21"},
    "44ca74d224564f97b164512dac4602bc":{
      "scriptId":"u22"},
    "1d26b6b49cef42faacd996d47aa581e6":{
      "scriptId":"u23"},
    "e7ac57af3ce1432ab20b9c3f76b9901a":{
      "scriptId":"u24"},
    "21755331f089403886dd7cb0f6d41038":{
      "scriptId":"u25"},
    "865acf0de6254bd29bd3476090a22800":{
      "scriptId":"u26"},
    "72877ad98d1147f2b0691d9c7efffa61":{
      "scriptId":"u27"},
    "e7f502e0e5ad4e49b9c7b32d8fb65fc0":{
      "scriptId":"u28"},
    "b24b1b743e584f57b1402d48ad31ea6f":{
      "scriptId":"u29"},
    "5541985aef724ef39d7353cc424080a0":{
      "scriptId":"u30"},
    "0a35bb5633884b579970f81547bcd7a5":{
      "scriptId":"u31"},
    "c852e654cfe84498896ef415c60ffc95":{
      "scriptId":"u32"},
    "9c8dec8976984c3ebbae2f7e0d8f4fda":{
      "scriptId":"u33"},
    "1c306b84d12e41ae83ddf6b61307d231":{
      "scriptId":"u34"},
    "031f8fa01c8f47e78972ad549538120b":{
      "scriptId":"u35"},
    "ec4a602580744fdcb2a506efb1301930":{
      "scriptId":"u36"},
    "19e7131b5fc7425cbeb9766a4d36298f":{
      "scriptId":"u37"}}});