$axure.loadCurrentPage({
  "url":"订单确认.html",
  "generationDate":new Date(1469080151264.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5941cc2c3a6d4d438bfa48ad8d047ab6",
    "type":"Axure:Page",
    "name":"订单确认",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1bb082af5a2c4a0fa2cc5487be4b8f8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69471d04a493439db011e5f3fa9bb8e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单确认/u0.png"}},
{
          "id":"add4f4ac3f16401584e34ce8c5b9f897",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":220},
            "size":{
              "width":144,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2eb07b3c4f36427ba061df01bd698e03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":220},
                "size":{
                  "width":144,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2de756fa5f942c1ba1a7b61f56876e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":255},
            "size":{
              "width":209,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f764afe2ad41e18fa29d063f2cb791",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":255},
                "size":{
                  "width":209,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单确认/u4.png"}},
{
          "id":"bed7b9d0a3e348bea8c580bf806dd26a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":375},
            "size":{
              "width":352,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7638181aed549b9b52df71bf541ebcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":375},
                "size":{
                  "width":352,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1440055aa364de6bde9721e91f0392e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":412},
            "size":{
              "width":1200,
              "height":142}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34e880e00dd34e55a7b54a51d1e03663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":412},
                "size":{
                  "width":1200,
                  "height":142}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单确认/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1bb082af5a2c4a0fa2cc5487be4b8f8f":{
      "scriptId":"u0"},
    "69471d04a493439db011e5f3fa9bb8e5":{
      "scriptId":"u1"},
    "add4f4ac3f16401584e34ce8c5b9f897":{
      "scriptId":"u2"},
    "2eb07b3c4f36427ba061df01bd698e03":{
      "scriptId":"u3"},
    "e2de756fa5f942c1ba1a7b61f56876e3":{
      "scriptId":"u4"},
    "d5f764afe2ad41e18fa29d063f2cb791":{
      "scriptId":"u5"},
    "bed7b9d0a3e348bea8c580bf806dd26a":{
      "scriptId":"u6"},
    "d7638181aed549b9b52df71bf541ebcf":{
      "scriptId":"u7"},
    "a1440055aa364de6bde9721e91f0392e":{
      "scriptId":"u8"},
    "34e880e00dd34e55a7b54a51d1e03663":{
      "scriptId":"u9"}}});