$axure.loadCurrentPage({
  "url":"我是债务人.html",
  "generationDate":new Date(1474884129278.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"53f4241b486a4aff9887042da54f226c",
    "type":"Axure:Page",
    "name":"我是债务人",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1f61b4dd78554a5b8efebd9fed280168",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"335a98807a194a06a9915d85395c84a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"14622cfd16584cf699c1d12a6579ddbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "size":{
              "width":375,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3da97332ea6f4686b08bee2469ca45d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "size":{
                  "width":375,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u2.png"}},
{
          "id":"4b1791a5ca9243738e3abe71ef390061",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c18334243566466ca778b4562c4cf975",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"089de4de60ff47c387b2593e3c856fac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":41},
            "size":{
              "width":375,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea6c2c5fd8be4b1390c74c7d7c2afee4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":41},
                "size":{
                  "width":375,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u6.png"}},
{
          "id":"7031c1b1a31445c08f00cdde798b5544",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":11,
              "y":112},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c721ae19a71448f8a42e5c5ca7b6ae31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":112},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u8.png"}},
{
          "id":"c8765cf6662c4297ac562f797a2c92e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":162},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25de059bb98749bfab50cf3593e08849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":162},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u8.png"}},
{
          "id":"c9efc8e65e3549c78558be860afec025",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":212},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0209a56d6e684f7ab2afaed44f570053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":212},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u8.png"}},
{
          "id":"0360e347be904bd0ac14afb6e4bd5579",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":265},
            "size":{
              "width":258,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"228ec3d318c64b33ac29312b7653c8ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":265},
                "size":{
                  "width":258,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u16.png"}},
{
          "id":"912955c13a314ae48b660bc153e122b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":265},
            "size":{
              "width":81,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece26ba2596643c8bcc0bbbafb7f213e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":265},
                "size":{
                  "width":81,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u18.png"}},
{
          "id":"bc555dd6eb994840b563a5fb7675618d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":315},
            "size":{
              "width":218,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84da0bceea4b4a08bf41ad553c574f60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":315},
                "size":{
                  "width":218,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u20.png"}},
{
          "id":"1db7938a475c41ecaafe823c94026065",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":240,
              "y":315},
            "size":{
              "width":121,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"237a3ccbc7754e6b81f93b404195473e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":315},
                "size":{
                  "width":121,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u22.png"}},
{
          "id":"5cb8b6105aff4d6287e5f147c020b7b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":365},
            "size":{
              "width":349,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d0210c1022e460b8b42efbe2a5cfcb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":365},
                "size":{
                  "width":349,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u24.png"}},
{
          "id":"1b5ac525060546aba1b306c26a42913c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":420},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"521649f4c5a64327bd80a875cf487571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":420},
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u30.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1f61b4dd78554a5b8efebd9fed280168":{
      "scriptId":"u0"},
    "335a98807a194a06a9915d85395c84a4":{
      "scriptId":"u1"},
    "14622cfd16584cf699c1d12a6579ddbf":{
      "scriptId":"u2"},
    "3da97332ea6f4686b08bee2469ca45d6":{
      "scriptId":"u3"},
    "4b1791a5ca9243738e3abe71ef390061":{
      "scriptId":"u4"},
    "c18334243566466ca778b4562c4cf975":{
      "scriptId":"u5"},
    "089de4de60ff47c387b2593e3c856fac":{
      "scriptId":"u6"},
    "ea6c2c5fd8be4b1390c74c7d7c2afee4":{
      "scriptId":"u7"},
    "7031c1b1a31445c08f00cdde798b5544":{
      "scriptId":"u8"},
    "c721ae19a71448f8a42e5c5ca7b6ae31":{
      "scriptId":"u9"},
    "c8765cf6662c4297ac562f797a2c92e3":{
      "scriptId":"u10"},
    "25de059bb98749bfab50cf3593e08849":{
      "scriptId":"u11"},
    "c9efc8e65e3549c78558be860afec025":{
      "scriptId":"u12"},
    "0209a56d6e684f7ab2afaed44f570053":{
      "scriptId":"u13"},
    "0360e347be904bd0ac14afb6e4bd5579":{
      "scriptId":"u14"},
    "228ec3d318c64b33ac29312b7653c8ff":{
      "scriptId":"u15"},
    "912955c13a314ae48b660bc153e122b9":{
      "scriptId":"u16"},
    "ece26ba2596643c8bcc0bbbafb7f213e":{
      "scriptId":"u17"},
    "bc555dd6eb994840b563a5fb7675618d":{
      "scriptId":"u18"},
    "84da0bceea4b4a08bf41ad553c574f60":{
      "scriptId":"u19"},
    "1db7938a475c41ecaafe823c94026065":{
      "scriptId":"u20"},
    "237a3ccbc7754e6b81f93b404195473e":{
      "scriptId":"u21"},
    "5cb8b6105aff4d6287e5f147c020b7b7":{
      "scriptId":"u22"},
    "8d0210c1022e460b8b42efbe2a5cfcb0":{
      "scriptId":"u23"},
    "1b5ac525060546aba1b306c26a42913c":{
      "scriptId":"u24"},
    "521649f4c5a64327bd80a875cf487571":{
      "scriptId":"u25"}}});