$axure.loadCurrentPage({
  "url":"我的清单.html",
  "generationDate":new Date(1449815486490.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"74a05465a163453bae025cc2dbd219a1",
    "type":"Axure:Page",
    "name":"我的清单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"55052c686ec344cbb1ea17164ab04ec7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e6c2a16efe643408524769892007d5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u0.png"}},
{
          "id":"795a60294da447d899af172f323d4812",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":37},
            "size":{
              "width":235,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f965395f07574d929f52cd3dcd18a2b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":37},
                "size":{
                  "width":235,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 押宝首页",
                      "target":{
                        "targetType":"page",
                        "url":"押宝首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u2.png"}},
{
          "id":"9586244abb394c7c82a6deeb22f170d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":380,
              "y":49.5},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dca1c48281f946269e0f418c79707cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":380,
                  "y":49.5},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"685b50a6d20949f792f47cbd49262ad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":477,
              "y":50},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d952475a86b44a0dbc57257b6f9bc24f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":477,
                  "y":50},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bca4ce7706e44808868133f9dcb15902",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":599,
              "y":50},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4cddc6e8c8b4643badcaed7d5f9e0a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":599,
                  "y":50},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c4ce2bdf50b4866aa326eb1aa14c9dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":42.5},
            "size":{
              "width":127,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bf2a13721364fabb0072cf557259906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":42.5},
                "size":{
                  "width":127,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的清单",
                      "target":{
                        "targetType":"page",
                        "url":"我的清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u10.png"}},
{
          "id":"3c3f55d42fa743f9a955a881dd0e5b71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":84},
            "size":{
              "width":1200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/押宝列表页/u12_line.png"}},
{
          "id":"265f535285544a9fbcf29ca65a17bcb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1370},
            "size":{
              "width":1200,
              "height":405}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7f0b750425449e094adaec2c1e242d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1370},
                "size":{
                  "width":1200,
                  "height":405}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u82.png"}},
{
          "id":"b6521d7abe2341b3ae6be985fd20ed82",
          "label":"动态",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":110},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"02c062f830ba4655a2b81e3c3a72fb9f",
              "label":"未选",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aadffd141ce44972a9a111eccade57e1",
                  "label":"",
                  "parentDynamicPanel":"b6521d7abe2341b3ae6be985fd20ed82",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1000,
                      "height":324}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"852179d0413e4d77a069be5c51b505f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6521d7abe2341b3ae6be985fd20ed82",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1000,
                          "height":324}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的清单/u16.png"}},
{
                  "id":"0b2e5fcc740048849cea276171d1872a",
                  "label":"",
                  "parentDynamicPanel":"b6521d7abe2341b3ae6be985fd20ed82",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":704,
                      "y":298},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 动态 to 已选",
                              "panelsToStates":[{
                                  "panelPath":["b6521d7abe2341b3ae6be985fd20ed82"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"dedb5000f1cd45a0a3f391d35cd04701",
              "label":"已选",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3c05b026badc4064a397e601ba411d78",
                  "label":"",
                  "parentDynamicPanel":"b6521d7abe2341b3ae6be985fd20ed82",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1000,
                      "height":325}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"417e971c1000451fad541faeaa239a02",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b6521d7abe2341b3ae6be985fd20ed82",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1000,
                          "height":325}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的清单/u19.png"}},
{
                  "id":"86eb21e6005b4e8c87c9eedba09b5d97",
                  "label":"",
                  "parentDynamicPanel":"b6521d7abe2341b3ae6be985fd20ed82",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":704,
                      "y":298},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 动态 to 未选",
                              "panelsToStates":[{
                                  "panelPath":["b6521d7abe2341b3ae6be985fd20ed82"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"8a073091923d4cfe804b5dcaaa3ebceb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":485},
            "size":{
              "width":1200,
              "height":405}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c5b45d7eede4f0088f246de732787e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":485},
                "size":{
                  "width":1200,
                  "height":405}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u82.png"}},
{
          "id":"a39a2bc9142f4dcca9758db6774eeb46",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":873,
              "y":267},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cb1a8b26a3040f8958f78bc692f8396",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":873,
                  "y":267},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"93cbee966574404f861a5d6dd13256db",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":873,
              "y":286},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a095b890068b4efdbe5ac7f2162d663b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":873,
                  "y":286},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "55052c686ec344cbb1ea17164ab04ec7":{
      "scriptId":"u0"},
    "9e6c2a16efe643408524769892007d5e":{
      "scriptId":"u1"},
    "795a60294da447d899af172f323d4812":{
      "scriptId":"u2"},
    "f965395f07574d929f52cd3dcd18a2b6":{
      "scriptId":"u3"},
    "9586244abb394c7c82a6deeb22f170d6":{
      "scriptId":"u4"},
    "dca1c48281f946269e0f418c79707cf8":{
      "scriptId":"u5"},
    "685b50a6d20949f792f47cbd49262ad1":{
      "scriptId":"u6"},
    "d952475a86b44a0dbc57257b6f9bc24f":{
      "scriptId":"u7"},
    "bca4ce7706e44808868133f9dcb15902":{
      "scriptId":"u8"},
    "a4cddc6e8c8b4643badcaed7d5f9e0a5":{
      "scriptId":"u9"},
    "3c4ce2bdf50b4866aa326eb1aa14c9dd":{
      "scriptId":"u10"},
    "1bf2a13721364fabb0072cf557259906":{
      "scriptId":"u11"},
    "3c3f55d42fa743f9a955a881dd0e5b71":{
      "scriptId":"u12"},
    "265f535285544a9fbcf29ca65a17bcb4":{
      "scriptId":"u13"},
    "a7f0b750425449e094adaec2c1e242d9":{
      "scriptId":"u14"},
    "b6521d7abe2341b3ae6be985fd20ed82":{
      "scriptId":"u15"},
    "aadffd141ce44972a9a111eccade57e1":{
      "scriptId":"u16"},
    "852179d0413e4d77a069be5c51b505f8":{
      "scriptId":"u17"},
    "0b2e5fcc740048849cea276171d1872a":{
      "scriptId":"u18"},
    "3c05b026badc4064a397e601ba411d78":{
      "scriptId":"u19"},
    "417e971c1000451fad541faeaa239a02":{
      "scriptId":"u20"},
    "86eb21e6005b4e8c87c9eedba09b5d97":{
      "scriptId":"u21"},
    "8a073091923d4cfe804b5dcaaa3ebceb":{
      "scriptId":"u22"},
    "2c5b45d7eede4f0088f246de732787e3":{
      "scriptId":"u23"},
    "a39a2bc9142f4dcca9758db6774eeb46":{
      "scriptId":"u24"},
    "6cb1a8b26a3040f8958f78bc692f8396":{
      "scriptId":"u25"},
    "93cbee966574404f861a5d6dd13256db":{
      "scriptId":"u26"},
    "a095b890068b4efdbe5ac7f2162d663b":{
      "scriptId":"u27"}}});