$axure.loadCurrentPage({
  "url":"库存资产处理.html",
  "generationDate":new Date(1474884129329.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f9284252576746048eb140e03e276c7c",
    "type":"Axure:Page",
    "name":"库存资产处理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1a2ab32c78914731b08ee2d772ac5e48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dc27c0f62a64d399de3c15ae5414c50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":375,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"34e52c131f3843139ae6db97fb7f9d77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "size":{
              "width":375,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dc5d066ccf741c9b13368b0e5d1685e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "size":{
                  "width":375,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u2.png"}},
{
          "id":"46ab9dce30a34efb8bb0b47821edb073",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5ee7c03c84745708f3aac4fa1ec5509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18fff4d1538a4b28845cbe873b3da778",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":41},
            "size":{
              "width":375,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90ba92fb66a44638880dc1614a18e06b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":41},
                "size":{
                  "width":375,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u6.png"}},
{
          "id":"937639e97cf34c00982fbf58cf329386",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":11,
              "y":112},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd0d96e1e6b84d3d8f175ad275651f3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":112},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u8.png"}},
{
          "id":"8b3b8f154e3649b59226d14068a9e72a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":162},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4821d8a6dea4d9891b6554ab3bf2c31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":162},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u8.png"}},
{
          "id":"3e4c62370ef54991899317092e19f7e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":212},
            "size":{
              "width":350,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00cda16b6aba4ddfad83b407d38dd557",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":212},
                "size":{
                  "width":350,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u8.png"}},
{
          "id":"3ea64b07d4b1499e9fa262692b2adad2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":266},
            "size":{
              "width":258,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21cfd9825eb2498bbde2d444a13c2e1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":266},
                "size":{
                  "width":258,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u16.png"}},
{
          "id":"090868a2c2ef47029d2ad375766ff243",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":266},
            "size":{
              "width":81,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d933900003448fa9ef123f0fdc8bf99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":266},
                "size":{
                  "width":81,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u18.png"}},
{
          "id":"6d2cd6dff7694f2bb94cae141352b056",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":316},
            "size":{
              "width":218,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b632120a5e47f8b940014445afe4cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":316},
                "size":{
                  "width":218,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u20.png"}},
{
          "id":"402606c58bf54a2395dc192e1f8a67d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":240,
              "y":316},
            "size":{
              "width":121,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0d5ba4f654d4185af8674cd0e3ab3ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":316},
                "size":{
                  "width":121,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u22.png"}},
{
          "id":"1880f3aba4604c128639e91bfad2e954",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":12,
              "y":366},
            "size":{
              "width":349,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65293b9d5d1648ad865d1e3fea44dcfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":12,
                  "y":366},
                "size":{
                  "width":349,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u24.png"}},
{
          "id":"edac31d8026c45d0bb1c2b32523e9fac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":12,
              "y":442},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5e8c77a5f47476dab686ec91e799013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":12,
                  "y":442},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u26.png"}},
{
          "id":"73ab20984ca441f49469ad91bfc00984",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":418},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c52997209ca34e7db5a7da45e239d6f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":418},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbac2e33e6804835ae8436aaadf8d848",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":560},
            "size":{
              "width":360,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c43d869a46c946c8913cf55c216390cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":560},
                "size":{
                  "width":360,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我是债权人/u30.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1a2ab32c78914731b08ee2d772ac5e48":{
      "scriptId":"u0"},
    "0dc27c0f62a64d399de3c15ae5414c50":{
      "scriptId":"u1"},
    "34e52c131f3843139ae6db97fb7f9d77":{
      "scriptId":"u2"},
    "0dc5d066ccf741c9b13368b0e5d1685e":{
      "scriptId":"u3"},
    "46ab9dce30a34efb8bb0b47821edb073":{
      "scriptId":"u4"},
    "a5ee7c03c84745708f3aac4fa1ec5509":{
      "scriptId":"u5"},
    "18fff4d1538a4b28845cbe873b3da778":{
      "scriptId":"u6"},
    "90ba92fb66a44638880dc1614a18e06b":{
      "scriptId":"u7"},
    "937639e97cf34c00982fbf58cf329386":{
      "scriptId":"u8"},
    "dd0d96e1e6b84d3d8f175ad275651f3e":{
      "scriptId":"u9"},
    "8b3b8f154e3649b59226d14068a9e72a":{
      "scriptId":"u10"},
    "e4821d8a6dea4d9891b6554ab3bf2c31":{
      "scriptId":"u11"},
    "3e4c62370ef54991899317092e19f7e2":{
      "scriptId":"u12"},
    "00cda16b6aba4ddfad83b407d38dd557":{
      "scriptId":"u13"},
    "3ea64b07d4b1499e9fa262692b2adad2":{
      "scriptId":"u14"},
    "21cfd9825eb2498bbde2d444a13c2e1b":{
      "scriptId":"u15"},
    "090868a2c2ef47029d2ad375766ff243":{
      "scriptId":"u16"},
    "8d933900003448fa9ef123f0fdc8bf99":{
      "scriptId":"u17"},
    "6d2cd6dff7694f2bb94cae141352b056":{
      "scriptId":"u18"},
    "76b632120a5e47f8b940014445afe4cd":{
      "scriptId":"u19"},
    "402606c58bf54a2395dc192e1f8a67d9":{
      "scriptId":"u20"},
    "a0d5ba4f654d4185af8674cd0e3ab3ff":{
      "scriptId":"u21"},
    "1880f3aba4604c128639e91bfad2e954":{
      "scriptId":"u22"},
    "65293b9d5d1648ad865d1e3fea44dcfd":{
      "scriptId":"u23"},
    "edac31d8026c45d0bb1c2b32523e9fac":{
      "scriptId":"u24"},
    "b5e8c77a5f47476dab686ec91e799013":{
      "scriptId":"u25"},
    "73ab20984ca441f49469ad91bfc00984":{
      "scriptId":"u26"},
    "c52997209ca34e7db5a7da45e239d6f2":{
      "scriptId":"u27"},
    "fbac2e33e6804835ae8436aaadf8d848":{
      "scriptId":"u28"},
    "c43d869a46c946c8913cf55c216390cd":{
      "scriptId":"u29"}}});