$axure.loadCurrentPage({
  "url":"我的团购.html",
  "generationDate":new Date(1458541390121.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"be44f978c3704307abf426fb493b8c6e",
    "type":"Axure:Page",
    "name":"我的团购",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f2b771f9bdbc40ceb3d85d6768621921",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7ccb8f8f3f94eb5b9b27c63ca5ce61d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"8996de928ba4468db73019240edc1654",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":24},
            "size":{
              "width":120,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6add9f1004e34e75b0cd2599e1566879",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":24},
                "size":{
                  "width":120,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u2.png"}},
{
          "id":"3e3c499d25414bd683aa237d8b9b5acd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":40},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b347c8552b42469d87bfe5e286297dcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":40},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0abefe38b1314c49a02d45afb3bbe785",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":393,
              "y":40},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ac0288c64234badbbc4508d0bfb161d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":393,
                  "y":40},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 项目列表",
                      "target":{
                        "targetType":"page",
                        "url":"项目列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da9d5d67a1004fd4a7c31deac6ea3172",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":40},
            "size":{
              "width":200,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28d9bceeca20488c8811f7397ab69632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":40},
                "size":{
                  "width":200,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的团购",
                      "target":{
                        "targetType":"page",
                        "url":"我的团购.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u8.png"}},
{
          "id":"3248fc4fef544d3bb5070a736eec5e61",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":86},
            "size":{
              "width":1200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/项目列表/u10_line.png"}},
{
          "id":"1ce87bcab345438cbb2e22a117b11793",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":200,
              "y":106},
            "size":{
              "width":97,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"483d925319694faf9bcb24edc67235f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":200,
                  "y":106},
                "size":{
                  "width":97,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64121716ee2e4717914e318b6244ccea",
          "label":"我的团购",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":135},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"3127ca374b18450f883654e202734cbc",
              "label":"我关注的",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5c4275b11db7461b8dea7689013bfc45",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":400,
                      "height":48},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf39e745ffd147f8857ffb58e95580c9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":400,
                          "height":48},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 我的团购 to 我参与的",
                              "panelsToStates":[{
                                  "panelPath":["64121716ee2e4717914e318b6244ccea"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/我的团购/u14.png"}},
{
                  "id":"6289f029bfaf41808a49522b7a45e25e",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":47},
                    "size":{
                      "width":800,
                      "height":358},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bdb50976bda445ed9755aa0c17b6671a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":47},
                        "size":{
                          "width":800,
                          "height":358},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFAEAEAE}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u16.png"}},
{
                  "id":"f787a3c5a69b4177882106ddda05833c",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1},
                    "size":{
                      "width":400,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a4675d3121174ed8936c77a4426ebc10",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF3333,
                          "opacity":1},
                        "size":{
                          "width":400,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFAEAEAE}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u18.png"}},
{
                  "id":"44ce9810008447d5a7363b3d63cf4dfe",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":58},
                    "size":{
                      "width":200,
                      "height":97}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"345f31ad8e2f416d86223e4db3c4eba3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":58},
                        "size":{
                          "width":200,
                          "height":97}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u20.png"}},
{
                  "id":"f726702b3f4346d093dd75b085f229f5",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":58},
                    "size":{
                      "width":320,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b2ee5ef5bba42ad8a7c9aa6019d8449",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":58},
                        "size":{
                          "width":320,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3055e66ae23f4911ace9e94fe5c0d8cf",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1},
                    "location":{
                      "x":227,
                      "y":95},
                    "size":{
                      "width":233,
                      "height":10},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f793de726694f5480528f6c76256206",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1},
                        "location":{
                          "x":227,
                          "y":95},
                        "size":{
                          "width":233,
                          "height":10},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u24.png"}},
{
                  "id":"fab9d5f688424ac99fc3066965a69422",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":227,
                      "y":95},
                    "size":{
                      "width":122,
                      "height":10},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b848e1439be4696a540d3fa55804568",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":227,
                          "y":95},
                        "size":{
                          "width":122,
                          "height":10},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u26.png"}},
{
                  "id":"149103423fde42db8a6bb9a725660da9",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":478,
                      "y":92},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3802bb3af53b47d6bc5dcc8045ddc35b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":478,
                          "y":92},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cb5e318d0ae94adcbad73bc6619baa6c",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":115},
                    "size":{
                      "width":107,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f547424edd24e39a21d3f6d2676193f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":115},
                        "size":{
                          "width":107,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fa4a0772533a46c0836ae1675f3641fd",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":140},
                    "size":{
                      "width":106,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e07e1971fc5c4b9ca1b0e5b2d0103371",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":140},
                        "size":{
                          "width":106,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fb6dc985e1ab4adda1b57206aed7171c",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":690,
                      "y":84},
                    "size":{
                      "width":80,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d83f95e2b03e4220ba6fed397fe5a1df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":690,
                          "y":84},
                        "size":{
                          "width":80,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u34.png"}},
{
                  "id":"f53ab05437c541938ee5bdc3bafcb10a",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":165},
                    "size":{
                      "width":800,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的团购/u36_line.png"}}]},
{
              "id":"89cf1d3f79e747f1b996ab140b8e116c",
              "label":"我参与的",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"df58d2ef4bad40a98c51f7e0defaf651",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":47},
                    "size":{
                      "width":800,
                      "height":523},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"046ca0d4ccb741f2b28f245ed94582a7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":47},
                        "size":{
                          "width":800,
                          "height":523},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFAEAEAE}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u37.png"}},
{
                  "id":"c50c9d3d65364c4bb6fd1f413c202783",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "size":{
                      "width":400,
                      "height":48},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13b1d761ac6b4555ae468b21191c68ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF3333,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "size":{
                          "width":400,
                          "height":48},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFAEAEAE}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 我的团购 to 我关注的",
                              "panelsToStates":[{
                                  "panelPath":["64121716ee2e4717914e318b6244ccea"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/我的团购/u14.png"}},
{
                  "id":"77abe5a96e4d459ca1e7f5b7feafb78f",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":58},
                    "size":{
                      "width":200,
                      "height":97}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35a5ef5bda5f4f30b6bb2d1ef80f43ac",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":58},
                        "size":{
                          "width":200,
                          "height":97}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u20.png"}},
{
                  "id":"8e3c58186ac04729a65174f3497928fb",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":58},
                    "size":{
                      "width":320,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"46b35d80d1744348972a5eb8393eb8be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":58},
                        "size":{
                          "width":320,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"07ee6c2ef0b54304bd518cd9764fa5b6",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1},
                    "location":{
                      "x":227,
                      "y":95},
                    "size":{
                      "width":233,
                      "height":10},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"041c64835af64c80a6beaaa7ca991319",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1},
                        "location":{
                          "x":227,
                          "y":95},
                        "size":{
                          "width":233,
                          "height":10},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u24.png"}},
{
                  "id":"ac06830f643c4ba0ad21488eeafe55e1",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":227,
                      "y":95},
                    "size":{
                      "width":122,
                      "height":10},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1840b893a37496790b57ac554c27773",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":227,
                          "y":95},
                        "size":{
                          "width":122,
                          "height":10},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u26.png"}},
{
                  "id":"2054ed9b9f474d53b470a602aac58130",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":478,
                      "y":92},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74e0cb769fb24079a37c09193f946648",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":478,
                          "y":92},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"35c4e16e9e924bf6b31151faef655c34",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":115},
                    "size":{
                      "width":107,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b8608bf06a047828660811452114c82",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":115},
                        "size":{
                          "width":107,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ada6e69ef6b74274b5857e706f8f0aaa",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":140},
                    "size":{
                      "width":106,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc72421b10a346468c26f1e744d8f0b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":140},
                        "size":{
                          "width":106,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a955a64dcbf44f03adbb89f7559c18b5",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":165},
                    "size":{
                      "width":800,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的团购/u36_line.png"}},
{
                  "id":"71c60865bf364e43b2308f083cf60c0b",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":400,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4540c392fe69451bb31fccdd22a040e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":400,
                          "y":0},
                        "size":{
                          "width":400,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFAEAEAE}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u18.png"}},
{
                  "id":"ac1b5f44d0d847eca5d2083b094b9fe1",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":660,
                      "y":88},
                    "size":{
                      "width":100,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c8dcaaafb17b4b02aabdf5656f3d21d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":660,
                          "y":88},
                        "size":{
                          "width":100,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u58.png"}},
{
                  "id":"06021b186dee40eeb067ca259169cf6a",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":181},
                    "size":{
                      "width":200,
                      "height":97}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88d44c5cfed643428fc1b9c06045c47f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":181},
                        "size":{
                          "width":200,
                          "height":97}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u20.png"}},
{
                  "id":"2f0a4c8b7b164e7c89ac9cada5ee6d78",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":181},
                    "size":{
                      "width":320,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8debd8b512f24b52a371cbd2796fa6b8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":181},
                        "size":{
                          "width":320,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6e0a51746f7340789faa474f94fbfadd",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1},
                    "location":{
                      "x":227,
                      "y":218},
                    "size":{
                      "width":233,
                      "height":10},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0fe37cdd66844db9298d21f071b8ec0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1},
                        "location":{
                          "x":227,
                          "y":218},
                        "size":{
                          "width":233,
                          "height":10},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u24.png"}},
{
                  "id":"ed9bf42b3aaa44e7bc818aa4ccdabd7d",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":227,
                      "y":218},
                    "size":{
                      "width":233,
                      "height":10},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"589c962ab80f4741b05330062080e1a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":227,
                          "y":218},
                        "size":{
                          "width":233,
                          "height":10},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u66.png"}},
{
                  "id":"c7d720b8f75a4f70a37a67dcf9e51ec6",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":478,
                      "y":215},
                    "size":{
                      "width":34,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32716f71fd2b4aec94c64e4b8bca922a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":478,
                          "y":215},
                        "size":{
                          "width":34,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"25054c74e64d44dda3ed233e3d1d2e73",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":238},
                    "size":{
                      "width":107,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"202199a6630649018337e31598db635c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":238},
                        "size":{
                          "width":107,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"495f9fdaa02d4cdcb9978288012b57cd",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":263},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dcf3be53ad9e483a86a3523ae6a98788",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":263},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"24c39cf0f5c64bdbad1d5659e956fdbe",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":288},
                    "size":{
                      "width":800,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的团购/u36_line.png"}},
{
                  "id":"9700590bd5de45fa9da19e4e225697b4",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":660,
                      "y":211},
                    "size":{
                      "width":100,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19cdb77389214503baae4d37bc5d7a52",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":660,
                          "y":211},
                        "size":{
                          "width":100,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u58.png"}},
{
                  "id":"664dd729af16401fbd35646bdcbd978b",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":10,
                      "y":304},
                    "size":{
                      "width":200,
                      "height":97}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"420bf06e8cea4a93a1ef38333402eb7b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":10,
                          "y":304},
                        "size":{
                          "width":200,
                          "height":97}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u20.png"}},
{
                  "id":"06b19fca41094ec085b74a049a663291",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":227,
                      "y":304},
                    "size":{
                      "width":320,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6e88015062f4a28aa77f11f20ae7af3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":227,
                          "y":304},
                        "size":{
                          "width":320,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b52d479152b84a2ca045d4eb385b0a96",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1},
                    "location":{
                      "x":227,
                      "y":341},
                    "size":{
                      "width":233,
                      "height":10},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba6d3f9553f840669dee1c7d6b8abb3e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1},
                        "location":{
                          "x":227,
                          "y":341},
                        "size":{
                          "width":233,
                          "height":10},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u24.png"}},
{
                  "id":"97ced95e981543adbb35f204e3277be2",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":227,
                      "y":341},
                    "size":{
                      "width":122,
                      "height":10},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9729e8529f504250a967b7502a0e375c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":227,
                          "y":341},
                        "size":{
                          "width":122,
                          "height":10},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u26.png"}},
{
                  "id":"95e24207a4c3400d90f0303adb79916b",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":478,
                      "y":338},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d3ceca043de74e7d91361935cc3f6002",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":478,
                          "y":338},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"65e5ec628099407784fcd58732097f4a",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":361},
                    "size":{
                      "width":107,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"514ecee134b64da08447384978387293",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":361},
                        "size":{
                          "width":107,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f4fee137bd0f46c39049486a43394b66",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":227,
                      "y":386},
                    "size":{
                      "width":131,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a1ce593da4f4b4cad685bb34a5873f7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":227,
                          "y":386},
                        "size":{
                          "width":131,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9edb197092864b00a132306d55a367af",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":411},
                    "size":{
                      "width":800,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/我的团购/u36_line.png"}},
{
                  "id":"b86384a52f4d481b9e3da0750d13c95c",
                  "label":"",
                  "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":660,
                      "y":334},
                    "size":{
                      "width":100,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4f3685a874d943b3aee43078dc40385a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"64121716ee2e4717914e318b6244ccea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":660,
                          "y":334},
                        "size":{
                          "width":100,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的团购/u58.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "f2b771f9bdbc40ceb3d85d6768621921":{
      "scriptId":"u0"},
    "d7ccb8f8f3f94eb5b9b27c63ca5ce61d":{
      "scriptId":"u1"},
    "8996de928ba4468db73019240edc1654":{
      "scriptId":"u2"},
    "6add9f1004e34e75b0cd2599e1566879":{
      "scriptId":"u3"},
    "3e3c499d25414bd683aa237d8b9b5acd":{
      "scriptId":"u4"},
    "b347c8552b42469d87bfe5e286297dcb":{
      "scriptId":"u5"},
    "0abefe38b1314c49a02d45afb3bbe785":{
      "scriptId":"u6"},
    "1ac0288c64234badbbc4508d0bfb161d":{
      "scriptId":"u7"},
    "da9d5d67a1004fd4a7c31deac6ea3172":{
      "scriptId":"u8"},
    "28d9bceeca20488c8811f7397ab69632":{
      "scriptId":"u9"},
    "3248fc4fef544d3bb5070a736eec5e61":{
      "scriptId":"u10"},
    "1ce87bcab345438cbb2e22a117b11793":{
      "scriptId":"u11"},
    "483d925319694faf9bcb24edc67235f2":{
      "scriptId":"u12"},
    "64121716ee2e4717914e318b6244ccea":{
      "scriptId":"u13"},
    "5c4275b11db7461b8dea7689013bfc45":{
      "scriptId":"u14"},
    "cf39e745ffd147f8857ffb58e95580c9":{
      "scriptId":"u15"},
    "6289f029bfaf41808a49522b7a45e25e":{
      "scriptId":"u16"},
    "bdb50976bda445ed9755aa0c17b6671a":{
      "scriptId":"u17"},
    "f787a3c5a69b4177882106ddda05833c":{
      "scriptId":"u18"},
    "a4675d3121174ed8936c77a4426ebc10":{
      "scriptId":"u19"},
    "44ce9810008447d5a7363b3d63cf4dfe":{
      "scriptId":"u20"},
    "345f31ad8e2f416d86223e4db3c4eba3":{
      "scriptId":"u21"},
    "f726702b3f4346d093dd75b085f229f5":{
      "scriptId":"u22"},
    "3b2ee5ef5bba42ad8a7c9aa6019d8449":{
      "scriptId":"u23"},
    "3055e66ae23f4911ace9e94fe5c0d8cf":{
      "scriptId":"u24"},
    "9f793de726694f5480528f6c76256206":{
      "scriptId":"u25"},
    "fab9d5f688424ac99fc3066965a69422":{
      "scriptId":"u26"},
    "2b848e1439be4696a540d3fa55804568":{
      "scriptId":"u27"},
    "149103423fde42db8a6bb9a725660da9":{
      "scriptId":"u28"},
    "3802bb3af53b47d6bc5dcc8045ddc35b":{
      "scriptId":"u29"},
    "cb5e318d0ae94adcbad73bc6619baa6c":{
      "scriptId":"u30"},
    "9f547424edd24e39a21d3f6d2676193f":{
      "scriptId":"u31"},
    "fa4a0772533a46c0836ae1675f3641fd":{
      "scriptId":"u32"},
    "e07e1971fc5c4b9ca1b0e5b2d0103371":{
      "scriptId":"u33"},
    "fb6dc985e1ab4adda1b57206aed7171c":{
      "scriptId":"u34"},
    "d83f95e2b03e4220ba6fed397fe5a1df":{
      "scriptId":"u35"},
    "f53ab05437c541938ee5bdc3bafcb10a":{
      "scriptId":"u36"},
    "df58d2ef4bad40a98c51f7e0defaf651":{
      "scriptId":"u37"},
    "046ca0d4ccb741f2b28f245ed94582a7":{
      "scriptId":"u38"},
    "c50c9d3d65364c4bb6fd1f413c202783":{
      "scriptId":"u39"},
    "13b1d761ac6b4555ae468b21191c68ec":{
      "scriptId":"u40"},
    "77abe5a96e4d459ca1e7f5b7feafb78f":{
      "scriptId":"u41"},
    "35a5ef5bda5f4f30b6bb2d1ef80f43ac":{
      "scriptId":"u42"},
    "8e3c58186ac04729a65174f3497928fb":{
      "scriptId":"u43"},
    "46b35d80d1744348972a5eb8393eb8be":{
      "scriptId":"u44"},
    "07ee6c2ef0b54304bd518cd9764fa5b6":{
      "scriptId":"u45"},
    "041c64835af64c80a6beaaa7ca991319":{
      "scriptId":"u46"},
    "ac06830f643c4ba0ad21488eeafe55e1":{
      "scriptId":"u47"},
    "e1840b893a37496790b57ac554c27773":{
      "scriptId":"u48"},
    "2054ed9b9f474d53b470a602aac58130":{
      "scriptId":"u49"},
    "74e0cb769fb24079a37c09193f946648":{
      "scriptId":"u50"},
    "35c4e16e9e924bf6b31151faef655c34":{
      "scriptId":"u51"},
    "2b8608bf06a047828660811452114c82":{
      "scriptId":"u52"},
    "ada6e69ef6b74274b5857e706f8f0aaa":{
      "scriptId":"u53"},
    "cc72421b10a346468c26f1e744d8f0b5":{
      "scriptId":"u54"},
    "a955a64dcbf44f03adbb89f7559c18b5":{
      "scriptId":"u55"},
    "71c60865bf364e43b2308f083cf60c0b":{
      "scriptId":"u56"},
    "4540c392fe69451bb31fccdd22a040e6":{
      "scriptId":"u57"},
    "ac1b5f44d0d847eca5d2083b094b9fe1":{
      "scriptId":"u58"},
    "c8dcaaafb17b4b02aabdf5656f3d21d8":{
      "scriptId":"u59"},
    "06021b186dee40eeb067ca259169cf6a":{
      "scriptId":"u60"},
    "88d44c5cfed643428fc1b9c06045c47f":{
      "scriptId":"u61"},
    "2f0a4c8b7b164e7c89ac9cada5ee6d78":{
      "scriptId":"u62"},
    "8debd8b512f24b52a371cbd2796fa6b8":{
      "scriptId":"u63"},
    "6e0a51746f7340789faa474f94fbfadd":{
      "scriptId":"u64"},
    "d0fe37cdd66844db9298d21f071b8ec0":{
      "scriptId":"u65"},
    "ed9bf42b3aaa44e7bc818aa4ccdabd7d":{
      "scriptId":"u66"},
    "589c962ab80f4741b05330062080e1a4":{
      "scriptId":"u67"},
    "c7d720b8f75a4f70a37a67dcf9e51ec6":{
      "scriptId":"u68"},
    "32716f71fd2b4aec94c64e4b8bca922a":{
      "scriptId":"u69"},
    "25054c74e64d44dda3ed233e3d1d2e73":{
      "scriptId":"u70"},
    "202199a6630649018337e31598db635c":{
      "scriptId":"u71"},
    "495f9fdaa02d4cdcb9978288012b57cd":{
      "scriptId":"u72"},
    "dcf3be53ad9e483a86a3523ae6a98788":{
      "scriptId":"u73"},
    "24c39cf0f5c64bdbad1d5659e956fdbe":{
      "scriptId":"u74"},
    "9700590bd5de45fa9da19e4e225697b4":{
      "scriptId":"u75"},
    "19cdb77389214503baae4d37bc5d7a52":{
      "scriptId":"u76"},
    "664dd729af16401fbd35646bdcbd978b":{
      "scriptId":"u77"},
    "420bf06e8cea4a93a1ef38333402eb7b":{
      "scriptId":"u78"},
    "06b19fca41094ec085b74a049a663291":{
      "scriptId":"u79"},
    "a6e88015062f4a28aa77f11f20ae7af3":{
      "scriptId":"u80"},
    "b52d479152b84a2ca045d4eb385b0a96":{
      "scriptId":"u81"},
    "ba6d3f9553f840669dee1c7d6b8abb3e":{
      "scriptId":"u82"},
    "97ced95e981543adbb35f204e3277be2":{
      "scriptId":"u83"},
    "9729e8529f504250a967b7502a0e375c":{
      "scriptId":"u84"},
    "95e24207a4c3400d90f0303adb79916b":{
      "scriptId":"u85"},
    "d3ceca043de74e7d91361935cc3f6002":{
      "scriptId":"u86"},
    "65e5ec628099407784fcd58732097f4a":{
      "scriptId":"u87"},
    "514ecee134b64da08447384978387293":{
      "scriptId":"u88"},
    "f4fee137bd0f46c39049486a43394b66":{
      "scriptId":"u89"},
    "4a1ce593da4f4b4cad685bb34a5873f7":{
      "scriptId":"u90"},
    "9edb197092864b00a132306d55a367af":{
      "scriptId":"u91"},
    "b86384a52f4d481b9e3da0750d13c95c":{
      "scriptId":"u92"},
    "4f3685a874d943b3aee43078dc40385a":{
      "scriptId":"u93"}}});