$axure.loadCurrentPage({
  "url":"个人中心我的挂单.html",
  "generationDate":new Date(1454637459471.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1589911b527949359760ccceeb8463da",
    "type":"Axure:Page",
    "name":"个人中心我的挂单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d009cb586243417ea51377af6a800ab1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5898dfbba25e4c93b93d9d8acd10bade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u0.png"}},
{
          "id":"5f26a2ff8afa4065a8357f16733339fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":36},
            "size":{
              "width":280,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7ff9265321242a3807655c3ca5e6fb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":280,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u2.png"}},
{
          "id":"643ba69c7288429bb9bfcf296c54c036",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":55},
            "size":{
              "width":650,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f4fd4757307409e85f55a99ea5f02a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":55},
                "size":{
                  "width":650,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u4.png"}},
{
          "id":"3c70a2c1d9e94394ac5e1bf2ebf363d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF303849},
            "location":{
              "x":0,
              "y":102},
            "size":{
              "width":1200,
              "height":1018}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"848ff7083e264f07b4c118281273b376",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF303849},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":1200,
                  "height":1018}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u6.png"}},
{
          "id":"61dc62d374eb4fda909489f4e8a0ad62",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"91f116cb2f8040f698b1ca7df07bfd3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":1000,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c91289c7f7044c6f8a6bd1d48035750a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":1000,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u20.png"}},
{
          "id":"f6c02ef97a5446b2b17090bb597b9f30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89f570ddc4dc43188cc0300dbda676eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u22.png"}},
{
          "id":"f2516a167b034b5995367bc87521a6a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef18b0d5a514425984beb9415b5f0bff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个股",
                      "target":{
                        "targetType":"page",
                        "url":"个股.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca420dbb20224e7ca2ead5de84cc023f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":210},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10771f5f42a542d6805b1588d9bc9c58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":210},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u26.png"}},
{
          "id":"7e83c2f6bf1e433d979b3f3da52e097e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":250},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4284b6f5237f4ede8ed8a31087d3ae82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":250},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c5bb687819d4d378b56b5370c74e524",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF282828,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0287FE},
            "location":{
              "x":100,
              "y":270},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915b837758e04f73a815a5b7634884bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF282828,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0287FE},
                "location":{
                  "x":100,
                  "y":270},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u24.png"}},
{
          "id":"bb58bdfa510047a881224d0cc8468c22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":278},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f060d6020ed4786ab90a0aa297d3198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":278},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u32.png"}},
{
          "id":"577de8b38b4c42aea9dc8e8ecc65def7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":321},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b247ba9d28264990afd50af09d347b80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":321},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca6e7ce6ff9e4684ad97129b115f1c87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":207},
            "size":{
              "width":271,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed73fcbf0f984428a951a76f54828ed5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":207},
                "size":{
                  "width":271,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u25.png"}},
{
          "id":"d45315a155dd45d6828235e6dcf1c9a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":265,
              "y":270},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ad762ba71804e46828ff76f44821797",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":265,
                  "y":270},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3e9344ecb414af38f1f8863f158eac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":270},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c07b5af22082426a8ad9a87b8f598b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":412,
                  "y":270},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad29f01ef6f640b5881166a5d2925c63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":539,
              "y":270},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4976aecb9f6742b6be59acc0d01e4625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":539,
                  "y":270},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a43dc680eb724bf6b3cb292f70718c9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":687,
              "y":270},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0add75da85ed4227a5b9dad5ccf44f71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":687,
                  "y":270},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bf45e4a0c2f4584b66ec18614602d8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":823,
              "y":270},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"144b1e602b7848c0bbb08b01a84b5c46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":823,
                  "y":270},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"676e0fd77c974ccfbfeba531f8b336f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":949,
              "y":270},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c41aca520e6f43c78c49fa9353e88bf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":949,
                  "y":270},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82b79284d2ce4939b7d90c5301829779",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":286},
            "size":{
              "width":842,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人中心我的挂单/u39_line.png"}},
{
          "id":"6fe171b2f5664786a90f48d25039f623",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":306},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0c6026f788f4aa396bcf1400df8fb5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":306},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d3e734a58f0406f8381d5f5e03f4cdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF669900,
              "opacity":1},
            "location":{
              "x":412,
              "y":306},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fadc8f1c6e140ebad3574765eccefe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF669900,
                  "opacity":1},
                "location":{
                  "x":412,
                  "y":306},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddea87daec61451bbe9f9e802742fd57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":306},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40059ce34d374bc6b23cf3407839dad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":306},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d5320bd4a6e4a9e8ff7b1553708610f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":696,
              "y":306},
            "size":{
              "width":25,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2589621c2884e2da5b817d54374fd4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":696,
                  "y":306},
                "size":{
                  "width":25,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ddaf201d51242d09fa064e7142b6661",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":817,
              "y":306},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11569c131ad44536ad78bdd7d7d81219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":817,
                  "y":306},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db7b961cad0f4157abcd2e8e4863aeaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":920,
              "y":304},
            "size":{
              "width":41,
              "height":20},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71ca7d80391742fc9999b7d15a1c3b26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":920,
                  "y":304},
                "size":{
                  "width":41,
                  "height":20},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u50.png"}},
{
          "id":"262d3f964f45450c8f638ab99d492944",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":967,
              "y":304},
            "size":{
              "width":41,
              "height":20},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58511dc1e0da4fbb915daaa495a4c9d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":967,
                  "y":304},
                "size":{
                  "width":41,
                  "height":20},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u50.png"}},
{
          "id":"b851c8a8ece749a39e3d6e379b76cc7b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":220},
            "size":{
              "width":68,
              "height":26}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成交记录",
                      "target":{
                        "targetType":"page",
                        "url":"成交记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"83e104f36a3047e998c311e72c405e35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":124},
            "size":{
              "width":59,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72083d18c9084109b9b9550c28563659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":124},
                "size":{
                  "width":59,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u224.png"}},
{
          "id":"61eab18a706d4aecb3cdb5b7f95e0a78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":129},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d2deffcf4774762b0e3c97095c2664a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":129},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95e992b4be0745df8a76ad784ba7d0d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":149},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"602d355f02db439080f717486b8512f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":149},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"037291f7671a426eaef2748fb7a3db36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":169},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2c4345f25004ac8938fa9f1cc96703b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":169},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef0bb58d5638416bbe7fc19e028829d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":117},
            "size":{
              "width":87,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c05609910ff4fe3afd62ed98c1921c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":117},
                "size":{
                  "width":87,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c287a4b675a7417096027cdeedd85afe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":432,
              "y":154},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c29f8e01425441e9088ef5ce2e079df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":432,
                  "y":154},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99ab5d500b204c3091f231aa2d0c138a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":470,
              "y":154},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"030cc676ca6945cb9dbf79dd9812ddfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":154},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a2f93d36be84f92b60c5b9adfbe1d7b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":527,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"5a54c4ba620c466c97b08c9a4565322c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":551,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73215e0111454936a9dbc2a5efea42be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":551,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56d2e6d762cc45ffaf9a577689560e4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":556,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaccee6bb30d4fc6a65deed23abe5559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9c1b0bb74ad4ea7841af440b7f3017c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":327,
              "y":120},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a0213b4384f415a8c26c4c280146796",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":120},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fd8fcef452d4b7f96090bcae40aabbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":150},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28ba5512fd5e484daafb2f3f39a5622f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":150},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u76.png"}},
{
          "id":"6137b3f309944b688d1dc870f270c180",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":150},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8452ed0da3c84591b1faf34e665143c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":150},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u78.png"}},
{
          "id":"940460aaf2fb4c6c83f904dd7a13787a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":610,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e3cfc5a57b54c449d9651d0db73b55d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":610,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79eabfd3f9e746489ce2ab5519ecc208",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF00,
              "opacity":1},
            "location":{
              "x":605,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c6daf12aaba43d29b081c4ebee4c04c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00,
                  "opacity":1},
                "location":{
                  "x":605,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfb0a151e9694f48a8e66a10e1e6ec91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":665,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e1ee459f1c458cbcbc1b6506981e79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":665,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d13418488a7482cbf84ce7c9b0221de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":660,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c27d100e5cd4c908cbc00b8255c8935",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9652f1ca34ba450880451a80d3482f8f",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"bb4f543165ad4de187a13f9e7f8ee8da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":738,
              "y":128},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65a0da8350724274a37eeed9276dfb26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":738,
                  "y":128},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8a90a0e1d5b4601b272a6693ebcb356",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":738,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37eaa353bc5645adbefe5b01d7ad3140",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":738,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"880db859f18e45069d71bef6a8613169",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":775,
              "y":127},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dac42648ecd44af4a759db780f788f16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":775,
                  "y":127},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b78a439dea4439f9e9ce1b66b4368c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":775,
              "y":153},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aa7807ecdfc455fa50cbef6991d7716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":775,
                  "y":153},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a22b7ce5fb88422eb06f2565c6b7f373",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":831,
              "y":128},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c680fdabd7494826af1b302052e6f474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":128},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"012be7565f4c470b9210f6328d2cf7d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":831,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30b488be897742c7bd74bf2d996a590f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"67e76ca0e37242c09c72b41a1837e0ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":868,
              "y":127},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75e0acdbc28b462eaf0e9c95dfbe038a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":127},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6244fadbc31346e9bfe82913f1e22f32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF00,
              "opacity":1},
            "location":{
              "x":868,
              "y":153},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ccdf020545848af83944c78f8259b46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":153},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d009cb586243417ea51377af6a800ab1":{
      "scriptId":"u0"},
    "5898dfbba25e4c93b93d9d8acd10bade":{
      "scriptId":"u1"},
    "5f26a2ff8afa4065a8357f16733339fc":{
      "scriptId":"u2"},
    "e7ff9265321242a3807655c3ca5e6fb7":{
      "scriptId":"u3"},
    "643ba69c7288429bb9bfcf296c54c036":{
      "scriptId":"u4"},
    "7f4fd4757307409e85f55a99ea5f02a3":{
      "scriptId":"u5"},
    "3c70a2c1d9e94394ac5e1bf2ebf363d2":{
      "scriptId":"u6"},
    "848ff7083e264f07b4c118281273b376":{
      "scriptId":"u7"},
    "61dc62d374eb4fda909489f4e8a0ad62":{
      "scriptId":"u8"},
    "91f116cb2f8040f698b1ca7df07bfd3a":{
      "scriptId":"u9"},
    "c91289c7f7044c6f8a6bd1d48035750a":{
      "scriptId":"u10"},
    "f6c02ef97a5446b2b17090bb597b9f30":{
      "scriptId":"u11"},
    "89f570ddc4dc43188cc0300dbda676eb":{
      "scriptId":"u12"},
    "f2516a167b034b5995367bc87521a6a5":{
      "scriptId":"u13"},
    "ef18b0d5a514425984beb9415b5f0bff":{
      "scriptId":"u14"},
    "ca420dbb20224e7ca2ead5de84cc023f":{
      "scriptId":"u15"},
    "10771f5f42a542d6805b1588d9bc9c58":{
      "scriptId":"u16"},
    "7e83c2f6bf1e433d979b3f3da52e097e":{
      "scriptId":"u17"},
    "4284b6f5237f4ede8ed8a31087d3ae82":{
      "scriptId":"u18"},
    "2c5bb687819d4d378b56b5370c74e524":{
      "scriptId":"u19"},
    "915b837758e04f73a815a5b7634884bf":{
      "scriptId":"u20"},
    "bb58bdfa510047a881224d0cc8468c22":{
      "scriptId":"u21"},
    "9f060d6020ed4786ab90a0aa297d3198":{
      "scriptId":"u22"},
    "577de8b38b4c42aea9dc8e8ecc65def7":{
      "scriptId":"u23"},
    "b247ba9d28264990afd50af09d347b80":{
      "scriptId":"u24"},
    "ca6e7ce6ff9e4684ad97129b115f1c87":{
      "scriptId":"u25"},
    "ed73fcbf0f984428a951a76f54828ed5":{
      "scriptId":"u26"},
    "d45315a155dd45d6828235e6dcf1c9a8":{
      "scriptId":"u27"},
    "2ad762ba71804e46828ff76f44821797":{
      "scriptId":"u28"},
    "f3e9344ecb414af38f1f8863f158eac8":{
      "scriptId":"u29"},
    "c07b5af22082426a8ad9a87b8f598b51":{
      "scriptId":"u30"},
    "ad29f01ef6f640b5881166a5d2925c63":{
      "scriptId":"u31"},
    "4976aecb9f6742b6be59acc0d01e4625":{
      "scriptId":"u32"},
    "a43dc680eb724bf6b3cb292f70718c9f":{
      "scriptId":"u33"},
    "0add75da85ed4227a5b9dad5ccf44f71":{
      "scriptId":"u34"},
    "3bf45e4a0c2f4584b66ec18614602d8a":{
      "scriptId":"u35"},
    "144b1e602b7848c0bbb08b01a84b5c46":{
      "scriptId":"u36"},
    "676e0fd77c974ccfbfeba531f8b336f9":{
      "scriptId":"u37"},
    "c41aca520e6f43c78c49fa9353e88bf4":{
      "scriptId":"u38"},
    "82b79284d2ce4939b7d90c5301829779":{
      "scriptId":"u39"},
    "6fe171b2f5664786a90f48d25039f623":{
      "scriptId":"u40"},
    "e0c6026f788f4aa396bcf1400df8fb5c":{
      "scriptId":"u41"},
    "4d3e734a58f0406f8381d5f5e03f4cdd":{
      "scriptId":"u42"},
    "9fadc8f1c6e140ebad3574765eccefe0":{
      "scriptId":"u43"},
    "ddea87daec61451bbe9f9e802742fd57":{
      "scriptId":"u44"},
    "40059ce34d374bc6b23cf3407839dad0":{
      "scriptId":"u45"},
    "5d5320bd4a6e4a9e8ff7b1553708610f":{
      "scriptId":"u46"},
    "f2589621c2884e2da5b817d54374fd4f":{
      "scriptId":"u47"},
    "2ddaf201d51242d09fa064e7142b6661":{
      "scriptId":"u48"},
    "11569c131ad44536ad78bdd7d7d81219":{
      "scriptId":"u49"},
    "db7b961cad0f4157abcd2e8e4863aeaf":{
      "scriptId":"u50"},
    "71ca7d80391742fc9999b7d15a1c3b26":{
      "scriptId":"u51"},
    "262d3f964f45450c8f638ab99d492944":{
      "scriptId":"u52"},
    "58511dc1e0da4fbb915daaa495a4c9d2":{
      "scriptId":"u53"},
    "b851c8a8ece749a39e3d6e379b76cc7b":{
      "scriptId":"u54"},
    "83e104f36a3047e998c311e72c405e35":{
      "scriptId":"u55"},
    "72083d18c9084109b9b9550c28563659":{
      "scriptId":"u56"},
    "61eab18a706d4aecb3cdb5b7f95e0a78":{
      "scriptId":"u57"},
    "1d2deffcf4774762b0e3c97095c2664a":{
      "scriptId":"u58"},
    "95e992b4be0745df8a76ad784ba7d0d6":{
      "scriptId":"u59"},
    "602d355f02db439080f717486b8512f8":{
      "scriptId":"u60"},
    "037291f7671a426eaef2748fb7a3db36":{
      "scriptId":"u61"},
    "a2c4345f25004ac8938fa9f1cc96703b":{
      "scriptId":"u62"},
    "ef0bb58d5638416bbe7fc19e028829d3":{
      "scriptId":"u63"},
    "7c05609910ff4fe3afd62ed98c1921c0":{
      "scriptId":"u64"},
    "c287a4b675a7417096027cdeedd85afe":{
      "scriptId":"u65"},
    "4c29f8e01425441e9088ef5ce2e079df":{
      "scriptId":"u66"},
    "99ab5d500b204c3091f231aa2d0c138a":{
      "scriptId":"u67"},
    "030cc676ca6945cb9dbf79dd9812ddfc":{
      "scriptId":"u68"},
    "7a2f93d36be84f92b60c5b9adfbe1d7b":{
      "scriptId":"u69"},
    "5a54c4ba620c466c97b08c9a4565322c":{
      "scriptId":"u70"},
    "73215e0111454936a9dbc2a5efea42be":{
      "scriptId":"u71"},
    "56d2e6d762cc45ffaf9a577689560e4b":{
      "scriptId":"u72"},
    "eaccee6bb30d4fc6a65deed23abe5559":{
      "scriptId":"u73"},
    "d9c1b0bb74ad4ea7841af440b7f3017c":{
      "scriptId":"u74"},
    "1a0213b4384f415a8c26c4c280146796":{
      "scriptId":"u75"},
    "5fd8fcef452d4b7f96090bcae40aabbe":{
      "scriptId":"u76"},
    "28ba5512fd5e484daafb2f3f39a5622f":{
      "scriptId":"u77"},
    "6137b3f309944b688d1dc870f270c180":{
      "scriptId":"u78"},
    "8452ed0da3c84591b1faf34e665143c9":{
      "scriptId":"u79"},
    "940460aaf2fb4c6c83f904dd7a13787a":{
      "scriptId":"u80"},
    "1e3cfc5a57b54c449d9651d0db73b55d":{
      "scriptId":"u81"},
    "79eabfd3f9e746489ce2ab5519ecc208":{
      "scriptId":"u82"},
    "8c6daf12aaba43d29b081c4ebee4c04c":{
      "scriptId":"u83"},
    "dfb0a151e9694f48a8e66a10e1e6ec91":{
      "scriptId":"u84"},
    "71e1ee459f1c458cbcbc1b6506981e79":{
      "scriptId":"u85"},
    "6d13418488a7482cbf84ce7c9b0221de":{
      "scriptId":"u86"},
    "3c27d100e5cd4c908cbc00b8255c8935":{
      "scriptId":"u87"},
    "9652f1ca34ba450880451a80d3482f8f":{
      "scriptId":"u88"},
    "bb4f543165ad4de187a13f9e7f8ee8da":{
      "scriptId":"u89"},
    "65a0da8350724274a37eeed9276dfb26":{
      "scriptId":"u90"},
    "e8a90a0e1d5b4601b272a6693ebcb356":{
      "scriptId":"u91"},
    "37eaa353bc5645adbefe5b01d7ad3140":{
      "scriptId":"u92"},
    "880db859f18e45069d71bef6a8613169":{
      "scriptId":"u93"},
    "dac42648ecd44af4a759db780f788f16":{
      "scriptId":"u94"},
    "4b78a439dea4439f9e9ce1b66b4368c4":{
      "scriptId":"u95"},
    "0aa7807ecdfc455fa50cbef6991d7716":{
      "scriptId":"u96"},
    "a22b7ce5fb88422eb06f2565c6b7f373":{
      "scriptId":"u97"},
    "c680fdabd7494826af1b302052e6f474":{
      "scriptId":"u98"},
    "012be7565f4c470b9210f6328d2cf7d8":{
      "scriptId":"u99"},
    "30b488be897742c7bd74bf2d996a590f":{
      "scriptId":"u100"},
    "67e76ca0e37242c09c72b41a1837e0ca":{
      "scriptId":"u101"},
    "75e0acdbc28b462eaf0e9c95dfbe038a":{
      "scriptId":"u102"},
    "6244fadbc31346e9bfe82913f1e22f32":{
      "scriptId":"u103"},
    "9ccdf020545848af83944c78f8259b46":{
      "scriptId":"u104"}}});