$axure.loadCurrentPage({
  "url":"晒单.html",
  "generationDate":new Date(1449815595986.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c3251eaee6174a7ea28c598a8af19c7e",
    "type":"Axure:Page",
    "name":"晒单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"55052c686ec344cbb1ea17164ab04ec7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e6c2a16efe643408524769892007d5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u0.png"}},
{
          "id":"795a60294da447d899af172f323d4812",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":37},
            "size":{
              "width":235,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f965395f07574d929f52cd3dcd18a2b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":37},
                "size":{
                  "width":235,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 押宝首页",
                      "target":{
                        "targetType":"page",
                        "url":"押宝首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u2.png"}},
{
          "id":"9586244abb394c7c82a6deeb22f170d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":380,
              "y":49.5},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dca1c48281f946269e0f418c79707cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":380,
                  "y":49.5},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"685b50a6d20949f792f47cbd49262ad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":477,
              "y":50},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d952475a86b44a0dbc57257b6f9bc24f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":477,
                  "y":50},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bca4ce7706e44808868133f9dcb15902",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":599,
              "y":50},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4cddc6e8c8b4643badcaed7d5f9e0a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":599,
                  "y":50},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c4ce2bdf50b4866aa326eb1aa14c9dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":42.5},
            "size":{
              "width":127,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bf2a13721364fabb0072cf557259906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":42.5},
                "size":{
                  "width":127,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 晒单",
                      "target":{
                        "targetType":"page",
                        "url":"晒单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u10.png"}},
{
          "id":"3c3f55d42fa743f9a955a881dd0e5b71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":84},
            "size":{
              "width":1200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/押宝列表页/u12_line.png"}},
{
          "id":"889ca3f8f4744fbe88d5bd000125fccd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":107},
            "size":{
              "width":230,
              "height":343}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53a24c3698324edbb6481d8488d187f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":107},
                "size":{
                  "width":230,
                  "height":343}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息/u39.png"}},
{
          "id":"673f07c67d094f8aa8dcde709124257f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":123},
            "size":{
              "width":220,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ecfc54f893944a0bedabcfd8090e24a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":123},
                "size":{
                  "width":220,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晒单/u15.png"}},
{
          "id":"ca4f428d215c4db5976d32ec1b34b474",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":130},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9184f41918d84e41ad95d6edfb9d26d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":130},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3db705b9c52948b69a060a8a1fdb3652",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":174},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d452361c9bd4c4d9f6e975a047948c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":335,
                  "y":174},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b668361ef3f64a3faf784103d36dba8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":174},
            "size":{
              "width":220,
              "height":126},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c0b0465f5c14d55a76744b34a0db3b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":174},
                "size":{
                  "width":220,
                  "height":126},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晒单/u21.png"}},
{
          "id":"961199c68f4f4ed2a05cf49b3ae2750a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":477,
              "y":330},
            "size":{
              "width":106,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1685fa4c789d409fbda287236861903c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":477,
                  "y":330},
                "size":{
                  "width":106,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晒单/u23.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "55052c686ec344cbb1ea17164ab04ec7":{
      "scriptId":"u0"},
    "9e6c2a16efe643408524769892007d5e":{
      "scriptId":"u1"},
    "795a60294da447d899af172f323d4812":{
      "scriptId":"u2"},
    "f965395f07574d929f52cd3dcd18a2b6":{
      "scriptId":"u3"},
    "9586244abb394c7c82a6deeb22f170d6":{
      "scriptId":"u4"},
    "dca1c48281f946269e0f418c79707cf8":{
      "scriptId":"u5"},
    "685b50a6d20949f792f47cbd49262ad1":{
      "scriptId":"u6"},
    "d952475a86b44a0dbc57257b6f9bc24f":{
      "scriptId":"u7"},
    "bca4ce7706e44808868133f9dcb15902":{
      "scriptId":"u8"},
    "a4cddc6e8c8b4643badcaed7d5f9e0a5":{
      "scriptId":"u9"},
    "3c4ce2bdf50b4866aa326eb1aa14c9dd":{
      "scriptId":"u10"},
    "1bf2a13721364fabb0072cf557259906":{
      "scriptId":"u11"},
    "3c3f55d42fa743f9a955a881dd0e5b71":{
      "scriptId":"u12"},
    "889ca3f8f4744fbe88d5bd000125fccd":{
      "scriptId":"u13"},
    "53a24c3698324edbb6481d8488d187f2":{
      "scriptId":"u14"},
    "673f07c67d094f8aa8dcde709124257f":{
      "scriptId":"u15"},
    "9ecfc54f893944a0bedabcfd8090e24a":{
      "scriptId":"u16"},
    "ca4f428d215c4db5976d32ec1b34b474":{
      "scriptId":"u17"},
    "9184f41918d84e41ad95d6edfb9d26d2":{
      "scriptId":"u18"},
    "3db705b9c52948b69a060a8a1fdb3652":{
      "scriptId":"u19"},
    "4d452361c9bd4c4d9f6e975a047948c3":{
      "scriptId":"u20"},
    "b668361ef3f64a3faf784103d36dba8e":{
      "scriptId":"u21"},
    "5c0b0465f5c14d55a76744b34a0db3b1":{
      "scriptId":"u22"},
    "961199c68f4f4ed2a05cf49b3ae2750a":{
      "scriptId":"u23"},
    "1685fa4c789d409fbda287236861903c":{
      "scriptId":"u24"}}});