$axure.loadCurrentPage({
  "url":"个人中心我的挂单.html",
  "generationDate":new Date(1451300189625.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1589911b527949359760ccceeb8463da",
    "type":"Axure:Page",
    "name":"个人中心我的挂单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d009cb586243417ea51377af6a800ab1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5898dfbba25e4c93b93d9d8acd10bade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/债权股交易中心/u0.png"}},
{
          "id":"5f26a2ff8afa4065a8357f16733339fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":36},
            "size":{
              "width":280,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7ff9265321242a3807655c3ca5e6fb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":280,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/债权股交易中心/u2.png"}},
{
          "id":"643ba69c7288429bb9bfcf296c54c036",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":55},
            "size":{
              "width":650,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f4fd4757307409e85f55a99ea5f02a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":55},
                "size":{
                  "width":650,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/债权股交易中心/u4.png"}},
{
          "id":"3c70a2c1d9e94394ac5e1bf2ebf363d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF303849},
            "location":{
              "x":0,
              "y":102},
            "size":{
              "width":1200,
              "height":1018}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"848ff7083e264f07b4c118281273b376",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF303849},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":1200,
                  "height":1018}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u6.png"}},
{
          "id":"61dc62d374eb4fda909489f4e8a0ad62",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/债权股交易中心/u8_line.png"}},
{
          "id":"40ab0cecf73d4a23b3aacd2405ff9cba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":330,
              "y":135},
            "size":{
              "width":72,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d87ff978ddf496cbf44fe340d2deeb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":330,
                  "y":135},
                "size":{
                  "width":72,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3689012d7cd14df9bbdbb1a7046556fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":412,
              "y":130},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efb2f4b55c7646baaa2677295c12e50f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":412,
                  "y":130},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"820fc6b687ea4a10882e68cd6d929389",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":412,
              "y":149},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b30985a4d54141d795fd4660a731e764",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":412,
                  "y":149},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ceeb72fd2224755825bda1e208da440",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/债权股交易中心/u8_line.png"}},
{
          "id":"c21efec485124c928e038c772bd471b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":490,
              "y":128},
            "size":{
              "width":610,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44c71b07dc7649d692b2712dd30a7a98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":128},
                "size":{
                  "width":610,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5a0d75adab643c3b0cd47e072290977",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":490,
              "y":154},
            "size":{
              "width":610,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39c4e6dab543419f860cd0256856d146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":154},
                "size":{
                  "width":610,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91f116cb2f8040f698b1ca7df07bfd3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":1000,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c91289c7f7044c6f8a6bd1d48035750a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":1000,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/债权股交易中心/u20.png"}},
{
          "id":"f6c02ef97a5446b2b17090bb597b9f30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89f570ddc4dc43188cc0300dbda676eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/债权股交易中心/u22.png"}},
{
          "id":"f2516a167b034b5995367bc87521a6a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef18b0d5a514425984beb9415b5f0bff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 债权股交易中心",
                      "target":{
                        "targetType":"page",
                        "url":"债权股交易中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca420dbb20224e7ca2ead5de84cc023f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":210},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10771f5f42a542d6805b1588d9bc9c58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":210},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/债权股交易中心/u26.png"}},
{
          "id":"7e83c2f6bf1e433d979b3f3da52e097e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":250},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4284b6f5237f4ede8ed8a31087d3ae82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":250},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c5bb687819d4d378b56b5370c74e524",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF282828,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0287FE},
            "location":{
              "x":100,
              "y":270},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915b837758e04f73a815a5b7634884bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF282828,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0287FE},
                "location":{
                  "x":100,
                  "y":270},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/债权股交易中心/u24.png"}},
{
          "id":"bb58bdfa510047a881224d0cc8468c22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":278},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f060d6020ed4786ab90a0aa297d3198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":278},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/债权股交易中心/u32.png"}},
{
          "id":"577de8b38b4c42aea9dc8e8ecc65def7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":321},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b247ba9d28264990afd50af09d347b80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":321},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca6e7ce6ff9e4684ad97129b115f1c87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":207},
            "size":{
              "width":271,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed73fcbf0f984428a951a76f54828ed5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":207},
                "size":{
                  "width":271,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u36.png"}},
{
          "id":"d45315a155dd45d6828235e6dcf1c9a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":265,
              "y":270},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ad762ba71804e46828ff76f44821797",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":265,
                  "y":270},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3e9344ecb414af38f1f8863f158eac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":412,
              "y":270},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c07b5af22082426a8ad9a87b8f598b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":412,
                  "y":270},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad29f01ef6f640b5881166a5d2925c63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":539,
              "y":270},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4976aecb9f6742b6be59acc0d01e4625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":539,
                  "y":270},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a43dc680eb724bf6b3cb292f70718c9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":687,
              "y":270},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0add75da85ed4227a5b9dad5ccf44f71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":687,
                  "y":270},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bf45e4a0c2f4584b66ec18614602d8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":823,
              "y":270},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"144b1e602b7848c0bbb08b01a84b5c46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":823,
                  "y":270},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"676e0fd77c974ccfbfeba531f8b336f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":949,
              "y":270},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c41aca520e6f43c78c49fa9353e88bf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":949,
                  "y":270},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82b79284d2ce4939b7d90c5301829779",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":286},
            "size":{
              "width":842,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人中心我的挂单/u50_line.png"}},
{
          "id":"6fe171b2f5664786a90f48d25039f623",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":306},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0c6026f788f4aa396bcf1400df8fb5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":306},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d3e734a58f0406f8381d5f5e03f4cdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF669900,
              "opacity":1},
            "location":{
              "x":412,
              "y":306},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fadc8f1c6e140ebad3574765eccefe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF669900,
                  "opacity":1},
                "location":{
                  "x":412,
                  "y":306},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddea87daec61451bbe9f9e802742fd57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":306},
            "size":{
              "width":35,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40059ce34d374bc6b23cf3407839dad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":306},
                "size":{
                  "width":35,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d5320bd4a6e4a9e8ff7b1553708610f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":696,
              "y":306},
            "size":{
              "width":25,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2589621c2884e2da5b817d54374fd4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":696,
                  "y":306},
                "size":{
                  "width":25,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ddaf201d51242d09fa064e7142b6661",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":817,
              "y":306},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11569c131ad44536ad78bdd7d7d81219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":817,
                  "y":306},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db7b961cad0f4157abcd2e8e4863aeaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":920,
              "y":304},
            "size":{
              "width":41,
              "height":20},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71ca7d80391742fc9999b7d15a1c3b26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":920,
                  "y":304},
                "size":{
                  "width":41,
                  "height":20},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u61.png"}},
{
          "id":"262d3f964f45450c8f638ab99d492944",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":967,
              "y":304},
            "size":{
              "width":41,
              "height":20},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58511dc1e0da4fbb915daaa495a4c9d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":967,
                  "y":304},
                "size":{
                  "width":41,
                  "height":20},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u61.png"}},
{
          "id":"b851c8a8ece749a39e3d6e379b76cc7b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":220},
            "size":{
              "width":68,
              "height":26}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成交记录",
                      "target":{
                        "targetType":"page",
                        "url":"成交记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"83e104f36a3047e998c311e72c405e35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":124},
            "size":{
              "width":59,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72083d18c9084109b9b9550c28563659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":124},
                "size":{
                  "width":59,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/债权股交易中心/u224.png"}},
{
          "id":"61eab18a706d4aecb3cdb5b7f95e0a78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":129},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d2deffcf4774762b0e3c97095c2664a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":129},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95e992b4be0745df8a76ad784ba7d0d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":149},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"602d355f02db439080f717486b8512f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":149},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"037291f7671a426eaef2748fb7a3db36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":169},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2c4345f25004ac8938fa9f1cc96703b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":169},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d009cb586243417ea51377af6a800ab1":{
      "scriptId":"u0"},
    "5898dfbba25e4c93b93d9d8acd10bade":{
      "scriptId":"u1"},
    "5f26a2ff8afa4065a8357f16733339fc":{
      "scriptId":"u2"},
    "e7ff9265321242a3807655c3ca5e6fb7":{
      "scriptId":"u3"},
    "643ba69c7288429bb9bfcf296c54c036":{
      "scriptId":"u4"},
    "7f4fd4757307409e85f55a99ea5f02a3":{
      "scriptId":"u5"},
    "3c70a2c1d9e94394ac5e1bf2ebf363d2":{
      "scriptId":"u6"},
    "848ff7083e264f07b4c118281273b376":{
      "scriptId":"u7"},
    "61dc62d374eb4fda909489f4e8a0ad62":{
      "scriptId":"u8"},
    "40ab0cecf73d4a23b3aacd2405ff9cba":{
      "scriptId":"u9"},
    "6d87ff978ddf496cbf44fe340d2deeb8":{
      "scriptId":"u10"},
    "3689012d7cd14df9bbdbb1a7046556fd":{
      "scriptId":"u11"},
    "efb2f4b55c7646baaa2677295c12e50f":{
      "scriptId":"u12"},
    "820fc6b687ea4a10882e68cd6d929389":{
      "scriptId":"u13"},
    "b30985a4d54141d795fd4660a731e764":{
      "scriptId":"u14"},
    "0ceeb72fd2224755825bda1e208da440":{
      "scriptId":"u15"},
    "c21efec485124c928e038c772bd471b7":{
      "scriptId":"u16"},
    "44c71b07dc7649d692b2712dd30a7a98":{
      "scriptId":"u17"},
    "f5a0d75adab643c3b0cd47e072290977":{
      "scriptId":"u18"},
    "39c4e6dab543419f860cd0256856d146":{
      "scriptId":"u19"},
    "91f116cb2f8040f698b1ca7df07bfd3a":{
      "scriptId":"u20"},
    "c91289c7f7044c6f8a6bd1d48035750a":{
      "scriptId":"u21"},
    "f6c02ef97a5446b2b17090bb597b9f30":{
      "scriptId":"u22"},
    "89f570ddc4dc43188cc0300dbda676eb":{
      "scriptId":"u23"},
    "f2516a167b034b5995367bc87521a6a5":{
      "scriptId":"u24"},
    "ef18b0d5a514425984beb9415b5f0bff":{
      "scriptId":"u25"},
    "ca420dbb20224e7ca2ead5de84cc023f":{
      "scriptId":"u26"},
    "10771f5f42a542d6805b1588d9bc9c58":{
      "scriptId":"u27"},
    "7e83c2f6bf1e433d979b3f3da52e097e":{
      "scriptId":"u28"},
    "4284b6f5237f4ede8ed8a31087d3ae82":{
      "scriptId":"u29"},
    "2c5bb687819d4d378b56b5370c74e524":{
      "scriptId":"u30"},
    "915b837758e04f73a815a5b7634884bf":{
      "scriptId":"u31"},
    "bb58bdfa510047a881224d0cc8468c22":{
      "scriptId":"u32"},
    "9f060d6020ed4786ab90a0aa297d3198":{
      "scriptId":"u33"},
    "577de8b38b4c42aea9dc8e8ecc65def7":{
      "scriptId":"u34"},
    "b247ba9d28264990afd50af09d347b80":{
      "scriptId":"u35"},
    "ca6e7ce6ff9e4684ad97129b115f1c87":{
      "scriptId":"u36"},
    "ed73fcbf0f984428a951a76f54828ed5":{
      "scriptId":"u37"},
    "d45315a155dd45d6828235e6dcf1c9a8":{
      "scriptId":"u38"},
    "2ad762ba71804e46828ff76f44821797":{
      "scriptId":"u39"},
    "f3e9344ecb414af38f1f8863f158eac8":{
      "scriptId":"u40"},
    "c07b5af22082426a8ad9a87b8f598b51":{
      "scriptId":"u41"},
    "ad29f01ef6f640b5881166a5d2925c63":{
      "scriptId":"u42"},
    "4976aecb9f6742b6be59acc0d01e4625":{
      "scriptId":"u43"},
    "a43dc680eb724bf6b3cb292f70718c9f":{
      "scriptId":"u44"},
    "0add75da85ed4227a5b9dad5ccf44f71":{
      "scriptId":"u45"},
    "3bf45e4a0c2f4584b66ec18614602d8a":{
      "scriptId":"u46"},
    "144b1e602b7848c0bbb08b01a84b5c46":{
      "scriptId":"u47"},
    "676e0fd77c974ccfbfeba531f8b336f9":{
      "scriptId":"u48"},
    "c41aca520e6f43c78c49fa9353e88bf4":{
      "scriptId":"u49"},
    "82b79284d2ce4939b7d90c5301829779":{
      "scriptId":"u50"},
    "6fe171b2f5664786a90f48d25039f623":{
      "scriptId":"u51"},
    "e0c6026f788f4aa396bcf1400df8fb5c":{
      "scriptId":"u52"},
    "4d3e734a58f0406f8381d5f5e03f4cdd":{
      "scriptId":"u53"},
    "9fadc8f1c6e140ebad3574765eccefe0":{
      "scriptId":"u54"},
    "ddea87daec61451bbe9f9e802742fd57":{
      "scriptId":"u55"},
    "40059ce34d374bc6b23cf3407839dad0":{
      "scriptId":"u56"},
    "5d5320bd4a6e4a9e8ff7b1553708610f":{
      "scriptId":"u57"},
    "f2589621c2884e2da5b817d54374fd4f":{
      "scriptId":"u58"},
    "2ddaf201d51242d09fa064e7142b6661":{
      "scriptId":"u59"},
    "11569c131ad44536ad78bdd7d7d81219":{
      "scriptId":"u60"},
    "db7b961cad0f4157abcd2e8e4863aeaf":{
      "scriptId":"u61"},
    "71ca7d80391742fc9999b7d15a1c3b26":{
      "scriptId":"u62"},
    "262d3f964f45450c8f638ab99d492944":{
      "scriptId":"u63"},
    "58511dc1e0da4fbb915daaa495a4c9d2":{
      "scriptId":"u64"},
    "b851c8a8ece749a39e3d6e379b76cc7b":{
      "scriptId":"u65"},
    "83e104f36a3047e998c311e72c405e35":{
      "scriptId":"u66"},
    "72083d18c9084109b9b9550c28563659":{
      "scriptId":"u67"},
    "61eab18a706d4aecb3cdb5b7f95e0a78":{
      "scriptId":"u68"},
    "1d2deffcf4774762b0e3c97095c2664a":{
      "scriptId":"u69"},
    "95e992b4be0745df8a76ad784ba7d0d6":{
      "scriptId":"u70"},
    "602d355f02db439080f717486b8512f8":{
      "scriptId":"u71"},
    "037291f7671a426eaef2748fb7a3db36":{
      "scriptId":"u72"},
    "a2c4345f25004ac8938fa9f1cc96703b":{
      "scriptId":"u73"}}});