$axure.loadCurrentPage({
  "url":"交易中心.html",
  "generationDate":new Date(1454637459943.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d99f6f081f934b3e8832d3a6ed3dbe9d",
    "type":"Axure:Page",
    "name":"交易中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0f5aa339bc194a8a833c33008c8de60a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb5b544c23bd4bb1a9574be6210c8e19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u0.png"}},
{
          "id":"fc738cff6a9446499964e8062d1ed182",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":36},
            "size":{
              "width":280,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2480ea408cbf41bca99dd5ae287893b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":280,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u2.png"}},
{
          "id":"bd1ede8dfcaf430987c424cc3fcd6f4d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":55},
            "size":{
              "width":650,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e2425f888894053b93d1c3b1058db5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":55},
                "size":{
                  "width":650,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u4.png"}},
{
          "id":"f8e6dce4f671455cb3d8f1d46289ec35",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF303849},
            "location":{
              "x":0,
              "y":102},
            "size":{
              "width":1200,
              "height":1198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc37987b3984251bba11598b8072d77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF303849},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":1200,
                  "height":1198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u6.png"}},
{
          "id":"32832cfc478a4b4ca073d4e1c3fb0659",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"a68d36d70b38406f9a27759f8b172f9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":117},
            "size":{
              "width":87,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b67d674b0fb94f94bbc02d7b6e2482e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":117},
                "size":{
                  "width":87,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac26dff6682a4b90bd83c98dbb0ca63d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":432,
              "y":154},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddeac5a868b242878a5d5fe9dbb88cce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":432,
                  "y":154},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1163f9e19230422c86e45650f0600099",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":470,
              "y":154},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a44e8156b26243f2a34eb7965c1a7145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":154},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76312df1f11c4bf7ad6a7e5f2d28bb98",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":527,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"c422db41850b4cd99e9956af6082ad9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":551,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9201a1d144a43df8eb73e5d5e220331",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":551,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fc4cb530d624dfe87accaf49f7de035",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":556,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c4ce4272aca4949864d303c4fbac3fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"649593a9a68d4028b9ae717486cc0d1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":1000,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3af2008bd47445c9bb62e708684044de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":1000,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u20.png"}},
{
          "id":"e1458956019a45d3b14c65cc9220254c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a25c75c7cd8d4f27b3f8f8e2a982c0cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u22.png"}},
{
          "id":"d61dbda1cd744ebe8ee8c3e8c4d030fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0287FE},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41f67dac7d894316b578e2e6760144e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0287FE},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u24.png"}},
{
          "id":"551fb9cf914b4d4c9c855c67c23913ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":210},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a7954c9ca00414089bd6dcee681b30b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":210},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u26.png"}},
{
          "id":"7ffdd25880b34cc29923dc948795c1c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":250},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b187c7886d784d609b28484fc4361af2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":250},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4aa2ae092c444caf99ef450b0b327125",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF282828,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":100,
              "y":270},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9833c8ddfc149d8963b498e2717f3a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF282828,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":100,
                  "y":270},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成交记录",
                      "target":{
                        "targetType":"page",
                        "url":"成交记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个股/u30.png"}},
{
          "id":"70304cee38044c6eaf48fe06e6a5be42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":278},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c26d729948e4e4db34c375176470852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":278},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u32.png"}},
{
          "id":"403859bdb1b84d4b8968c3326107ad2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":321},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a353f62da094506bc36fea2259d76bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":321},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0217a3a6f4841fdab0af9c20c147e36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":1158},
            "size":{
              "width":595,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57f8f65e8ecd4b3aafb4fe6a937124a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":1158},
                "size":{
                  "width":595,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u222.png"}},
{
          "id":"13da9ac1dc2c42ed82223791869c3587",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":121},
            "size":{
              "width":59,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38edc839c15a46a498152a23eba34547",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":121},
                "size":{
                  "width":59,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u224.png"}},
{
          "id":"3d64b07bbae44200a9cd122d269a8658",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":126},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f486795f41264f19aeef9fe58d6fffca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":126},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f4e7bb9a0ed481aaa7af187b23d39ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":146},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce7fc58f39244d198823f44b06b2d3bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":146},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64ad8e5360b64468ab1966cd40cd44a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":166},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1f3e42a96d643c6b9e31613ed567896",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":166},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99f044b4dcf74ba2bcb69d7d31309b61",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":203},
            "size":{
              "width":910,
              "height":283}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e50bca6a4e964995a299b82a8785983a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":203},
                "size":{
                  "width":910,
                  "height":283}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易中心/u46.png"}},
{
          "id":"9250722d317f4cb9a849eebf96bf2691",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":779,
              "y":220},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c2d7f5e081549cfb165222a3fdf9033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":779,
                  "y":220},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de547e9347d848509228458889cd06c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":327,
              "y":120},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aca8b85c540448887dcbfab106e081e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":120},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fee6eeb6a7654b63bd97ef421a4e955e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":150},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"086cff4b4bc44de7adafb4196322b03a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":150},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u76.png"}},
{
          "id":"0fdaaae76eff488491db90f66c7c24a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":150},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72d9df12ce1e47a3a9dfc37af87a7144",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":150},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u78.png"}},
{
          "id":"5df2d0669fe947faa6b50efbfc24b4bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":610,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be972dc4901e4091974270f7eca73145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":610,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"072f18ae8ca645239fece1d15d5eb146",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF00,
              "opacity":1},
            "location":{
              "x":605,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2dad28304ac48f6aad56cbca7be3df1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00,
                  "opacity":1},
                "location":{
                  "x":605,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7e6c2fcbccb4048baf0e28e25736cfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":665,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"418e44f956204ff4b2a0a21534e2fd30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":665,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"998812c9a02349869ef5c110ecf3b6f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":660,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27b33cb455a24a9393f46abcb24c291a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4eef2a5922bf4d4384cdfa0b8cc38cbf",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"cd79d3618b524029a6af0d099a905d80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":738,
              "y":128},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ab65dd332ba436e801ab3a370ab39b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":738,
                  "y":128},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6834f84d015441119c570d00dba0b4e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":738,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9123318a4ef4b0dae6ecb4f2237dad6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":738,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0679aedc1c64bc4b89f93070198121c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":775,
              "y":127},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22773e65537e44b88c1f694f89c4404e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":775,
                  "y":127},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cb32faff212486ba898e07111f7495a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":775,
              "y":153},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99cd4a8fcf3b49188818617f13f2f32f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":775,
                  "y":153},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1faa8507251942e38cea5862cec47a2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":831,
              "y":128},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ef2e5de1c6c43bd935528211c8cb06c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":128},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b63c31eecb0439ba61a3f9032cb8742",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":831,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"719d8572cd7c4ea3925e04d8fdf9760d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff3848d62abf4c548e7cba51eeecd85b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":868,
              "y":127},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2fb3477a2a9497b9a6891e4f1a46418",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":127},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f2cfa6e4cee480388366c64cc10efc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF00,
              "opacity":1},
            "location":{
              "x":868,
              "y":153},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36d0ad9b2dd249018ab343b5c128d403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":153},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00c940453a2147f3867428129438e083",
          "label":"个股新闻",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":492},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"11c99e669f5c4643a4312ae98f73c25f",
              "label":"个股列表",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fd85212f36684eb6966c671967cb073a",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":850,
                      "height":113}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"26da752fe5474d618d6292c4317a47ac",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":850,
                          "height":113}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u82.png"}},
{
                  "id":"b883f73deb6d4bfea2f5ab15e09992d8",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":112},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48809b6d93b24029a3d70bf1acca6b6e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":112},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"f8d581808981445db8520ce85821e615",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":155},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6703b34203ee46b187ffa54ced65bf5d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":155},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"71872711254b4f129a9bc901c9ec8d9a",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":198},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbc5b93412bc47aa8db38da3b6ca8747",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":198},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"8bfecb0a14174edbb93088ce4bcfce64",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d161961af2441ffa53e9b2e68036410",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":240},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"2ccdffd1d9504372a6f44740f029873d",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":283},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8dae84efb15f4962afcf6057935570a7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":283},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"d553cb2821b1475e81d887acac8567f5",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":326},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f375a47f5cd48cc86a79b70d4ac88ea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":326},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"ae90ea172a304b9f9a37b6ca1b475bde",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":367},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d07928b1d9d7412baeeffc1fc97c352d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":367},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"176e083f6a444032b205c456e1aaa868",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":410},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10c704de9cfc468284f90bc622453dc4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":410},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"3e76738efd0345e78296ebaa9aff6b80",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":452},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b5e14da416994c26ad0f9ba4729710c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":452},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"fa9a059422f640f1a77dfbd4d4498c82",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":495},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3b33032b244b4e0384dcab225462966b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":495},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"a9e0db4b0c4f4ab284f719b97178d878",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":538},
                    "size":{
                      "width":850,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"315f70ceecef4f87a636d32ae7da2095",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":538},
                        "size":{
                          "width":850,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u84.png"}},
{
                  "id":"d462a33e66454725b0fc4dbf12182246",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":110,
                      "y":10},
                    "size":{
                      "width":110,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 个股新闻 to 新闻列表",
                              "panelsToStates":[{
                                  "panelPath":["00c940453a2147f3867428129438e083"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"f000646235b5460b84dcaeb9d3db4c6d",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":70},
                    "size":{
                      "width":820,
                      "height":512}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 个股",
                              "target":{
                                "targetType":"page",
                                "url":"个股.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]},
{
              "id":"4e6918b25f3a4a6390682186d9b99a2c",
              "label":"新闻列表",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"043bbb927723418b94ddc82583dfb237",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":850,
                      "height":113}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67de43f179c9471280d7d84a41193ca0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":850,
                          "height":113}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u82.png"}},
{
                  "id":"8fd15b8d1fe145beb1daf0a1e028f1f2",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":850,
                      "height":108}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"679797eddcd54be5927daa50ad40f85e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":850,
                          "height":108}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u110.png"}},
{
                  "id":"96eda072e2844475b2e3f3664d85579f",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":106},
                    "size":{
                      "width":850,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87c243ad2c264c899e0f908f0a121c2c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":106},
                        "size":{
                          "width":850,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u112.png"}},
{
                  "id":"272f4b5e3de14541a02b7c6f99736e93",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":151},
                    "size":{
                      "width":850,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f3934ce8c5b84bfc9b2965b19ba5c7d7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":151},
                        "size":{
                          "width":850,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u112.png"}},
{
                  "id":"caf1d924948242cfbceb43670653aa7f",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":195},
                    "size":{
                      "width":850,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"07354865c4bd4aecbf7a5365be8a185e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":195},
                        "size":{
                          "width":850,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u112.png"}},
{
                  "id":"647e134aad1e48cb9b5fcb73035ec00f",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":239},
                    "size":{
                      "width":850,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad44727e28c94b10979e94ea4ab32826",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":239},
                        "size":{
                          "width":850,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u112.png"}},
{
                  "id":"f4d11059f3814f808bf1507d442ad20f",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":283},
                    "size":{
                      "width":850,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5acccc588f4c40f5bfbd45f0da76e209",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":283},
                        "size":{
                          "width":850,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u112.png"}},
{
                  "id":"549c4ea8c9954fbabf89e5ef5e4c978f",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":328},
                    "size":{
                      "width":850,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"409f21fbc7b24e7a81e8ca6560b6949f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":328},
                        "size":{
                          "width":850,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u112.png"}},
{
                  "id":"f6f8297bff38462facc2b35aa032c65e",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":372},
                    "size":{
                      "width":850,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"318326a5366e4e3d93a14eef1c02493b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":372},
                        "size":{
                          "width":850,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u112.png"}},
{
                  "id":"0f7d0f6566414a9fa7c7d506f36fecf0",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":416},
                    "size":{
                      "width":850,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"04a872f750e24394a0b67fa167212352",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":416},
                        "size":{
                          "width":850,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u112.png"}},
{
                  "id":"e5bb353a600449518a2f0baa0a28bbba",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":460},
                    "size":{
                      "width":850,
                      "height":45}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a05a13c0a926466ab3acfe3ea6f70c41",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":460},
                        "size":{
                          "width":850,
                          "height":45}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交易中心/u112.png"}},
{
                  "id":"0c5ef4565c2b476eb1882b63fe0b9acc",
                  "label":"",
                  "parentDynamicPanel":"00c940453a2147f3867428129438e083",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":110,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 个股新闻 to 个股列表",
                              "panelsToStates":[{
                                  "panelPath":["00c940453a2147f3867428129438e083"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"11df20cb40b546f9ac93da8f40664e6b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":1078},
            "size":{
              "width":336,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e859e31428464bc99fa1323c55786651",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":1078},
                "size":{
                  "width":336,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易中心/u131.png"}},
{
          "id":"dce2e0dc34034bdbacd6c7826dd0bb86",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":250},
            "size":{
              "width":610,
              "height":230}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 资讯",
                      "target":{
                        "targetType":"page",
                        "url":"资讯.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "0f5aa339bc194a8a833c33008c8de60a":{
      "scriptId":"u0"},
    "eb5b544c23bd4bb1a9574be6210c8e19":{
      "scriptId":"u1"},
    "fc738cff6a9446499964e8062d1ed182":{
      "scriptId":"u2"},
    "2480ea408cbf41bca99dd5ae287893b2":{
      "scriptId":"u3"},
    "bd1ede8dfcaf430987c424cc3fcd6f4d":{
      "scriptId":"u4"},
    "9e2425f888894053b93d1c3b1058db5d":{
      "scriptId":"u5"},
    "f8e6dce4f671455cb3d8f1d46289ec35":{
      "scriptId":"u6"},
    "3cc37987b3984251bba11598b8072d77":{
      "scriptId":"u7"},
    "32832cfc478a4b4ca073d4e1c3fb0659":{
      "scriptId":"u8"},
    "a68d36d70b38406f9a27759f8b172f9c":{
      "scriptId":"u9"},
    "b67d674b0fb94f94bbc02d7b6e2482e3":{
      "scriptId":"u10"},
    "ac26dff6682a4b90bd83c98dbb0ca63d":{
      "scriptId":"u11"},
    "ddeac5a868b242878a5d5fe9dbb88cce":{
      "scriptId":"u12"},
    "1163f9e19230422c86e45650f0600099":{
      "scriptId":"u13"},
    "a44e8156b26243f2a34eb7965c1a7145":{
      "scriptId":"u14"},
    "76312df1f11c4bf7ad6a7e5f2d28bb98":{
      "scriptId":"u15"},
    "c422db41850b4cd99e9956af6082ad9d":{
      "scriptId":"u16"},
    "f9201a1d144a43df8eb73e5d5e220331":{
      "scriptId":"u17"},
    "3fc4cb530d624dfe87accaf49f7de035":{
      "scriptId":"u18"},
    "6c4ce4272aca4949864d303c4fbac3fb":{
      "scriptId":"u19"},
    "649593a9a68d4028b9ae717486cc0d1b":{
      "scriptId":"u20"},
    "3af2008bd47445c9bb62e708684044de":{
      "scriptId":"u21"},
    "e1458956019a45d3b14c65cc9220254c":{
      "scriptId":"u22"},
    "a25c75c7cd8d4f27b3f8f8e2a982c0cf":{
      "scriptId":"u23"},
    "d61dbda1cd744ebe8ee8c3e8c4d030fd":{
      "scriptId":"u24"},
    "41f67dac7d894316b578e2e6760144e2":{
      "scriptId":"u25"},
    "551fb9cf914b4d4c9c855c67c23913ba":{
      "scriptId":"u26"},
    "3a7954c9ca00414089bd6dcee681b30b":{
      "scriptId":"u27"},
    "7ffdd25880b34cc29923dc948795c1c4":{
      "scriptId":"u28"},
    "b187c7886d784d609b28484fc4361af2":{
      "scriptId":"u29"},
    "4aa2ae092c444caf99ef450b0b327125":{
      "scriptId":"u30"},
    "d9833c8ddfc149d8963b498e2717f3a6":{
      "scriptId":"u31"},
    "70304cee38044c6eaf48fe06e6a5be42":{
      "scriptId":"u32"},
    "5c26d729948e4e4db34c375176470852":{
      "scriptId":"u33"},
    "403859bdb1b84d4b8968c3326107ad2b":{
      "scriptId":"u34"},
    "2a353f62da094506bc36fea2259d76bc":{
      "scriptId":"u35"},
    "c0217a3a6f4841fdab0af9c20c147e36":{
      "scriptId":"u36"},
    "57f8f65e8ecd4b3aafb4fe6a937124a8":{
      "scriptId":"u37"},
    "13da9ac1dc2c42ed82223791869c3587":{
      "scriptId":"u38"},
    "38edc839c15a46a498152a23eba34547":{
      "scriptId":"u39"},
    "3d64b07bbae44200a9cd122d269a8658":{
      "scriptId":"u40"},
    "f486795f41264f19aeef9fe58d6fffca":{
      "scriptId":"u41"},
    "5f4e7bb9a0ed481aaa7af187b23d39ba":{
      "scriptId":"u42"},
    "ce7fc58f39244d198823f44b06b2d3bf":{
      "scriptId":"u43"},
    "64ad8e5360b64468ab1966cd40cd44a9":{
      "scriptId":"u44"},
    "a1f3e42a96d643c6b9e31613ed567896":{
      "scriptId":"u45"},
    "99f044b4dcf74ba2bcb69d7d31309b61":{
      "scriptId":"u46"},
    "e50bca6a4e964995a299b82a8785983a":{
      "scriptId":"u47"},
    "9250722d317f4cb9a849eebf96bf2691":{
      "scriptId":"u48"},
    "3c2d7f5e081549cfb165222a3fdf9033":{
      "scriptId":"u49"},
    "de547e9347d848509228458889cd06c0":{
      "scriptId":"u50"},
    "5aca8b85c540448887dcbfab106e081e":{
      "scriptId":"u51"},
    "fee6eeb6a7654b63bd97ef421a4e955e":{
      "scriptId":"u52"},
    "086cff4b4bc44de7adafb4196322b03a":{
      "scriptId":"u53"},
    "0fdaaae76eff488491db90f66c7c24a6":{
      "scriptId":"u54"},
    "72d9df12ce1e47a3a9dfc37af87a7144":{
      "scriptId":"u55"},
    "5df2d0669fe947faa6b50efbfc24b4bc":{
      "scriptId":"u56"},
    "be972dc4901e4091974270f7eca73145":{
      "scriptId":"u57"},
    "072f18ae8ca645239fece1d15d5eb146":{
      "scriptId":"u58"},
    "f2dad28304ac48f6aad56cbca7be3df1":{
      "scriptId":"u59"},
    "f7e6c2fcbccb4048baf0e28e25736cfd":{
      "scriptId":"u60"},
    "418e44f956204ff4b2a0a21534e2fd30":{
      "scriptId":"u61"},
    "998812c9a02349869ef5c110ecf3b6f4":{
      "scriptId":"u62"},
    "27b33cb455a24a9393f46abcb24c291a":{
      "scriptId":"u63"},
    "4eef2a5922bf4d4384cdfa0b8cc38cbf":{
      "scriptId":"u64"},
    "cd79d3618b524029a6af0d099a905d80":{
      "scriptId":"u65"},
    "3ab65dd332ba436e801ab3a370ab39b7":{
      "scriptId":"u66"},
    "6834f84d015441119c570d00dba0b4e6":{
      "scriptId":"u67"},
    "a9123318a4ef4b0dae6ecb4f2237dad6":{
      "scriptId":"u68"},
    "d0679aedc1c64bc4b89f93070198121c":{
      "scriptId":"u69"},
    "22773e65537e44b88c1f694f89c4404e":{
      "scriptId":"u70"},
    "3cb32faff212486ba898e07111f7495a":{
      "scriptId":"u71"},
    "99cd4a8fcf3b49188818617f13f2f32f":{
      "scriptId":"u72"},
    "1faa8507251942e38cea5862cec47a2a":{
      "scriptId":"u73"},
    "9ef2e5de1c6c43bd935528211c8cb06c":{
      "scriptId":"u74"},
    "5b63c31eecb0439ba61a3f9032cb8742":{
      "scriptId":"u75"},
    "719d8572cd7c4ea3925e04d8fdf9760d":{
      "scriptId":"u76"},
    "ff3848d62abf4c548e7cba51eeecd85b":{
      "scriptId":"u77"},
    "a2fb3477a2a9497b9a6891e4f1a46418":{
      "scriptId":"u78"},
    "1f2cfa6e4cee480388366c64cc10efc8":{
      "scriptId":"u79"},
    "36d0ad9b2dd249018ab343b5c128d403":{
      "scriptId":"u80"},
    "00c940453a2147f3867428129438e083":{
      "scriptId":"u81"},
    "fd85212f36684eb6966c671967cb073a":{
      "scriptId":"u82"},
    "26da752fe5474d618d6292c4317a47ac":{
      "scriptId":"u83"},
    "b883f73deb6d4bfea2f5ab15e09992d8":{
      "scriptId":"u84"},
    "48809b6d93b24029a3d70bf1acca6b6e":{
      "scriptId":"u85"},
    "f8d581808981445db8520ce85821e615":{
      "scriptId":"u86"},
    "6703b34203ee46b187ffa54ced65bf5d":{
      "scriptId":"u87"},
    "71872711254b4f129a9bc901c9ec8d9a":{
      "scriptId":"u88"},
    "dbc5b93412bc47aa8db38da3b6ca8747":{
      "scriptId":"u89"},
    "8bfecb0a14174edbb93088ce4bcfce64":{
      "scriptId":"u90"},
    "7d161961af2441ffa53e9b2e68036410":{
      "scriptId":"u91"},
    "2ccdffd1d9504372a6f44740f029873d":{
      "scriptId":"u92"},
    "8dae84efb15f4962afcf6057935570a7":{
      "scriptId":"u93"},
    "d553cb2821b1475e81d887acac8567f5":{
      "scriptId":"u94"},
    "8f375a47f5cd48cc86a79b70d4ac88ea":{
      "scriptId":"u95"},
    "ae90ea172a304b9f9a37b6ca1b475bde":{
      "scriptId":"u96"},
    "d07928b1d9d7412baeeffc1fc97c352d":{
      "scriptId":"u97"},
    "176e083f6a444032b205c456e1aaa868":{
      "scriptId":"u98"},
    "10c704de9cfc468284f90bc622453dc4":{
      "scriptId":"u99"},
    "3e76738efd0345e78296ebaa9aff6b80":{
      "scriptId":"u100"},
    "b5e14da416994c26ad0f9ba4729710c5":{
      "scriptId":"u101"},
    "fa9a059422f640f1a77dfbd4d4498c82":{
      "scriptId":"u102"},
    "3b33032b244b4e0384dcab225462966b":{
      "scriptId":"u103"},
    "a9e0db4b0c4f4ab284f719b97178d878":{
      "scriptId":"u104"},
    "315f70ceecef4f87a636d32ae7da2095":{
      "scriptId":"u105"},
    "d462a33e66454725b0fc4dbf12182246":{
      "scriptId":"u106"},
    "f000646235b5460b84dcaeb9d3db4c6d":{
      "scriptId":"u107"},
    "043bbb927723418b94ddc82583dfb237":{
      "scriptId":"u108"},
    "67de43f179c9471280d7d84a41193ca0":{
      "scriptId":"u109"},
    "8fd15b8d1fe145beb1daf0a1e028f1f2":{
      "scriptId":"u110"},
    "679797eddcd54be5927daa50ad40f85e":{
      "scriptId":"u111"},
    "96eda072e2844475b2e3f3664d85579f":{
      "scriptId":"u112"},
    "87c243ad2c264c899e0f908f0a121c2c":{
      "scriptId":"u113"},
    "272f4b5e3de14541a02b7c6f99736e93":{
      "scriptId":"u114"},
    "f3934ce8c5b84bfc9b2965b19ba5c7d7":{
      "scriptId":"u115"},
    "caf1d924948242cfbceb43670653aa7f":{
      "scriptId":"u116"},
    "07354865c4bd4aecbf7a5365be8a185e":{
      "scriptId":"u117"},
    "647e134aad1e48cb9b5fcb73035ec00f":{
      "scriptId":"u118"},
    "ad44727e28c94b10979e94ea4ab32826":{
      "scriptId":"u119"},
    "f4d11059f3814f808bf1507d442ad20f":{
      "scriptId":"u120"},
    "5acccc588f4c40f5bfbd45f0da76e209":{
      "scriptId":"u121"},
    "549c4ea8c9954fbabf89e5ef5e4c978f":{
      "scriptId":"u122"},
    "409f21fbc7b24e7a81e8ca6560b6949f":{
      "scriptId":"u123"},
    "f6f8297bff38462facc2b35aa032c65e":{
      "scriptId":"u124"},
    "318326a5366e4e3d93a14eef1c02493b":{
      "scriptId":"u125"},
    "0f7d0f6566414a9fa7c7d506f36fecf0":{
      "scriptId":"u126"},
    "04a872f750e24394a0b67fa167212352":{
      "scriptId":"u127"},
    "e5bb353a600449518a2f0baa0a28bbba":{
      "scriptId":"u128"},
    "a05a13c0a926466ab3acfe3ea6f70c41":{
      "scriptId":"u129"},
    "0c5ef4565c2b476eb1882b63fe0b9acc":{
      "scriptId":"u130"},
    "11df20cb40b546f9ac93da8f40664e6b":{
      "scriptId":"u131"},
    "e859e31428464bc99fa1323c55786651":{
      "scriptId":"u132"},
    "dce2e0dc34034bdbacd6c7826dd0bb86":{
      "scriptId":"u133"}}});