$axure.loadCurrentPage({
  "url":"秒杀首页.html",
  "generationDate":new Date(1457072024680.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"90737196615c428491175f8d7b04b2db",
    "type":"Axure:Page",
    "name":"秒杀首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d73f3a20d7a44d51b5dba0fa80916055",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd250e6ce394489b60313fcec99d269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/秒杀首页/u0.png"}},
{
          "id":"8883eff5fffe4669bb42254698ef2397",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":1200,
              "height":59},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d10ed765a1664fe9bbc7d6ace86b2e72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":1200,
                  "height":59},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/秒杀首页/u2.png"}},
{
          "id":"8d33991a85104ec6ad352f47f35a20b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":691},
            "size":{
              "width":1200,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9299439d29e4d19831cb144dee9a0de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":691},
                "size":{
                  "width":1200,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/秒杀首页/u4.png"}},
{
          "id":"6a12e1c7c18d4986bedeb1e1033a085c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":159},
            "size":{
              "width":1200,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd794de6f8fa4576b8474f94b3273b55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":159},
                "size":{
                  "width":1200,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/秒杀首页/u6.png"}},
{
          "id":"0ce20ae793ad48748893861dca94787f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":85},
            "size":{
              "width":1000,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea2512e512a345eb84e500be4eb442fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":85},
                "size":{
                  "width":1000,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/秒杀首页/u8.png"}},
{
          "id":"00903fe1238b4a48bbfaa88779942995",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":417},
            "size":{
              "width":1200,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4a236b184554136aba3e13706491430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":417},
                "size":{
                  "width":1200,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/秒杀首页/u6.png"}},
{
          "id":"7b8d7917dfab4b509e5217f13cd25b66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFED623},
            "location":{
              "x":0,
              "y":85},
            "size":{
              "width":100,
              "height":62},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e56c1882fd14226ad8ec95f6ef32f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFED623},
                "location":{
                  "x":0,
                  "y":85},
                "size":{
                  "width":100,
                  "height":62},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/秒杀首页/u12.png"}},
{
          "id":"5af8efaa1e524dddb566d7ee08652752",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFED623},
            "location":{
              "x":1100,
              "y":85},
            "size":{
              "width":100,
              "height":62},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f54610ec2d494d1d9cc52c8ebc87db65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFED623},
                "location":{
                  "x":1100,
                  "y":85},
                "size":{
                  "width":100,
                  "height":62},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/秒杀首页/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d73f3a20d7a44d51b5dba0fa80916055":{
      "scriptId":"u0"},
    "4bd250e6ce394489b60313fcec99d269":{
      "scriptId":"u1"},
    "8883eff5fffe4669bb42254698ef2397":{
      "scriptId":"u2"},
    "d10ed765a1664fe9bbc7d6ace86b2e72":{
      "scriptId":"u3"},
    "8d33991a85104ec6ad352f47f35a20b7":{
      "scriptId":"u4"},
    "c9299439d29e4d19831cb144dee9a0de":{
      "scriptId":"u5"},
    "6a12e1c7c18d4986bedeb1e1033a085c":{
      "scriptId":"u6"},
    "fd794de6f8fa4576b8474f94b3273b55":{
      "scriptId":"u7"},
    "0ce20ae793ad48748893861dca94787f":{
      "scriptId":"u8"},
    "ea2512e512a345eb84e500be4eb442fd":{
      "scriptId":"u9"},
    "00903fe1238b4a48bbfaa88779942995":{
      "scriptId":"u10"},
    "a4a236b184554136aba3e13706491430":{
      "scriptId":"u11"},
    "7b8d7917dfab4b509e5217f13cd25b66":{
      "scriptId":"u12"},
    "9e56c1882fd14226ad8ec95f6ef32f38":{
      "scriptId":"u13"},
    "5af8efaa1e524dddb566d7ee08652752":{
      "scriptId":"u14"},
    "f54610ec2d494d1d9cc52c8ebc87db65":{
      "scriptId":"u15"}}});