$axure.loadCurrentPage({
  "url":"资讯.html",
  "generationDate":new Date(1454637460174.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"30c35896483545f9809ebb43d5cb4fa4",
    "type":"Axure:Page",
    "name":"资讯",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9654716f95d1402f92c8cdbd05e12a53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"643e2074ed014ea0a901d5bfb1fcefe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u0.png"}},
{
          "id":"0d03f7cacb7c4cc9a6ea12e0aa942b96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":36},
            "size":{
              "width":280,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7880e43af8a74919b5b3e5a2b1d86021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":280,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u2.png"}},
{
          "id":"08be34167a9a448881212d04064af89b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":55},
            "size":{
              "width":650,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a577e0e88ef24c2bab2bb60a431b71e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":55},
                "size":{
                  "width":650,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u4.png"}},
{
          "id":"275592438670448da6476f4755265102",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF303849},
            "location":{
              "x":0,
              "y":102},
            "size":{
              "width":1200,
              "height":1198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"316c6c51ab88425ba50a29fcda848290",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF303849},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":1200,
                  "height":1198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u6.png"}},
{
          "id":"51cfe8af49194637a3f093d12fcdfd49",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"fa0d123a9b4945d281cfb2d89cb338e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":117},
            "size":{
              "width":87,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"005791cae06f4c769fae5236b5e65403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":117},
                "size":{
                  "width":87,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0a083e39d804840b9e5b8f2e859d318",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":432,
              "y":154},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a01cda8b326b409eba21dce33f700d73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":432,
                  "y":154},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5651cd54ed6849f1b97ccc4a5c202ff8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":470,
              "y":154},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00dbf984eb304566a54f1c5fdb683fa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":154},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"760c55d181bd48cd92b66a930c6b1f19",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":527,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"5e393aeb49b24dbeb3af122618bb5725",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":551,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4975029f32e4e2091ff8516d0a0e8cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":551,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43161f80aff54595a53f5377fcd8fc02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":556,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3821f4ac44842f39fd9aad54616abf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df0265f0983e402895c621affc67e8c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":1000,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1d514de024c484db530d75529be13ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":1000,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u20.png"}},
{
          "id":"c25df7213f4243ccbb060a6f208a570c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c40ce66d8c84984a2d292757edcaea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u22.png"}},
{
          "id":"e1965559effb40e882037d97a461ee65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0287FE},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c4a86d135b3448fbb203b980446fd72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0287FE},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 交易中心",
                      "target":{
                        "targetType":"page",
                        "url":"交易中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个股/u24.png"}},
{
          "id":"01b33a11171e4960b3c19670685a1d94",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":210},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebf56a2dee5b4d099e6a1d2ee8b64ef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":210},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u26.png"}},
{
          "id":"096941512d2c4cac8a85f600076db832",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":250},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67489d97c9a44de9aaa307a3a6f0c4ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":250},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b0c4bdad4b04e25b6dc2005ebcb6500",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF282828,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":100,
              "y":270},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c1ef02ed258472da02f7caf275a31a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF282828,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":100,
                  "y":270},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成交记录",
                      "target":{
                        "targetType":"page",
                        "url":"成交记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个股/u30.png"}},
{
          "id":"2e78ac1aed9e41b4aeb8dd2daa0ddaa2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":278},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f56b885cfa041e6886a6c60e78a3706",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":278},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u32.png"}},
{
          "id":"79bcc1108b6a4adfb5db85fd8b84daf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":321},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feaaf7f0f3144694991d13a6ea4b7992",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":321},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4eab7b5cff694bbc8a3d0d7a3052b779",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":1158},
            "size":{
              "width":595,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8017ffdd95d4f37ae47e61402e32e86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":1158},
                "size":{
                  "width":595,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u222.png"}},
{
          "id":"e9298e561486407ab8575f9d59e0a4e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":121},
            "size":{
              "width":59,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d961e062dfa44848a0c765b56c540267",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":121},
                "size":{
                  "width":59,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u224.png"}},
{
          "id":"7c55285a1d414c3e83fb98d46acd8872",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":126},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34e2fb9a906242638a92359ffc4289db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":126},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db20f2992b474638aa2fb3560e94a7bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":146},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b132d95312d042958853b3e22ea7369f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":146},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8492a485c7d4bdb9700ee741486f026",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":166},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05129d74230e482192a3f963b425c201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":166},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3ae4ad5a9454784ae4c2bfb180cf10a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":203},
            "size":{
              "width":910,
              "height":283}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a8f63a9e4b6408ab2b49228233d2593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":203},
                "size":{
                  "width":910,
                  "height":283}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交易中心/u46.png"}},
{
          "id":"7163ce3b30bc42d7862941bb2210e541",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":779,
              "y":220},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0d6f8a67d5b49edbe1ed581eb879e56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":779,
                  "y":220},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c983b22eb4ec4c5293fe44cb3d0a3437",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":327,
              "y":120},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2340ffd188c0437cbeb205ca8bb2455d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":120},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13ea805b8182448f8cbdbcabac47636a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":150},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6af3e97fe1b484cb52a36a331614e63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":150},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u76.png"}},
{
          "id":"da0631efd3ed48bea8c38b7afd5cd11e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":150},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"608fdac36e474754bc51c1ae16aeb543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":150},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u78.png"}},
{
          "id":"68e7cf5b554d4be8aafaefd8de267523",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":610,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dde9d631ba0f4ed693fbf834975fd5bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":610,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29afe85282354e839b58125113021678",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF00,
              "opacity":1},
            "location":{
              "x":605,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c183c2ab7e042fea9bc7785a752e661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00,
                  "opacity":1},
                "location":{
                  "x":605,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db43672d13764b97b458eec552b4cd8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":665,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce41786514c64a7fbf9c16cb0f94ddb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":665,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64fbb3aca4cd4c348f16e34689976b8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":660,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b82358449d7945839b6c4c0a35d2aab4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33cf9c2bf87044b8bbe7787d7410d30e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"20fa6bdade9242268e970c75f45cae29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":738,
              "y":128},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a58ed3cc090b41fd9e50cb2a720f01c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":738,
                  "y":128},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"849b80bf03814f6c8a11338cd1b1688c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":738,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd0f7d51ec534e92a97ea23023aed7b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":738,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0122edb93e6b44839d0eb7f89dd5e6da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":775,
              "y":127},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a07017ecd1642c4898c94d278dc1270",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":775,
                  "y":127},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a7e1e689f3d4bb681fdde730291fced",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":775,
              "y":153},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57e1e4599719407c8834ed6e63b0d5b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":775,
                  "y":153},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53167daa210f49fe9aff671335697dee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":831,
              "y":128},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"647d660929ae4015b44b774f28e0c2e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":128},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abbf151c2a0444abb02f3eb822386a91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":831,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71f320194b8b4f8d9658dc62bc5357c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb333b1d14944c3faceb36f58c5614a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":868,
              "y":127},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c3073991ee04cc5b4105fa06788709b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":127},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f1719c56d434324be2747172c582c19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF00,
              "opacity":1},
            "location":{
              "x":868,
              "y":153},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0900ce7fb114f83ae76a884336eb739",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":153},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cd191d039d74c2b95441f747f45191a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":210},
            "size":{
              "width":630,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96f7a07a8daf43d0a2e6f82e8f590a92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":210},
                "size":{
                  "width":630,
                  "height":280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资讯/u81.png"}},
{
          "id":"d0d6a1e4e4594d8597ba55e03905beb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":861,
              "y":512},
            "size":{
              "width":212,
              "height":147}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3c1e663fdcc479b902224e3cf69e5dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":861,
                  "y":512},
                "size":{
                  "width":212,
                  "height":147}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资讯/u83.png"}},
{
          "id":"21cb239b1895448e8986f7e56dd9b24a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":500},
            "size":{
              "width":610,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1225c0d5584146c19fbbb43d3f0a3bfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":500},
                "size":{
                  "width":610,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资讯/u85.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9654716f95d1402f92c8cdbd05e12a53":{
      "scriptId":"u0"},
    "643e2074ed014ea0a901d5bfb1fcefe0":{
      "scriptId":"u1"},
    "0d03f7cacb7c4cc9a6ea12e0aa942b96":{
      "scriptId":"u2"},
    "7880e43af8a74919b5b3e5a2b1d86021":{
      "scriptId":"u3"},
    "08be34167a9a448881212d04064af89b":{
      "scriptId":"u4"},
    "a577e0e88ef24c2bab2bb60a431b71e9":{
      "scriptId":"u5"},
    "275592438670448da6476f4755265102":{
      "scriptId":"u6"},
    "316c6c51ab88425ba50a29fcda848290":{
      "scriptId":"u7"},
    "51cfe8af49194637a3f093d12fcdfd49":{
      "scriptId":"u8"},
    "fa0d123a9b4945d281cfb2d89cb338e9":{
      "scriptId":"u9"},
    "005791cae06f4c769fae5236b5e65403":{
      "scriptId":"u10"},
    "c0a083e39d804840b9e5b8f2e859d318":{
      "scriptId":"u11"},
    "a01cda8b326b409eba21dce33f700d73":{
      "scriptId":"u12"},
    "5651cd54ed6849f1b97ccc4a5c202ff8":{
      "scriptId":"u13"},
    "00dbf984eb304566a54f1c5fdb683fa5":{
      "scriptId":"u14"},
    "760c55d181bd48cd92b66a930c6b1f19":{
      "scriptId":"u15"},
    "5e393aeb49b24dbeb3af122618bb5725":{
      "scriptId":"u16"},
    "e4975029f32e4e2091ff8516d0a0e8cb":{
      "scriptId":"u17"},
    "43161f80aff54595a53f5377fcd8fc02":{
      "scriptId":"u18"},
    "f3821f4ac44842f39fd9aad54616abf8":{
      "scriptId":"u19"},
    "df0265f0983e402895c621affc67e8c1":{
      "scriptId":"u20"},
    "c1d514de024c484db530d75529be13ed":{
      "scriptId":"u21"},
    "c25df7213f4243ccbb060a6f208a570c":{
      "scriptId":"u22"},
    "9c40ce66d8c84984a2d292757edcaea1":{
      "scriptId":"u23"},
    "e1965559effb40e882037d97a461ee65":{
      "scriptId":"u24"},
    "4c4a86d135b3448fbb203b980446fd72":{
      "scriptId":"u25"},
    "01b33a11171e4960b3c19670685a1d94":{
      "scriptId":"u26"},
    "ebf56a2dee5b4d099e6a1d2ee8b64ef5":{
      "scriptId":"u27"},
    "096941512d2c4cac8a85f600076db832":{
      "scriptId":"u28"},
    "67489d97c9a44de9aaa307a3a6f0c4ed":{
      "scriptId":"u29"},
    "7b0c4bdad4b04e25b6dc2005ebcb6500":{
      "scriptId":"u30"},
    "7c1ef02ed258472da02f7caf275a31a8":{
      "scriptId":"u31"},
    "2e78ac1aed9e41b4aeb8dd2daa0ddaa2":{
      "scriptId":"u32"},
    "2f56b885cfa041e6886a6c60e78a3706":{
      "scriptId":"u33"},
    "79bcc1108b6a4adfb5db85fd8b84daf9":{
      "scriptId":"u34"},
    "feaaf7f0f3144694991d13a6ea4b7992":{
      "scriptId":"u35"},
    "4eab7b5cff694bbc8a3d0d7a3052b779":{
      "scriptId":"u36"},
    "d8017ffdd95d4f37ae47e61402e32e86":{
      "scriptId":"u37"},
    "e9298e561486407ab8575f9d59e0a4e0":{
      "scriptId":"u38"},
    "d961e062dfa44848a0c765b56c540267":{
      "scriptId":"u39"},
    "7c55285a1d414c3e83fb98d46acd8872":{
      "scriptId":"u40"},
    "34e2fb9a906242638a92359ffc4289db":{
      "scriptId":"u41"},
    "db20f2992b474638aa2fb3560e94a7bd":{
      "scriptId":"u42"},
    "b132d95312d042958853b3e22ea7369f":{
      "scriptId":"u43"},
    "d8492a485c7d4bdb9700ee741486f026":{
      "scriptId":"u44"},
    "05129d74230e482192a3f963b425c201":{
      "scriptId":"u45"},
    "e3ae4ad5a9454784ae4c2bfb180cf10a":{
      "scriptId":"u46"},
    "6a8f63a9e4b6408ab2b49228233d2593":{
      "scriptId":"u47"},
    "7163ce3b30bc42d7862941bb2210e541":{
      "scriptId":"u48"},
    "a0d6f8a67d5b49edbe1ed581eb879e56":{
      "scriptId":"u49"},
    "c983b22eb4ec4c5293fe44cb3d0a3437":{
      "scriptId":"u50"},
    "2340ffd188c0437cbeb205ca8bb2455d":{
      "scriptId":"u51"},
    "13ea805b8182448f8cbdbcabac47636a":{
      "scriptId":"u52"},
    "a6af3e97fe1b484cb52a36a331614e63":{
      "scriptId":"u53"},
    "da0631efd3ed48bea8c38b7afd5cd11e":{
      "scriptId":"u54"},
    "608fdac36e474754bc51c1ae16aeb543":{
      "scriptId":"u55"},
    "68e7cf5b554d4be8aafaefd8de267523":{
      "scriptId":"u56"},
    "dde9d631ba0f4ed693fbf834975fd5bd":{
      "scriptId":"u57"},
    "29afe85282354e839b58125113021678":{
      "scriptId":"u58"},
    "4c183c2ab7e042fea9bc7785a752e661":{
      "scriptId":"u59"},
    "db43672d13764b97b458eec552b4cd8f":{
      "scriptId":"u60"},
    "ce41786514c64a7fbf9c16cb0f94ddb0":{
      "scriptId":"u61"},
    "64fbb3aca4cd4c348f16e34689976b8f":{
      "scriptId":"u62"},
    "b82358449d7945839b6c4c0a35d2aab4":{
      "scriptId":"u63"},
    "33cf9c2bf87044b8bbe7787d7410d30e":{
      "scriptId":"u64"},
    "20fa6bdade9242268e970c75f45cae29":{
      "scriptId":"u65"},
    "a58ed3cc090b41fd9e50cb2a720f01c8":{
      "scriptId":"u66"},
    "849b80bf03814f6c8a11338cd1b1688c":{
      "scriptId":"u67"},
    "fd0f7d51ec534e92a97ea23023aed7b2":{
      "scriptId":"u68"},
    "0122edb93e6b44839d0eb7f89dd5e6da":{
      "scriptId":"u69"},
    "1a07017ecd1642c4898c94d278dc1270":{
      "scriptId":"u70"},
    "7a7e1e689f3d4bb681fdde730291fced":{
      "scriptId":"u71"},
    "57e1e4599719407c8834ed6e63b0d5b0":{
      "scriptId":"u72"},
    "53167daa210f49fe9aff671335697dee":{
      "scriptId":"u73"},
    "647d660929ae4015b44b774f28e0c2e5":{
      "scriptId":"u74"},
    "abbf151c2a0444abb02f3eb822386a91":{
      "scriptId":"u75"},
    "71f320194b8b4f8d9658dc62bc5357c5":{
      "scriptId":"u76"},
    "cb333b1d14944c3faceb36f58c5614a4":{
      "scriptId":"u77"},
    "4c3073991ee04cc5b4105fa06788709b":{
      "scriptId":"u78"},
    "3f1719c56d434324be2747172c582c19":{
      "scriptId":"u79"},
    "f0900ce7fb114f83ae76a884336eb739":{
      "scriptId":"u80"},
    "3cd191d039d74c2b95441f747f45191a":{
      "scriptId":"u81"},
    "96f7a07a8daf43d0a2e6f82e8f590a92":{
      "scriptId":"u82"},
    "d0d6a1e4e4594d8597ba55e03905beb5":{
      "scriptId":"u83"},
    "f3c1e663fdcc479b902224e3cf69e5dd":{
      "scriptId":"u84"},
    "21cb239b1895448e8986f7e56dd9b24a":{
      "scriptId":"u85"},
    "1225c0d5584146c19fbbb43d3f0a3bfa":{
      "scriptId":"u86"}}});