$axure.loadCurrentPage({
  "url":"商品详情.html",
  "generationDate":new Date(1469080151235.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d3ee1e9899944189a9e3b253b0c752c0",
    "type":"Axure:Page",
    "name":"商品详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"baae60764194465b9b7977fa08cae563",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":20},
            "size":{
              "width":250,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16866069931e4ebeb7a4ba50512a05ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":20},
                "size":{
                  "width":250,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u0.png"}},
{
          "id":"4c9206502a294c338cfae480efd1d514",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":280},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1d7f5d0bec84477b801fc599c5bc595",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":280},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u2.png"}},
{
          "id":"140ca6d8a71e4ad7a2949b48b82506f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":280},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5334c2d1b8234b989124537f4d22a8c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":280},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u2.png"}},
{
          "id":"f261c366b59e47128a06c50300c0abe9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":280},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd1aa0d2da4243dab31bf9322103b1d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":280},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u2.png"}},
{
          "id":"249af8fd599d4ba5ac1e671f5b44af67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":280},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dab51cb3b67b486db7cc2a52c2b6efac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":280},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u2.png"}},
{
          "id":"518b334355cb4d908fdf1965823ecca1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":280},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3941c625fdda41e79129cf91861df9a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":280},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u2.png"}},
{
          "id":"7241743dead54d4ca6d075ac29c5de5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":20},
            "size":{
              "width":232,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b18b5feaad80474781b059127b6cc6c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":20},
                "size":{
                  "width":232,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"232ce2d799384011bfbb9e893bcf73b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":346,
              "y":58},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23b480f83061403caa52d3d4261fbcb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":346,
                  "y":58},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"053ca2d869c346149a88b7dc6bd9f22f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":346,
              "y":84},
            "size":{
              "width":148,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52e1935877414fe8bf8a7457a7360b30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":346,
                  "y":84},
                "size":{
                  "width":148,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9e3b02ba10d44f390549c1d399a02ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":346,
              "y":121},
            "size":{
              "width":146,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14586d47c2d245a39f955ae6e3e44f57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":346,
                  "y":121},
                "size":{
                  "width":146,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5b7b9470ddc45fcb3621b915bd6f405",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":346,
              "y":150},
            "size":{
              "width":148,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23caa466eb7349a583c49b50eaa5b4a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":346,
                  "y":150},
                "size":{
                  "width":148,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"362ef4524a5e4a4cb3370912a6237510",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":179},
            "size":{
              "width":340,
              "height":161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a8b3b04df34465cab0fc4c149244ae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":343,
                  "y":179},
                "size":{
                  "width":340,
                  "height":161}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商品详情/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "baae60764194465b9b7977fa08cae563":{
      "scriptId":"u0"},
    "16866069931e4ebeb7a4ba50512a05ae":{
      "scriptId":"u1"},
    "4c9206502a294c338cfae480efd1d514":{
      "scriptId":"u2"},
    "c1d7f5d0bec84477b801fc599c5bc595":{
      "scriptId":"u3"},
    "140ca6d8a71e4ad7a2949b48b82506f0":{
      "scriptId":"u4"},
    "5334c2d1b8234b989124537f4d22a8c0":{
      "scriptId":"u5"},
    "f261c366b59e47128a06c50300c0abe9":{
      "scriptId":"u6"},
    "dd1aa0d2da4243dab31bf9322103b1d5":{
      "scriptId":"u7"},
    "249af8fd599d4ba5ac1e671f5b44af67":{
      "scriptId":"u8"},
    "dab51cb3b67b486db7cc2a52c2b6efac":{
      "scriptId":"u9"},
    "518b334355cb4d908fdf1965823ecca1":{
      "scriptId":"u10"},
    "3941c625fdda41e79129cf91861df9a5":{
      "scriptId":"u11"},
    "7241743dead54d4ca6d075ac29c5de5c":{
      "scriptId":"u12"},
    "b18b5feaad80474781b059127b6cc6c6":{
      "scriptId":"u13"},
    "232ce2d799384011bfbb9e893bcf73b7":{
      "scriptId":"u14"},
    "23b480f83061403caa52d3d4261fbcb4":{
      "scriptId":"u15"},
    "053ca2d869c346149a88b7dc6bd9f22f":{
      "scriptId":"u16"},
    "52e1935877414fe8bf8a7457a7360b30":{
      "scriptId":"u17"},
    "c9e3b02ba10d44f390549c1d399a02ea":{
      "scriptId":"u18"},
    "14586d47c2d245a39f955ae6e3e44f57":{
      "scriptId":"u19"},
    "b5b7b9470ddc45fcb3621b915bd6f405":{
      "scriptId":"u20"},
    "23caa466eb7349a583c49b50eaa5b4a0":{
      "scriptId":"u21"},
    "362ef4524a5e4a4cb3370912a6237510":{
      "scriptId":"u22"},
    "3a8b3b04df34465cab0fc4c149244ae1":{
      "scriptId":"u23"}}});