$axure.loadCurrentPage({
  "url":"1第一次进入.html",
  "generationDate":new Date(1444989698981.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9ee9be7ebc284d7a95d45d5114d83247",
    "type":"Axure:Page",
    "name":"1第一次进入",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"55acc32a1a1e46dc9e4360f99f322b21",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "masterId":"7ddeb125ab1346d78fab0f7c44d11c2d"},
{
          "id":"4ed33bfd472c4cec9038f005b833a6b8",
          "label":"拖动广告",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 拖动广告 x 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["099e4677c2524bdaa09bafb9a726069e"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onDragDrop":{
              "description":"OnDragDrop",
              "cases":[{
                  "description":"用例 1<br> (If &quot;[[LVAR1.x&gt;0]]&quot;等于: &quot;true&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[LVAR1.x>0]]",
                      "localVariables":{
                        "lvar1":{
                          "exprType":"fcall",
                          "functionName":"GetWidget",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["099e4677c2524bdaa09bafb9a726069e"]}]}},
                      "stos":[{
                          "computedType":"boolean",
                          "sto":"binOp",
                          "op":">",
                          "leftSTO":{
                            "computedType":"int",
                            "sto":"propCall",
                            "thisSTO":{
                              "sto":"var",
                              "name":"lvar1"},
                            "prop":"x"},
                          "rightSTO":{
                            "computedType":"int",
                            "sto":"literal",
                            "value":0}}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"true",
                      "stos":[]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 拖动广告 到 (0,0) 摆动 500ms",
                      "objectsToMoves":[{
                          "objectPath":["099e4677c2524bdaa09bafb9a726069e"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"swing",
                              "duration":500}}}]}]},
{
                  "description":"用例 2<br> (Else If &quot;[[LVAR1.x&lt;-640]]&quot;等于: &quot;true&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[LVAR1.x<-640]]",
                      "localVariables":{
                        "lvar1":{
                          "exprType":"fcall",
                          "functionName":"GetWidget",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":false,
                              "isFocused":false,
                              "isTarget":false,
                              "value":["099e4677c2524bdaa09bafb9a726069e"]}]}},
                      "stos":[{
                          "computedType":"boolean",
                          "sto":"binOp",
                          "op":"<",
                          "leftSTO":{
                            "computedType":"int",
                            "sto":"propCall",
                            "thisSTO":{
                              "sto":"var",
                              "name":"lvar1"},
                            "prop":"x"},
                          "rightSTO":{
                            "computedType":"int",
                            "sto":"unOp",
                            "op":"-",
                            "inputSTO":{
                              "computedType":"int",
                              "sto":"literal",
                              "value":640}}}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"true",
                      "stos":[]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 拖动广告 到 (-640,0) 摆动 500ms",
                      "objectsToMoves":[{
                          "objectPath":["099e4677c2524bdaa09bafb9a726069e"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"-640",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"swing",
                              "duration":500}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"5bfccd688d3344b4945f53f71af7e0e4",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"099e4677c2524bdaa09bafb9a726069e",
                  "label":"拖动广告",
                  "parentDynamicPanel":"4ed33bfd472c4cec9038f005b833a6b8",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"a23d02dec96343ce8d6d900229087207",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"d068bd8693b640fba33b4ec37d50a036",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'华文细黑 Regular', '华文细黑'",
                            "fontSize":"12px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF999999},
                            "location":{
                              "x":0,
                              "y":18},
                            "size":{
                              "width":320,
                              "height":462},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"3bd2c49876124d07b697af3894d34665",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'华文细黑 Regular', '华文细黑'",
                                "fontSize":"12px",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF999999},
                                "location":{
                                  "x":0,
                                  "y":18},
                                "size":{
                                  "width":320,
                                  "height":462},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u7.png"}},
{
                          "id":"29e7286ec5b945768382371a27473c68",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"h1",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "fontSize":"48px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "location":{
                              "x":48,
                              "y":148},
                            "size":{
                              "width":223,
                              "height":62}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9dea97d8c69d4bc28414ab442d5e9a36",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "fontSize":"48px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "location":{
                                  "x":48,
                                  "y":148},
                                "size":{
                                  "width":223,
                                  "height":62}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"ff3f4fedc39a4dafb96efeee6dddbe16",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFC9C9C9},
                            "location":{
                              "x":141,
                              "y":410},
                            "size":{
                              "width":10,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"79c7c55351b148c5af9eebdb2b2b0b0b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFC9C9C9},
                                "location":{
                                  "x":141,
                                  "y":410},
                                "size":{
                                  "width":10,
                                  "height":10}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u11.png"}},
{
                          "id":"8d4c8ff5b69c4e29bce85f56a8fffdef",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":155,
                              "y":410},
                            "size":{
                              "width":10,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"932825e9cb004212a42d8ad1ef8f5b94",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":155,
                                  "y":410},
                                "size":{
                                  "width":10,
                                  "height":10}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u13.png"}},
{
                          "id":"14388e60c0704db9aae5933115796965",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":169,
                              "y":410},
                            "size":{
                              "width":10,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a20eac0f03b244d890fadeee6b802cf1",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":169,
                                  "y":410},
                                "size":{
                                  "width":10,
                                  "height":10}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u13.png"}},
{
                          "id":"f33146729e454a7691e94ba9d840d47a",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'华文细黑 Regular', '华文细黑'",
                            "fontSize":"12px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF999999},
                            "location":{
                              "x":320,
                              "y":18},
                            "size":{
                              "width":320,
                              "height":462},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9f516269fc264920989a03c5559f3bfc",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'华文细黑 Regular', '华文细黑'",
                                "fontSize":"12px",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF999999},
                                "location":{
                                  "x":320,
                                  "y":18},
                                "size":{
                                  "width":320,
                                  "height":462},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u7.png"}},
{
                          "id":"61142d2fa19c47e9a792b93ab16cd9ec",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"h1",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "fontSize":"48px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "location":{
                              "x":368,
                              "y":148},
                            "size":{
                              "width":223,
                              "height":62}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d8cf6f78d3f94d9186025c7fd6050477",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "fontSize":"48px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "location":{
                                  "x":368,
                                  "y":148},
                                "size":{
                                  "width":223,
                                  "height":62}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"128287694923465f8883497289689998",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFC9C9C9},
                            "location":{
                              "x":461,
                              "y":410},
                            "size":{
                              "width":10,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"139cb57580c34eedb9926f5fce9441b2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFC9C9C9},
                                "location":{
                                  "x":461,
                                  "y":410},
                                "size":{
                                  "width":10,
                                  "height":10}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u11.png"}},
{
                          "id":"053750bf0cfa4acb8d7eaca24ee44962",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":475,
                              "y":410},
                            "size":{
                              "width":10,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"591a8a1292f841949cf5ab3e8c497e60",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":475,
                                  "y":410},
                                "size":{
                                  "width":10,
                                  "height":10}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u13.png"}},
{
                          "id":"e37d5fc244a64954af698ff1117180c7",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":489,
                              "y":410},
                            "size":{
                              "width":10,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ca28ee6b85a740fcbba00daf80a27a1f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":489,
                                  "y":410},
                                "size":{
                                  "width":10,
                                  "height":10}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u13.png"}},
{
                          "id":"e43dfb5272824e36bd305d40efbd54ee",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'华文细黑 Regular', '华文细黑'",
                            "fontSize":"12px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF999999},
                            "location":{
                              "x":640,
                              "y":18},
                            "size":{
                              "width":320,
                              "height":462},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"808f7958f6ff4499bf0a7737e2cdc452",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'华文细黑 Regular', '华文细黑'",
                                "fontSize":"12px",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF999999},
                                "location":{
                                  "x":640,
                                  "y":18},
                                "size":{
                                  "width":320,
                                  "height":462},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u7.png"}},
{
                          "id":"fc4a3dae82d04476bcf0c39278d5ae5f",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"h1",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Regular', '微软雅黑'",
                            "fontSize":"48px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "location":{
                              "x":688,
                              "y":148},
                            "size":{
                              "width":223,
                              "height":62}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b1f217c4b1224859a5c751407954ff9b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                                "fontSize":"48px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "location":{
                                  "x":688,
                                  "y":148},
                                "size":{
                                  "width":223,
                                  "height":62}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"bf3b092dd8b04bdeba7b49d3f629e69e",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFC9C9C9},
                            "location":{
                              "x":781,
                              "y":410},
                            "size":{
                              "width":10,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"82ae9deba2ff4b51b8663d0d37331e55",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFC9C9C9},
                                "location":{
                                  "x":781,
                                  "y":410},
                                "size":{
                                  "width":10,
                                  "height":10}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u11.png"}},
{
                          "id":"7cdcc009ba02475286d0aed60667d18b",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":795,
                              "y":410},
                            "size":{
                              "width":10,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"6f7afb82ac964755974b629510ec7c39",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":795,
                                  "y":410},
                                "size":{
                                  "width":10,
                                  "height":10}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u13.png"}},
{
                          "id":"f10aa0d5e016495a96872af5c8b0a3d6",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":809,
                              "y":410},
                            "size":{
                              "width":10,
                              "height":10}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"8cd95168991a485bbdcbe686580d106f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":809,
                                  "y":410},
                                "size":{
                                  "width":10,
                                  "height":10}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/1第一次进入/u13.png"}},
{
                          "id":"2d563111a793463a837e2327962522f1",
                          "label":"",
                          "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":735,
                              "y":340},
                            "size":{
                              "width":130,
                              "height":30},
                            "borderWidth":"-1",
                            "cornerRadiusTopLeft":"2"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b5130ba4b8cc46268b38833b59e90727",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"099e4677c2524bdaa09bafb9a726069e",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":735,
                                  "y":340},
                                "size":{
                                  "width":130,
                                  "height":30},
                                "borderWidth":"-1",
                                "cornerRadiusTopLeft":"2"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 1首页",
                                      "target":{
                                        "targetType":"page",
                                        "url":"1首页.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/1第一次进入/u37.png"}}]}]}]}]},
{
          "id":"8bd1766ad8a647349593ba4354ee2d74",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":601}},
          "adaptiveStyles":{
},
          "masterId":"7ddeb125ab1346d78fab0f7c44d11c2d"},
{
          "id":"b26d084e6c204bb4813b01ba613e8e40",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":324,
              "y":601}},
          "adaptiveStyles":{
},
          "masterId":"7ddeb125ab1346d78fab0f7c44d11c2d"},
{
          "id":"b76f7f47a38645aab6dc1b66dc7ebf40",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":648,
              "y":601}},
          "adaptiveStyles":{
},
          "masterId":"7ddeb125ab1346d78fab0f7c44d11c2d"},
{
          "id":"8bc10bfca133476d9d1ecc019c44fc42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":619},
            "size":{
              "width":320,
              "height":462},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f1936581fb241c9b70d7c665df00544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":619},
                "size":{
                  "width":320,
                  "height":462},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u7.png"}},
{
          "id":"d025376e25cc41dba474701b06cd71ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":48,
              "y":747},
            "size":{
              "width":223,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c422138b7d3b4f8dad721db5946045de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":48,
                  "y":747},
                "size":{
                  "width":223,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6d3661193e5400ea3ec9d8d1bb51f91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":141,
              "y":1009},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"697340a95fa14c69adb22139fae18ccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":141,
                  "y":1009},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u11.png"}},
{
          "id":"b6e618ef010a41c8b2a849501d092d79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":1009},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f7f95ba79ca40e7b6f0d94a92828197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":1009},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u13.png"}},
{
          "id":"f27e9fa8928f4f5385b2e847729d2f18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":1009},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"247268b5af754184a9fec0789a215c22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":1009},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u13.png"}},
{
          "id":"f9ae75571deb444d8dfb5e8348044333",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":324,
              "y":619},
            "size":{
              "width":320,
              "height":462},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"430c7ff9851a4871b20f8c0ba026aaa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":324,
                  "y":619},
                "size":{
                  "width":320,
                  "height":462},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u7.png"}},
{
          "id":"d594381b0fcc45a4987982aa4f798235",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":372,
              "y":747},
            "size":{
              "width":223,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d69280bf01a4b6297c5dcbb0eb7aba9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":372,
                  "y":747},
                "size":{
                  "width":223,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b121d027d6e345f392c1fa63fb5cd179",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":465,
              "y":1009},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20601bc49d7b4df1ab960a44fbe7345a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":465,
                  "y":1009},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u11.png"}},
{
          "id":"927f9216f1aa451ab52f943760ccf60c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":479,
              "y":1009},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc8fecb3968048c29dcadaa1bb09d8c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":479,
                  "y":1009},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u13.png"}},
{
          "id":"f6d70d01a10747cfb58c72fa2754f1bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":493,
              "y":1009},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f45387cf08448efb4f2ee8d44991c2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":493,
                  "y":1009},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u13.png"}},
{
          "id":"e5d954bd3956428399106954a77b5723",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":648,
              "y":619},
            "size":{
              "width":320,
              "height":462},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f62d140a0aa1454f9b12b3b661a3e954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":648,
                  "y":619},
                "size":{
                  "width":320,
                  "height":462},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u7.png"}},
{
          "id":"80e4835df2b94ef5b7c8ab1e17416545",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":696,
              "y":747},
            "size":{
              "width":223,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"068d046c2745468ea686d39df250c465",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":696,
                  "y":747},
                "size":{
                  "width":223,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d12ef04941b7481fbc7f76815fa401a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":789,
              "y":1009},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"186ed7cffda64ee98df8c29e65e3c75c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":789,
                  "y":1009},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u11.png"}},
{
          "id":"c3bd081edfef497197e4d8d8b15d568c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":803,
              "y":1009},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d2ff84b07a44a1785ad0456b0e6eff3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":803,
                  "y":1009},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u13.png"}},
{
          "id":"9108960f4ce74f95ac4c6bbcf21642db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":817,
              "y":1009},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2890fd5cbfb4404cab38a7a8969acd8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":817,
                  "y":1009},
                "size":{
                  "width":10,
                  "height":10}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u13.png"}},
{
          "id":"d75bc0bb64c64d17b92b7d1653d712ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":743,
              "y":939},
            "size":{
              "width":130,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f73b311ad5f14442bab0404f7fd5f4d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":743,
                  "y":939},
                "size":{
                  "width":130,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 1首页",
                      "target":{
                        "targetType":"page",
                        "url":"1首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/1第一次进入/u37.png"}},
{
          "id":"706f1c78356b446f9ca848b94e72e344",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":0,
              "y":543},
            "borderWidth":"2",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"550692ed22dc43b69c6eb2f3bd68f4ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":0,
                  "y":543},
                "borderWidth":"2",
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}]},
{
          "id":"488800ad11bc4a6ab1dbce240d0e73b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":10,
              "y":563},
            "size":{
              "width":320,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5b0c3cfb6b446bfb2854edc6cc9f5cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":10,
                  "y":563},
                "size":{
                  "width":320,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1第一次进入/u88.png"}}]}},
  "masters":{
    "7ddeb125ab1346d78fab0f7c44d11c2d":{
      "packageId":"7ddeb125ab1346d78fab0f7c44d11c2d",
      "type":"Axure:Master",
      "name":"底板全局",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8a3aa33e825441e69d45f7a647bad681",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "location":{
                "x":0,
                "y":18},
              "size":{
                "width":320,
                "height":462},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c6a74bf75a24bdca4179771b933a601",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":0,
                    "y":18},
                  "size":{
                    "width":320,
                    "height":462},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u17.png",
              "normal~":"images/全局说明/u17.png",
              "normal~":"images/全局说明/u17.png",
              "normal~":"images/全局说明/u17.png"}},
{
            "id":"4828941e46b34c7c95a3b5ac3d332e1b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":18},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd395427e46e4ef694ef269fa45dbf1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":18},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u19.png",
              "normal~":"images/全局说明/u19.png",
              "normal~":"images/全局说明/u19.png",
              "normal~":"images/全局说明/u19.png"}}]}}},
  "objectPaths":{
    "55acc32a1a1e46dc9e4360f99f322b21":{
      "scriptId":"u0",
      "8a3aa33e825441e69d45f7a647bad681":{
        "scriptId":"u1"},
      "1c6a74bf75a24bdca4179771b933a601":{
        "scriptId":"u2"},
      "4828941e46b34c7c95a3b5ac3d332e1b":{
        "scriptId":"u3"},
      "cd395427e46e4ef694ef269fa45dbf1a":{
        "scriptId":"u4"}},
    "4ed33bfd472c4cec9038f005b833a6b8":{
      "scriptId":"u5"},
    "099e4677c2524bdaa09bafb9a726069e":{
      "scriptId":"u6"},
    "d068bd8693b640fba33b4ec37d50a036":{
      "scriptId":"u7"},
    "3bd2c49876124d07b697af3894d34665":{
      "scriptId":"u8"},
    "29e7286ec5b945768382371a27473c68":{
      "scriptId":"u9"},
    "9dea97d8c69d4bc28414ab442d5e9a36":{
      "scriptId":"u10"},
    "ff3f4fedc39a4dafb96efeee6dddbe16":{
      "scriptId":"u11"},
    "79c7c55351b148c5af9eebdb2b2b0b0b":{
      "scriptId":"u12"},
    "8d4c8ff5b69c4e29bce85f56a8fffdef":{
      "scriptId":"u13"},
    "932825e9cb004212a42d8ad1ef8f5b94":{
      "scriptId":"u14"},
    "14388e60c0704db9aae5933115796965":{
      "scriptId":"u15"},
    "a20eac0f03b244d890fadeee6b802cf1":{
      "scriptId":"u16"},
    "f33146729e454a7691e94ba9d840d47a":{
      "scriptId":"u17"},
    "9f516269fc264920989a03c5559f3bfc":{
      "scriptId":"u18"},
    "61142d2fa19c47e9a792b93ab16cd9ec":{
      "scriptId":"u19"},
    "d8cf6f78d3f94d9186025c7fd6050477":{
      "scriptId":"u20"},
    "128287694923465f8883497289689998":{
      "scriptId":"u21"},
    "139cb57580c34eedb9926f5fce9441b2":{
      "scriptId":"u22"},
    "053750bf0cfa4acb8d7eaca24ee44962":{
      "scriptId":"u23"},
    "591a8a1292f841949cf5ab3e8c497e60":{
      "scriptId":"u24"},
    "e37d5fc244a64954af698ff1117180c7":{
      "scriptId":"u25"},
    "ca28ee6b85a740fcbba00daf80a27a1f":{
      "scriptId":"u26"},
    "e43dfb5272824e36bd305d40efbd54ee":{
      "scriptId":"u27"},
    "808f7958f6ff4499bf0a7737e2cdc452":{
      "scriptId":"u28"},
    "fc4a3dae82d04476bcf0c39278d5ae5f":{
      "scriptId":"u29"},
    "b1f217c4b1224859a5c751407954ff9b":{
      "scriptId":"u30"},
    "bf3b092dd8b04bdeba7b49d3f629e69e":{
      "scriptId":"u31"},
    "82ae9deba2ff4b51b8663d0d37331e55":{
      "scriptId":"u32"},
    "7cdcc009ba02475286d0aed60667d18b":{
      "scriptId":"u33"},
    "6f7afb82ac964755974b629510ec7c39":{
      "scriptId":"u34"},
    "f10aa0d5e016495a96872af5c8b0a3d6":{
      "scriptId":"u35"},
    "8cd95168991a485bbdcbe686580d106f":{
      "scriptId":"u36"},
    "2d563111a793463a837e2327962522f1":{
      "scriptId":"u37"},
    "b5130ba4b8cc46268b38833b59e90727":{
      "scriptId":"u38"},
    "8bd1766ad8a647349593ba4354ee2d74":{
      "scriptId":"u39",
      "8a3aa33e825441e69d45f7a647bad681":{
        "scriptId":"u40"},
      "1c6a74bf75a24bdca4179771b933a601":{
        "scriptId":"u41"},
      "4828941e46b34c7c95a3b5ac3d332e1b":{
        "scriptId":"u42"},
      "cd395427e46e4ef694ef269fa45dbf1a":{
        "scriptId":"u43"}},
    "b26d084e6c204bb4813b01ba613e8e40":{
      "scriptId":"u44",
      "8a3aa33e825441e69d45f7a647bad681":{
        "scriptId":"u45"},
      "1c6a74bf75a24bdca4179771b933a601":{
        "scriptId":"u46"},
      "4828941e46b34c7c95a3b5ac3d332e1b":{
        "scriptId":"u47"},
      "cd395427e46e4ef694ef269fa45dbf1a":{
        "scriptId":"u48"}},
    "b76f7f47a38645aab6dc1b66dc7ebf40":{
      "scriptId":"u49",
      "8a3aa33e825441e69d45f7a647bad681":{
        "scriptId":"u50"},
      "1c6a74bf75a24bdca4179771b933a601":{
        "scriptId":"u51"},
      "4828941e46b34c7c95a3b5ac3d332e1b":{
        "scriptId":"u52"},
      "cd395427e46e4ef694ef269fa45dbf1a":{
        "scriptId":"u53"}},
    "8bc10bfca133476d9d1ecc019c44fc42":{
      "scriptId":"u54"},
    "4f1936581fb241c9b70d7c665df00544":{
      "scriptId":"u55"},
    "d025376e25cc41dba474701b06cd71ca":{
      "scriptId":"u56"},
    "c422138b7d3b4f8dad721db5946045de":{
      "scriptId":"u57"},
    "a6d3661193e5400ea3ec9d8d1bb51f91":{
      "scriptId":"u58"},
    "697340a95fa14c69adb22139fae18ccc":{
      "scriptId":"u59"},
    "b6e618ef010a41c8b2a849501d092d79":{
      "scriptId":"u60"},
    "1f7f95ba79ca40e7b6f0d94a92828197":{
      "scriptId":"u61"},
    "f27e9fa8928f4f5385b2e847729d2f18":{
      "scriptId":"u62"},
    "247268b5af754184a9fec0789a215c22":{
      "scriptId":"u63"},
    "f9ae75571deb444d8dfb5e8348044333":{
      "scriptId":"u64"},
    "430c7ff9851a4871b20f8c0ba026aaa1":{
      "scriptId":"u65"},
    "d594381b0fcc45a4987982aa4f798235":{
      "scriptId":"u66"},
    "8d69280bf01a4b6297c5dcbb0eb7aba9":{
      "scriptId":"u67"},
    "b121d027d6e345f392c1fa63fb5cd179":{
      "scriptId":"u68"},
    "20601bc49d7b4df1ab960a44fbe7345a":{
      "scriptId":"u69"},
    "927f9216f1aa451ab52f943760ccf60c":{
      "scriptId":"u70"},
    "dc8fecb3968048c29dcadaa1bb09d8c4":{
      "scriptId":"u71"},
    "f6d70d01a10747cfb58c72fa2754f1bf":{
      "scriptId":"u72"},
    "2f45387cf08448efb4f2ee8d44991c2c":{
      "scriptId":"u73"},
    "e5d954bd3956428399106954a77b5723":{
      "scriptId":"u74"},
    "f62d140a0aa1454f9b12b3b661a3e954":{
      "scriptId":"u75"},
    "80e4835df2b94ef5b7c8ab1e17416545":{
      "scriptId":"u76"},
    "068d046c2745468ea686d39df250c465":{
      "scriptId":"u77"},
    "d12ef04941b7481fbc7f76815fa401a9":{
      "scriptId":"u78"},
    "186ed7cffda64ee98df8c29e65e3c75c":{
      "scriptId":"u79"},
    "c3bd081edfef497197e4d8d8b15d568c":{
      "scriptId":"u80"},
    "9d2ff84b07a44a1785ad0456b0e6eff3":{
      "scriptId":"u81"},
    "9108960f4ce74f95ac4c6bbcf21642db":{
      "scriptId":"u82"},
    "2890fd5cbfb4404cab38a7a8969acd8c":{
      "scriptId":"u83"},
    "d75bc0bb64c64d17b92b7d1653d712ef":{
      "scriptId":"u84"},
    "f73b311ad5f14442bab0404f7fd5f4d7":{
      "scriptId":"u85"},
    "706f1c78356b446f9ca848b94e72e344":{
      "scriptId":"u86"},
    "550692ed22dc43b69c6eb2f3bd68f4ff":{
      "scriptId":"u87"},
    "488800ad11bc4a6ab1dbce240d0e73b9":{
      "scriptId":"u88"},
    "a5b0c3cfb6b446bfb2854edc6cc9f5cf":{
      "scriptId":"u89"}}});