$axure.loadCurrentPage({
  "url":"全部晒单.html",
  "generationDate":new Date(1449815595955.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5ad517c0eaf0462e9f53b6a4faed25c8",
    "type":"Axure:Page",
    "name":"全部晒单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"55052c686ec344cbb1ea17164ab04ec7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e6c2a16efe643408524769892007d5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u0.png"}},
{
          "id":"795a60294da447d899af172f323d4812",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":37},
            "size":{
              "width":235,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f965395f07574d929f52cd3dcd18a2b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":37},
                "size":{
                  "width":235,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 押宝首页",
                      "target":{
                        "targetType":"page",
                        "url":"押宝首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u2.png"}},
{
          "id":"9586244abb394c7c82a6deeb22f170d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":380,
              "y":49.5},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dca1c48281f946269e0f418c79707cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":380,
                  "y":49.5},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"685b50a6d20949f792f47cbd49262ad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":477,
              "y":50},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d952475a86b44a0dbc57257b6f9bc24f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":477,
                  "y":50},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bca4ce7706e44808868133f9dcb15902",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":599,
              "y":50},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4cddc6e8c8b4643badcaed7d5f9e0a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":599,
                  "y":50},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c4ce2bdf50b4866aa326eb1aa14c9dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":42.5},
            "size":{
              "width":127,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bf2a13721364fabb0072cf557259906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":42.5},
                "size":{
                  "width":127,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全部晒单",
                      "target":{
                        "targetType":"page",
                        "url":"全部晒单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u10.png"}},
{
          "id":"3c3f55d42fa743f9a955a881dd0e5b71",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":84},
            "size":{
              "width":1200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/押宝列表页/u12_line.png"}},
{
          "id":"ee9c5f3518e341249ee2cee7c625f6a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":104},
            "size":{
              "width":1000,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01d0a265df4143978bb662d5274e7370",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":104},
                "size":{
                  "width":1000,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部晒单/u13.png"}},
{
          "id":"26bc0a3e6f074158a32980fb57fefcf0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":440},
            "size":{
              "width":1000,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b7cd07eeab4680ae4ae8f375b8f102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":440},
                "size":{
                  "width":1000,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部晒单/u13.png"}},
{
          "id":"16354597bb974e3496816171f98e65dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":737,
              "y":802},
            "size":{
              "width":360,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ed9a97256f44b85a47ca4dcaffe4381",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":737,
                  "y":802},
                "size":{
                  "width":360,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部晒单/u17.png"}},
{
          "id":"0e6569237c214fb0894c583b45f58ee1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":856},
            "size":{
              "width":1200,
              "height":405}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"984b0511032b49f29cf1aa81b259c0a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":856},
                "size":{
                  "width":1200,
                  "height":405}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u82.png"}},
{
          "id":"fb9c49ffc5904060bbf55b8e3d4462ee",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":260},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户信息",
                      "target":{
                        "targetType":"page",
                        "url":"用户信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a63ab71d22c94f3a97b953cc75fef7b3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":120},
            "size":{
              "width":140,
              "height":146}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 往期押宝详情",
                      "target":{
                        "targetType":"page",
                        "url":"往期押宝详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"634583d8f95c494daeda8b7d7a5536a0",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":136},
            "size":{
              "width":270,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 往期押宝详情",
                      "target":{
                        "targetType":"page",
                        "url":"往期押宝详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"efa2d931a9024896b464649a0f14de88",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":270},
            "size":{
              "width":70,
              "height":15}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户信息",
                      "target":{
                        "targetType":"page",
                        "url":"用户信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "55052c686ec344cbb1ea17164ab04ec7":{
      "scriptId":"u0"},
    "9e6c2a16efe643408524769892007d5e":{
      "scriptId":"u1"},
    "795a60294da447d899af172f323d4812":{
      "scriptId":"u2"},
    "f965395f07574d929f52cd3dcd18a2b6":{
      "scriptId":"u3"},
    "9586244abb394c7c82a6deeb22f170d6":{
      "scriptId":"u4"},
    "dca1c48281f946269e0f418c79707cf8":{
      "scriptId":"u5"},
    "685b50a6d20949f792f47cbd49262ad1":{
      "scriptId":"u6"},
    "d952475a86b44a0dbc57257b6f9bc24f":{
      "scriptId":"u7"},
    "bca4ce7706e44808868133f9dcb15902":{
      "scriptId":"u8"},
    "a4cddc6e8c8b4643badcaed7d5f9e0a5":{
      "scriptId":"u9"},
    "3c4ce2bdf50b4866aa326eb1aa14c9dd":{
      "scriptId":"u10"},
    "1bf2a13721364fabb0072cf557259906":{
      "scriptId":"u11"},
    "3c3f55d42fa743f9a955a881dd0e5b71":{
      "scriptId":"u12"},
    "ee9c5f3518e341249ee2cee7c625f6a3":{
      "scriptId":"u13"},
    "01d0a265df4143978bb662d5274e7370":{
      "scriptId":"u14"},
    "26bc0a3e6f074158a32980fb57fefcf0":{
      "scriptId":"u15"},
    "29b7cd07eeab4680ae4ae8f375b8f102":{
      "scriptId":"u16"},
    "16354597bb974e3496816171f98e65dc":{
      "scriptId":"u17"},
    "6ed9a97256f44b85a47ca4dcaffe4381":{
      "scriptId":"u18"},
    "0e6569237c214fb0894c583b45f58ee1":{
      "scriptId":"u19"},
    "984b0511032b49f29cf1aa81b259c0a7":{
      "scriptId":"u20"},
    "fb9c49ffc5904060bbf55b8e3d4462ee":{
      "scriptId":"u21"},
    "a63ab71d22c94f3a97b953cc75fef7b3":{
      "scriptId":"u22"},
    "634583d8f95c494daeda8b7d7a5536a0":{
      "scriptId":"u23"},
    "efa2d931a9024896b464649a0f14de88":{
      "scriptId":"u24"}}});