$axure.loadCurrentPage({
  "url":"成交记录.html",
  "generationDate":new Date(1451352770064.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"92dacb3d9c7c4cea9d3300605c0435da",
    "type":"Axure:Page",
    "name":"成交记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d1a7351d23554724a5d0db7e90edcb08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58cf32e7f18b4ada83988896739851e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u0.png"}},
{
          "id":"8e374f2b0daf4107a31713baa0a09ffa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":36},
            "size":{
              "width":280,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cad1c40ef7eb4d83b2cedaaa88b32b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":280,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u2.png"}},
{
          "id":"22ecd95e4ea94b27a2bfc9cdc1bf487c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":55},
            "size":{
              "width":650,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ac3a8d564fa476cb0239cbce9ded1ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":55},
                "size":{
                  "width":650,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u4.png"}},
{
          "id":"e2d6767153a4450ca86d0ff62aed21ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF303849},
            "location":{
              "x":0,
              "y":102},
            "size":{
              "width":1200,
              "height":1028}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f587d613871465ab8126f1ac0eb7ad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF303849},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":1200,
                  "height":1028}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u6.png"}},
{
          "id":"77b496599a5c453e96dc200ed5abe343",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/成交记录/regen/u8_line.png"}},
{
          "id":"3e11967afa684b45972a5af11114a51b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":330,
              "y":135},
            "size":{
              "width":72,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84add432f4514e68a0d5e967ae5916b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":330,
                  "y":135},
                "size":{
                  "width":72,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e80b0752c088498cb4e0cae2f35e5e1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":412,
              "y":130},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37dbb9b362b14af0baf3d29c9b762108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":412,
                  "y":130},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"066dc408b8704b8981e0151d369692f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":412,
              "y":149},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8ff78086c84490793f515620f79bab0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":412,
                  "y":149},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3371378dca6e472c95179fed92f3fa99",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/成交记录/regen/u8_line.png"}},
{
          "id":"71123908ce264c5e9ffcf5e78f3ee0c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":490,
              "y":128},
            "size":{
              "width":610,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e95335a6e254450aa8f68a118652db7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":128},
                "size":{
                  "width":610,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c077905f847489da29906e473a0dfb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":490,
              "y":154},
            "size":{
              "width":610,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4027d0700e554befaabf9df1dca3d96d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":490,
                  "y":154},
                "size":{
                  "width":610,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49812fb0dc0e4178b083e36d1d1a212c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":1000,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04dedb7331f14e469b64c3e488e56a4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":1000,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u20.png"}},
{
          "id":"a825cecea3fb4c2287546ce9eb1a22e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5bbe680adfb49e68302b02c864f66ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u22.png"}},
{
          "id":"acc5e2411d914f768514c9f72ac3b9e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"790eeb049c524564bd42c8544d2e026f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 债权股交易中心",
                      "target":{
                        "targetType":"page",
                        "url":"债权股交易中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4fba80b160e433096fe38d6399b1f4c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":210},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"037e110dec024fc6b450d54e44b8158b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":210},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u26.png"}},
{
          "id":"2ed69fa4a04f4459b1a1b482b51542f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":250},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a384efd13a8423b8df6004afee1f373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":250},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46ff308c2b6a4d8dbc04c459cd0822c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF282828,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0287FE},
            "location":{
              "x":100,
              "y":270},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bd68dd9622a4d03a6bfc70144e6d841",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF282828,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0287FE},
                "location":{
                  "x":100,
                  "y":270},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u30.png"}},
{
          "id":"72574da95fa54681a73600d14be08805",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":278},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"961e01a660c24c85abf2a3fb07812a50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":278},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u32.png"}},
{
          "id":"f1500b29eb3347148ae3a8435dbefea9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":321},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e17ff3e548be41c79d1e14ee24c97bf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":321},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bda16dd4a78043928f4edb6c47c868c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":302},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4520ffa110544d3a6b4152b7e721af7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":302},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5efedadf77ac41a58027f89a2341ef7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":431,
              "y":302},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23f35b9db93d415c8c278005fa04113d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":302},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e21a371c2c03436ba9063bb4b30bba10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":302},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc57bcceab9a46158e6df7f26beaa95a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":302},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5aad6c92054b4059babfa3967a1c7b8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":302},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a681671603134c08b7414c129eb4e93b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":302},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97493de5b0b445e6a17b9b6ffaf32cc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":893,
              "y":302},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"631480a947f9418b8a49b26e8f433435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":893,
                  "y":302},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2c5b98732614107a0821af76e588dbf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":318},
            "size":{
              "width":842,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/成交记录/regen/u46_line.png"}},
{
          "id":"6337e243a0d04736901fdf8695945482",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":338},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d867a836842140c692b314162223fedc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":338},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"611cb92f17ce4d5295da0328159f3670",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF669900,
              "opacity":1},
            "location":{
              "x":431,
              "y":338},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6087a2286719423c965da376c3969747",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF669900,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":338},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c149427e283b4bdbb1109e0519dea6cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":338},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef22df7c18ee4233a9d8ae006b6320d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":575,
                  "y":338},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c12ebc990bb54c499a5746f105072d05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":338},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c2207449f084d8d88805243176c7a6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":338},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59131e5c85a049d99601291a1cac2b52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":886,
              "y":338},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99e5bf2b931d4c34a354065b98a6cf56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":886,
                  "y":338},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4412008ce46449be980fe4fced939071",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":210},
            "size":{
              "width":289,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9665989972d04a23b83046bb2b43a8a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":210},
                "size":{
                  "width":289,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u57.png"}},
{
          "id":"4df3d716e0c34ecda07d19ea7a0009e1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":215},
            "size":{
              "width":74,
              "height":26}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人中心我的挂单",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心我的挂单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e41d5e53ebad433f86502ed7e5537ea7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":124},
            "size":{
              "width":59,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e2f66fbf9849d99b505f7ff37e6ec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":124},
                "size":{
                  "width":59,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u60.png"}},
{
          "id":"c337a6e9ee144f9082f71de348028239",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":129},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"239db4b9f3334156b659b97c1307263c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":129},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdf0ecd467ad439c85336472f8413194",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":149},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddb2c2d6f200471cb5a62f11e9a54264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":149},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7231b95eef6c47e2bc95754dc20bcefe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":169},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"441b343890134890913065ae901f56fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":169},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28ccc27a9733459190416f5cd8e0d7f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":259.5},
            "size":{
              "width":64,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5c0aa10dfb941619a26787871284269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":259.5},
                "size":{
                  "width":64,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u68.png"}},
{
          "id":"a8f2235e3bc04208b9da39275bb43a1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":259.5},
            "size":{
              "width":64,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9b39142b5e24577b05bca34fb65ead6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":259.5},
                "size":{
                  "width":64,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/regen/u68.png"}},
{
          "id":"6e7969dfdcad4596ad12c0f2ab9c9b99",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":355,
              "y":264.5},
            "size":{
              "width":20,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/成交记录/regen/u72_line.png"}},
{
          "id":"396f7435617f466b934020165a6e9c81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":262},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b2f74ecc96d49edac19373b70790e33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":262},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d1a7351d23554724a5d0db7e90edcb08":{
      "scriptId":"u0"},
    "58cf32e7f18b4ada83988896739851e7":{
      "scriptId":"u1"},
    "8e374f2b0daf4107a31713baa0a09ffa":{
      "scriptId":"u2"},
    "cad1c40ef7eb4d83b2cedaaa88b32b27":{
      "scriptId":"u3"},
    "22ecd95e4ea94b27a2bfc9cdc1bf487c":{
      "scriptId":"u4"},
    "4ac3a8d564fa476cb0239cbce9ded1ac":{
      "scriptId":"u5"},
    "e2d6767153a4450ca86d0ff62aed21ff":{
      "scriptId":"u6"},
    "3f587d613871465ab8126f1ac0eb7ad1":{
      "scriptId":"u7"},
    "77b496599a5c453e96dc200ed5abe343":{
      "scriptId":"u8"},
    "3e11967afa684b45972a5af11114a51b":{
      "scriptId":"u9"},
    "84add432f4514e68a0d5e967ae5916b2":{
      "scriptId":"u10"},
    "e80b0752c088498cb4e0cae2f35e5e1f":{
      "scriptId":"u11"},
    "37dbb9b362b14af0baf3d29c9b762108":{
      "scriptId":"u12"},
    "066dc408b8704b8981e0151d369692f8":{
      "scriptId":"u13"},
    "d8ff78086c84490793f515620f79bab0":{
      "scriptId":"u14"},
    "3371378dca6e472c95179fed92f3fa99":{
      "scriptId":"u15"},
    "71123908ce264c5e9ffcf5e78f3ee0c0":{
      "scriptId":"u16"},
    "e95335a6e254450aa8f68a118652db7c":{
      "scriptId":"u17"},
    "7c077905f847489da29906e473a0dfb8":{
      "scriptId":"u18"},
    "4027d0700e554befaabf9df1dca3d96d":{
      "scriptId":"u19"},
    "49812fb0dc0e4178b083e36d1d1a212c":{
      "scriptId":"u20"},
    "04dedb7331f14e469b64c3e488e56a4a":{
      "scriptId":"u21"},
    "a825cecea3fb4c2287546ce9eb1a22e5":{
      "scriptId":"u22"},
    "d5bbe680adfb49e68302b02c864f66ba":{
      "scriptId":"u23"},
    "acc5e2411d914f768514c9f72ac3b9e4":{
      "scriptId":"u24"},
    "790eeb049c524564bd42c8544d2e026f":{
      "scriptId":"u25"},
    "c4fba80b160e433096fe38d6399b1f4c":{
      "scriptId":"u26"},
    "037e110dec024fc6b450d54e44b8158b":{
      "scriptId":"u27"},
    "2ed69fa4a04f4459b1a1b482b51542f5":{
      "scriptId":"u28"},
    "2a384efd13a8423b8df6004afee1f373":{
      "scriptId":"u29"},
    "46ff308c2b6a4d8dbc04c459cd0822c1":{
      "scriptId":"u30"},
    "9bd68dd9622a4d03a6bfc70144e6d841":{
      "scriptId":"u31"},
    "72574da95fa54681a73600d14be08805":{
      "scriptId":"u32"},
    "961e01a660c24c85abf2a3fb07812a50":{
      "scriptId":"u33"},
    "f1500b29eb3347148ae3a8435dbefea9":{
      "scriptId":"u34"},
    "e17ff3e548be41c79d1e14ee24c97bf9":{
      "scriptId":"u35"},
    "bda16dd4a78043928f4edb6c47c868c3":{
      "scriptId":"u36"},
    "e4520ffa110544d3a6b4152b7e721af7":{
      "scriptId":"u37"},
    "5efedadf77ac41a58027f89a2341ef7d":{
      "scriptId":"u38"},
    "23f35b9db93d415c8c278005fa04113d":{
      "scriptId":"u39"},
    "e21a371c2c03436ba9063bb4b30bba10":{
      "scriptId":"u40"},
    "dc57bcceab9a46158e6df7f26beaa95a":{
      "scriptId":"u41"},
    "5aad6c92054b4059babfa3967a1c7b8b":{
      "scriptId":"u42"},
    "a681671603134c08b7414c129eb4e93b":{
      "scriptId":"u43"},
    "97493de5b0b445e6a17b9b6ffaf32cc2":{
      "scriptId":"u44"},
    "631480a947f9418b8a49b26e8f433435":{
      "scriptId":"u45"},
    "b2c5b98732614107a0821af76e588dbf":{
      "scriptId":"u46"},
    "6337e243a0d04736901fdf8695945482":{
      "scriptId":"u47"},
    "d867a836842140c692b314162223fedc":{
      "scriptId":"u48"},
    "611cb92f17ce4d5295da0328159f3670":{
      "scriptId":"u49"},
    "6087a2286719423c965da376c3969747":{
      "scriptId":"u50"},
    "c149427e283b4bdbb1109e0519dea6cf":{
      "scriptId":"u51"},
    "ef22df7c18ee4233a9d8ae006b6320d6":{
      "scriptId":"u52"},
    "c12ebc990bb54c499a5746f105072d05":{
      "scriptId":"u53"},
    "4c2207449f084d8d88805243176c7a6e":{
      "scriptId":"u54"},
    "59131e5c85a049d99601291a1cac2b52":{
      "scriptId":"u55"},
    "99e5bf2b931d4c34a354065b98a6cf56":{
      "scriptId":"u56"},
    "4412008ce46449be980fe4fced939071":{
      "scriptId":"u57"},
    "9665989972d04a23b83046bb2b43a8a8":{
      "scriptId":"u58"},
    "4df3d716e0c34ecda07d19ea7a0009e1":{
      "scriptId":"u59"},
    "e41d5e53ebad433f86502ed7e5537ea7":{
      "scriptId":"u60"},
    "92e2f66fbf9849d99b505f7ff37e6ec9":{
      "scriptId":"u61"},
    "c337a6e9ee144f9082f71de348028239":{
      "scriptId":"u62"},
    "239db4b9f3334156b659b97c1307263c":{
      "scriptId":"u63"},
    "bdf0ecd467ad439c85336472f8413194":{
      "scriptId":"u64"},
    "ddb2c2d6f200471cb5a62f11e9a54264":{
      "scriptId":"u65"},
    "7231b95eef6c47e2bc95754dc20bcefe":{
      "scriptId":"u66"},
    "441b343890134890913065ae901f56fa":{
      "scriptId":"u67"},
    "28ccc27a9733459190416f5cd8e0d7f5":{
      "scriptId":"u68"},
    "d5c0aa10dfb941619a26787871284269":{
      "scriptId":"u69"},
    "a8f2235e3bc04208b9da39275bb43a1b":{
      "scriptId":"u70"},
    "e9b39142b5e24577b05bca34fb65ead6":{
      "scriptId":"u71"},
    "6e7969dfdcad4596ad12c0f2ab9c9b99":{
      "scriptId":"u72"},
    "396f7435617f466b934020165a6e9c81":{
      "scriptId":"u73"},
    "0b2f74ecc96d49edac19373b70790e33":{
      "scriptId":"u74"}}});