$axure.loadCurrentPage({
  "url":"押宝列表页.html",
  "generationDate":new Date(1449815486170.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"836d6245abff49beadd14292d213f491",
    "type":"Axure:Page",
    "name":"押宝列表页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4a2a871b87614030a6e609c186746b38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd327be4e3e74094afcc7b1a0fb11d42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u0.png"}},
{
          "id":"4037976a0e2944069a84d58fde8ed8cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":37},
            "size":{
              "width":235,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2d245119f3c462da73c448237d60129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":37},
                "size":{
                  "width":235,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 押宝首页",
                      "target":{
                        "targetType":"page",
                        "url":"押宝首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u2.png"}},
{
          "id":"07cce59fe71243c081aa8ee03c513c21",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":380,
              "y":49.5},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f9351a75a87426ca1e7d59c5f9a0aa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":380,
                  "y":49.5},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"372d74ad4c3d49089aa0017c8323048f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":477,
              "y":50},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"386fb592ad0443fc91aeb3f6fc0cdeec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":477,
                  "y":50},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64d081c714ab4c27a908443b4e5d6b50",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":599,
              "y":50},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3152d97d0f864feea0ad3efdbe87ebad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":599,
                  "y":50},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3925dcf9ab0b40f2aee5c9876af95fcf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":42.5},
            "size":{
              "width":127,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e493f94b83844338c2a8937ac56bd0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":42.5},
                "size":{
                  "width":127,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的清单",
                      "target":{
                        "targetType":"page",
                        "url":"我的清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u10.png"}},
{
          "id":"1acfaac962f14933a9a75dd6ed475404",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":84},
            "size":{
              "width":1200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/押宝列表页/u12_line.png"}},
{
          "id":"4a83504d74754e3598c2c55c250aed47",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":104},
            "size":{
              "width":358,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84dc200d90c84501b54af9ba9c44ba09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":104},
                "size":{
                  "width":358,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝列表页/u13.png"}},
{
          "id":"f38213eb61ac43918dc62875ebf57312",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":165},
            "size":{
              "width":425,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2052ebfd60b645afadc42d48dc9ed583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":165},
                "size":{
                  "width":425,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝列表页/u15.png"}},
{
          "id":"977d32a734af449ba44fa1b4bde56041",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":216},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7273f988518a4b53947dbdaf66ffb1e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":216},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"596e8354dfb649cd9f23c28dc34eb17c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":216},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"699e92803d594167b45fbe189d556d06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":216},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"d96476afc7da470baa6562ebae605307",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":492,
              "y":216},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bb128d5cca04014849d35794649d185",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":492,
                  "y":216},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"ab098ca5ee5f4db1bce63562af50786c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":216},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f847bb282604c47933717010fb43456",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":216},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"130a51b9de274b1c8be342c502dbfed5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":892,
              "y":216},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"031661da7eb14548b454c85b0c216280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":892,
                  "y":216},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"5164276cdb0a4941bbeb935d2cd12142",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":521},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a190ee0cfd54a28b2b21936b92b52f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":521},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"700634682cce4478975ef407fb8d49bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":521},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aec379eb129946318b5a28af481afe04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":521},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"ad6b39b02ad44a2db4f99698ddf52c30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":492,
              "y":521},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75640416423b430599a2d8857f599de5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":492,
                  "y":521},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"19a5a4a52baa4561afa85973ca21d2cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":521},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e37b9ad6a5cb4bddbc1d6d86e132f084",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":521},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"151973882aac48ef94727135f0337539",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":892,
              "y":521},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"267c97c39bf3400a926a1f487f94fc87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":892,
                  "y":521},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"9809a48ab7f1446398ccd0f8d63cdd36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":827},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b047926c8a94ecd97351b5761f90e26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":827},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"9bd07f82d627400cab711d52ddb06122",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":295,
              "y":827},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44b32bca301c4ddcba391560a776703b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":295,
                  "y":827},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"4240a868e96e40b3aaff0430fd782fda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":492,
              "y":827},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebebc037eafa40be9e5507f0c2eb76c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":492,
                  "y":827},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"0918b70099ff49e7b6b20b0c7c3e1b84",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":693,
              "y":827},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fbbde5f36dd4a628e34c4098b94ccb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":693,
                  "y":827},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"7d8f38f0ee4248a882887ec6800eb52c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":892,
              "y":827},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77882c1610e34184b0661b073fee60f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":892,
                  "y":827},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"437220457b7845a2a945268bb25cb4de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":1132},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"674914cf230b4d528191567dd1499a1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":1132},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"95c4b97c74074b4e8e1f02e6d758720c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":1132},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b414d667ada4f29928db25fa826d15f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":1132},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"7f2eefb0857145ceb516fddab3b8d90f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":1132},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50c61fb3dbe14c8eacba781aa7e7bae0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":1132},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"89c397cd110846fc80b829311f9e6891",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":692,
              "y":1132},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53bc5c5015024201946a13132f94aadb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":692,
                  "y":1132},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"a990ed25edda4151a16f3d5070bf3958",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":1132},
            "size":{
              "width":203,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31e7d87566494b74b18d4fefd0f33339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":1132},
                "size":{
                  "width":203,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u16.png"}},
{
          "id":"3320eac29e6849a6ae9cd0073be82e01",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1463},
            "size":{
              "width":1200,
              "height":405}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e90cd81141844630a447c963c9871a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1463},
                "size":{
                  "width":1200,
                  "height":405}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u82.png"}},
{
          "id":"131c6c9148c14a0888ddf8e7745a7818",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":216},
            "size":{
              "width":980,
              "height":244}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 押宝详情页",
                      "target":{
                        "targetType":"page",
                        "url":"押宝详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"27a8d60e133046519a5f427ae8c09638",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":461},
            "size":{
              "width":110,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的清单",
                      "target":{
                        "targetType":"page",
                        "url":"我的清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a349d39643854c64be594806aaf9a8e5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":461},
            "size":{
              "width":110,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的清单",
                      "target":{
                        "targetType":"page",
                        "url":"我的清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d76742470f1c47b693e688e0d713a313",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":461},
            "size":{
              "width":110,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的清单",
                      "target":{
                        "targetType":"page",
                        "url":"我的清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6b05f7ad05564e4ca5eb80bb4e6f6503",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":461},
            "size":{
              "width":110,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的清单",
                      "target":{
                        "targetType":"page",
                        "url":"我的清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d1399547d1df4fd1aca4920c3b11e244",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":461},
            "size":{
              "width":110,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的清单",
                      "target":{
                        "targetType":"page",
                        "url":"我的清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "4a2a871b87614030a6e609c186746b38":{
      "scriptId":"u0"},
    "dd327be4e3e74094afcc7b1a0fb11d42":{
      "scriptId":"u1"},
    "4037976a0e2944069a84d58fde8ed8cd":{
      "scriptId":"u2"},
    "e2d245119f3c462da73c448237d60129":{
      "scriptId":"u3"},
    "07cce59fe71243c081aa8ee03c513c21":{
      "scriptId":"u4"},
    "5f9351a75a87426ca1e7d59c5f9a0aa1":{
      "scriptId":"u5"},
    "372d74ad4c3d49089aa0017c8323048f":{
      "scriptId":"u6"},
    "386fb592ad0443fc91aeb3f6fc0cdeec":{
      "scriptId":"u7"},
    "64d081c714ab4c27a908443b4e5d6b50":{
      "scriptId":"u8"},
    "3152d97d0f864feea0ad3efdbe87ebad":{
      "scriptId":"u9"},
    "3925dcf9ab0b40f2aee5c9876af95fcf":{
      "scriptId":"u10"},
    "1e493f94b83844338c2a8937ac56bd0d":{
      "scriptId":"u11"},
    "1acfaac962f14933a9a75dd6ed475404":{
      "scriptId":"u12"},
    "4a83504d74754e3598c2c55c250aed47":{
      "scriptId":"u13"},
    "84dc200d90c84501b54af9ba9c44ba09":{
      "scriptId":"u14"},
    "f38213eb61ac43918dc62875ebf57312":{
      "scriptId":"u15"},
    "2052ebfd60b645afadc42d48dc9ed583":{
      "scriptId":"u16"},
    "977d32a734af449ba44fa1b4bde56041":{
      "scriptId":"u17"},
    "7273f988518a4b53947dbdaf66ffb1e1":{
      "scriptId":"u18"},
    "596e8354dfb649cd9f23c28dc34eb17c":{
      "scriptId":"u19"},
    "699e92803d594167b45fbe189d556d06":{
      "scriptId":"u20"},
    "d96476afc7da470baa6562ebae605307":{
      "scriptId":"u21"},
    "5bb128d5cca04014849d35794649d185":{
      "scriptId":"u22"},
    "ab098ca5ee5f4db1bce63562af50786c":{
      "scriptId":"u23"},
    "7f847bb282604c47933717010fb43456":{
      "scriptId":"u24"},
    "130a51b9de274b1c8be342c502dbfed5":{
      "scriptId":"u25"},
    "031661da7eb14548b454c85b0c216280":{
      "scriptId":"u26"},
    "5164276cdb0a4941bbeb935d2cd12142":{
      "scriptId":"u27"},
    "5a190ee0cfd54a28b2b21936b92b52f8":{
      "scriptId":"u28"},
    "700634682cce4478975ef407fb8d49bb":{
      "scriptId":"u29"},
    "aec379eb129946318b5a28af481afe04":{
      "scriptId":"u30"},
    "ad6b39b02ad44a2db4f99698ddf52c30":{
      "scriptId":"u31"},
    "75640416423b430599a2d8857f599de5":{
      "scriptId":"u32"},
    "19a5a4a52baa4561afa85973ca21d2cb":{
      "scriptId":"u33"},
    "e37b9ad6a5cb4bddbc1d6d86e132f084":{
      "scriptId":"u34"},
    "151973882aac48ef94727135f0337539":{
      "scriptId":"u35"},
    "267c97c39bf3400a926a1f487f94fc87":{
      "scriptId":"u36"},
    "9809a48ab7f1446398ccd0f8d63cdd36":{
      "scriptId":"u37"},
    "1b047926c8a94ecd97351b5761f90e26":{
      "scriptId":"u38"},
    "9bd07f82d627400cab711d52ddb06122":{
      "scriptId":"u39"},
    "44b32bca301c4ddcba391560a776703b":{
      "scriptId":"u40"},
    "4240a868e96e40b3aaff0430fd782fda":{
      "scriptId":"u41"},
    "ebebc037eafa40be9e5507f0c2eb76c7":{
      "scriptId":"u42"},
    "0918b70099ff49e7b6b20b0c7c3e1b84":{
      "scriptId":"u43"},
    "0fbbde5f36dd4a628e34c4098b94ccb7":{
      "scriptId":"u44"},
    "7d8f38f0ee4248a882887ec6800eb52c":{
      "scriptId":"u45"},
    "77882c1610e34184b0661b073fee60f7":{
      "scriptId":"u46"},
    "437220457b7845a2a945268bb25cb4de":{
      "scriptId":"u47"},
    "674914cf230b4d528191567dd1499a1c":{
      "scriptId":"u48"},
    "95c4b97c74074b4e8e1f02e6d758720c":{
      "scriptId":"u49"},
    "7b414d667ada4f29928db25fa826d15f":{
      "scriptId":"u50"},
    "7f2eefb0857145ceb516fddab3b8d90f":{
      "scriptId":"u51"},
    "50c61fb3dbe14c8eacba781aa7e7bae0":{
      "scriptId":"u52"},
    "89c397cd110846fc80b829311f9e6891":{
      "scriptId":"u53"},
    "53bc5c5015024201946a13132f94aadb":{
      "scriptId":"u54"},
    "a990ed25edda4151a16f3d5070bf3958":{
      "scriptId":"u55"},
    "31e7d87566494b74b18d4fefd0f33339":{
      "scriptId":"u56"},
    "3320eac29e6849a6ae9cd0073be82e01":{
      "scriptId":"u57"},
    "e90cd81141844630a447c963c9871a0f":{
      "scriptId":"u58"},
    "131c6c9148c14a0888ddf8e7745a7818":{
      "scriptId":"u59"},
    "27a8d60e133046519a5f427ae8c09638":{
      "scriptId":"u60"},
    "a349d39643854c64be594806aaf9a8e5":{
      "scriptId":"u61"},
    "d76742470f1c47b693e688e0d713a313":{
      "scriptId":"u62"},
    "6b05f7ad05564e4ca5eb80bb4e6f6503":{
      "scriptId":"u63"},
    "d1399547d1df4fd1aca4920c3b11e244":{
      "scriptId":"u64"}}});