$axure.loadCurrentPage({
  "url":"押宝详情页.html",
  "generationDate":new Date(1449815595665.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"015fe6ff88c343f68c59f79346339e72",
    "type":"Axure:Page",
    "name":"押宝详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"219c727c769c4438aa4e1005e83c0b45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":123},
            "size":{
              "width":700,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b5a9b69191945f8a04d9c1a9c492e85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":123},
                "size":{
                  "width":700,
                  "height":360}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝详情页/u0.png"}},
{
          "id":"3eec34d4e1d24155bc44ec3913586b2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e20078ff98142708e1597a918320405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u0.png"}},
{
          "id":"75bd2b38f4f64dfba1e22df37a2c5427",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":37},
            "size":{
              "width":235,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"775fce13c2d848b2802a4e586f43cd6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":37},
                "size":{
                  "width":235,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 押宝首页",
                      "target":{
                        "targetType":"page",
                        "url":"押宝首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u2.png"}},
{
          "id":"c0eefc047e6444d1b49f2cbae675f45f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":380,
              "y":49.5},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecfbb1d3753f4aecba840db7a7b01ea9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":380,
                  "y":49.5},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e86cb858d294fa2b8ea2a8799de08c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":477,
              "y":50},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a858a59695a4d7796db18f1a2c47a89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":477,
                  "y":50},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51fc22bec9d34ed98ec0231aa381e6dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":599,
              "y":50},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"191e97ef2c874f66b69e235d2c46f520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":599,
                  "y":50},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a12699a436234921a39db7379659ecc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":42.5},
            "size":{
              "width":127,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1654bbf8997a4d0995fea105acc8f822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":42.5},
                "size":{
                  "width":127,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的清单",
                      "target":{
                        "targetType":"page",
                        "url":"我的清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/押宝首页/u10.png"}},
{
          "id":"6fd098e14a344c24892aacc2d7cbd78c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":84},
            "size":{
              "width":1200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/押宝列表页/u12_line.png"}},
{
          "id":"f5969ff802ff4b67907754989bc145d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":100,
              "y":96},
            "size":{
              "width":375,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b325a9bd32e846b5a39601592306f8cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":100,
                  "y":96},
                "size":{
                  "width":375,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbc99fb074e4498dbe90f1f4b5198fd8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":878,
              "y":132},
            "size":{
              "width":219,
              "height":468}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"286ece2eeb8e49cd93b25eb95ee43f0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":878,
                  "y":132},
                "size":{
                  "width":219,
                  "height":468}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝详情页/u17.png"}},
{
          "id":"4a3773652afc446ba6a9c8221bf6302d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":373},
            "size":{
              "width":430,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fdd22e1282e4b858166f0f416c2932c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":373},
                "size":{
                  "width":430,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝详情页/u19.png"}},
{
          "id":"fa1c4003fd4540b1842c4d1ba4b7f407",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":493},
            "size":{
              "width":164,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e898dda51b6440f2984b46656121467b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":493},
                "size":{
                  "width":164,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝详情页/u21.png"}},
{
          "id":"b7d8581870e54bac981ccddc690512f8",
          "label":"详情",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":610},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a76bd045abf5414b88e7fbd4d3f4ea5c",
              "label":"奖品详情",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8a53ee6aa4324693bbd1ab12afa019e9",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1002,
                      "height":43}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d26bb4fa67d491b81e16a11000e005f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1002,
                          "height":43}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/押宝详情页/u24.png"}},
{
                  "id":"e98a987ce6fe4deb80b034b0dff2861d",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":203,
                      "y":69},
                    "size":{
                      "width":629,
                      "height":689}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af88e776406d4e309425c261fd422d0a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":203,
                          "y":69},
                        "size":{
                          "width":629,
                          "height":689}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/押宝详情页/u26.png"}},
{
                  "id":"4dd9aeb7852d4ba0a6b4a995ea6890be",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":104,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 详情 to 参与记录",
                              "panelsToStates":[{
                                  "panelPath":["b7d8581870e54bac981ccddc690512f8"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"d017e553d1fb43ea83af72a2fa32e644",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":204,
                      "y":2},
                    "size":{
                      "width":90,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 详情 to 晒单",
                              "panelsToStates":[{
                                  "panelPath":["b7d8581870e54bac981ccddc690512f8"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"b8e1cc22655c494dac9b463b988d98b3",
              "label":"参与记录",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1af272740b014d2bbfc5910488f5a2e4",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1002,
                      "height":43}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6015acfc412487faed1fcf9b9819868",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1002,
                          "height":43}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/押宝详情页/u30.png"}},
{
                  "id":"9e400d419cff48e28753c224bb5ca27d",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":48},
                    "size":{
                      "width":1000,
                      "height":441}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a75a9cfd809440d28013b488d73b8b06",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":48},
                        "size":{
                          "width":1000,
                          "height":441}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/押宝详情页/u32.png"}},
{
                  "id":"eb6c0bd56506412488909f96c87dbc78",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":221,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 详情 to 晒单",
                              "panelsToStates":[{
                                  "panelPath":["b7d8581870e54bac981ccddc690512f8"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"2d55c85f8e144804ae4b222fdd9c973f",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":90,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 详情 to 奖品详情",
                              "panelsToStates":[{
                                  "panelPath":["b7d8581870e54bac981ccddc690512f8"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]},
{
              "id":"928694780e924ee5bec4a7ee64c9f30f",
              "label":"晒单",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"165c8a3bbbbe416b86d1c96ed95015f0",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":68},
                    "size":{
                      "width":1000,
                      "height":265}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28ea634f649641ac8d0562d2e5ca5012",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":68},
                        "size":{
                          "width":1000,
                          "height":265}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/押宝详情页/u36.png"}},
{
                  "id":"eb766bc3c1be4b66bae5f4702b23eaaa",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1000,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bbb27775c5e14964b1d77eb34c0ef023",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1000,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/押宝详情页/u38.png"}},
{
                  "id":"55a5915e01c54e37b94ab0f3b7eab92d",
                  "label":"",
                  "parentDynamicPanel":"b7d8581870e54bac981ccddc690512f8",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":104,
                      "y":0},
                    "size":{
                      "width":90,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 详情 to 参与记录",
                              "panelsToStates":[{
                                  "panelPath":["b7d8581870e54bac981ccddc690512f8"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true}]}]},
{
          "id":"dbe1f8f0c77f436ebdb05ea6f7d38b4a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1400},
            "size":{
              "width":1200,
              "height":405}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0028dea8ff684bc3be58987938cb0b96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1400},
                "size":{
                  "width":1200,
                  "height":405}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/押宝首页/u82.png"}},
{
          "id":"7fd35437b5cb4d34ad1c5935dd6afc0c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1020,
              "y":210},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 往期押宝详情",
                      "target":{
                        "targetType":"page",
                        "url":"往期押宝详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"92a1634fc38348869e6bcc1c771f9913",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1020,
              "y":270},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 往期押宝详情",
                      "target":{
                        "targetType":"page",
                        "url":"往期押宝详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"d28837a9050b4ca888d0e34b68a32864",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1020,
              "y":330},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 往期押宝详情",
                      "target":{
                        "targetType":"page",
                        "url":"往期押宝详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1b61753263134031b1dfb2f0d399c126",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1020,
              "y":389.5},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 往期押宝详情",
                      "target":{
                        "targetType":"page",
                        "url":"往期押宝详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"81b7195c639949c3b6bc44d28bcfcf48",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1020,
              "y":450},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 往期押宝详情",
                      "target":{
                        "targetType":"page",
                        "url":"往期押宝详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"11c9361d75cf4b8db4652b61323ab926",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1020,
              "y":510},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 往期押宝详情",
                      "target":{
                        "targetType":"page",
                        "url":"往期押宝详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"48d052254dc5402d82ccf3c1ddcc99f7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":323},
            "size":{
              "width":190,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的清单",
                      "target":{
                        "targetType":"page",
                        "url":"我的清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "219c727c769c4438aa4e1005e83c0b45":{
      "scriptId":"u0"},
    "7b5a9b69191945f8a04d9c1a9c492e85":{
      "scriptId":"u1"},
    "3eec34d4e1d24155bc44ec3913586b2e":{
      "scriptId":"u2"},
    "5e20078ff98142708e1597a918320405":{
      "scriptId":"u3"},
    "75bd2b38f4f64dfba1e22df37a2c5427":{
      "scriptId":"u4"},
    "775fce13c2d848b2802a4e586f43cd6e":{
      "scriptId":"u5"},
    "c0eefc047e6444d1b49f2cbae675f45f":{
      "scriptId":"u6"},
    "ecfbb1d3753f4aecba840db7a7b01ea9":{
      "scriptId":"u7"},
    "8e86cb858d294fa2b8ea2a8799de08c7":{
      "scriptId":"u8"},
    "6a858a59695a4d7796db18f1a2c47a89":{
      "scriptId":"u9"},
    "51fc22bec9d34ed98ec0231aa381e6dc":{
      "scriptId":"u10"},
    "191e97ef2c874f66b69e235d2c46f520":{
      "scriptId":"u11"},
    "a12699a436234921a39db7379659ecc5":{
      "scriptId":"u12"},
    "1654bbf8997a4d0995fea105acc8f822":{
      "scriptId":"u13"},
    "6fd098e14a344c24892aacc2d7cbd78c":{
      "scriptId":"u14"},
    "f5969ff802ff4b67907754989bc145d1":{
      "scriptId":"u15"},
    "b325a9bd32e846b5a39601592306f8cc":{
      "scriptId":"u16"},
    "dbc99fb074e4498dbe90f1f4b5198fd8":{
      "scriptId":"u17"},
    "286ece2eeb8e49cd93b25eb95ee43f0d":{
      "scriptId":"u18"},
    "4a3773652afc446ba6a9c8221bf6302d":{
      "scriptId":"u19"},
    "4fdd22e1282e4b858166f0f416c2932c":{
      "scriptId":"u20"},
    "fa1c4003fd4540b1842c4d1ba4b7f407":{
      "scriptId":"u21"},
    "e898dda51b6440f2984b46656121467b":{
      "scriptId":"u22"},
    "b7d8581870e54bac981ccddc690512f8":{
      "scriptId":"u23"},
    "8a53ee6aa4324693bbd1ab12afa019e9":{
      "scriptId":"u24"},
    "0d26bb4fa67d491b81e16a11000e005f":{
      "scriptId":"u25"},
    "e98a987ce6fe4deb80b034b0dff2861d":{
      "scriptId":"u26"},
    "af88e776406d4e309425c261fd422d0a":{
      "scriptId":"u27"},
    "4dd9aeb7852d4ba0a6b4a995ea6890be":{
      "scriptId":"u28"},
    "d017e553d1fb43ea83af72a2fa32e644":{
      "scriptId":"u29"},
    "1af272740b014d2bbfc5910488f5a2e4":{
      "scriptId":"u30"},
    "b6015acfc412487faed1fcf9b9819868":{
      "scriptId":"u31"},
    "9e400d419cff48e28753c224bb5ca27d":{
      "scriptId":"u32"},
    "a75a9cfd809440d28013b488d73b8b06":{
      "scriptId":"u33"},
    "eb6c0bd56506412488909f96c87dbc78":{
      "scriptId":"u34"},
    "2d55c85f8e144804ae4b222fdd9c973f":{
      "scriptId":"u35"},
    "165c8a3bbbbe416b86d1c96ed95015f0":{
      "scriptId":"u36"},
    "28ea634f649641ac8d0562d2e5ca5012":{
      "scriptId":"u37"},
    "eb766bc3c1be4b66bae5f4702b23eaaa":{
      "scriptId":"u38"},
    "bbb27775c5e14964b1d77eb34c0ef023":{
      "scriptId":"u39"},
    "55a5915e01c54e37b94ab0f3b7eab92d":{
      "scriptId":"u40"},
    "dbe1f8f0c77f436ebdb05ea6f7d38b4a":{
      "scriptId":"u41"},
    "0028dea8ff684bc3be58987938cb0b96":{
      "scriptId":"u42"},
    "7fd35437b5cb4d34ad1c5935dd6afc0c":{
      "scriptId":"u43"},
    "92a1634fc38348869e6bcc1c771f9913":{
      "scriptId":"u44"},
    "d28837a9050b4ca888d0e34b68a32864":{
      "scriptId":"u45"},
    "1b61753263134031b1dfb2f0d399c126":{
      "scriptId":"u46"},
    "81b7195c639949c3b6bc44d28bcfcf48":{
      "scriptId":"u47"},
    "11c9361d75cf4b8db4652b61323ab926":{
      "scriptId":"u48"},
    "48d052254dc5402d82ccf3c1ddcc99f7":{
      "scriptId":"u49"}}});