$axure.loadCurrentPage({
  "url":"商品销售信息.html",
  "generationDate":new Date(1455876388382.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"97cf30ee92a243c1a1f5285fd411f5dd",
    "type":"Axure:Page",
    "name":"商品销售信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"94234361d511482f90b9ecb740d2a803",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":643}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a057cf915f9e4f5383d34dccca0f5909",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":643}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u0.png"}},
{
          "id":"2462633b5baf4abb8cdc4056f5a218b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":170,
              "y":82},
            "size":{
              "width":140,
              "height":28},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84940cd972934ef88a744e65d48b62d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":170,
                  "y":82},
                "size":{
                  "width":140,
                  "height":28},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u235.png"}},
{
          "id":"755d958b24f14bbe8293ace45e6fa1b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":1028,
              "y":82},
            "size":{
              "width":120,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b28c10c1409a42d0afc02b8d9b382248",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":1028,
                  "y":82},
                "size":{
                  "width":120,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员统计/u237.png"}},
{
          "id":"fec2502c613840a3a6ede0dfdd9ecf52",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":115},
            "size":{
              "width":340,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11c21cf9f02546ff99b0aa41f2355e53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":115},
                "size":{
                  "width":340,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单统计/u4.png"}},
{
          "id":"589a2423c1cb471a937903dc5b95adb3",
          "label":"订单统计",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":167},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"09bad53f408a418e9fa549c6abd18be4",
              "label":"访问购买率",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4ad51967bcad463fa351b4a1e387f9f8",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC},
                    "size":{
                      "width":1020,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"92a6b3e9ddd441e891506a93cdc0aabd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC},
                        "size":{
                          "width":1020,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/订单统计/u7.png"}},
{
                  "id":"7128e207dc274099b3be1765bcd2e0eb",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":10,
                      "y":0},
                    "size":{
                      "width":68,
                      "height":20},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"662840b5a5f643639eb5f8e4b8a49eba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":10,
                          "y":0},
                        "size":{
                          "width":68,
                          "height":20},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 订单统计 to 访问购买率",
                              "panelsToStates":[{
                                  "panelPath":["589a2423c1cb471a937903dc5b95adb3"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/订单统计/u23.png"}},
{
                  "id":"39a297b36c114dbb9f2d1d7f05537631",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":80,
                      "y":0},
                    "size":{
                      "width":68,
                      "height":20},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"209f5f6c885140418a19fc129af8bdb2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":80,
                          "y":0},
                        "size":{
                          "width":68,
                          "height":20},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 订单统计 to 质量信息",
                              "panelsToStates":[{
                                  "panelPath":["589a2423c1cb471a937903dc5b95adb3"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/订单统计/u23.png"}},
{
                  "id":"9aed0a30706f457eba777abac115e868",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"717f32ae52454102b0fa3be86c4bb121",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u15.png"}},
{
                  "id":"badb4a5da7d545e18e7e2fcddf15f131",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":205,
                      "y":30},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b9cfa92004b94c1a9eebb63d6d7ad5e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":205,
                          "y":30},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u15.png"}},
{
                  "id":"6adbd21dba6446c7b9706750e3d4679f",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":409,
                      "y":30},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"681823dd2a934023ba8e9b33b09b6847",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":409,
                          "y":30},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u15.png"}},
{
                  "id":"c492e0b9481645b4a730f7b3606f2998",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":612,
                      "y":30},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7cc740b5e08344a48284bade8f1ca916",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":612,
                          "y":30},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u15.png"}},
{
                  "id":"8118488da62c482bbee323739d901795",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":59},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"614ccb3ce7b5444897339e7a1c2cddc2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":59},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"e4dd66b249f9468b8fe8a24a4c66dc4e",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":204,
                      "y":59},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9881b60822b4ecbbbaf9adfabfc2d0a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":204,
                          "y":59},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"2b5f055ca6c440f3aef774545db17ff7",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":408,
                      "y":59},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41df8b44824640faa461352ac1b47a23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":408,
                          "y":59},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"8a88d5f10257415eb754088037332a77",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":612,
                      "y":59},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7eb508e723b344e79c679c42c3460945",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":612,
                          "y":59},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"fbb32b55ed24442481c76a0d7eb46c9f",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":816,
                      "y":30},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df0441884cf74fa391cec2e6e0882453",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":816,
                          "y":30},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u15.png"}},
{
                  "id":"96c45a91a50040d49fac07c58b677f7c",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":816,
                      "y":59},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"304666686c524ec79b5da4802565946a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":816,
                          "y":59},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"e07dcfb2237c4cea8db4a095cbf5a317",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":88},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2ddd0f303674b268edb90ff507f568f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"71a487b2858546ac98ddbe15f29ea789",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":204,
                      "y":88},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d7d4af46890642d3b155ff13638e025c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":204,
                          "y":88},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"03e9f85298ff4eb8904733772339a8d2",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":408,
                      "y":88},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76d0f8be982e4bcd8e6c36b3b81964b8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":408,
                          "y":88},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"0a01f277234f4db19a01c75823630817",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":612,
                      "y":88},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b7b819831dee48178d9092ea7d0a7f36",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":612,
                          "y":88},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"df892a32fbe049f88fefd7613a5a78bd",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":816,
                      "y":88},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b71f27aadd8439bb15f868b1702f0cb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":816,
                          "y":88},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}}]},
{
              "id":"2e3d873e7acd41728286ae7ae5012ab4",
              "label":"质量信息",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"75e6639e5fa74fd3aa72764682834d65",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC},
                    "size":{
                      "width":1020,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05735c28b523412db8ef693672ce0364",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC},
                        "size":{
                          "width":1020,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/订单统计/u7.png"}},
{
                  "id":"2b1d7d685e294a58b895885823d63288",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":10,
                      "y":0},
                    "size":{
                      "width":68,
                      "height":20},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2cb35bd90b1442dba8cda114058e9890",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":10,
                          "y":0},
                        "size":{
                          "width":68,
                          "height":20},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 订单统计 to 访问购买率",
                              "panelsToStates":[{
                                  "panelPath":["589a2423c1cb471a937903dc5b95adb3"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/订单统计/u23.png"}},
{
                  "id":"4bf433f3bf094f9188a9450f8be0554a",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":80,
                      "y":0},
                    "size":{
                      "width":68,
                      "height":20},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"358f803c304b489faa20dff0f0e417f7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":80,
                          "y":0},
                        "size":{
                          "width":68,
                          "height":20},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 订单统计 to 质量信息",
                              "panelsToStates":[{
                                  "panelPath":["589a2423c1cb471a937903dc5b95adb3"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/订单统计/u23.png"}},
{
                  "id":"f9f7722eb60744e5a42d3b1541a3cfc4",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"293093a0b77742d8818cd7a2c1ee176a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u15.png"}},
{
                  "id":"3729de9755b44f20a6ab575952871000",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":204,
                      "y":30},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0308256ec3e14319ae89099a70efa616",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":204,
                          "y":30},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u15.png"}},
{
                  "id":"0c731c77fbbe40b7bc5ce593c9749371",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":409,
                      "y":30},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c6dc0b167d91485cbb3212fa00ae183a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":409,
                          "y":30},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u15.png"}},
{
                  "id":"641888f5dfc549e2a587d7e098176db2",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":611,
                      "y":30},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d2c2cd888d4a47b8a29a6ffc283add51",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":611,
                          "y":30},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u15.png"}},
{
                  "id":"527e967c019a42718757d8a10995848c",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":59},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13c689e837e6479f87c3bb40eb8f8404",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":59},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"72919764233b41a29367dc075b932bdf",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":204,
                      "y":59},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce90e17a229443b8b4c043595908689c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":204,
                          "y":59},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"37815748ecaa4e5aa9634a757cb5b14c",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":407,
                      "y":59},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"13fb3ea696e6402facdc885f1c356084",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":407,
                          "y":59},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"58f5cc357b7b424887fab0146a371ec3",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":611,
                      "y":59},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb8c42ed6ef2467d9aef435231c4a0f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":611,
                          "y":59},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"3c357cb280874d1a947d3f1f4caba4d8",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":816,
                      "y":30},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a8c6f016e804ed2becb12bece44c18c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":816,
                          "y":30},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u15.png"}},
{
                  "id":"bdaa70d5db2243afaf8a2d4d1a7ea5a4",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":816,
                      "y":59},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b924a31ca8d4421a397c8c96e299855",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":816,
                          "y":59},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"26011a768768407f9b0ffc5b7194f7a6",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":88},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9401811412c04cc0a6c2f40d5bc709d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":88},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"d75792c760ba4a3aa9a589315a972ee3",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":204,
                      "y":88},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f4971268a9944168b06c2e84a128fd0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":204,
                          "y":88},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"dda8e6f182cb42f6b8bc729b1b16e5ae",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":407,
                      "y":88},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33e268b5e16f4a1fb0165ca27cfabaf0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":407,
                          "y":88},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"a37a595ab97541ffa8e9b75888173f87",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":611,
                      "y":88},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7ebe597209641b899f8faf0ca31301d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":611,
                          "y":88},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}},
{
                  "id":"d560b8612c004ba999ed8c843d49481f",
                  "label":"",
                  "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":816,
                      "y":88},
                    "size":{
                      "width":204,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dashed"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fad3769fd04d44cab95543f8e36865dc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"589a2423c1cb471a937903dc5b95adb3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":816,
                          "y":88},
                        "size":{
                          "width":204,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dashed"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品销售信息/u23.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "94234361d511482f90b9ecb740d2a803":{
      "scriptId":"u0"},
    "a057cf915f9e4f5383d34dccca0f5909":{
      "scriptId":"u1"},
    "2462633b5baf4abb8cdc4056f5a218b5":{
      "scriptId":"u2"},
    "84940cd972934ef88a744e65d48b62d9":{
      "scriptId":"u3"},
    "755d958b24f14bbe8293ace45e6fa1b6":{
      "scriptId":"u4"},
    "b28c10c1409a42d0afc02b8d9b382248":{
      "scriptId":"u5"},
    "fec2502c613840a3a6ede0dfdd9ecf52":{
      "scriptId":"u6"},
    "11c21cf9f02546ff99b0aa41f2355e53":{
      "scriptId":"u7"},
    "589a2423c1cb471a937903dc5b95adb3":{
      "scriptId":"u8"},
    "4ad51967bcad463fa351b4a1e387f9f8":{
      "scriptId":"u9"},
    "92a6b3e9ddd441e891506a93cdc0aabd":{
      "scriptId":"u10"},
    "7128e207dc274099b3be1765bcd2e0eb":{
      "scriptId":"u11"},
    "662840b5a5f643639eb5f8e4b8a49eba":{
      "scriptId":"u12"},
    "39a297b36c114dbb9f2d1d7f05537631":{
      "scriptId":"u13"},
    "209f5f6c885140418a19fc129af8bdb2":{
      "scriptId":"u14"},
    "9aed0a30706f457eba777abac115e868":{
      "scriptId":"u15"},
    "717f32ae52454102b0fa3be86c4bb121":{
      "scriptId":"u16"},
    "badb4a5da7d545e18e7e2fcddf15f131":{
      "scriptId":"u17"},
    "b9cfa92004b94c1a9eebb63d6d7ad5e2":{
      "scriptId":"u18"},
    "6adbd21dba6446c7b9706750e3d4679f":{
      "scriptId":"u19"},
    "681823dd2a934023ba8e9b33b09b6847":{
      "scriptId":"u20"},
    "c492e0b9481645b4a730f7b3606f2998":{
      "scriptId":"u21"},
    "7cc740b5e08344a48284bade8f1ca916":{
      "scriptId":"u22"},
    "8118488da62c482bbee323739d901795":{
      "scriptId":"u23"},
    "614ccb3ce7b5444897339e7a1c2cddc2":{
      "scriptId":"u24"},
    "e4dd66b249f9468b8fe8a24a4c66dc4e":{
      "scriptId":"u25"},
    "e9881b60822b4ecbbbaf9adfabfc2d0a":{
      "scriptId":"u26"},
    "2b5f055ca6c440f3aef774545db17ff7":{
      "scriptId":"u27"},
    "41df8b44824640faa461352ac1b47a23":{
      "scriptId":"u28"},
    "8a88d5f10257415eb754088037332a77":{
      "scriptId":"u29"},
    "7eb508e723b344e79c679c42c3460945":{
      "scriptId":"u30"},
    "fbb32b55ed24442481c76a0d7eb46c9f":{
      "scriptId":"u31"},
    "df0441884cf74fa391cec2e6e0882453":{
      "scriptId":"u32"},
    "96c45a91a50040d49fac07c58b677f7c":{
      "scriptId":"u33"},
    "304666686c524ec79b5da4802565946a":{
      "scriptId":"u34"},
    "e07dcfb2237c4cea8db4a095cbf5a317":{
      "scriptId":"u35"},
    "f2ddd0f303674b268edb90ff507f568f":{
      "scriptId":"u36"},
    "71a487b2858546ac98ddbe15f29ea789":{
      "scriptId":"u37"},
    "d7d4af46890642d3b155ff13638e025c":{
      "scriptId":"u38"},
    "03e9f85298ff4eb8904733772339a8d2":{
      "scriptId":"u39"},
    "76d0f8be982e4bcd8e6c36b3b81964b8":{
      "scriptId":"u40"},
    "0a01f277234f4db19a01c75823630817":{
      "scriptId":"u41"},
    "b7b819831dee48178d9092ea7d0a7f36":{
      "scriptId":"u42"},
    "df892a32fbe049f88fefd7613a5a78bd":{
      "scriptId":"u43"},
    "4b71f27aadd8439bb15f868b1702f0cb":{
      "scriptId":"u44"},
    "75e6639e5fa74fd3aa72764682834d65":{
      "scriptId":"u45"},
    "05735c28b523412db8ef693672ce0364":{
      "scriptId":"u46"},
    "2b1d7d685e294a58b895885823d63288":{
      "scriptId":"u47"},
    "2cb35bd90b1442dba8cda114058e9890":{
      "scriptId":"u48"},
    "4bf433f3bf094f9188a9450f8be0554a":{
      "scriptId":"u49"},
    "358f803c304b489faa20dff0f0e417f7":{
      "scriptId":"u50"},
    "f9f7722eb60744e5a42d3b1541a3cfc4":{
      "scriptId":"u51"},
    "293093a0b77742d8818cd7a2c1ee176a":{
      "scriptId":"u52"},
    "3729de9755b44f20a6ab575952871000":{
      "scriptId":"u53"},
    "0308256ec3e14319ae89099a70efa616":{
      "scriptId":"u54"},
    "0c731c77fbbe40b7bc5ce593c9749371":{
      "scriptId":"u55"},
    "c6dc0b167d91485cbb3212fa00ae183a":{
      "scriptId":"u56"},
    "641888f5dfc549e2a587d7e098176db2":{
      "scriptId":"u57"},
    "d2c2cd888d4a47b8a29a6ffc283add51":{
      "scriptId":"u58"},
    "527e967c019a42718757d8a10995848c":{
      "scriptId":"u59"},
    "13c689e837e6479f87c3bb40eb8f8404":{
      "scriptId":"u60"},
    "72919764233b41a29367dc075b932bdf":{
      "scriptId":"u61"},
    "ce90e17a229443b8b4c043595908689c":{
      "scriptId":"u62"},
    "37815748ecaa4e5aa9634a757cb5b14c":{
      "scriptId":"u63"},
    "13fb3ea696e6402facdc885f1c356084":{
      "scriptId":"u64"},
    "58f5cc357b7b424887fab0146a371ec3":{
      "scriptId":"u65"},
    "eb8c42ed6ef2467d9aef435231c4a0f5":{
      "scriptId":"u66"},
    "3c357cb280874d1a947d3f1f4caba4d8":{
      "scriptId":"u67"},
    "9a8c6f016e804ed2becb12bece44c18c":{
      "scriptId":"u68"},
    "bdaa70d5db2243afaf8a2d4d1a7ea5a4":{
      "scriptId":"u69"},
    "2b924a31ca8d4421a397c8c96e299855":{
      "scriptId":"u70"},
    "26011a768768407f9b0ffc5b7194f7a6":{
      "scriptId":"u71"},
    "9401811412c04cc0a6c2f40d5bc709d3":{
      "scriptId":"u72"},
    "d75792c760ba4a3aa9a589315a972ee3":{
      "scriptId":"u73"},
    "7f4971268a9944168b06c2e84a128fd0":{
      "scriptId":"u74"},
    "dda8e6f182cb42f6b8bc729b1b16e5ae":{
      "scriptId":"u75"},
    "33e268b5e16f4a1fb0165ca27cfabaf0":{
      "scriptId":"u76"},
    "a37a595ab97541ffa8e9b75888173f87":{
      "scriptId":"u77"},
    "f7ebe597209641b899f8faf0ca31301d":{
      "scriptId":"u78"},
    "d560b8612c004ba999ed8c843d49481f":{
      "scriptId":"u79"},
    "fad3769fd04d44cab95543f8e36865dc":{
      "scriptId":"u80"}}});