$axure.loadCurrentPage({
  "url":"自选.html",
  "generationDate":new Date(1454637460379.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c16a11dec476471fbc5d7dc67cee0eda",
    "type":"Axure:Page",
    "name":"自选",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"973d388e2fe0449fa59aadf59eae337d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86281632f00c4fd39320c8d624b5e931",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u0.png"}},
{
          "id":"720800fc38d7432887c88aac998ccdac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":36},
            "size":{
              "width":280,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d360f43ae1c4099a010ad0b109aa05e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":280,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u2.png"}},
{
          "id":"684c0f7d6af445ad84ff828b41690bfc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":55},
            "size":{
              "width":650,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a0eb1feb5ea4eb5a97d8219e53cb349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":55},
                "size":{
                  "width":650,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u4.png"}},
{
          "id":"261eb9e20e954f539b20fb1c2ccaeb15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF303849},
            "location":{
              "x":0,
              "y":102},
            "size":{
              "width":1200,
              "height":1018}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b6c6bbca78848289d7c888a7c06a565",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF303849},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":1200,
                  "height":1018}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u6.png"}},
{
          "id":"743ec93001704df1ab758a62e2872617",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"2ce97a626e584bfbb5afe670ba4d366c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":1000,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"354e6a98666746d090b40a2891425e99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":1000,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u20.png"}},
{
          "id":"771330ab67fd4df3845bd692961b364a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c75d9a1373541de96712fbb2e49fa9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u22.png"}},
{
          "id":"fba543ecdfd3449c8a8391226c88e6ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acc917b8f5f143c995136c49bdbc36f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个股",
                      "target":{
                        "targetType":"page",
                        "url":"个股.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"632c834afcfe42ea98e5ade84ecccb4c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":210},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d12adc5daf44fb2b9fddc42484bdade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":210},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u26.png"}},
{
          "id":"741d3843a1a84f23a0f4e3c9381e49af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":250},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f819520cf845448c801d48135dbc2468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":250},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ada14b89907040f39f0d3e91c0ab36bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":124},
            "size":{
              "width":59,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dedbc2529ec94a9597f14ab7c794e130",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":124},
                "size":{
                  "width":59,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u224.png"}},
{
          "id":"31b8a043fae648b892ba24beb73e58b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":129},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e81eb2c596cd4d828e3e2c113fc5811b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":129},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29fc130163d6414194bda7e26dcb65db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":149},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1c49f6fc9ee4c44a7038e7b27dfd16f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":149},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d4b94d3405f4323a32caf1bf94b417d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":169},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df43728594954b598565f804021f5b72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":169},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"278ecc6d823f4a2fb9a6c54d346aa4d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":117},
            "size":{
              "width":87,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99f2cfdfddb944c1890a651570537db5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":117},
                "size":{
                  "width":87,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8456638b0ef84100b44e29eec5876b78",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":432,
              "y":154},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0bb0d76e0d9406087d14d65d17a75b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":432,
                  "y":154},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2e66cd501e24d0ea5b7ba06829eb5c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":470,
              "y":154},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"617f88417cc545579f159cf322f1eb30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":154},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba8ca57a381541edbe4458c57c87fdb3",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":527,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"5126a5c7063c4c4e9c401f8d7944cb20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":551,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11276dda81e74218ad1b166bd4173d3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":551,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00e632e30d8446938a3f28eaae08e760",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":556,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3300dbd25ae14b07956c189761dbbeae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33c8f1e363154c90ba4709da0ef1bcb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":327,
              "y":120},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdc1c8d387f84fa88fd4a60c227ac786",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":120},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"daed5756ce924fcaaba0286b8c772c66",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":150},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"011928059156463a91ed808ff5a73ef0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":150},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u76.png"}},
{
          "id":"35aa185e728641058c4a0edcb7b08d78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":150},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02200597a6914a9a90be71dbdb2c1657",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":150},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u78.png"}},
{
          "id":"ea5e8700268b4c7ab6c1adecad3362c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":610,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6a71974577347f18ee80e93b16bec38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":610,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"081b37dd106c49b0861ab5fd2fd57b65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF00,
              "opacity":1},
            "location":{
              "x":605,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a613e534b8e4cea8e183aff7bc3c27c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00,
                  "opacity":1},
                "location":{
                  "x":605,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98ed085fe6604ea79a524871907cbd01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":665,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25c739424089458bb2cd2ace430f0672",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":665,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ecc342686fd48749322e38e590b9cd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":660,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b023ceb92252474488f780bf046981d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"576a3bec66544dc08ebfd9279e72847a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"47f3e13216104bfd9583a568ee724f43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":738,
              "y":128},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80fd37662965434aa5bf562cc564c0cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":738,
                  "y":128},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae3629eae4f242efaeb8b2b3bc551c29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":738,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fcfbe7bc97942a1a08ff750f400840d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":738,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03a1165f401944d389169b990476b707",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":775,
              "y":127},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4da36d5ddf9b4b759caedc930a57d7ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":775,
                  "y":127},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d81f2bbe7cbe45a7afcb7776c3d91ed5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":775,
              "y":153},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee4765fbe1c94cf19cf6137021ec37a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":775,
                  "y":153},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ac3f0375f4a4e8fb7a21e2cb4603f1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":831,
              "y":128},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9f0bc58f420442394e5dcdde89f94bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":128},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2db6b7580a34c8e9c3d3801bae12e30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":831,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b3acc55e24147de8a9f09321d2b08b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb81097e07cf4fa8aa97c433522f0284",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":868,
              "y":127},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ebd80d8508e43df80a6526b1d1ada05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":127},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9faa7f32ee3946eaa03397a1f913fa17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF00,
              "opacity":1},
            "location":{
              "x":868,
              "y":153},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fb6dee794a843f094f36b5e4babb1ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":153},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f73e456274d242d5a661da69faa24fb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF282828,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":100,
              "y":270},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ba309b797f34b6d9c9d04e17e7064fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF282828,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":100,
                  "y":270},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 成交记录",
                      "target":{
                        "targetType":"page",
                        "url":"成交记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个股/u30.png"}},
{
          "id":"d8529fefa90c473aba118ac980d898c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":278},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d4114bc32f24a76b482708aa4394636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":278},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u32.png"}},
{
          "id":"34d83e71b2d64754aff4372ae4c477f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":321},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d62f4de4b8c4edca42081d6e852c5e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":321},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b297bbb4f6714ac19af63c7a66ea5a45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF0287FE},
            "location":{
              "x":100,
              "y":340},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9c0060954cb4f0892fbb042c5a81ecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0287FE},
                "location":{
                  "x":100,
                  "y":340},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u24.png"}},
{
          "id":"2709d28014c54a3492e64f70ab3065b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":390},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"810ccc2759454b43a3d789b6cd7a759e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":390},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf88803acd64473996b9bde4513c6f0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":350},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"004b6db4a8614b489eb32224b8015f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":350},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/自选/u79.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "973d388e2fe0449fa59aadf59eae337d":{
      "scriptId":"u0"},
    "86281632f00c4fd39320c8d624b5e931":{
      "scriptId":"u1"},
    "720800fc38d7432887c88aac998ccdac":{
      "scriptId":"u2"},
    "6d360f43ae1c4099a010ad0b109aa05e":{
      "scriptId":"u3"},
    "684c0f7d6af445ad84ff828b41690bfc":{
      "scriptId":"u4"},
    "1a0eb1feb5ea4eb5a97d8219e53cb349":{
      "scriptId":"u5"},
    "261eb9e20e954f539b20fb1c2ccaeb15":{
      "scriptId":"u6"},
    "7b6c6bbca78848289d7c888a7c06a565":{
      "scriptId":"u7"},
    "743ec93001704df1ab758a62e2872617":{
      "scriptId":"u8"},
    "2ce97a626e584bfbb5afe670ba4d366c":{
      "scriptId":"u9"},
    "354e6a98666746d090b40a2891425e99":{
      "scriptId":"u10"},
    "771330ab67fd4df3845bd692961b364a":{
      "scriptId":"u11"},
    "0c75d9a1373541de96712fbb2e49fa9b":{
      "scriptId":"u12"},
    "fba543ecdfd3449c8a8391226c88e6ce":{
      "scriptId":"u13"},
    "acc917b8f5f143c995136c49bdbc36f5":{
      "scriptId":"u14"},
    "632c834afcfe42ea98e5ade84ecccb4c":{
      "scriptId":"u15"},
    "1d12adc5daf44fb2b9fddc42484bdade":{
      "scriptId":"u16"},
    "741d3843a1a84f23a0f4e3c9381e49af":{
      "scriptId":"u17"},
    "f819520cf845448c801d48135dbc2468":{
      "scriptId":"u18"},
    "ada14b89907040f39f0d3e91c0ab36bd":{
      "scriptId":"u19"},
    "dedbc2529ec94a9597f14ab7c794e130":{
      "scriptId":"u20"},
    "31b8a043fae648b892ba24beb73e58b0":{
      "scriptId":"u21"},
    "e81eb2c596cd4d828e3e2c113fc5811b":{
      "scriptId":"u22"},
    "29fc130163d6414194bda7e26dcb65db":{
      "scriptId":"u23"},
    "f1c49f6fc9ee4c44a7038e7b27dfd16f":{
      "scriptId":"u24"},
    "1d4b94d3405f4323a32caf1bf94b417d":{
      "scriptId":"u25"},
    "df43728594954b598565f804021f5b72":{
      "scriptId":"u26"},
    "278ecc6d823f4a2fb9a6c54d346aa4d0":{
      "scriptId":"u27"},
    "99f2cfdfddb944c1890a651570537db5":{
      "scriptId":"u28"},
    "8456638b0ef84100b44e29eec5876b78":{
      "scriptId":"u29"},
    "c0bb0d76e0d9406087d14d65d17a75b0":{
      "scriptId":"u30"},
    "e2e66cd501e24d0ea5b7ba06829eb5c1":{
      "scriptId":"u31"},
    "617f88417cc545579f159cf322f1eb30":{
      "scriptId":"u32"},
    "ba8ca57a381541edbe4458c57c87fdb3":{
      "scriptId":"u33"},
    "5126a5c7063c4c4e9c401f8d7944cb20":{
      "scriptId":"u34"},
    "11276dda81e74218ad1b166bd4173d3c":{
      "scriptId":"u35"},
    "00e632e30d8446938a3f28eaae08e760":{
      "scriptId":"u36"},
    "3300dbd25ae14b07956c189761dbbeae":{
      "scriptId":"u37"},
    "33c8f1e363154c90ba4709da0ef1bcb7":{
      "scriptId":"u38"},
    "cdc1c8d387f84fa88fd4a60c227ac786":{
      "scriptId":"u39"},
    "daed5756ce924fcaaba0286b8c772c66":{
      "scriptId":"u40"},
    "011928059156463a91ed808ff5a73ef0":{
      "scriptId":"u41"},
    "35aa185e728641058c4a0edcb7b08d78":{
      "scriptId":"u42"},
    "02200597a6914a9a90be71dbdb2c1657":{
      "scriptId":"u43"},
    "ea5e8700268b4c7ab6c1adecad3362c6":{
      "scriptId":"u44"},
    "d6a71974577347f18ee80e93b16bec38":{
      "scriptId":"u45"},
    "081b37dd106c49b0861ab5fd2fd57b65":{
      "scriptId":"u46"},
    "1a613e534b8e4cea8e183aff7bc3c27c":{
      "scriptId":"u47"},
    "98ed085fe6604ea79a524871907cbd01":{
      "scriptId":"u48"},
    "25c739424089458bb2cd2ace430f0672":{
      "scriptId":"u49"},
    "5ecc342686fd48749322e38e590b9cd9":{
      "scriptId":"u50"},
    "b023ceb92252474488f780bf046981d2":{
      "scriptId":"u51"},
    "576a3bec66544dc08ebfd9279e72847a":{
      "scriptId":"u52"},
    "47f3e13216104bfd9583a568ee724f43":{
      "scriptId":"u53"},
    "80fd37662965434aa5bf562cc564c0cd":{
      "scriptId":"u54"},
    "ae3629eae4f242efaeb8b2b3bc551c29":{
      "scriptId":"u55"},
    "6fcfbe7bc97942a1a08ff750f400840d":{
      "scriptId":"u56"},
    "03a1165f401944d389169b990476b707":{
      "scriptId":"u57"},
    "4da36d5ddf9b4b759caedc930a57d7ee":{
      "scriptId":"u58"},
    "d81f2bbe7cbe45a7afcb7776c3d91ed5":{
      "scriptId":"u59"},
    "ee4765fbe1c94cf19cf6137021ec37a6":{
      "scriptId":"u60"},
    "5ac3f0375f4a4e8fb7a21e2cb4603f1f":{
      "scriptId":"u61"},
    "b9f0bc58f420442394e5dcdde89f94bc":{
      "scriptId":"u62"},
    "f2db6b7580a34c8e9c3d3801bae12e30":{
      "scriptId":"u63"},
    "4b3acc55e24147de8a9f09321d2b08b1":{
      "scriptId":"u64"},
    "fb81097e07cf4fa8aa97c433522f0284":{
      "scriptId":"u65"},
    "3ebd80d8508e43df80a6526b1d1ada05":{
      "scriptId":"u66"},
    "9faa7f32ee3946eaa03397a1f913fa17":{
      "scriptId":"u67"},
    "8fb6dee794a843f094f36b5e4babb1ac":{
      "scriptId":"u68"},
    "f73e456274d242d5a661da69faa24fb4":{
      "scriptId":"u69"},
    "0ba309b797f34b6d9c9d04e17e7064fc":{
      "scriptId":"u70"},
    "d8529fefa90c473aba118ac980d898c0":{
      "scriptId":"u71"},
    "8d4114bc32f24a76b482708aa4394636":{
      "scriptId":"u72"},
    "34d83e71b2d64754aff4372ae4c477f0":{
      "scriptId":"u73"},
    "3d62f4de4b8c4edca42081d6e852c5e6":{
      "scriptId":"u74"},
    "b297bbb4f6714ac19af63c7a66ea5a45":{
      "scriptId":"u75"},
    "f9c0060954cb4f0892fbb042c5a81ecc":{
      "scriptId":"u76"},
    "2709d28014c54a3492e64f70ab3065b9":{
      "scriptId":"u77"},
    "810ccc2759454b43a3d789b6cd7a759e":{
      "scriptId":"u78"},
    "bf88803acd64473996b9bde4513c6f0d":{
      "scriptId":"u79"},
    "004b6db4a8614b489eb32224b8015f00":{
      "scriptId":"u80"}}});