$axure.loadCurrentPage({
  "url":"支付成功.html",
  "generationDate":new Date(1449815587120.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f912e18105a44274a264ec53d42b2922",
    "type":"Axure:Page",
    "name":"支付成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fdc1d603598b4ee1bf6e718cf11210fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35206fb9532f44b199b5072da2ce6a23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/regen/u0.png"}},
{
          "id":"d1254bc894b34163b0441e5c74d3bee3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":95,
              "y":37},
            "size":{
              "width":235,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdb2805381684b429324b197feb14d9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":95,
                  "y":37},
                "size":{
                  "width":235,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 押宝首页",
                      "target":{
                        "targetType":"page",
                        "url":"押宝首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付成功/regen/u2.png"}},
{
          "id":"d927faef6d6445129e916e1aeb4f682b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":380,
              "y":50},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0412f40a3f6545848e572d0a9c30bf81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":380,
                  "y":50},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"113ec68650344a25a3b8e8e8fc4d33c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":477,
              "y":50},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bc642c1be5c49158203d1ccf18416dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":477,
                  "y":50},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8fff9528c344f6d8f83cec79f3f5d38",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":599,
              "y":50},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48972d09423a45fa80aa14f6f3e55edc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":599,
                  "y":50},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80060b70475b4a9fb9219e899e45d6ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":42},
            "size":{
              "width":127,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8f14799af924b569ec4f0e68a29bb9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":42},
                "size":{
                  "width":127,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的清单",
                      "target":{
                        "targetType":"page",
                        "url":"我的清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付成功/regen/u10.png"}},
{
          "id":"1f50b85d0299420693a25f18968180ba",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":84},
            "size":{
              "width":1200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/支付成功/regen/u12_line.png"}},
{
          "id":"3c13a0df41e34c73ab14bce9a65f2721",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1370},
            "size":{
              "width":1200,
              "height":405}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2e30132eb6049a6bbb5a972fa4907d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1370},
                "size":{
                  "width":1200,
                  "height":405}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/regen/u13.png"}},
{
          "id":"ec3a77cddf1d41c4b58102c61b16648b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":466},
            "size":{
              "width":1200,
              "height":405}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dc0cba95fe045429659efa57a58e82b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":466},
                "size":{
                  "width":1200,
                  "height":405}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/regen/u13.png"}},
{
          "id":"8d5cde3d4cd44a81a699574b6f502919",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":359,
              "y":168},
            "size":{
              "width":517,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08091b425d55480bb337776539493815",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":359,
                  "y":168},
                "size":{
                  "width":517,
                  "height":154}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付成功/regen/u17.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fdc1d603598b4ee1bf6e718cf11210fb":{
      "scriptId":"u0"},
    "35206fb9532f44b199b5072da2ce6a23":{
      "scriptId":"u1"},
    "d1254bc894b34163b0441e5c74d3bee3":{
      "scriptId":"u2"},
    "bdb2805381684b429324b197feb14d9c":{
      "scriptId":"u3"},
    "d927faef6d6445129e916e1aeb4f682b":{
      "scriptId":"u4"},
    "0412f40a3f6545848e572d0a9c30bf81":{
      "scriptId":"u5"},
    "113ec68650344a25a3b8e8e8fc4d33c5":{
      "scriptId":"u6"},
    "7bc642c1be5c49158203d1ccf18416dd":{
      "scriptId":"u7"},
    "b8fff9528c344f6d8f83cec79f3f5d38":{
      "scriptId":"u8"},
    "48972d09423a45fa80aa14f6f3e55edc":{
      "scriptId":"u9"},
    "80060b70475b4a9fb9219e899e45d6ec":{
      "scriptId":"u10"},
    "c8f14799af924b569ec4f0e68a29bb9b":{
      "scriptId":"u11"},
    "1f50b85d0299420693a25f18968180ba":{
      "scriptId":"u12"},
    "3c13a0df41e34c73ab14bce9a65f2721":{
      "scriptId":"u13"},
    "a2e30132eb6049a6bbb5a972fa4907d0":{
      "scriptId":"u14"},
    "ec3a77cddf1d41c4b58102c61b16648b":{
      "scriptId":"u15"},
    "1dc0cba95fe045429659efa57a58e82b":{
      "scriptId":"u16"},
    "8d5cde3d4cd44a81a699574b6f502919":{
      "scriptId":"u17"},
    "08091b425d55480bb337776539493815":{
      "scriptId":"u18"}}});