$axure.loadCurrentPage({
  "url":"手机版列表.html",
  "generationDate":new Date(1457072024833.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4eb4c444eb31432b871a7cea809657bb",
    "type":"Axure:Page",
    "name":"手机版列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"04fbd17464fd4b4694a90b25fbeccac3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"7ddeb125ab1346d78fab0f7c44d11c2d"},
{
          "id":"7ec02485c9d64d83a2bcb1787341fbf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":21},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78ae15aeb8dd4ce3a1ba31060dfcc916",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":21},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机版列表/u5.png"}},
{
          "id":"f8bc0a7eb24947c7aec0477de20d33d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Calibri Regular', 'Calibri'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "location":{
              "x":19,
              "y":27},
            "size":{
              "width":11,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1fb2f66d45045ada30a94947031fc46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Calibri Regular', 'Calibri'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":27},
                "size":{
                  "width":11,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"887745b6aaf244d29e58b1cf767c3624",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":28},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6eaf565dad3749d69a00a1ec6655e625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":28},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1<br> (If visibility of 不明等于: false)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["47285fe7c9da4f21ad3e9c16d03e8b2e",
"69abecdd38b243fb90f134617583d7a8"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":false}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]},
{
                      "action":"moveWidget",
                      "description":"Move Widget",
                      "objectsToMoves":[]}]},
{
                  "description":"用例 2<br> (Else If visibility of 不明等于: 真)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["47285fe7c9da4f21ad3e9c16d03e8b2e",
"69abecdd38b243fb90f134617583d7a8"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"moveWidget",
                      "description":"Move Widget",
                      "objectsToMoves":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机版列表/u9.png"}},
{
          "id":"7e74c7b0599f44b29957073f12d78e48",
          "label":"秒杀时间",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":61},
            "size":{
              "width":320,
              "height":62}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 滑动 x 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["cd0b33f9dcb944308e5aa5ebfdf6311b"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"278afcce108546898de1ca1c75c000a2",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                  "label":"滑动",
                  "parentDynamicPanel":"7e74c7b0599f44b29957073f12d78e48",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":49}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"c27528bcfa12464cb84248a6e0ee8ad0",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"952bd2e9552e4ad2b55287a4453cd1d5",
                          "label":"",
                          "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":320,
                              "height":50}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"18006307060f4efa954d40df5900ac8b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":320,
                                  "height":50}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机版列表/u13.png"}},
{
                          "id":"2a7b3aa575ec49a29e25de9c4d57eaf9",
                          "label":"",
                          "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF515151},
                            "size":{
                              "width":60,
                              "height":50},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9e41cbf4d584407fa8085f508e36fb70",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF515151},
                                "size":{
                                  "width":60,
                                  "height":50},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机版列表/u15.png"}},
{
                          "id":"6378e9a57bbb42eda9c4cd6e9af3723f",
                          "label":"",
                          "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF515151},
                            "location":{
                              "x":60,
                              "y":0},
                            "size":{
                              "width":60,
                              "height":50},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ca0cb90080294f7c81d606fca44730da",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF515151},
                                "location":{
                                  "x":60,
                                  "y":0},
                                "size":{
                                  "width":60,
                                  "height":50},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机版列表/u15.png"}},
{
                          "id":"e9bab81b16634a81b3753a8e4d47498d",
                          "label":"",
                          "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negreta', 'Arial'",
                            "fontWeight":"700",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF0000},
                            "location":{
                              "x":120,
                              "y":0},
                            "size":{
                              "width":60,
                              "height":50},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"c92ac74672bf4a4e96a511273c0de10c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Arial Negreta', 'Arial'",
                                "fontWeight":"700",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFF0000},
                                "location":{
                                  "x":120,
                                  "y":0},
                                "size":{
                                  "width":60,
                                  "height":50},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机版列表/u19.png"}},
{
                          "id":"4bf4740f63da4102a0baee7698a32ba3",
                          "label":"",
                          "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF515151},
                            "location":{
                              "x":180,
                              "y":0},
                            "size":{
                              "width":60,
                              "height":50},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5b732c6c0b6747df8e11e90122b627d8",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF515151},
                                "location":{
                                  "x":180,
                                  "y":0},
                                "size":{
                                  "width":60,
                                  "height":50},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机版列表/u15.png"}},
{
                          "id":"a3d35d5408844e4f8182c498923ecc10",
                          "label":"",
                          "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF515151},
                            "location":{
                              "x":240,
                              "y":0},
                            "size":{
                              "width":60,
                              "height":50},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b1ba5eb99c484eb8aaa27615467c6b79",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF515151},
                                "location":{
                                  "x":240,
                                  "y":0},
                                "size":{
                                  "width":60,
                                  "height":50},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机版列表/u15.png"}},
{
                          "id":"87aed2ab5e2c4e5cbbae109ab37cefdf",
                          "label":"",
                          "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF515151},
                            "location":{
                              "x":300,
                              "y":0},
                            "size":{
                              "width":60,
                              "height":50},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"468eb73d041c413cb1dec76169f2927b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF515151},
                                "location":{
                                  "x":300,
                                  "y":0},
                                "size":{
                                  "width":60,
                                  "height":50},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机版列表/u15.png"}},
{
                          "id":"7c3f9b65b28546b4ab4de60a13826f46",
                          "label":"",
                          "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF515151},
                            "location":{
                              "x":360,
                              "y":0},
                            "size":{
                              "width":60,
                              "height":50},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1ba567fb21bd491fb4d95b93b0d3290c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF515151},
                                "location":{
                                  "x":360,
                                  "y":0},
                                "size":{
                                  "width":60,
                                  "height":50},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机版列表/u15.png"}},
{
                          "id":"2a1f6f32b6564acd850317e22e439f5d",
                          "label":"",
                          "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF515151},
                            "location":{
                              "x":420,
                              "y":0},
                            "size":{
                              "width":60,
                              "height":50},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"c7452e226cdd47ae9ac20915f3eeb056",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF515151},
                                "location":{
                                  "x":420,
                                  "y":0},
                                "size":{
                                  "width":60,
                                  "height":50},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机版列表/u15.png"}},
{
                          "id":"5f1fc1a1247b45a99df3b769b59872bd",
                          "label":"",
                          "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF0000},
                            "location":{
                              "x":140,
                              "y":49},
                            "size":{
                              "width":20,
                              "height":10},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ad48c7c3843a4fa7a5523ee45f741359",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cd0b33f9dcb944308e5aa5ebfdf6311b",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFF0000},
                                "location":{
                                  "x":140,
                                  "y":49},
                                "size":{
                                  "width":20,
                                  "height":10},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机版列表/u31.png"}}]}]}]}]},
{
          "id":"4e6521fba75547d7b6b33833279ddbe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":123},
            "size":{
              "width":320,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fc09f67274c4699a39bcbe948f5e8c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":123},
                "size":{
                  "width":320,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机版列表/u33.png"}},
{
          "id":"c9f5827948a540b19d0f592da90be1f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":150},
            "size":{
              "width":86,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19e85039375c45179f531ebb8b96b28f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":150},
                "size":{
                  "width":86,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机版列表/u35.png"}},
{
          "id":"ed1a1635b3e9440098e420d7919825c6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":237},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机版列表/u37_line.png"}},
{
          "id":"6a77b814a6844500a12cbafe0c28c904",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":100,
              "y":150},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c805db909ec14a4b95fabb4936038b95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":100,
                  "y":150},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c864f640e894f8b9e3fece05c7e1d89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":96,
              "y":217},
            "size":{
              "width":41,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8588ac24752c430999b1a16b35574ccb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":96,
                  "y":217},
                "size":{
                  "width":41,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d88b890e4fce463b8f980effda6fb26e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF363636,
              "opacity":1},
            "location":{
              "x":142,
              "y":222},
            "size":{
              "width":28,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a729c603b35e40b6bfc8c57d46630ec1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF363636,
                  "opacity":1},
                "location":{
                  "x":142,
                  "y":222},
                "size":{
                  "width":28,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fcabb258558420c84b0b08f619f4f2b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":224},
            "size":{
              "width":28,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机版列表/u44_line.png"}},
{
          "id":"eebe6064488d4f5d981965333adc1750",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3333},
            "location":{
              "x":199,
              "y":204},
            "size":{
              "width":101,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"336b75f66788457bbe640b1c05acaf4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3333},
                "location":{
                  "x":199,
                  "y":204},
                "size":{
                  "width":101,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 手机版详情",
                      "target":{
                        "targetType":"page",
                        "url":"手机版详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机版列表/u45.png"}}]}},
  "masters":{
    "7ddeb125ab1346d78fab0f7c44d11c2d":{
      "packageId":"7ddeb125ab1346d78fab0f7c44d11c2d",
      "type":"Axure:Master",
      "name":"底板全局",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8a3aa33e825441e69d45f7a647bad681",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":0,
                "y":18},
              "size":{
                "width":320,
                "height":462},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c6a74bf75a24bdca4179771b933a601",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":0,
                    "y":18},
                  "size":{
                    "width":320,
                    "height":462},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机版列表/u1.png"}},
{
            "id":"4828941e46b34c7c95a3b5ac3d332e1b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":18},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd395427e46e4ef694ef269fa45dbf1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":18},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机版列表/u3.png"}}]}}},
  "objectPaths":{
    "04fbd17464fd4b4694a90b25fbeccac3":{
      "scriptId":"u0",
      "8a3aa33e825441e69d45f7a647bad681":{
        "scriptId":"u1"},
      "1c6a74bf75a24bdca4179771b933a601":{
        "scriptId":"u2"},
      "4828941e46b34c7c95a3b5ac3d332e1b":{
        "scriptId":"u3"},
      "cd395427e46e4ef694ef269fa45dbf1a":{
        "scriptId":"u4"}},
    "7ec02485c9d64d83a2bcb1787341fbf4":{
      "scriptId":"u5"},
    "78ae15aeb8dd4ce3a1ba31060dfcc916":{
      "scriptId":"u6"},
    "f8bc0a7eb24947c7aec0477de20d33d6":{
      "scriptId":"u7"},
    "c1fb2f66d45045ada30a94947031fc46":{
      "scriptId":"u8"},
    "887745b6aaf244d29e58b1cf767c3624":{
      "scriptId":"u9"},
    "6eaf565dad3749d69a00a1ec6655e625":{
      "scriptId":"u10"},
    "7e74c7b0599f44b29957073f12d78e48":{
      "scriptId":"u11"},
    "cd0b33f9dcb944308e5aa5ebfdf6311b":{
      "scriptId":"u12"},
    "952bd2e9552e4ad2b55287a4453cd1d5":{
      "scriptId":"u13"},
    "18006307060f4efa954d40df5900ac8b":{
      "scriptId":"u14"},
    "2a7b3aa575ec49a29e25de9c4d57eaf9":{
      "scriptId":"u15"},
    "9e41cbf4d584407fa8085f508e36fb70":{
      "scriptId":"u16"},
    "6378e9a57bbb42eda9c4cd6e9af3723f":{
      "scriptId":"u17"},
    "ca0cb90080294f7c81d606fca44730da":{
      "scriptId":"u18"},
    "e9bab81b16634a81b3753a8e4d47498d":{
      "scriptId":"u19"},
    "c92ac74672bf4a4e96a511273c0de10c":{
      "scriptId":"u20"},
    "4bf4740f63da4102a0baee7698a32ba3":{
      "scriptId":"u21"},
    "5b732c6c0b6747df8e11e90122b627d8":{
      "scriptId":"u22"},
    "a3d35d5408844e4f8182c498923ecc10":{
      "scriptId":"u23"},
    "b1ba5eb99c484eb8aaa27615467c6b79":{
      "scriptId":"u24"},
    "87aed2ab5e2c4e5cbbae109ab37cefdf":{
      "scriptId":"u25"},
    "468eb73d041c413cb1dec76169f2927b":{
      "scriptId":"u26"},
    "7c3f9b65b28546b4ab4de60a13826f46":{
      "scriptId":"u27"},
    "1ba567fb21bd491fb4d95b93b0d3290c":{
      "scriptId":"u28"},
    "2a1f6f32b6564acd850317e22e439f5d":{
      "scriptId":"u29"},
    "c7452e226cdd47ae9ac20915f3eeb056":{
      "scriptId":"u30"},
    "5f1fc1a1247b45a99df3b769b59872bd":{
      "scriptId":"u31"},
    "ad48c7c3843a4fa7a5523ee45f741359":{
      "scriptId":"u32"},
    "4e6521fba75547d7b6b33833279ddbe1":{
      "scriptId":"u33"},
    "3fc09f67274c4699a39bcbe948f5e8c0":{
      "scriptId":"u34"},
    "c9f5827948a540b19d0f592da90be1f2":{
      "scriptId":"u35"},
    "19e85039375c45179f531ebb8b96b28f":{
      "scriptId":"u36"},
    "ed1a1635b3e9440098e420d7919825c6":{
      "scriptId":"u37"},
    "6a77b814a6844500a12cbafe0c28c904":{
      "scriptId":"u38"},
    "c805db909ec14a4b95fabb4936038b95":{
      "scriptId":"u39"},
    "2c864f640e894f8b9e3fece05c7e1d89":{
      "scriptId":"u40"},
    "8588ac24752c430999b1a16b35574ccb":{
      "scriptId":"u41"},
    "d88b890e4fce463b8f980effda6fb26e":{
      "scriptId":"u42"},
    "a729c603b35e40b6bfc8c57d46630ec1":{
      "scriptId":"u43"},
    "2fcabb258558420c84b0b08f619f4f2b":{
      "scriptId":"u44"},
    "eebe6064488d4f5d981965333adc1750":{
      "scriptId":"u45"},
    "336b75f66788457bbe640b1c05acaf4c":{
      "scriptId":"u46"}}});