$axure.loadCurrentPage({
  "url":"成交记录.html",
  "generationDate":new Date(1454637459702.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"92dacb3d9c7c4cea9d3300605c0435da",
    "type":"Axure:Page",
    "name":"成交记录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d1a7351d23554724a5d0db7e90edcb08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58cf32e7f18b4ada83988896739851e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u0.png"}},
{
          "id":"8e374f2b0daf4107a31713baa0a09ffa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":36},
            "size":{
              "width":280,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cad1c40ef7eb4d83b2cedaaa88b32b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":36},
                "size":{
                  "width":280,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u2.png"}},
{
          "id":"22ecd95e4ea94b27a2bfc9cdc1bf487c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":55},
            "size":{
              "width":650,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ac3a8d564fa476cb0239cbce9ded1ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":55},
                "size":{
                  "width":650,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u4.png"}},
{
          "id":"e2d6767153a4450ca86d0ff62aed21ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF303849},
            "location":{
              "x":0,
              "y":102},
            "size":{
              "width":1200,
              "height":1028}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f587d613871465ab8126f1ac0eb7ad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF303849},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":1200,
                  "height":1028}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/u6.png"}},
{
          "id":"77b496599a5c453e96dc200ed5abe343",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"49812fb0dc0e4178b083e36d1d1a212c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":1000,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04dedb7331f14e469b64c3e488e56a4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":1000,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u20.png"}},
{
          "id":"a825cecea3fb4c2287546ce9eb1a22e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF282828},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":920},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5bbe680adfb49e68302b02c864f66ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF282828},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":920},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u22.png"}},
{
          "id":"acc5e2411d914f768514c9f72ac3b9e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"790eeb049c524564bd42c8544d2e026f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个股",
                      "target":{
                        "targetType":"page",
                        "url":"个股.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4fba80b160e433096fe38d6399b1f4c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":210},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"037e110dec024fc6b450d54e44b8158b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":210},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u26.png"}},
{
          "id":"2ed69fa4a04f4459b1a1b482b51542f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":250},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a384efd13a8423b8df6004afee1f373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":250},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46ff308c2b6a4d8dbc04c459cd0822c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF282828,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0287FE},
            "location":{
              "x":100,
              "y":270},
            "size":{
              "width":70,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bd68dd9622a4d03a6bfc70144e6d841",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF282828,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0287FE},
                "location":{
                  "x":100,
                  "y":270},
                "size":{
                  "width":70,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u24.png"}},
{
          "id":"72574da95fa54681a73600d14be08805",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":278},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"961e01a660c24c85abf2a3fb07812a50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":278},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u32.png"}},
{
          "id":"f1500b29eb3347148ae3a8435dbefea9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":108,
              "y":321},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e17ff3e548be41c79d1e14ee24c97bf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":321},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bda16dd4a78043928f4edb6c47c868c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":266,
              "y":302},
            "size":{
              "width":98,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4520ffa110544d3a6b4152b7e721af7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":266,
                  "y":302},
                "size":{
                  "width":98,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5efedadf77ac41a58027f89a2341ef7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":431,
              "y":302},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23f35b9db93d415c8c278005fa04113d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":302},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e21a371c2c03436ba9063bb4b30bba10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":302},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc57bcceab9a46158e6df7f26beaa95a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":302},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5aad6c92054b4059babfa3967a1c7b8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":302},
            "size":{
              "width":75,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a681671603134c08b7414c129eb4e93b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":302},
                "size":{
                  "width":75,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97493de5b0b445e6a17b9b6ffaf32cc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":893,
              "y":302},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"631480a947f9418b8a49b26e8f433435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":893,
                  "y":302},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2c5b98732614107a0821af76e588dbf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":318},
            "size":{
              "width":842,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人中心我的挂单/u39_line.png"}},
{
          "id":"6337e243a0d04736901fdf8695945482",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":338},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d867a836842140c692b314162223fedc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":253,
                  "y":338},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"611cb92f17ce4d5295da0328159f3670",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF669900,
              "opacity":1},
            "location":{
              "x":431,
              "y":338},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6087a2286719423c965da376c3969747",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF669900,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":338},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c149427e283b4bdbb1109e0519dea6cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":575,
              "y":338},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef22df7c18ee4233a9d8ae006b6320d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":575,
                  "y":338},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c12ebc990bb54c499a5746f105072d05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":338},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c2207449f084d8d88805243176c7a6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":338},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59131e5c85a049d99601291a1cac2b52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":886,
              "y":338},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99e5bf2b931d4c34a354065b98a6cf56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":886,
                  "y":338},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4412008ce46449be980fe4fced939071",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":210},
            "size":{
              "width":289,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9665989972d04a23b83046bb2b43a8a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":210},
                "size":{
                  "width":289,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/u46.png"}},
{
          "id":"4df3d716e0c34ecda07d19ea7a0009e1",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":206,
              "y":215},
            "size":{
              "width":74,
              "height":26}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人中心我的挂单",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心我的挂单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e41d5e53ebad433f86502ed7e5537ea7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":124},
            "size":{
              "width":59,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e2f66fbf9849d99b505f7ff37e6ec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":124},
                "size":{
                  "width":59,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个股/u224.png"}},
{
          "id":"c337a6e9ee144f9082f71de348028239",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":129},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"239db4b9f3334156b659b97c1307263c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":129},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdf0ecd467ad439c85336472f8413194",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":149},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddb2c2d6f200471cb5a62f11e9a54264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":149},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7231b95eef6c47e2bc95754dc20bcefe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":190,
              "y":169},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"441b343890134890913065ae901f56fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":169},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28ccc27a9733459190416f5cd8e0d7f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":259.5},
            "size":{
              "width":64,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5c0aa10dfb941619a26787871284269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":259.5},
                "size":{
                  "width":64,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/u57.png"}},
{
          "id":"a8f2235e3bc04208b9da39275bb43a1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":259.5},
            "size":{
              "width":64,
              "height":21},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9b39142b5e24577b05bca34fb65ead6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":259.5},
                "size":{
                  "width":64,
                  "height":21},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/成交记录/u57.png"}},
{
          "id":"6e7969dfdcad4596ad12c0f2ab9c9b99",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":355,
              "y":264.5},
            "size":{
              "width":20,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/成交记录/u61_line.png"}},
{
          "id":"396f7435617f466b934020165a6e9c81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":208,
              "y":262},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b2f74ecc96d49edac19373b70790e33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":208,
                  "y":262},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c747e24e0723481f86f09efa31cef81f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":431,
              "y":117},
            "size":{
              "width":87,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dd3b87fa74a4be78d7de9fd177b5901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":431,
                  "y":117},
                "size":{
                  "width":87,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ab73d2ec8054df889199c07d1710dc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":432,
              "y":154},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82d3b8d3e0064872944157bb0beb03e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":432,
                  "y":154},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ede42e175194012824032ff13e9d2b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":470,
              "y":154},
            "size":{
              "width":48,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61e222fe192346dd9e90291b02935901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":154},
                "size":{
                  "width":48,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9eab159e5faa42faa9a32b47d2606b64",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":527,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"1d0009a08ba6488abf6ebd089a83ebdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":551,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb5dfe020b844533a299fe688bb61230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":551,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b6fa2a442d748f68d751c784482526c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":556,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecd23bcdf6804e119af6121e8497193f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":556,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ff92e1a64c846f9946075890a2e00ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":327,
              "y":120},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b95343289fe49aeaf00abb0e2ff4abf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":327,
                  "y":120},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65005aa83d1e4e299c38e2e0a1ab4ddc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":150},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9f73abc04284178af2676bffa8b8026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":150},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u76.png"}},
{
          "id":"79141440fd234581b3bb84800e1c611e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":150},
            "size":{
              "width":73,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"381eb63157ff4d46a66b65f6f9647723",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":150},
                "size":{
                  "width":73,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心我的挂单/u78.png"}},
{
          "id":"e707aef8b41d4403ba8baaa802832305",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":610,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f74f12ed319e4b5f9920d7bb89550657",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":610,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e1ed9f7b74c418ea5bf8e3e2c87252d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF00,
              "opacity":1},
            "location":{
              "x":605,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"842b7894c28f4fae91b106c2650ba918",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00,
                  "opacity":1},
                "location":{
                  "x":605,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba5a140b3a7d457886b1b590604c70fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":665,
              "y":152},
            "size":{
              "width":28,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cfeb025286549fab9c5cd04d8bcd455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":665,
                  "y":152},
                "size":{
                  "width":28,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5afe37af062247e2b8f6a97ab46cd898",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":660,
              "y":125},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f811469a7b543d0a6926dd718466237",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":125},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3efb36cbbde84a989922da49ae554160",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":128},
            "size":{
              "width":10,
              "height":42}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个股/u8_line.png"}},
{
          "id":"283d1c3fde9e4b6ba2419eb67972eb20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":738,
              "y":128},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"416392d301814337a1b8f215cd1aa3f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":738,
                  "y":128},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08c198fd13aa48ae8cd11f9f0411d40c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":738,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ca067ba776c4fc98c7d73852e5352c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":738,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53990e7769ef406592687e8ed527d53b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":775,
              "y":127},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f58ca2fff32f4520a8e8ef5c9406e445",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":775,
                  "y":127},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abe3b812511b453fb1b07563553336a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":775,
              "y":153},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"022899b25b8246aebb9928668851c71c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":775,
                  "y":153},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf95e4ecdc8042acbcf4c33085d40f5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":831,
              "y":128},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc0d901411c9454d85861e395e750800",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":128},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a2573202e2f4e6fb8344892512b465c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2,
              "opacity":1},
            "location":{
              "x":831,
              "y":154},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e83d965460254fcd99c3abda9de1ee3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2,
                  "opacity":1},
                "location":{
                  "x":831,
                  "y":154},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bc6f0b933ae4531ab4621c968579e43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":868,
              "y":127},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d2f76d025a34574b9c2ceccd8e644e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":127},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b887dea0d7894f0fa360c83c60c2cb3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF66FF00,
              "opacity":1},
            "location":{
              "x":868,
              "y":153},
            "size":{
              "width":38,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1a5c59a49a545ecb7db3756413e502d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF66FF00,
                  "opacity":1},
                "location":{
                  "x":868,
                  "y":153},
                "size":{
                  "width":38,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d1a7351d23554724a5d0db7e90edcb08":{
      "scriptId":"u0"},
    "58cf32e7f18b4ada83988896739851e7":{
      "scriptId":"u1"},
    "8e374f2b0daf4107a31713baa0a09ffa":{
      "scriptId":"u2"},
    "cad1c40ef7eb4d83b2cedaaa88b32b27":{
      "scriptId":"u3"},
    "22ecd95e4ea94b27a2bfc9cdc1bf487c":{
      "scriptId":"u4"},
    "4ac3a8d564fa476cb0239cbce9ded1ac":{
      "scriptId":"u5"},
    "e2d6767153a4450ca86d0ff62aed21ff":{
      "scriptId":"u6"},
    "3f587d613871465ab8126f1ac0eb7ad1":{
      "scriptId":"u7"},
    "77b496599a5c453e96dc200ed5abe343":{
      "scriptId":"u8"},
    "49812fb0dc0e4178b083e36d1d1a212c":{
      "scriptId":"u9"},
    "04dedb7331f14e469b64c3e488e56a4a":{
      "scriptId":"u10"},
    "a825cecea3fb4c2287546ce9eb1a22e5":{
      "scriptId":"u11"},
    "d5bbe680adfb49e68302b02c864f66ba":{
      "scriptId":"u12"},
    "acc5e2411d914f768514c9f72ac3b9e4":{
      "scriptId":"u13"},
    "790eeb049c524564bd42c8544d2e026f":{
      "scriptId":"u14"},
    "c4fba80b160e433096fe38d6399b1f4c":{
      "scriptId":"u15"},
    "037e110dec024fc6b450d54e44b8158b":{
      "scriptId":"u16"},
    "2ed69fa4a04f4459b1a1b482b51542f5":{
      "scriptId":"u17"},
    "2a384efd13a8423b8df6004afee1f373":{
      "scriptId":"u18"},
    "46ff308c2b6a4d8dbc04c459cd0822c1":{
      "scriptId":"u19"},
    "9bd68dd9622a4d03a6bfc70144e6d841":{
      "scriptId":"u20"},
    "72574da95fa54681a73600d14be08805":{
      "scriptId":"u21"},
    "961e01a660c24c85abf2a3fb07812a50":{
      "scriptId":"u22"},
    "f1500b29eb3347148ae3a8435dbefea9":{
      "scriptId":"u23"},
    "e17ff3e548be41c79d1e14ee24c97bf9":{
      "scriptId":"u24"},
    "bda16dd4a78043928f4edb6c47c868c3":{
      "scriptId":"u25"},
    "e4520ffa110544d3a6b4152b7e721af7":{
      "scriptId":"u26"},
    "5efedadf77ac41a58027f89a2341ef7d":{
      "scriptId":"u27"},
    "23f35b9db93d415c8c278005fa04113d":{
      "scriptId":"u28"},
    "e21a371c2c03436ba9063bb4b30bba10":{
      "scriptId":"u29"},
    "dc57bcceab9a46158e6df7f26beaa95a":{
      "scriptId":"u30"},
    "5aad6c92054b4059babfa3967a1c7b8b":{
      "scriptId":"u31"},
    "a681671603134c08b7414c129eb4e93b":{
      "scriptId":"u32"},
    "97493de5b0b445e6a17b9b6ffaf32cc2":{
      "scriptId":"u33"},
    "631480a947f9418b8a49b26e8f433435":{
      "scriptId":"u34"},
    "b2c5b98732614107a0821af76e588dbf":{
      "scriptId":"u35"},
    "6337e243a0d04736901fdf8695945482":{
      "scriptId":"u36"},
    "d867a836842140c692b314162223fedc":{
      "scriptId":"u37"},
    "611cb92f17ce4d5295da0328159f3670":{
      "scriptId":"u38"},
    "6087a2286719423c965da376c3969747":{
      "scriptId":"u39"},
    "c149427e283b4bdbb1109e0519dea6cf":{
      "scriptId":"u40"},
    "ef22df7c18ee4233a9d8ae006b6320d6":{
      "scriptId":"u41"},
    "c12ebc990bb54c499a5746f105072d05":{
      "scriptId":"u42"},
    "4c2207449f084d8d88805243176c7a6e":{
      "scriptId":"u43"},
    "59131e5c85a049d99601291a1cac2b52":{
      "scriptId":"u44"},
    "99e5bf2b931d4c34a354065b98a6cf56":{
      "scriptId":"u45"},
    "4412008ce46449be980fe4fced939071":{
      "scriptId":"u46"},
    "9665989972d04a23b83046bb2b43a8a8":{
      "scriptId":"u47"},
    "4df3d716e0c34ecda07d19ea7a0009e1":{
      "scriptId":"u48"},
    "e41d5e53ebad433f86502ed7e5537ea7":{
      "scriptId":"u49"},
    "92e2f66fbf9849d99b505f7ff37e6ec9":{
      "scriptId":"u50"},
    "c337a6e9ee144f9082f71de348028239":{
      "scriptId":"u51"},
    "239db4b9f3334156b659b97c1307263c":{
      "scriptId":"u52"},
    "bdf0ecd467ad439c85336472f8413194":{
      "scriptId":"u53"},
    "ddb2c2d6f200471cb5a62f11e9a54264":{
      "scriptId":"u54"},
    "7231b95eef6c47e2bc95754dc20bcefe":{
      "scriptId":"u55"},
    "441b343890134890913065ae901f56fa":{
      "scriptId":"u56"},
    "28ccc27a9733459190416f5cd8e0d7f5":{
      "scriptId":"u57"},
    "d5c0aa10dfb941619a26787871284269":{
      "scriptId":"u58"},
    "a8f2235e3bc04208b9da39275bb43a1b":{
      "scriptId":"u59"},
    "e9b39142b5e24577b05bca34fb65ead6":{
      "scriptId":"u60"},
    "6e7969dfdcad4596ad12c0f2ab9c9b99":{
      "scriptId":"u61"},
    "396f7435617f466b934020165a6e9c81":{
      "scriptId":"u62"},
    "0b2f74ecc96d49edac19373b70790e33":{
      "scriptId":"u63"},
    "c747e24e0723481f86f09efa31cef81f":{
      "scriptId":"u64"},
    "8dd3b87fa74a4be78d7de9fd177b5901":{
      "scriptId":"u65"},
    "0ab73d2ec8054df889199c07d1710dc7":{
      "scriptId":"u66"},
    "82d3b8d3e0064872944157bb0beb03e7":{
      "scriptId":"u67"},
    "8ede42e175194012824032ff13e9d2b7":{
      "scriptId":"u68"},
    "61e222fe192346dd9e90291b02935901":{
      "scriptId":"u69"},
    "9eab159e5faa42faa9a32b47d2606b64":{
      "scriptId":"u70"},
    "1d0009a08ba6488abf6ebd089a83ebdb":{
      "scriptId":"u71"},
    "fb5dfe020b844533a299fe688bb61230":{
      "scriptId":"u72"},
    "2b6fa2a442d748f68d751c784482526c":{
      "scriptId":"u73"},
    "ecd23bcdf6804e119af6121e8497193f":{
      "scriptId":"u74"},
    "1ff92e1a64c846f9946075890a2e00ab":{
      "scriptId":"u75"},
    "6b95343289fe49aeaf00abb0e2ff4abf":{
      "scriptId":"u76"},
    "65005aa83d1e4e299c38e2e0a1ab4ddc":{
      "scriptId":"u77"},
    "d9f73abc04284178af2676bffa8b8026":{
      "scriptId":"u78"},
    "79141440fd234581b3bb84800e1c611e":{
      "scriptId":"u79"},
    "381eb63157ff4d46a66b65f6f9647723":{
      "scriptId":"u80"},
    "e707aef8b41d4403ba8baaa802832305":{
      "scriptId":"u81"},
    "f74f12ed319e4b5f9920d7bb89550657":{
      "scriptId":"u82"},
    "8e1ed9f7b74c418ea5bf8e3e2c87252d":{
      "scriptId":"u83"},
    "842b7894c28f4fae91b106c2650ba918":{
      "scriptId":"u84"},
    "ba5a140b3a7d457886b1b590604c70fd":{
      "scriptId":"u85"},
    "8cfeb025286549fab9c5cd04d8bcd455":{
      "scriptId":"u86"},
    "5afe37af062247e2b8f6a97ab46cd898":{
      "scriptId":"u87"},
    "6f811469a7b543d0a6926dd718466237":{
      "scriptId":"u88"},
    "3efb36cbbde84a989922da49ae554160":{
      "scriptId":"u89"},
    "283d1c3fde9e4b6ba2419eb67972eb20":{
      "scriptId":"u90"},
    "416392d301814337a1b8f215cd1aa3f8":{
      "scriptId":"u91"},
    "08c198fd13aa48ae8cd11f9f0411d40c":{
      "scriptId":"u92"},
    "9ca067ba776c4fc98c7d73852e5352c2":{
      "scriptId":"u93"},
    "53990e7769ef406592687e8ed527d53b":{
      "scriptId":"u94"},
    "f58ca2fff32f4520a8e8ef5c9406e445":{
      "scriptId":"u95"},
    "abe3b812511b453fb1b07563553336a5":{
      "scriptId":"u96"},
    "022899b25b8246aebb9928668851c71c":{
      "scriptId":"u97"},
    "bf95e4ecdc8042acbcf4c33085d40f5e":{
      "scriptId":"u98"},
    "dc0d901411c9454d85861e395e750800":{
      "scriptId":"u99"},
    "1a2573202e2f4e6fb8344892512b465c":{
      "scriptId":"u100"},
    "e83d965460254fcd99c3abda9de1ee3c":{
      "scriptId":"u101"},
    "6bc6f0b933ae4531ab4621c968579e43":{
      "scriptId":"u102"},
    "0d2f76d025a34574b9c2ceccd8e644e7":{
      "scriptId":"u103"},
    "b887dea0d7894f0fa360c83c60c2cb3b":{
      "scriptId":"u104"},
    "c1a5c59a49a545ecb7db3756413e502d":{
      "scriptId":"u105"}}});