$axure.loadCurrentPage({
  "url":"资产详情_排号中_.html",
  "generationDate":new Date(1473824948737.79),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cb5bbb2c815b4eafb499b9116ea455bc",
    "type":"Axure:Page",
    "name":"资产详情(排号中)",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFF2F2F2},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a05ba2dd80b8436db30e7de0f3733229",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1200,
              "height":173}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6265fc6c878c490b8c55158badfc4489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1200,
                  "height":173}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特供商城/u0.png"}},
{
          "id":"97bfbbf2183f44cea78dac330343b36f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":186},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4888d99c6da94ccf9aad421b7aee0c6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":186},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fc17328c3a440619a98f4d09d2a38e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":186},
            "size":{
              "width":39,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8defa021bd92479f8eafede5d7ff8282",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":186},
                "size":{
                  "width":39,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b12409e53dda4b1380b6bbc60fabcb39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":186},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06d51b82dca84ac295353e6cb6cffe25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":186},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e049e56df02d4fd4b83ffba485a3eb73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":212},
            "size":{
              "width":1000,
              "height":1208},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"797ac522304341fbb8da40a40bd41cfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":212},
                "size":{
                  "width":1000,
                  "height":1208},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u8.png"}},
{
          "id":"2c62363f6e30459385b679cce33adc48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":230},
            "size":{
              "width":300,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be3d89bef4d4e93a70539bc1d41861c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":230},
                "size":{
                  "width":300,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u10.png"}},
{
          "id":"6b68a86a42a243acb525d576a77b5c6d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":540},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63cdf89f1cf94074a4ddecea0fab0152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":540},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u12.png"}},
{
          "id":"d242f3598baf4767af57bd35e55f5fdd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":182,
              "y":540},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a83951873804c9f908ba1848bf19bd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":182,
                  "y":540},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u12.png"}},
{
          "id":"c283251d1aa44b49b9617d11bb317e73",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":540},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c4b9afc4e0946ae917c89ed7a684e9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":242,
                  "y":540},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u12.png"}},
{
          "id":"6c52629ff60c42118e5f84dd1d3153ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":302,
              "y":540},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b6e559e69cb4c7dad97ff36cb3e2789",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":302,
                  "y":540},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u12.png"}},
{
          "id":"ef3a45ce89d84893a324ced453df8ac8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":540},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e9bd2dba5f46a3b0d3f1f6a6460125",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":540},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u12.png"}},
{
          "id":"2a4292f6648f40649ebd879e0ce79d1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":450,
              "y":230},
            "size":{
              "width":260,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4c686fa977f421abc765e0208ca806c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":450,
                  "y":230},
                "size":{
                  "width":260,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a10a7fc948f94e74b8e340364e057f89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":450,
              "y":268},
            "size":{
              "width":70,
              "height":28},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5375a61c0914d1598dbde3d9b1dd2cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":450,
                  "y":268},
                "size":{
                  "width":70,
                  "height":28},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u24.png"}},
{
          "id":"44abe87e542c422c93ae8d390839e951",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":274},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07de14b61a9f4b3aa9acfd9da3c26744",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":274},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb7c89b834814d22979a8b5611721937",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":422,
              "y":313},
            "size":{
              "width":378,
              "height":125},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b754383d07f74c18b5f5451d58a0bd10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":422,
                  "y":313},
                "size":{
                  "width":378,
                  "height":125},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u28.png"}},
{
          "id":"d37fbdcc0a554cd2860c352155aae01f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"13px",
            "fontWeight":"400",
            "location":{
              "x":476,
              "y":337},
            "size":{
              "width":44,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7142797c6d9e4f82b107c55258f44efa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"13px",
                "fontWeight":"400",
                "location":{
                  "x":476,
                  "y":337},
                "size":{
                  "width":44,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a71ee8e965d4d9facaf93ad9ce95b2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":331},
            "size":{
              "width":86,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd51bffee2f2447e9f7f0acb0819a9ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":331},
                "size":{
                  "width":86,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92dd413c7f014c96a918ebeb89e026bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":476,
              "y":386},
            "size":{
              "width":164,
              "height":34},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db8e4948b79f4f7698fbacafe16fa4bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":476,
                  "y":386},
                "size":{
                  "width":164,
                  "height":34},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 排号费页面",
                      "target":{
                        "targetType":"page",
                        "url":"排号费页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/资产详情_排号中_/u34.png"}},
{
          "id":"52c1365b478a4b8582005056aa8fec62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":474},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59a0cc0e7e014e53bbf0f86b8a226fc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":474},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9daeb93eca34d06b4580d96988c48cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":474},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b81d7d9790d44f6b9b226ab671c17d33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":474},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"308b6b1cd0874bdfb5c78526bf128563",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":509},
            "size":{
              "width":123,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0bfa8b522cc4765abf18b0a886247ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":509},
                "size":{
                  "width":123,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5ebfa15148e476fae9f2a809fc6a1b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":340,
              "y":634},
            "size":{
              "width":110,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75a72354856147049d971b9de79a41f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":340,
                  "y":634},
                "size":{
                  "width":110,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u42.png"}},
{
          "id":"4f5617d9340841f0bec9e447dad4ddeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":509},
            "size":{
              "width":97,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3e2fe36786942f1af8988090e3f5a50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":509},
                "size":{
                  "width":97,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5740949232f74013830922d069579e8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":231,
              "y":634},
            "size":{
              "width":110,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"381690c1790840cebd6782ca6434cd13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":231,
                  "y":634},
                "size":{
                  "width":110,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u42.png"}},
{
          "id":"bf2f7ede2d8c4cd99d7316fcc00e8628",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":544},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"535306f6503049e08a79c043d338b5c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":544},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65ff73a4fe2b4967a0b149a68ea5e8bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":593,
              "y":544},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1a54872cdda44fe8eb87f186c5bd211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":593,
                  "y":544},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de1ec6f0d2544efeb166c33a83ec63f9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":664},
            "size":{
              "width":678,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资产详情_排号中_/u52_line.png"}},
{
          "id":"30facfe1377f4fd599724676c4a7c9b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":634},
            "size":{
              "width":110,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e18b44b9c5d24050ba577b473ddccff3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":634},
                "size":{
                  "width":110,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u53.png"}},
{
          "id":"89caa48a352d4e64abf7315091c07d82",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":630},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"4"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资产详情_排号中_/u55_line.png"}},
{
          "id":"0c171545384e45d2aa2408aca79bea86",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":854,
              "y":230},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcf3cd97e27f41fc812e6a9438c6ec62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":854,
                  "y":230},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce7dd251c1b94fad8b5cddfefecaf2a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":264},
            "size":{
              "width":220,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbd540a998d34f68828b29932e3db1ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":264},
                "size":{
                  "width":220,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u58.png"}},
{
          "id":"614a821a160e47088eab47b54523462a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":494},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32779cdcaad04a50abaa73bca6ea152a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":494},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca5784e948824d79b61abe0a64d45ac5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":517},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a10d7e710b6f4843a8a6c2a2626703ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":517},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79b88960075e48e0b9ecb999036fe0fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":551},
            "size":{
              "width":220,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a4293f63ad043dc8426337ad12f9e50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":551},
                "size":{
                  "width":220,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u58.png"}},
{
          "id":"a4755e737c784c54a1419d07df217a45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":781},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfba124a45d141ac814b5dfc3b31c206",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":781},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da5ba0f26af7407ab897df34bcc3b61e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":804},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a036673b23184c54acc2eeaefd2354b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":804},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91b6329d6c444feaa13a8d329e33199b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":841},
            "size":{
              "width":220,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3391de7d34f45deac192bc6c0c246aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":841},
                "size":{
                  "width":220,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u58.png"}},
{
          "id":"dfb65603296440b6ba52f322c814b2d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":1071},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44ad976abfcf4e4e8511e59f7b218711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":1071},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3653592818524a2cafa7312b2cb322ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":1094},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b24e216c6bb4bdea52eab496b685ede",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":1094},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21651a98438a407a8cb9ed1603c91980",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":1130},
            "size":{
              "width":220,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b22305769779473bb386b2c4c955add5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":1130},
                "size":{
                  "width":220,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资产详情_排号中_/u58.png"}},
{
          "id":"ac1a44dfc6804a31951e05e93d1f235e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":1360},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc4ee8fda349469ba63e826271ed2271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":1360},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f43ed427948e44299f1fcf8a5d157e30",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":854,
              "y":1383},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de19b1d7b65542e9b796d25aa0b8f056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":854,
                  "y":1383},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fb72fbf3fe343b9b5765ad67a1f93a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1486},
            "size":{
              "width":1200,
              "height":284}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf3e63de17ed42e399e99d9420a1f92b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1486},
                "size":{
                  "width":1200,
                  "height":284}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/特供商城/u239.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a05ba2dd80b8436db30e7de0f3733229":{
      "scriptId":"u0"},
    "6265fc6c878c490b8c55158badfc4489":{
      "scriptId":"u1"},
    "97bfbbf2183f44cea78dac330343b36f":{
      "scriptId":"u2"},
    "4888d99c6da94ccf9aad421b7aee0c6a":{
      "scriptId":"u3"},
    "7fc17328c3a440619a98f4d09d2a38e5":{
      "scriptId":"u4"},
    "8defa021bd92479f8eafede5d7ff8282":{
      "scriptId":"u5"},
    "b12409e53dda4b1380b6bbc60fabcb39":{
      "scriptId":"u6"},
    "06d51b82dca84ac295353e6cb6cffe25":{
      "scriptId":"u7"},
    "e049e56df02d4fd4b83ffba485a3eb73":{
      "scriptId":"u8"},
    "797ac522304341fbb8da40a40bd41cfc":{
      "scriptId":"u9"},
    "2c62363f6e30459385b679cce33adc48":{
      "scriptId":"u10"},
    "0be3d89bef4d4e93a70539bc1d41861c":{
      "scriptId":"u11"},
    "6b68a86a42a243acb525d576a77b5c6d":{
      "scriptId":"u12"},
    "63cdf89f1cf94074a4ddecea0fab0152":{
      "scriptId":"u13"},
    "d242f3598baf4767af57bd35e55f5fdd":{
      "scriptId":"u14"},
    "4a83951873804c9f908ba1848bf19bd6":{
      "scriptId":"u15"},
    "c283251d1aa44b49b9617d11bb317e73":{
      "scriptId":"u16"},
    "9c4b9afc4e0946ae917c89ed7a684e9b":{
      "scriptId":"u17"},
    "6c52629ff60c42118e5f84dd1d3153ac":{
      "scriptId":"u18"},
    "9b6e559e69cb4c7dad97ff36cb3e2789":{
      "scriptId":"u19"},
    "ef3a45ce89d84893a324ced453df8ac8":{
      "scriptId":"u20"},
    "c0e9bd2dba5f46a3b0d3f1f6a6460125":{
      "scriptId":"u21"},
    "2a4292f6648f40649ebd879e0ce79d1d":{
      "scriptId":"u22"},
    "b4c686fa977f421abc765e0208ca806c":{
      "scriptId":"u23"},
    "a10a7fc948f94e74b8e340364e057f89":{
      "scriptId":"u24"},
    "b5375a61c0914d1598dbde3d9b1dd2cc":{
      "scriptId":"u25"},
    "44abe87e542c422c93ae8d390839e951":{
      "scriptId":"u26"},
    "07de14b61a9f4b3aa9acfd9da3c26744":{
      "scriptId":"u27"},
    "eb7c89b834814d22979a8b5611721937":{
      "scriptId":"u28"},
    "b754383d07f74c18b5f5451d58a0bd10":{
      "scriptId":"u29"},
    "d37fbdcc0a554cd2860c352155aae01f":{
      "scriptId":"u30"},
    "7142797c6d9e4f82b107c55258f44efa":{
      "scriptId":"u31"},
    "4a71ee8e965d4d9facaf93ad9ce95b2b":{
      "scriptId":"u32"},
    "dd51bffee2f2447e9f7f0acb0819a9ca":{
      "scriptId":"u33"},
    "92dd413c7f014c96a918ebeb89e026bf":{
      "scriptId":"u34"},
    "db8e4948b79f4f7698fbacafe16fa4bd":{
      "scriptId":"u35"},
    "52c1365b478a4b8582005056aa8fec62":{
      "scriptId":"u36"},
    "59a0cc0e7e014e53bbf0f86b8a226fc6":{
      "scriptId":"u37"},
    "f9daeb93eca34d06b4580d96988c48cb":{
      "scriptId":"u38"},
    "b81d7d9790d44f6b9b226ab671c17d33":{
      "scriptId":"u39"},
    "308b6b1cd0874bdfb5c78526bf128563":{
      "scriptId":"u40"},
    "f0bfa8b522cc4765abf18b0a886247ab":{
      "scriptId":"u41"},
    "f5ebfa15148e476fae9f2a809fc6a1b2":{
      "scriptId":"u42"},
    "75a72354856147049d971b9de79a41f5":{
      "scriptId":"u43"},
    "4f5617d9340841f0bec9e447dad4ddeb":{
      "scriptId":"u44"},
    "a3e2fe36786942f1af8988090e3f5a50":{
      "scriptId":"u45"},
    "5740949232f74013830922d069579e8e":{
      "scriptId":"u46"},
    "381690c1790840cebd6782ca6434cd13":{
      "scriptId":"u47"},
    "bf2f7ede2d8c4cd99d7316fcc00e8628":{
      "scriptId":"u48"},
    "535306f6503049e08a79c043d338b5c0":{
      "scriptId":"u49"},
    "65ff73a4fe2b4967a0b149a68ea5e8bc":{
      "scriptId":"u50"},
    "d1a54872cdda44fe8eb87f186c5bd211":{
      "scriptId":"u51"},
    "de1ec6f0d2544efeb166c33a83ec63f9":{
      "scriptId":"u52"},
    "30facfe1377f4fd599724676c4a7c9b3":{
      "scriptId":"u53"},
    "e18b44b9c5d24050ba577b473ddccff3":{
      "scriptId":"u54"},
    "89caa48a352d4e64abf7315091c07d82":{
      "scriptId":"u55"},
    "0c171545384e45d2aa2408aca79bea86":{
      "scriptId":"u56"},
    "bcf3cd97e27f41fc812e6a9438c6ec62":{
      "scriptId":"u57"},
    "ce7dd251c1b94fad8b5cddfefecaf2a3":{
      "scriptId":"u58"},
    "bbd540a998d34f68828b29932e3db1ed":{
      "scriptId":"u59"},
    "614a821a160e47088eab47b54523462a":{
      "scriptId":"u60"},
    "32779cdcaad04a50abaa73bca6ea152a":{
      "scriptId":"u61"},
    "ca5784e948824d79b61abe0a64d45ac5":{
      "scriptId":"u62"},
    "a10d7e710b6f4843a8a6c2a2626703ec":{
      "scriptId":"u63"},
    "79b88960075e48e0b9ecb999036fe0fa":{
      "scriptId":"u64"},
    "3a4293f63ad043dc8426337ad12f9e50":{
      "scriptId":"u65"},
    "a4755e737c784c54a1419d07df217a45":{
      "scriptId":"u66"},
    "bfba124a45d141ac814b5dfc3b31c206":{
      "scriptId":"u67"},
    "da5ba0f26af7407ab897df34bcc3b61e":{
      "scriptId":"u68"},
    "a036673b23184c54acc2eeaefd2354b9":{
      "scriptId":"u69"},
    "91b6329d6c444feaa13a8d329e33199b":{
      "scriptId":"u70"},
    "a3391de7d34f45deac192bc6c0c246aa":{
      "scriptId":"u71"},
    "dfb65603296440b6ba52f322c814b2d7":{
      "scriptId":"u72"},
    "44ad976abfcf4e4e8511e59f7b218711":{
      "scriptId":"u73"},
    "3653592818524a2cafa7312b2cb322ce":{
      "scriptId":"u74"},
    "4b24e216c6bb4bdea52eab496b685ede":{
      "scriptId":"u75"},
    "21651a98438a407a8cb9ed1603c91980":{
      "scriptId":"u76"},
    "b22305769779473bb386b2c4c955add5":{
      "scriptId":"u77"},
    "ac1a44dfc6804a31951e05e93d1f235e":{
      "scriptId":"u78"},
    "dc4ee8fda349469ba63e826271ed2271":{
      "scriptId":"u79"},
    "f43ed427948e44299f1fcf8a5d157e30":{
      "scriptId":"u80"},
    "de19b1d7b65542e9b796d25aa0b8f056":{
      "scriptId":"u81"},
    "1fb72fbf3fe343b9b5765ad67a1f93a6":{
      "scriptId":"u82"},
    "cf3e63de17ed42e399e99d9420a1f92b":{
      "scriptId":"u83"}}});