$axure.loadCurrentPage({
  "url":"商户提现审批.html",
  "generationDate":new Date(1466647807266.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"419f7bc3c4be429e97b70bbae45f3778",
    "type":"Axure:Page",
    "name":"商户提现审批",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"54b7b3e2dac04eb8af745755b3d31a4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "size":{
              "width":1200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89faab371be3490884825ec569ef9666",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "size":{
                  "width":1200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户提现审批/u0.png"}},
{
          "id":"ed9e8a731bca4043aea1b095bdf65d07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":39},
            "size":{
              "width":160,
              "height":560}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf4f9c95818743a380c1c64b8b114965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":39},
                "size":{
                  "width":160,
                  "height":560}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户提现审批/u2.png"}},
{
          "id":"b565de69edc445c6865a6a8b236a41ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":50},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfa00bb2b83545cfac487db2bec4b495",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172,
                  "y":50},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de3644504a85429da86c6bcb60e0d745",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":172,
              "y":76},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa45b0c1a537411db8993a258224dfe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":172,
                  "y":76},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a86ccf7ffac4e868b764f5027cad6fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":121},
            "size":{
              "width":200,
              "height":22},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3db22a732b3446796d7de0161421c2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":121},
                "size":{
                  "width":200,
                  "height":22},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户提现审批/u8.png"}},
{
          "id":"eb8254f2a12a4afaafed081fa09caa06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":121},
            "size":{
              "width":60,
              "height":22},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da77a6f4e6f1488c93c245987e25d5a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":121},
                "size":{
                  "width":60,
                  "height":22},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户提现审批/u10.png"}},
{
          "id":"70c163ce3a844e13a4b4b3ada000a070",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":121},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"795f213b60014844a5856840457a8630",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":121},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7c7b1aba254a4eb3ad59b10cdc7b65fc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":121},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"92c2189a04d047d79eb165078b860d4d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":121},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 对账时间选择 to 状态1 show if hidden",
                      "panelsToStates":[{
                          "panelPath":["179bdd6d94c144929727947cb8f617c3"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":true,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"2a119464d1d44dff9027d6aa28142200",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":153},
            "size":{
              "width":1030,
              "height":446}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b33296fddbc452783ff8626c407ffee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":153},
                "size":{
                  "width":1030,
                  "height":446}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户提现审批/u16.png"}},
{
          "id":"179bdd6d94c144929727947cb8f617c3",
          "label":"对账时间选择",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":450,
              "y":269},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"991da531fa8e4a39b8677e5fe61acd3b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2668214d81b34b458cb606e3610260ad",
                  "label":"",
                  "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":255,
                      "height":161}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c5ef5bf8f8e49268b41a354f2fbeb4e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":255,
                          "height":161}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户提现审批/u19.png"}},
{
                  "id":"a41ed7f68b2e40968960223313f60218",
                  "label":"",
                  "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":21},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cfaec040ca324270900d05d1ba489a97",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":21},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"11b0724ef32b415ca86727901c1e6bb0",
                  "label":"",
                  "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":45,
                      "y":79},
                    "size":{
                      "width":80,
                      "height":22},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48be06836dab4b02a83c4f4dc7a9656b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":45,
                          "y":79},
                        "size":{
                          "width":80,
                          "height":22},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户提现审批/u23.png"}},
{
                  "id":"891309485ef34e79a04c568a5d88802e",
                  "label":"",
                  "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":135,
                      "y":79},
                    "size":{
                      "width":80,
                      "height":22},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f42d040b6e904a3995af5cf38a97912c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":135,
                          "y":79},
                        "size":{
                          "width":80,
                          "height":22},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商户提现审批/u23.png"}},
{
                  "id":"6721bc0a8b4241959ab883bd7a58d8b5",
                  "label":"",
                  "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":45,
                      "y":55},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee710f95927b444797f80317572a9d3a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":45,
                          "y":55},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"08f91ee6317d475f864f29542cd7cf4c",
                  "label":"",
                  "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":135,
                      "y":55},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1923052ed23b46a2bd83a13d33b4af19",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":135,
                          "y":55},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7893e29d5d1c414fa1b0a53af24522d6",
                  "label":"",
                  "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":45,
                      "y":121},
                    "size":{
                      "width":65,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 对账数据",
                              "target":{
                                "targetType":"page",
                                "url":"对账数据.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"1a9043918519440aa337f1ff05334762",
                  "label":"",
                  "parentDynamicPanel":"179bdd6d94c144929727947cb8f617c3",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":121},
                    "size":{
                      "width":65,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 对账时间选择",
                              "objectsToFades":[{
                                  "objectPath":["179bdd6d94c144929727947cb8f617c3"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "54b7b3e2dac04eb8af745755b3d31a4a":{
      "scriptId":"u0"},
    "89faab371be3490884825ec569ef9666":{
      "scriptId":"u1"},
    "ed9e8a731bca4043aea1b095bdf65d07":{
      "scriptId":"u2"},
    "bf4f9c95818743a380c1c64b8b114965":{
      "scriptId":"u3"},
    "b565de69edc445c6865a6a8b236a41ab":{
      "scriptId":"u4"},
    "dfa00bb2b83545cfac487db2bec4b495":{
      "scriptId":"u5"},
    "de3644504a85429da86c6bcb60e0d745":{
      "scriptId":"u6"},
    "aa45b0c1a537411db8993a258224dfe7":{
      "scriptId":"u7"},
    "3a86ccf7ffac4e868b764f5027cad6fa":{
      "scriptId":"u8"},
    "f3db22a732b3446796d7de0161421c2d":{
      "scriptId":"u9"},
    "eb8254f2a12a4afaafed081fa09caa06":{
      "scriptId":"u10"},
    "da77a6f4e6f1488c93c245987e25d5a0":{
      "scriptId":"u11"},
    "70c163ce3a844e13a4b4b3ada000a070":{
      "scriptId":"u12"},
    "795f213b60014844a5856840457a8630":{
      "scriptId":"u13"},
    "7c7b1aba254a4eb3ad59b10cdc7b65fc":{
      "scriptId":"u14"},
    "92c2189a04d047d79eb165078b860d4d":{
      "scriptId":"u15"},
    "2a119464d1d44dff9027d6aa28142200":{
      "scriptId":"u16"},
    "2b33296fddbc452783ff8626c407ffee":{
      "scriptId":"u17"},
    "179bdd6d94c144929727947cb8f617c3":{
      "scriptId":"u18"},
    "2668214d81b34b458cb606e3610260ad":{
      "scriptId":"u19"},
    "1c5ef5bf8f8e49268b41a354f2fbeb4e":{
      "scriptId":"u20"},
    "a41ed7f68b2e40968960223313f60218":{
      "scriptId":"u21"},
    "cfaec040ca324270900d05d1ba489a97":{
      "scriptId":"u22"},
    "11b0724ef32b415ca86727901c1e6bb0":{
      "scriptId":"u23"},
    "48be06836dab4b02a83c4f4dc7a9656b":{
      "scriptId":"u24"},
    "891309485ef34e79a04c568a5d88802e":{
      "scriptId":"u25"},
    "f42d040b6e904a3995af5cf38a97912c":{
      "scriptId":"u26"},
    "6721bc0a8b4241959ab883bd7a58d8b5":{
      "scriptId":"u27"},
    "ee710f95927b444797f80317572a9d3a":{
      "scriptId":"u28"},
    "08f91ee6317d475f864f29542cd7cf4c":{
      "scriptId":"u29"},
    "1923052ed23b46a2bd83a13d33b4af19":{
      "scriptId":"u30"},
    "7893e29d5d1c414fa1b0a53af24522d6":{
      "scriptId":"u31"},
    "1a9043918519440aa337f1ff05334762":{
      "scriptId":"u32"}}});