$axure.loadDocument({
  "configuration":{
    "showPageNotes":true,
    "showPageNoteNames":false,
    "showAnnotations":true,
    "linkStyle":"b",
    "linkFlowsToPages":true,
    "linkFlowsToPagesNewWindow":true,
    "hideAddress":false,
    "preventScroll":false,
    "useLabels":false,
    "enabledViewIds":[],
    "loadFeedbackPlugin":false},
  "sitemap":{
    "rootNodes":[{
        "pageName":"修改记录",
        "type":"Wireframe",
        "url":"修改记录.html"},
{
        "pageName":"总览-流程/结构",
        "type":"Wireframe",
        "url":"总览-流程_结构.html"},
{
        "pageName":"全局说明",
        "type":"Wireframe",
        "url":"全局说明.html"},
{
        "pageName":"演示",
        "type":"Wireframe",
        "url":"演示.html"},
{
        "pageName":"A启动页",
        "type":"Folder",
        "url":"",
        "children":[{
            "pageName":"1启动页",
            "type":"Wireframe",
            "url":"1启动页.html"},
{
            "pageName":"1第一次进入",
            "type":"Wireframe",
            "url":"1第一次进入.html"}]},
{
        "pageName":"B主页",
        "type":"Folder",
        "url":"",
        "children":[{
            "pageName":"1首页",
            "type":"Wireframe",
            "url":"1首页.html"},
{
            "pageName":"2搜索页",
            "type":"Wireframe",
            "url":"2搜索页.html"},
{
            "pageName":"2类目",
            "type":"Wireframe",
            "url":"2类目.html"},
{
            "pageName":"2列表页",
            "type":"Wireframe",
            "url":"2列表页.html"},
{
            "pageName":"3商品详情",
            "type":"Wireframe",
            "url":"3商品详情.html"}]},
{
        "pageName":"C特供",
        "type":"Folder",
        "url":""},
{
        "pageName":"D债权",
        "type":"Folder",
        "url":""},
{
        "pageName":"E购物车",
        "type":"Folder",
        "url":""},
{
        "pageName":"F我",
        "type":"Folder",
        "url":"",
        "children":[{
            "pageName":"1我",
            "type":"Wireframe",
            "url":"1我.html"}]}]},
  "globalVariables":{
    "onloadvariable":""},
  "defaultAdaptiveView":{
    "name":"",
    "size":{
      "width":0,
      "height":0},
    "condition":"<="},
  "adaptiveViews":[],
  "stylesheet":{
    "defaultStyles":{
      "buttonShape":{
        "id":"ae9700d66da547ce86cdd9f579a0fcb2",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "verticalAlignment":"middle",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "paragraph":{
        "id":"be6f8b738f954b9dad0b1dd74f5c8b6a",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "h1":{
        "id":"172cf2e406754718bddab96d85027787",
        "fontName":"'Arial Negreta', 'Arial'",
        "fontSize":"32px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "h2":{
        "id":"16a70afc015449b19b5818c98d7216b7",
        "fontName":"'Arial Negreta', 'Arial'",
        "fontSize":"24px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "h3":{
        "id":"548fedd4932141848f9371a51185ee3a",
        "fontName":"'Arial Negreta', 'Arial'",
        "fontSize":"18px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "h4":{
        "id":"9c222fd1ad924d198cd76211f35e0991",
        "fontName":"'Arial Negreta', 'Arial'",
        "fontSize":"14px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "h5":{
        "id":"23d76730aa7a43c39fd4a6ea64ba5679",
        "fontName":"'Arial Negreta', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "h6":{
        "id":"9414f8b481e14665979f6e691d6166bb",
        "fontName":"'Arial Negreta', 'Arial'",
        "fontSize":"10px",
        "fontWeight":"700",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"0",
        "paddingBottom":"0",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "imageBox":{
        "id":"805ab8d3c7634cf5876e8b9debe5d464",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "verticalAlignment":"middle",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "hyperlink":{
        "id":"cd2298b250904fce954f75d638a5e9f0",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF0000FF,
          "opacity":1},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "limbo":false},
      "hyperlinkMouseOver":{
        "id":"344b75c231e64150851004b22915e1eb",
        "underline":true},
      "hyperlinkMouseDown":{
        "id":"5a09ffd822684a01bf099f611b321bd6"},
      "textBox":{
        "id":"ecc339281832408f91259ba59f6e29b6",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "stateStyles":{
},
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "textArea":{
        "id":"5f27d19eee5f42d8b93da17ee8a27ec6",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "stateStyles":{
},
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "comboBox":{
        "id":"b0c164a387c049529dcbff109ca11fbc",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "listBox":{
        "id":"172efe8090a341fe916b2a660211c90b",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "checkbox":{
        "id":"69d41dcfb9b5435cbd0469e1540f0038",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "radioButton":{
        "id":"24eb9c4db2db4fee902ee75c5c21d588",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "flowShape":{
        "id":"c370fadb24a54fc29c1ffe9ba43d070d",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "verticalAlignment":"middle",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"linearGradient",
          "colors":[{
              "color":0xFFFFFFFF},
{
              "color":0xFFF2F2F2},
{
              "color":0xFFE4E4E4},
{
              "color":0xFFFFFFFF}]},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979},
        "linePattern":"solid",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "treeNodeObject":{
        "id":"b5f9af8c1cd840e68f632de6f27bf57e",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "stateStyles":{
},
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "limbo":false,
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979},
        "linePattern":"solid"},
      "button":{
        "id":"2beadce5b3324b15824f4ce80009679c",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF000000,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "imageMapRegion":{
        "id":"07c6fe32294c48c5b1709dc7a76e1048",
        "fontName":"'Arial Normal', 'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0"},
      "inlineFrame":{
        "id":"068d2bfba173495a98efc84513e57f14",
        "fontName":"'Arial Normal', 'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "dynamicPanel":{
        "id":"c5972712f55e4f8ca54e5a01357740d7",
        "fontName":"'Arial Normal', 'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "referenceDiagramObject":{
        "id":"7cfd0b4236454967aec0ffb7d5963d98",
        "fontName":"'Arial Normal', 'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false},
      "repeater":{
        "id":"4f366ee078704e9abf3b6e2abe9c0a8b",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "verticalAlignment":"middle",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "opacity":"1",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "textRotation":"0",
        "borderWidth":"-1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979},
        "linePattern":"solid",
        "cornerRadiusTopLeft":"0",
        "outerShadow":{
          "on":false,
          "offsetX":5,
          "offsetY":5,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.349019607843137}}},
      "table":{
        "id":"785146b86e804029857151acbdaf2efa",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "verticalAlignment":"middle",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979}},
      "tableCell":{
        "id":"ab3de1d87bb749c8b6a265f9e52e1d08",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"left",
        "verticalAlignment":"top",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "lineSpacing":"0px",
        "stateStyles":{
},
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "textShadow":{
          "on":false,
          "offsetX":1,
          "offsetY":1,
          "blurRadius":5,
          "color":{
            "r":0,
            "g":0,
            "b":0,
            "a":0.647058823529412}},
        "paddingTop":"2",
        "paddingBottom":"2",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "limbo":false,
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979}},
      "menuObject":{
        "id":"df1718f151124eff831306ab44681101",
        "fontName":"'Arial Normal', 'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF797979}},
      "horizontalLine":{
        "id":"d93b444534aa46718875c990d0a47bde",
        "fontName":"'Arial Normal', 'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "opacity":"1",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF000000},
        "linePattern":"solid"},
      "verticalLine":{
        "id":"102178cf59744a29a663f65786533bd8",
        "fontName":"'Arial Normal', 'Arial'",
        "fontWeight":"400",
        "fontStyle":"normal",
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "opacity":"1",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "visible":true,
        "limbo":false,
        "rotation":"0",
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF000000},
        "linePattern":"solid"},
      "connector":{
        "id":"1bbfcfc3a3a74b0a93c3382b7c28138b",
        "fontName":"'Arial Normal', 'Arial'",
        "fontSize":"13px",
        "fontWeight":"400",
        "fontStyle":"normal",
        "underline":false,
        "horizontalAlignment":"center",
        "foreGroundFill":{
          "fillType":"solid",
          "color":0xFF333333,
          "opacity":1},
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "location":{
          "x":0,
          "y":0},
        "size":{
          "width":0,
          "height":0},
        "limbo":false,
        "borderWidth":"1",
        "borderFill":{
          "fillType":"solid",
          "color":0xFF0099CC},
        "linePattern":"solid"}},
    "customStyles":{
}}});