$axure.loadCurrentPage({
  "url":"最新销售明细.html",
  "generationDate":new Date(1455876388403.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a80a233a99c84cb29c3bba0824de4cf2",
    "type":"Axure:Page",
    "name":"最新销售明细",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"912e8457d86c4c9a80740db1ef2f9895",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":190},
            "size":{
              "width":929,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80a3a4879a0c4c02aacf996bd6b2f55f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":190},
                "size":{
                  "width":929,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "912e8457d86c4c9a80740db1ef2f9895":{
      "scriptId":"u0"},
    "80a3a4879a0c4c02aacf996bd6b2f55f":{
      "scriptId":"u1"}}});