$axure.loadCurrentPage({
  "url":"1启动页.html",
  "generationDate":new Date(1444989698809.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e8ac55042ce4302ada99bac4c862d09",
    "type":"Axure:Page",
    "name":"1启动页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"wait",
                "description":"等待1000毫秒",
                "waitTime":1000},
{
                "action":"linkWindow",
                "description":"在 当前窗口 打开 1第一次进入",
                "target":{
                  "targetType":"page",
                  "url":"1第一次进入.html",
                  "includeVariables":true},
                "linkType":"current"}]}]}},
    "diagram":{
      "objects":[{
          "id":"8e3a72c297b84fae92076c9b52fa310e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"7ddeb125ab1346d78fab0f7c44d11c2d"},
{
          "id":"2b5f68323904490eb2ee739b84d3694e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'华文细黑 Regular', '华文细黑'",
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":18},
            "size":{
              "width":320,
              "height":462},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c370009720a941bd804bfa935a667593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'华文细黑 Regular', '华文细黑'",
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":18},
                "size":{
                  "width":320,
                  "height":462},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1启动页/u5.png"}},
{
          "id":"5a41114f1b1a4687a02e401cdda182a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":89,
              "y":136},
            "size":{
              "width":142,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb7d3d0a6d524a91bfb384982d46e6d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":136},
                "size":{
                  "width":142,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "7ddeb125ab1346d78fab0f7c44d11c2d":{
      "packageId":"7ddeb125ab1346d78fab0f7c44d11c2d",
      "type":"Axure:Master",
      "name":"底板全局",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8a3aa33e825441e69d45f7a647bad681",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'华文细黑 Regular', '华文细黑'",
              "fontSize":"12px",
              "location":{
                "x":0,
                "y":18},
              "size":{
                "width":320,
                "height":462},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1c6a74bf75a24bdca4179771b933a601",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'华文细黑 Regular', '华文细黑'",
                  "fontSize":"12px",
                  "location":{
                    "x":0,
                    "y":18},
                  "size":{
                    "width":320,
                    "height":462},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u17.png"}},
{
            "id":"4828941e46b34c7c95a3b5ac3d332e1b",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":18},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cd395427e46e4ef694ef269fa45dbf1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":18},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/全局说明/u19.png"}}]}}},
  "objectPaths":{
    "8e3a72c297b84fae92076c9b52fa310e":{
      "scriptId":"u0",
      "8a3aa33e825441e69d45f7a647bad681":{
        "scriptId":"u1"},
      "1c6a74bf75a24bdca4179771b933a601":{
        "scriptId":"u2"},
      "4828941e46b34c7c95a3b5ac3d332e1b":{
        "scriptId":"u3"},
      "cd395427e46e4ef694ef269fa45dbf1a":{
        "scriptId":"u4"}},
    "2b5f68323904490eb2ee739b84d3694e":{
      "scriptId":"u5"},
    "c370009720a941bd804bfa935a667593":{
      "scriptId":"u6"},
    "5a41114f1b1a4687a02e401cdda182a5":{
      "scriptId":"u7"},
    "bb7d3d0a6d524a91bfb384982d46e6d9":{
      "scriptId":"u8"}}});